### ISSUE TITLE
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by wpitallo** [aspnet/AspNetCore#10086]
Hi, I just upgraded to .Net core 2.2.4 from 2.1 and I am getting the following error the first time that I await a task:

```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Service.ExecuteAsync(CancellationToken cancellationToken) in C:\Service.cs:line 71
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.ExecuteAsync(Func`2 callback)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.ExecuteAsync(Func`2 callback)
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.StartAsync(CancellationToken token)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Service.ExecuteAsync(CancellationToken cancellationToken) in service.cs:line 71
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.ExecuteAsync(Func`2 callback)<---
```

This is happening inside a hosted service. Also it throws the exception but the task does complete. Then any awaits after that work perfectly so the error only occurs the first time.

**Comment by Eilon** [comment]
The exceptions seem to be coming from `Service.ExecuteAsync`, in `Service.cs`. Is that your code? Also, if you catch the AggregateException in a debugger, what are the inner exceptions (aggregate exception is just a container for multiple inner exceptions, which have the real info).

**Comment by davidfowl** [comment]
Can you provide a minimal repro with sample code.

**Comment by wpitallo** [comment]
I found the issue, I was creating the singleton hosted service twice. in startup.cs.  It would be great if we could get more intuitive error messages for these kind of issues. 

Thanks for the help!
