### ISSUE TITLE
.Net Core 3.0 Preview 5 TypeLoadException

### ISSUE THREAD

**Issue by JMan7777** [aspnet/AspNetCore#10103]
Hello,

after just upgrading a .Net Core 3.0 Preview 4 project to Preview 5 I cannot start the application anymore. (All .Net Core 3.0 related nuget packages are updated to Preview 5 as well)

I'm running (normally) under a Linux Docker container which uses the latest Preview 5 images:

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-bionic AS base
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-bionic AS build

but getting the same error also when running locally under a Windows IIS Server in VS 2019.

Loaded related type is as follows (Docker):

`Loaded '/usr/share/dotnet/shared/Microsoft.AspNetCore.App/3.0.0-preview5-19227-01/Microsoft.AspNetCore.Mvc.ViewFeatures.dll'`

Thx a lot.

See the details and TypeLoadException below.

`System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Mvc.IViewComponentHelper Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper': Could not load type 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewComponentInvokerCache' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Mvc.ViewComponents.IViewComponentInvokerFactory Lifetime: Transient ImplementationType: StackExchange.Profiling.Internal.ProfilingViewComponentInvokerFactory': Could not load type 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewComponentInvokerCache' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MyProgram.Program.<Main>d__0.MoveNext() in C:\Users\User\Desktop\Visual-Studio\MyProgram\MyProgram\Program.cs:line 33
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyProgram.Program.<Main>(String[] args)

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Mvc.IViewComponentHelper Lifetime: Transient ImplementationType: Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper': Could not load type 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewComponentInvokerCache' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Inner Exception 2:
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewComponentInvokerCache' from assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
`

**Comment by JMan7777** [comment]
I found the issue.

The latest Nuget package `MiniProfiler` (version 4.0.165) is not compatible with .Net Core 3.0 Preview 5. After removing it the application works.
