### ISSUE TITLE
DateTime.Today.ToShortDateString() .Net Core causes a null reference exception

### ISSUE THREAD

**Issue by ShadyNawara** [aspnet/AspNetCore#10160]
using DateTime to do a TryParse, toString, toShortString or anything that is string related would throw a null reference exception on Ubuntu 18.04 dotnet core 2.1. Same code works as expected when run on windows.

    string today = DateTime.Today.ToShortDateString();

or 

    DateTime.TryParse("5/10/2019", out DateTime Date)

   
exact error code
```
System.NullReferenceException: Object reference not set to an instance of an object.
       at System.Globalization.CalendarData.NormalizeDatePattern(String input)
       at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId

    )
       at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
       at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
       at System.Globalization.CultureData.DateSeparator(CalendarId calendarId)
       at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
       at System.Globalization.CultureInfo.get_DateTimeFormat()
       at System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
       at System.DateTime.TryParse(String s, DateTime& result)
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
       at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
       at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
       at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
       at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
       at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
       at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by blowdart** [comment]
@Eilon please move to corefx

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#37630

**Comment by Eilon** [comment]
BTW moving issues is democratized: https://hubbup.io/Mover 😄
