### ISSUE TITLE
Blazor extension failing to install

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#10185]
The Blazor extension is failing to install for me on VS 16.1 preview 3 (latest) and .NET 4.8. The error is like:
```C#
5/11/2019 4:14:55 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Blazor' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

I'm not sure what the root cause of this is, because the VSIX requires `[4.7.2, )` which is a requirement of visual studio. I have the latest version of windows and of .NET framework 🤷‍♂  - my machine has 4.8.

I'd suggest that remove this requirement from the VSIX and use that to work around this issue. 4.7.2 will be required by the version of VS we use, so it's redundant for us to specify anyway.

**Comment by rynowak** [comment]
Tracked this down to a VS bug that's being worked on already. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888265

I still want to remove the requirement from our manifest if possible because it's totally unnecessary.

**Comment by rynowak** [comment]
We've worked around this problem.
