### ISSUE TITLE
DataProtection - CryptographicException when using EntityFramework as Key Storage Provider 

### ISSUE THREAD

**Issue by HansMusterWhatElse** [aspnet/AspNetCore#10266]
### Describe the bug

I am currently investigating some strange behaviour in regards to our recent change to use EntityFramework as key storage provider.

**Before our Change:**

`services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(dataProtectionFileShare)).SetApplicationName("XY");`
         
**After the Change:**

`services.AddDataProtection().PersistKeysToDbContext<MyDbContext>();`

**Further Information**

- Generally speaking the applications are working as before and the exceptions which are being thrown (see below) are far to few to be a general problem, considering the load on our applications.

- This problem exists now since **over a month** and the applications have been **deployed many times**. I don't see any way how the key material hasn't been propogated yet.

- The table with the key material hasn't been touched during that time and the whole lifecycle mangement of the keys was entirely left to the framework.

- The exception only seems to be raised in conjunction with the **session cookie** implementation. So far I couldn't find any exceptions related to the anti forgery token which also makes use of `DataProtection`.

- My initial guess what that some of the old cookies on the client browser are still encrypted with the key material from the fileshare. Our session cookie has an expiration time of **15 minutes** which could only be explained if some users wouldn't have closed their browser for over a month.

- For the EF key storage provider I now also use `SetApplicationName("XY")`. Could it be that this was caused by not setting an explicit application name?

**Exceptions:**

The day we released the change to our environment, we started to receive the following exceptions:

```
2019-05-15T13:57:45.010 DHG 12388 Server123 NA NA proc NA NA NA: NA WARN Order NA Microsoft.AspNetCore.Session.SessionMiddleware Error unprotecting the session cookie. System.Security.Cryptography.CryptographicException: The payload was invalid.
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

At the same time we also started to occasionally receive the following exceptions:

```
2019-05-15T09:10:25.527 DHG 1444 Server123 NA NA proc NA NA NA: NA WARN Order NA Microsoft.AspNetCore.Session.SessionMiddleware Error unprotecting the session cookie. System.Security.Cryptography.CryptographicException: The key {45d17fe3-4617-4735-a23d-759a560eca75} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

### Expected

- Finding out what's the reason `Unprotect()` is throwing a `CryptographicException` 

- Why the key for some of the session cookies can't be found?

- Are there any known bugs related to the entity framework key storage provider?

Thank you in advance.

**Comment by blowdart** [comment]
There are no known bugs.

We can't give detailed error information, because its a security error we don't leak details as they could be useful to an attacker.

Not setting a specific application name could have caused this if the deployment path changes. I think I'd force your users to dump all cookies, and start again (or configure your app to use difference cookie names and force it that way), and then we can rule out old cookies or old keys, then start from there.

**Comment by HansMusterWhatElse** [comment]
> There are no known bugs.
> 
> We can't give detailed error information, because its a security error we don't leak details as they could be useful to an attacker.
> 
> Not setting a specific application name could have caused this if the deployment path changes. I think I'd force your users to dump all cookies, and start again (or configure your app to use difference cookie names and force it that way), and then we can rule out old cookies or old keys, then start from there.

I like the idea with renaming the cookie and will definitely consider that an option if I can't see any progress soon. Thank you very much.

**Comment by HansMusterWhatElse** [comment]
This issue can be closed, renaming the cookie has shown a drastic decrease of exceptions.
