### ISSUE TITLE
SignalR 3.0-preview5 throws InvalidDataException

### ISSUE THREAD

**Issue by dsuryd** [aspnet/AspNetCore#10373]
After upgrading to 3.0-preview5, my SignalR server starts throwing `InvalidDataException` when invoking a hub method from a Javascript client (@aspnet/signalr v1.1.0):
```csharp
      Failed to invoke hub method 'Update_VM'.
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.Read(JsonTokenType tokenType, JsonSerializerOptions options, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindType(JsonElement jsonObject, Type type)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(JsonElement jsonArray, IReadOnlyList`1 paramTypes)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(JsonElement jsonArray, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
```

This is the websocket message sent by the browser:
```json
{"arguments":["CustomerForm",{"SelectedContact":4}],"invocationId":"12","target":"Update_VM","type":1}
```

And this is that hub method definition:
```csharp
public void Update_VM(string vmId, Dictionary<string, object> vmData)
```

## Workaround
Changing the hub protocol back to `NewtonsoftJsonProtocol` fixes the issue.

**Comment by BrennanConroy** [comment]
In preview 5 only simple types are supported for Dictionary<string, T>. You can try out the daily builds which have more types supported.
________________________________
