### ISSUE TITLE
Publish Worker Service as Self-contained

### ISSUE THREAD

**Issue by Mario-HL-Duarte** [aspnet/AspNetCore#10486]
I'm not being able to publish a worker service as a self-contained. As Framework Dependent works fine.

![ProfileSettings](https://user-images.githubusercontent.com/38980017/58259889-d8831800-7d4b-11e9-9e6e-91fab43fdead.jpg)

![message](https://user-images.githubusercontent.com/38980017/58259908-e20c8000-7d4b-11e9-9b0f-2077c0fc3f00.jpg)

```
23/05/2019 11:11:05
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__176.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

===================
```

**Comment by Eilon** [comment]
@Mario-HL-Duarte can you provide more info on how to reproduce this issue?

Tagging @vijayrkn

**Comment by Mario-HL-Duarte** [comment]
@vijayrkn 

I was creating a sample project when I identified where the problem occurs.
If the project references Hangfire.Autofac, I can do pretty much everything except publish as Self-contained. (Publishing as Framework Dependent works fine)
I've created another project without reference Hangfire.Autofac for you to take as an example.

[WorkerServiceTest.zip](https://github.com/aspnet/AspNetCore/files/3213602/WorkerServiceTest.zip)

**Comment by vijayrkn** [comment]
@Mario-HL-Duarte 
Thanks for the repro project. Publish works fine for the project without Autofac dependency. 

I can reproduce the issue with the project with Autofac dependency but this issue is not publish related. It is failing with package downgrade errors. You will get the exact same error during compile time if you add this line to the csproj. You will have to address these issues if you want to publish this project in a self-contained way. Hope this helps.  

`    <RuntimeIdentifier>win-x86</RuntimeIdentifier>`

e.g of error: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
 WorkerServiceTestWithAutofac -> Hangfire.Autofac 2.3.1 -> NETStandard.Library 1.6.0 -> Microsoft.Win32.Primitives 4.0.1 -> runtime.win.Microsoft.Win32.Primitives 4.3.0 -> System.Runtime.InteropServices (>= 4.3.0) 
 WorkerServiceTestWithAutofac -> Hangfire.Autofac 2.3.1 -> NETStandard.Library 1.6.0 -> System.Runtime.InteropServices (>= 4.1.0)	WorkerServiceTestWithAutofac	C:\Users\vramak\Downloads\WorkerServiceTest\WorkerServiceTest\WorkerServiceTest\WorkerServiceTestWithAutofac.csproj	1	
```

**Comment by Mario-HL-Duarte** [comment]
Thank you!
