### ISSUE TITLE
Blazor Compilation error

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#10534]
I  just tried Blazor, Preview5

An I have this error on compile:

````
4>Fatal error in IL Linker
4>
4>Unhandled Exception: Mono.Linker.LoadException: Error while processing references of 'Microsoft.Extensions.Identity.Stores, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Cryptography.KeyDerivation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Cryptography.KeyDerivation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
4>   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
4>   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
4>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
4>   --- End of inner exception stack trace ---
4>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
4>   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
4>   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
4>   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
4>   --- End of inner exception stack trace ---
4>   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
4>   at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly)
4>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
4>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
4>   at Mono.Linker.Pipeline.Process(LinkContext context)
4>   at Mono.Linker.Driver.Run(ILogger customLogger)
4>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
4>   at Mono.Linker.Driver.Main(String[] args)
4>C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview5-19227-01\targets\Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview-20190325.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Client\obj\Debug\netstandard2.0\blazor\linker/" -x "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview5-19227-01\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Client\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview5-19227-01\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.components\3.0.0-preview5-19227-01\lib\netstandard2.0\Microsoft.AspNetCore.Components.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.aspnetcore.components.browser\3.0.0-preview5-19227-01\lib\netstandard2.0\Microsoft.AspNetCore.Components.Browser.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.configuration\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.configuration.abstractions\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.configuration.binder\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.dependencyinjection\3.0.0-preview5.19227.9\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview5.19227.9\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.identity.core\3.0.0-preview-18579-0056\lib\netstandard2.0\Microsoft.Extensions.Identity.Core.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.identity.stores\3.0.0-preview-18579-0056\lib\netstandard2.0\Microsoft.Extensions.Identity.Stores.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.logging\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Logging.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.logging.abstractions\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.options\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Options.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.extensions.primitives\3.0.0-preview.18572.1\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll" -a "C:\Users\Julien\.nuget\packages\microsoft.jsinterop\3.0.0-preview5.19227.9\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\Julien\.nuget\packages\mono.webassembly.interop\3.0.0-preview5.19227.9\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\Julien\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll" -a "C:\Users\Julien\.nuget\packages\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Users\Julien\.nuget\packages\system.componentmodel.annotations\4.6.0-preview5.19224.8\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\Julien\.nuget\packages\system.memory\4.5.2-servicing-27114-05\lib\netstandard2.0\System.Memory.dll" -a "C:\Users\Julien\.nuget\packages\system.numerics.vectors\4.4.0\lib\netstandard2.0\System.Numerics.Vectors.dll" -a "C:\Users\Julien\.nuget\packages\system.runtime.compilerservices.unsafe\4.6.0-preview.18571.3\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll" -a "C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Contracts\bin\Debug\netstandard2.0\ProjectManagementSuite.Contracts.dll" -a "C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Models\bin\Debug\netstandard2.0\ProjectManagementSuite.Models.dll" -a "C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Client\obj\Debug\netstandard2.0\ProjectManagementSuite.Client.dll"" exited with code -532462766.
3>ProjectManagementSuite.Data -> C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Data\bin\Debug\netcoreapp3.0\ProjectManagementSuite.Data.dll
4>Done building project "ProjectManagementSuite.Client.csproj" -- FAILED.
5>------ Build started: Project: ProjectManagementSuite.Services, Configuration: Debug Any CPU ------
5>ProjectManagementSuite.Services -> C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Services\bin\Debug\netcoreapp3.0\ProjectManagementSuite.Services.dll
6>------ Build started: Project: ProjectManagementSuite.Server, Configuration: Debug Any CPU ------
6>ProjectManagementSuite.Server -> C:\Team Foundation Workspace\Project Management Suite\ProjectManagementSuite.Server\bin\Debug\netcoreapp3.0\ProjectManagementSuite.Server.dll
````

**Comment by 3x0dv5** [comment]
Looks like you need to add a couple of references. But I have a question for you, did you add a reference to Microsoft.Extensions.Identity.Stores to the Blazor project (maybe through an indirect dependency)? If so why? I think you should only add that reference to the server/api project not to the blazor client. 
Is your blazor client project referencing any other project in that solution like the Data?

This seems fishy:
`Microsoft.Extensions.Identity.Stores, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 
---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Cryptography.KeyDerivation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Cryptography.KeyDerivation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

**Comment by arivera12** [comment]
Microsoft.Extensions.Identity.Stores will not compile on blazor client side it's not supported. He need to refactor his libs or dependencies to compile error go away. Microsoft.Extensions.Identity.Stores should exist on server side api project.

**Comment by JulienM28** [comment]
Thanks for you answers.
Effectively I was a bit lazy, and used some Model class directly in the front instead of creating propper dtos.

After removing all references to my Model project it works fine.

My apologies.

**Comment by 3x0dv5** [comment]
No need to be sorry, you helped other people, the item will be indexed by search engines and other people will end up here and so thank you for helping the community
