### ISSUE TITLE
Blazor runtime error. Unhandled exception disposing circuit host: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by aford22** [aspnet/AspNetCore#10696]
Server-side blazor with .net core 3 preview 5. Release build. Repeated occurrence of the following exception thrown:

```
Unhandled exception disposing circuit host:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at bool System.Collections.Generic.Dictionary<TKey, TValue>+ValueCollection+Enumerator.MoveNext()
   at void Microsoft.AspNetCore.Components.Rendering.Renderer.Dispose(bool disposing)
   at void Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer.Dispose(bool disposing)
   at void Microsoft.AspNetCore.Components.Rendering.Renderer.Dispose()
   at async ValueTask Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.DisposeAsync()+(?) => { }
   at void Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c__DisplayClass9_0+<<InvokeAsync>b__0>d.MoveNext()
   at async ValueTask Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.DisposeAsync()
   at async Task Microsoft.AspNetCore.Components.Server.Circuits.CircuitRegistry.DisposeCircuitHost(CircuitHost circuitHost)
```

This seems to happen at random intervals during runtime. I can't identify a single set of tasks to reproduce...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @aford22.
Please provide us with a repro project, so we can investigate this.

**Comment by defend** [comment]
I have faced with the next exception, which was thrown by a parallel access to an observable collection from a render thread and an another thread (async task). Invoking the concrete part (which was updating this collection) of the async task in the render thread helped to resolve the issue. Dont sure about connection between these issues, but it has the same behaviour(it happens very rarely). 
But my issue doesn't stop render process, server just throws this exception and causes big memory leak. I guess it is an absolutely wrong behaviour.
.NET Core 3.0 Preview 5 Blazor Server-Side

`warn: Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Akmetron.ComponentLibrary.Blazor.Visual.GridView`1.BuildRenderTree(RenderTreeBuilder builder) in C:\Users\rns\source\repos\Experimental\PriceSurfer\Akmetron.ComponentLibrary.Blazor\Visual\GridView.razor:line 29
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
warn: Microsoft.AspNetCore.Components.Server.ComponentHub[0]
      Unhandled Server-Side exception
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Akmetron.ComponentLibrary.Blazor.Visual.GridView`1.BuildRenderTree(RenderTreeBuilder builder) in C:\Users\rns\source\repos\Experimental\PriceSurfer\Akmetron.ComponentLibrary.Blazor\Visual\GridView.razor:line 29
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()`

**Comment by pranavkm** [comment]
@aford22 I tried a couple of things and I am unable to reproduce the stack trace that you produced. Dispose happens inside of the sync context, I am unable to find a code path where the state is modified in a concurrent way that would reproduce this problem.

@defend your stack trace looks like an issue with the 3rd party package. I'd recommend following up with them.
