### ISSUE TITLE
TestServer regression with pipes

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#10737]
The ASP.NET Core change to how it uses pipes has caused a regression with HttpRequest.PipeReader. A gRPC functional test is now failing.

Change: https://github.com/aspnet/AspNetCore/pull/10154
gRPC reaction: https://github.com/grpc/grpc-dotnet/pull/281

Failing test: https://github.com/grpc/grpc-dotnet/blob/d22b985ddd5b757d827c98736a0d83160675f9cc/test/FunctionalTests/UnaryMethodTests.cs#L339-L366

Error:
```
Cannot access a closed Stream.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.<ReadSingleMessageAsync>d__19.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\PipeExtensions.cs:line 212
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.<HandleCallAsyncCore>d__3.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\CallHandlers\UnaryServerCallHandler.cs:line 81
```

The test has two calls to the test server. I'm guessing something in the PR has caused TestServer's internal `MemoryStream` to incorrectly close after the first request is complete.

**Comment by Tratcher** [comment]
I think you'd actually get the same result using a normal HttpClient, having the request body disposed after sending it. No?

**Comment by JamesNK** [comment]
Probably. TestServer didn't though. This either needs to be changed back or called out as a breaking change.

**Comment by davidfowl** [comment]
I think we should fix it but not in pipes in the test server. The test server should noop when disposing the request stream. This is similar to how Kestrel noops when user code disposes the body.

**Comment by Tratcher** [comment]
But should TestServer dispose the HttpRequestMessage/HttpContent/Stream like a real HttpClient?

**Comment by davidfowl** [comment]
Good question, maybe it should but that's also a breaking change right? So we'd need to change that behavior and then document it.

**Comment by davidfowl** [comment]
I’ve fixed this issue in the mean time, we can decide if we want to explicitly break this behavior

**Comment by davidfowl** [comment]
@JamesNK can you verify this fixes the issue?
