### ISSUE TITLE
Docker support with Blazor (webassembly asp.net hosted) : Directory Name Invalid (linux docker)

### ISSUE THREAD

**Issue by sowsan** [aspnet/AspNetCore#10747]
Blazor webassembly asp.net hosted application failed to run by throwing file not found error at  app.UseBlazor<Client.Startup>(); of startup.cs

### To Reproduce
1. Using this version of ASP.NET Core 3.0.100-preview5-011568
2. Create a project using Blazor web assembly asp.net hosted
3. Add docker support which will add the below docker by default in VS 2019 Preview

FROM **mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim** AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
....
.....

### Expected behavior
Expected to run the application without any issue from the docker container

### Screenshots
![image](https://user-images.githubusercontent.com/11544153/58768093-6ee0e600-8563-11e9-9c78-72fc05458cfc.png)

**Comment by sowsan** [comment]
> directory name is invalid

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @sowsan.
We're currently heads-down working on most-critical issues and features for the upcoming release. We'll be able to look into this after 3.0 release.

**Comment by Herdo** [comment]
@sowsan  @mkArtakMSFT From the error message and stack trace, this seems to be the exact same issue as #9704.

**Comment by mkArtakMSFT** [comment]
Closing as a dupe per @Herdo's comment.

**Comment by digitalsigi** [comment]
Seems it hit same issue.
I am working with 3.0.100-preview9-014004. 
Created a brand new project with
`
dotnew new blazorwasm --hosted
`

Opened solution in VS 2019 Preview, run solution successfully.
Added Docker Support in VS 2019.
Hit F5 and got an exception:

`
System.ArgumentException
  HResult=0x80070057
  Message=The path must be absolute.
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles(IApplicationBuilder app, String clientAssemblyFilePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles[TClientApp](IApplicationBuilder app)
   at BlazorDocker.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\jbogad\source\repos\BlazorDocker\Server\Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
`
How to fix this?
