### ISSUE TITLE
Renaming a class in blazor project does not work in VS 2019

### ISSUE THREAD

**Issue by nvmkpk** [aspnet/AspNetCore#10752]
### Describe the bug
Class rename does not work in a blazor project when it is used in a .razor file.

### To Reproduce
1. Create a blazor project using preview 5 of Asp.net Core 3.0
2. Define a new class in a cs file.
3. Reference the class in Index.razor (or any other .razor file)
4. Rename the class to some different name
5. Now using the quick actions choose the option to rename (usually the first option)
6. The yellow bar appears on top saying rename failed and clicking on Show Stack Trace shows below exception details in a dialog:
```
System.AggregateException : One or more errors occurred. ---> Changing document 'C:\Users\Nvmkpk\Projects\Apps\Azure\WebApps\Panchangam\Views\Pages\Index.g.cs' is not supported.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
---> (Inner Exception #0) System.NotSupportedException : Changing document 'C:\Users\Nvmkpk\Projects\Apps\Azure\WebApps\Panchangam\Views\Pages\Index.g.cs' is not supported.
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForGlobalIdentifierRename(Workspace workspace,Solution newSolution,Solution oldSolution,String undoName,IEnumerable`1 changedDocuments,ISymbol symbol,String newName,Int32 trackingSessionId)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---
```

### Expected behavior
Rename completes and all references are updated (including the .razor file).

### Additional context
I hope this is a known issue and might have already been reported but I could not find anything in github issues when I tried to search.

**Comment by TheFanatr** [comment]
I am experiencing the same issue.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @nvmkpk.
This is not something we have control of. Consider reporting this issue through VS Feedback.
