### ISSUE TITLE
Blazor: @attribute directive does not work in _Imports.razor

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/AspNetCore#10868]
Repro:
- Create a new Blazor server side project
- Add `@attribute [Serializable]` to the end of `_Imports.razor`
- Build the app

It fails to build with the following error,
```
Error Message:
 System.IndexOutOfRangeException : Index was outside the bounds of the array.
Stack Trace:
   at System.String.get_Chars(Int32 index)
   at Microsoft.AspNetCore.Razor.Language.StringSourceDocument.get_Item(Int32 position) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\StringSourceDocument.cs:line 41
   at Microsoft.AspNetCore.Razor.Language.StreamSourceDocument.get_Item(Int32 position) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\StreamSourceDocument.cs:line 35
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.CodeWriterExtensions.<WritePadding>g__CalculatePadding|3_0(<>c__DisplayClass3_0& ) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\CodeWriterExtensions.cs:line 75
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.CodeWriterExtensions.WritePadding(CodeWriter writer, Int32 offset, Nullable`1 span, CodeRenderingContext context) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\CodeWriterExtensions.cs:line 41
   at Microsoft.AspNetCore.Razor.Language.Components.ComponentRuntimeNodeWriter.WriteCSharpCode(CodeRenderingContext context, CSharpCodeIntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Components\ComponentRuntimeNodeWriter.cs:line 59
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultDocumentWriter.Visitor.VisitCSharpCode(CSharpCodeIntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultDocumentWriter.cs:line 229
   at Microsoft.AspNetCore.Razor.Language.Intermediate.CSharpCodeIntermediateNode.Accept(IntermediateNodeVisitor visitor) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Intermediate\CSharpCodeIntermediateNode.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeVisitor.Visit(IntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Intermediate\IntermediateNodeVisitor.cs:line 10
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultCodeRenderingContext.RenderChildren(IntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultCodeRenderingContext.cs:line 146
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultDocumentWriter.Visitor.VisitDefault(IntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultDocumentWriter.cs:line 309
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultDocumentWriter.Visitor.VisitNamespaceDeclaration(NamespaceDeclarationIntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultDocumentWriter.cs:line 142
   at Microsoft.AspNetCore.Razor.Language.Intermediate.NamespaceDeclarationIntermediateNode.Accept(IntermediateNodeVisitor visitor) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Intermediate\NamespaceDeclarationIntermediateNode.cs:line 21
   at Microsoft.AspNetCore.Razor.Language.Intermediate.IntermediateNodeVisitor.Visit(IntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Intermediate\IntermediateNodeVisitor.cs:line 10
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultCodeRenderingContext.RenderChildren(IntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultCodeRenderingContext.cs:line 146
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultDocumentWriter.Visitor.VisitDefault(IntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultDocumentWriter.cs:line 309
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultDocumentWriter.Visitor.VisitDocument(DocumentIntermediateNode node) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultDocumentWriter.cs:line 127
   at Microsoft.AspNetCore.Razor.Language.CodeGeneration.DefaultDocumentWriter.WriteDocument(RazorCodeDocument codeDocument, DocumentIntermediateNode documentNode) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\CodeGeneration\DefaultDocumentWriter.cs:line 42
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorCSharpLoweringPhase.ExecuteCore(RazorCodeDocument codeDocument) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\DefaultRazorCSharpLoweringPhase.cs:line 29
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\RazorEnginePhaseBase.cs:line 40
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document) in C:\Github\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\DefaultRazorEngine.cs:line 51
```

cc @NTaylorMullen @rynowak

**Comment by rynowak** [comment]
Does this crash in the editor?

**Comment by ajaybhargavb** [comment]
Yes it does.

**Comment by rynowak** [comment]
😲

**Comment by ajaybhargavb** [comment]
Yeah `@attribute`s are basically unusable in imports :(. In some cases, it doesn't crash in imports. 
I'm investigating more and working on a fix
