### ISSUE TITLE
[CI Helix] Microsoft.AspNetCore.Identity.FunctionalTests fail with user limit (128) on the number of inotify instances has been reached

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#11038]
On Helix Microsoft.AspNetCore.Identity.FunctionalTests are failing with 

> System.IO.IOException : The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.

```
at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 373
   at Microsoft.AspNetCore.Identity.FunctionalTests.ServerFactory`2.CreateHost(IHostBuilder builder) in /_/src/Identity/test/Identity.FunctionalTests/Infrastructure/ServerFactory.cs:line 55
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DelegatedWebApplicationFactory.CreateHost(IHostBuilder builder) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 540
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer() in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 156
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 415
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 463
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 400
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient() in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 392
   at Microsoft.AspNetCore.Identity.FunctionalTests.NoIdentityAddedTests.QueryingIdentityEndpointsReturnsNotFoundWhenIdentityIsNotPresent(String endpoint) in /_/src/Identity/test/Identity.FunctionalTests/NoIdentityAddedTests.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
```

Seen in https://github.com/aspnet/AspNetCore/pull/9359 and https://github.com/aspnet/AspNetCore/pull/10319

/cc @rynowak as you were participating in https://github.com/dotnet/corefx/issues/32024 around a similar issue

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore-Internal/issues/2648 is also tracking this (our automation files bugs for flaky/failing tests in AspNetCore-Internal, which does have the problem of being invisible to external contributors ;)). Leaving this open though since it's public and the other issue isn't.

**Comment by blowdart** [comment]
We assume this is fixed now
