### ISSUE TITLE
[Preview 6] Blazor (Server Side) overriding identity via scaffolding - Internal Server Error

### ISSUE THREAD

**Issue by sidebarpronto** [aspnet/AspNetCore#11228]
### Description
I tried extending the user registration with custom attributes to a sample project by using the Scaffold Identity steps (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.0&tabs=visual-studio) - the end result is a mess; I ended up discarding the project. 

 Could you please streamline this to work with new Blazor libraries. Thank you. 

### To Reproduce
1. Create a sample Blazor server-side with single user authentication. Project gets generated, run the project - works like a charm. 
2. Now extend the app with Scaffold Identity. In order to do that, create a dummy pagelayout page and put that into your shared folder otherwise you will run into this issue. (https://github.com/aspnet/AspNetCore/issues/11179) 
3. Select Account\Registration page as an override option. 
4. Select the dbcontext. VS adds additional code and pages - try running the project you will run into build issues.  Clear the build issues by fixing _ViewImports page. 
Run the project - you will get this internal server error.

### Error Details
An unhandled exception occurred while processing the request.
NotSupportedException: Specified method is not supported.
Microsoft.AspNetCore.Mvc.RazorPages.PageBase.EnsureRenderedBodyOrSections()
Stack Query Cookies Headers Routing 
NotSupportedException: Specified method is not supported.
Microsoft.AspNetCore.Mvc.RazorPages.PageBase.EnsureRenderedBodyOrSections()
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details 
System.NotSupportedException: Specified method is not supported.

   at Microsoft.AspNetCore.Mvc.RazorPages.PageBase.EnsureRenderedBodyOrSections()

   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)

   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)

   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Screenshots
Scaffolding Widget:
![image](https://user-images.githubusercontent.com/9969616/59524329-6acc9680-8e88-11e9-8667-282d6e7aa3f8.png)
Build errors:
![image](https://user-images.githubusercontent.com/9969616/59524314-61dbc500-8e88-11e9-8772-7e1835126614.png)
Browser Stack after fixing build errors:
![image](https://user-images.githubusercontent.com/9969616/59524449-c6971f80-8e88-11e9-8a11-8902ef207e70.png)

**Comment by TomaszGrzmilas** [comment]
Hi,

I wanted to change Login and Registration page. I did scaffold identity and I got error:

- Using the generic type 'SignInManager<TUser>' requires 1 type arguments C:\(...)\Pages\Shared\_LoginPartial.cshtml
- The type or namespace name 'IHostingEnvironment' could not be found (are you missing a using directive or an assembly reference?) C:\(...)\Pages\Shared\_Layout.cshtm

**Comment by danroth27** [comment]
@HaoK @vijayrkn I believe we've done some work to improve identity scaffolding with Blazor for preview9. Are these issues now resolved?

**Comment by HaoK** [comment]
These two issues should be fixed now via https://github.com/aspnet/AspNetCore/issues/11880 and https://github.com/aspnet/Scaffolding/commit/bd37b0e2b7505d56b99e07d8aa3402538efe54d9

**Comment by danroth27** [comment]
Cool - sounds like this can be closed then.

**Comment by Gpd1969** [comment]
I have  similar issue when overriding all scaffold items for Identities.
![Untitled-4](https://user-images.githubusercontent.com/54655459/63909731-d89d4e80-c9f1-11e9-9642-d378e1c00727.png)
![ErrorApp0004](https://user-images.githubusercontent.com/54655459/63909728-d89d4e80-c9f1-11e9-9a16-a79e33c8efdb.png)
![ErrorApp0002](https://user-images.githubusercontent.com/54655459/63909729-d89d4e80-c9f1-11e9-9d2e-a5a35eb6358e.png)
![ErrorApp0001](https://user-images.githubusercontent.com/54655459/63909730-d89d4e80-c9f1-11e9-8ca6-69c9db5c8f25.png)

**Comment by ADefWebserver** [comment]
Looks like there is a workaround on this thread https://github.com/aspnet/AspNetCore/issues/13120
