### ISSUE TITLE
Server-Side Blazor Preview 6 breaks onpointerdown event handlers

### ISSUE THREAD

**Issue by willdean** [aspnet/AspNetCore#11224]
### Describe the bug
SDK Preview 6 has broken onpointerdown handlers in server-side Blazor

### To Reproduce
1. Using SDK preview 6, create the default server-side Blazor project.
2. In Counter.razor, change `@onclick` to `@onpointerdown` in the button element
3. Run the project and open the debug console in the browser (Chrome, here)
4. Click on the "Click Me" button on the Counter page

### Expected behavior
Counter should increment

Instead, the following error is thrown on the browser console

```
blazor.server.js:8 Uncaught (in promise) Error: System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.clientX | LineNumber: 0 | BytePositionInLine: 89.
   at System.Text.Json.ThrowHelper.ThowJsonException(String message, Utf8JsonReader& reader, String path)
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType, Utf8JsonReader& reader, String path)
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options)
   at Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher.ParseEventArgsJson(String eventArgsType, String eventArgsJson)
   at Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher.DispatchEvent(BrowserEventDescriptor eventDescriptor, String eventArgsJson)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (https://localhost:44322/_framework/blazor.server.js:8:21783)
    at https://localhost:44322/_framework/blazor.server.js:8:21434
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44322/_framework/blazor.server.js:8:21403)
    at https://localhost:44322/_framework/blazor.server.js:1:16653
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44322/_framework/blazor.server.js:1:16624)
    at e.processIncomingData (https://localhost:44322/_framework/blazor.server.js:1:14624)
    at e.connection.onreceive (https://localhost:44322/_framework/blazor.server.js:1:11165)
    at WebSocket.i.onmessage (https://localhost:44322/_framework/blazor.server.js:1:30454)
```

Preview 5 did not have this problem.

**Comment by danroth27** [comment]
@pranavkm @rynowak Looks like a potential System.Text.Json issue

**Comment by willdean** [comment]
I've backed-out back to to Pre5 for now so that we can make progress, but if this is a System.Text.Json issue, is it likely that an `AddNewtonsoftJson` could be made somewhere that would help avoid this?

**Comment by Mercurial** [comment]
I think its also related to my problem #11244 11224

**Comment by pranavkm** [comment]
Tracking validating this using https://github.com/aspnet/AspNetCore/issues/11396
