### ISSUE TITLE
Null ref in HubConnection if parameter is null

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#11239]
```C#
   at System.Object.GetType()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.PackageStreamingParams(ConnectionState connectionState, Object[]& args, List`1& streamIds)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendCoreAsyncCore(String methodName, Object[] args, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendCoreAsync(String methodName, Object[] args, CancellationToken cancellationToken)
   at BenchmarksClient.Workers.BlazorIgnitor.<>c__DisplayClass23_2.<<Clicker>b__1>d.MoveNext() in D:\work\Benchmarks\src\BenchmarksClient\Workers\BlazorIgnitor.cs:line 160
```

I did `connection.SendAsync("foo", 1, null);`

**Comment by pranavkm** [comment]
cc @BrennanConroy

**Comment by mikaelm12** [comment]
There actually is a Java component to this issue. I found it as I was adding a test. I'll explain more in the coming PR

**Comment by mikaelm12** [comment]
Verified in Java.

**Comment by mikaelm12** [comment]
Came back to this. Now verified in the .NET client as well.

**Comment by mikaelm12** [comment]
**Acceptance checklist** (check one item)
* [ ] We decided not to take this fix.
* [ ] The fix is tests-only.
* [ ] This is a Docs issue.
* [x] The fix contains product changes (**check all items below**).
	* [x] Relevant XML documentation comments for new public APIs are present. - Not needed
	* [x] Narrative docs (docs.microsoft.com) are updated. (**check one item below**)
    	* [ ] The change requires a new article. An issue with an outline has been filed here: [ISSUE LINK]
		* [ ] The change requires a change to an existing article. A **closed** docs PR with these changes is linked here: [PR LINK]
		* [x] The change requires no docs changes.
	* [x] Verification has been completed. (**check one item below**)
    	* [ ] The change is in the shared framework and was verified against the following versions 
			* SDK installer: [VERSION]
			* ASP.NET Core Runtime: [VERSION]
			* .NET Core Runtime: [VERSION]
	    * [x] The change is in an OOB NuGet/NPM/JAR package and was verified against the following version of that package: 3.0.0-preview7.19325.8
