### ISSUE TITLE
[X86/Linux] Build AspNetCore-2.1 Failed at the functionaltests@1.0.0 build:webpack

### ISSUE THREAD

**Issue by xiangzhai** [aspnet/AspNetCore#11309]
### Describe the bug
npm ERR! Failed at the functionaltests@1.0.0 build script 'npm run clean && npm run build:lint && npm run build:webpack'.

### To Reproduce
1. Using ASP.NET Core 'origin/release/2.1' branch:

```
commit d805ee112b9961fe19b693a3d5ce065c7ee71894 (HEAD, origin/release/2.1)
Author: Pranav K <prkrishn@hotmail.com>
Date:   Tue Jun 11 14:35:20 2019 -0700

    Make the test input a bit more reasonable (#11096)
    
    Fixes https://github.com/aspnet/AspNetCore-Internal/issues/2626

```

2. Run './build.sh'
3. See error:

```
ERROR in ./ts/ConnectionTests.ts
  Module build failed (from ../common/node_modules/ts-loader/index.js):
  Error: Typescript emitted no output for /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts.
      at successLoader (/disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/common/node_modules/ts-loader/dist/index.js:41:15)
      at Object.loader (/disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/common/node_modules/ts-loader/dist/index.js:21:12)
   @ ./ts/index.ts 5:0-27
  
  ERROR in ./ts/TestLogger.ts
  Module build failed (from ../common/node_modules/ts-loader/index.js):
  Error: Typescript emitted no output for /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/TestLogger.ts.
      at successLoader (/disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/common/node_modules/ts-loader/dist/index.js:41:15)
      at Object.loader (/disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/common/node_modules/ts-loader/dist/index.js:21:12)
   @ ./ts/WebDriverReporter.ts 2:0-42 47:22-32
   @ ./ts/index.ts
  
  ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts
  ./ts/ConnectionTests.ts
  [tsl] ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts(12,32)
        TS2307: Cannot find module '@aspnet/signalr/dist/esm/HttpConnection'.
  
  ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts
  ./ts/ConnectionTests.ts
  [tsl] ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts(42,19)
        TS7006: Parameter 'e' implicitly has an 'any' type.
  
  ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts
  ./ts/ConnectionTests.ts
  [tsl] ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/ConnectionTests.ts(106,27)
        TS7006: Parameter 'e' implicitly has an 'any' type.
  
  ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/TestLogger.ts
  ./ts/TestLogger.ts
  [tsl] ERROR in /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/ts/TestLogger.ts(5,31)
        TS2307: Cannot find module '@aspnet/signalr/dist/esm/Utils'.
  
  npm ERR! Linux 4.15.0-50-generic
  npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:webpack"
  npm ERR! node v8.10.0
  npm ERR! npm  v3.5.2
  npm ERR! code ELIFECYCLE
  npm ERR! functionaltests@1.0.0 build:webpack: `node ../common/node_modules/webpack-cli/bin/cli.js`
  npm ERR! Exit status 2
  npm ERR! 
  npm ERR! Failed at the functionaltests@1.0.0 build:webpack script 'node ../common/node_modules/webpack-cli/bin/cli.js'.
  npm ERR! Make sure you have the latest version of node.js and npm installed.
  npm ERR! If you do, this is most likely a problem with the functionaltests package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     node ../common/node_modules/webpack-cli/bin/cli.js
  npm ERR! You can get information on how to open an issue for this project with:
  npm ERR!     npm bugs functionaltests
  npm ERR! Or if that isn't available, you can get their info via:
  npm ERR!     npm owner ls functionaltests
  npm ERR! There is likely additional logging output above.
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/npm-debug.log
  
  npm ERR! Linux 4.15.0-50-generic
  npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
  npm ERR! node v8.10.0
  npm ERR! npm  v3.5.2
  npm ERR! code ELIFECYCLE
  npm ERR! functionaltests@1.0.0 build: `npm run clean && npm run build:lint && npm run build:webpack`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the functionaltests@1.0.0 build script 'npm run clean && npm run build:lint && npm run build:webpack'.
  npm ERR! Make sure you have the latest version of node.js and npm installed.
  npm ERR! If you do, this is most likely a problem with the functionaltests package,
  npm ERR! not with npm itself.
  npm ERR! Tell the author that this fails on your system:
  npm ERR!     npm run clean && npm run build:lint && npm run build:webpack
  npm ERR! You can get information on how to open an issue for this project with:
  npm ERR!     npm bugs functionaltests
  npm ERR! Or if that isn't available, you can get their info via:
  npm ERR!     npm owner ls functionaltests
  npm ERR! There is likely additional logging output above.
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/npm-debug.log
```

### Expected behavior
Successfully build AspNetCore-2.1 for X86/Linux.

### Additional context

```
$ cat /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle functionaltests@1.0.0~prebuild: functionaltests@1.0.0
6 silly lifecycle functionaltests@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle functionaltests@1.0.0~build: functionaltests@1.0.0
8 verbose lifecycle functionaltests@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle functionaltests@1.0.0~build: PATH: /usr/share/npm/bin/node-gyp-bin:/disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests/node_modules/.bin:/home/loongson/.dotnet:/home/loongson/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/redis/bin
10 verbose lifecycle functionaltests@1.0.0~build: CWD: /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests
11 silly lifecycle functionaltests@1.0.0~build: Args: [ '-c',
11 silly lifecycle   'npm run clean && npm run build:lint && npm run build:webpack' ]
12 silly lifecycle functionaltests@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle functionaltests@1.0.0~build: Failed to exec build script
14 verbose stack Error: functionaltests@1.0.0 build: `npm run clean && npm run build:lint && npm run build:webpack`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid functionaltests@1.0.0
16 verbose cwd /disk/zhaixiang/AspNetCore-2.1/src/SignalR/clients/ts/FunctionalTests
17 error Linux 4.15.0-50-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error functionaltests@1.0.0 build: `npm run clean && npm run build:lint && npm run build:webpack`
22 error Exit status 1
23 error Failed at the functionaltests@1.0.0 build script 'npm run clean && npm run build:lint && npm run build:webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the functionaltests package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && npm run build:lint && npm run build:webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs functionaltests
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls functionaltests
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Thanks @Pilchie 

AspNetCore-2.1 is platform independent, correct?

```
$ file dotnet-sdk-2.1.700-linux-x64/shared/Microsoft.AspNetCore.App/2.1.11/Microsoft.AspNetCore.dll
dotnet-sdk-2.1.700-linux-x64/shared/Microsoft.AspNetCore.App/2.1.11/Microsoft.AspNetCore.dll: PE32+ executable (DLL) (console) Mono/.Net assembly, for MS Windows
```

And there is no native build stuff compared with corefx-2.1:

```
$ file corefx-2.1-Linux.mips64.Debug/System.Native.so 
corefx-2.1-Linux.mips64.Debug/System.Native.so: ELF 64-bit LSB shared object, MIPS, MIPS64 rel2 version 1 (SYSV), dynamically linked, BuildID[sha1]=0e61d563f6485ff883a375d14ca32f451fc90c98, not stripped
```

So is it able to use X86's [dotnet-sdk-2.1.700-linux-x64/shared/Microsoft.AspNetCore.App](https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.1.700-linux-x64-binaries) for AArch64 and other Targets directly?

Cheers,
Leslie Zhai
