### ISSUE TITLE
Blazor Component RuntimeBinderException with dynamic and null

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore#11321]
The following two Blazor Components
```razor
@* App.razor *@
<Test Value="null"></Test>
@* Test.razor *@
<div>@Value</div>
@code
{
    [Parameter] public dynamic Value { get; set; }
}
```
Result in immediate `RuntimeBinderException`:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The call is ambiguous between the following methods or properties: 'Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddAttribute(int, string, System.Func<Microsoft.AspNetCore.Components.UIEventArgs,System.Threading.Tasks.Task>)' and 'Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddAttribute(int, string, string)'
   at CallSite.Target(Closure , CallSite , RenderTreeBuilder , Int32 , String , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at BlazorServerPreview6.App.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
[…]

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tragetaschen.
Why wouldn't you just use `string` for `Value` property?
It's not really clear what's the value for this. Please provide more details about your scenario.

**Comment by Tragetaschen** [comment]
A had started migrating my existing Angular application to server-side Blazor. In one part of the application, I use an `object`-based interface (with possible null values) and published instances of anonymous types that are then JSON-serialized over a SignalR connection to Angular. Since nothing in the C# world between the creation and serialization needed access to those anonymous types, this was a rather elegant way of creating a JSON property bag.

While converting to components, I then needed access to those anonymous typed objects and accepted them as Parameters typed dynamic, so I can "dot into" them in the C# world. This is when I encountered the above Exception and reduced it to the bare minimum in the OP.

I have since replaced the anonymous types with actual named types and downcast the received objects. That way, I don't need dynamic to "dot into".

**Comment by mkArtakMSFT** [comment]
Thanks, @Tragetaschen. Looks like you've already worked through this on your own.
We're moving this to the Backlog. If more people will start facing this issue we may decide to do something about it.

**Comment by oiBio** [comment]
i had the same issue today. I wanted to create a component that is able to handle my ExpandoObject. 
My solution was to change the parameter to to object and pass it as such. Maybe myworkaround helps someone else.

**MyCustom.razor**
```
@using System.Dynamic

<input @bind="ValueInputString" />

@code {

    [Parameter] public object DynamicAsObject { get; set; } = new ExpandoObject();
    [Parameter] EventCallback<object> DynamicAsObjectChanged { get; set; }
    [Parameter] public string PropertyName { get; set; }
    private IDictionary<string, object> _dynamicAsDict{ get => (IDictionary<string, object>)DynamicAsObject; set => DynamicAsObject = value; }
    string ValueInputString { get => GetDynamicValue(); set => SetDynamicValue(value); }


    private string GetDynamicValue()
    {
        if (_dynamicAsDict.ContainsKey(PropertyName))
        {
            return _dynamicAsDict[PropertyName].ToString();
        }
        return default;
    }

    private void SetDynamicValue(string value)
    {
        if (_dynamicAsDict.ContainsKey(PropertyName))
        {
            _dynamicAsDict[PropertyName] = value;
        }
        else
        {
            _dynamicAsDict.Add(PropertyName, value);
        }
        DynamicAsObjectChanged.InvokeAsync(DynamicAsObject);
    }
}
```
**Component is called like this** 
```
@{ 
    object dynamicObj = Model.Custom;

}
<MyCustom @bind-DynamicAsObject="@dynamicObj" PropertyName="@("Foo")" />
```

**Comment by SteveSandersonMS** [comment]
Since in .NET 5 we've moved to the CoreFx base class library, it's very likely this no longer applies. If it still occurs on .NET 5, please let us know.

**Comment by juho-hanhimaki** [comment]
I think this issue still exists.

I have a DynamicObject that returns null for a member that doesn't exists:
![image](https://user-images.githubusercontent.com/12390182/101614924-30f53580-3a16-11eb-8fbb-0d6be3c45c12.png)

When used in a component:
![image](https://user-images.githubusercontent.com/12390182/101615324-a8c36000-3a16-11eb-83fa-02695b6886e3.png)

Exception is thrown:
![image](https://user-images.githubusercontent.com/12390182/101615260-977a5380-3a16-11eb-882b-7f1934f0e09e.png)

Works as expected when empty string is returned instead of null:
![image](https://user-images.githubusercontent.com/12390182/101614771-05724b00-3a16-11eb-80dc-5e241b8a7324.png)

**Comment by SteveSandersonMS** [comment]
I'm unsure whether the runtime should do something different with this, or whether it's an intentional limitation in how `dynamic` works.

I would have expected the runtime to resolve this to the `object?` overload of `AddContent`, but I see it gets treated as ambiguous.

Moving to runtime repo.
