### ISSUE TITLE
SignalR yarn builds are flaky

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#11385]
I'm seeing some build flakiness introduced by conversion to arcade:
https://dev.azure.com/dnceng/public/_build/results?buildId=230748

cc @aspnet/build 

```
$ yarn run build:lint && yarn run build:esm && yarn run build:cjs && yarn run build:browser && yarn run build:webworker && yarn run build:uglify
  $ node ../common/node_modules/tslint/bin/tslint -c ../tslint.json -p ./tsconfig.json
  Tests succeeded: F:\workspace\_work\1\s\artifacts\bin\Microsoft.AspNetCore.Http.Features.Tests\Release\netcoreapp3.0\Microsoft.AspNetCore.Http.Features.Tests.dll [netcoreapp3.0|x64]
  PASS signalr/tests/HubConnection.Reconnect.test.ts
  PASS signalr/tests/HttpConnection.test.ts (6.078s)
  PASS signalr/tests/HubConnectionBuilder.test.ts
  FAIL signalr-protocol-msgpack/tests/MessagePackHubProtocol.test.ts
    ΓùÅ Test suite failed to run
  
YARN : Configuration error :  [F:\workspace\_work\1\s\src\SignalR\clients\ts\client-ts.npmproj]
##[error]YARN(0,0): error : 
  
      Could not locate module @aspnet/signalr mapped as:
      F:\workspace\_work\1\s\src\SignalR\clients\ts\signalr\dist\cjs\index.js.
  
      Please check your configuration for these entries:
      {
        "moduleNameMapper": {
          "/^@aspnet\/signalr$/": "F:\workspace\_work\1\s\src\SignalR\clients\ts\signalr\dist\cjs\index.js"
        },
        "resolver": null
      }
  
        2 | // Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
        3 | 
      > 4 | import { CompletionMessage, InvocationMessage, MessageType, NullLogger, StreamItemMessage } from "@aspnet/signalr";
          | ^
        5 | import { MessagePackHubProtocol } from "../src/MessagePackHubProtocol";
        6 | 
        7 | describe("MessagePackHubProtocol", () => {
  
        at createNoMappedModuleFoundError (common/node_modules/jest-resolve/build/index.js:472:17)
        at Object.<anonymous> (signalr-protocol-msgpack/tests/MessagePackHubProtocol.test.ts:4:1)
```

**Comment by dougbu** [comment]
Seems likely the build order isn't as reliable as it was before last Arcade transition (when restore / build / test were separate).

@pranavkm any suggestions? Should this be assigned to you?

**Comment by JunTaoLuo** [comment]
This is related to signalr so maybe @anurse can help finding a volunteer as well. I have a feeling this is going to involve looking through the msbuild targets to see why builds are not triggered in the order that we expect.

**Comment by anurse** [comment]
@BrennanConroy can probably look at this.

We generally don't rely on MSBuild to get the build ordering we want, though I don't know if that's changed since the mondo merge. The error does indicate that there's an ordering problem going on though...
