### ISSUE TITLE
HttpRequestException calling ASP.NET service in 3.0 Preview 7

### ISSUE THREAD

**Issue by mthalman** [aspnet/AspNetCore#11427]
### Describe the bug
We've got automated tests for our .NET Docker images at http://github.com/dotnet/dotnet-docker that have encountered an exception running the ASP.NET-related test for the latest preview7 drop.  The issue is a `HttpRequestException` when invoking `HttpClient.GetAsync` due to a failure to respond from the ASP.NET service.  The code being executed can be found here: https://github.com/dotnet/dotnet-docker/blob/38c0bca9054504e24082ad8cb07cfbe15c15a10f/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs#L215

The issue only occurs in our Windows-based Docker containers.  Our Linux tests are passing.

This is a regression.  The test was passing in version 3.0.100-preview7-0125**21** of the .NET Core SDK and is now failing in version 3.0.100-preview7-0125**31**.

I did try modifying the test to call GetAsync on a public web URL and it succeeded so it doesn't appear to be an issue on the client side.

### To Reproduce
Run this code in a Windows Docker container against an ASP.NET service: https://github.com/dotnet/dotnet-docker/blob/38c0bca9054504e24082ad8cb07cfbe15c15a10f/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs#L215

### Expected behavior
Test should pass.  It passed using version 3.0.100-preview7-012521 of the .NET Core SDK.

### Additional context
Here's the log output from the test:
```
Executing: docker run --name 3.0-create-web-132055381049528673 -w /app -p 80 mcr.microsoft.com/dotnet/core-nightly/sdk:3.0-nanoserver-1809 dotnet new web --framework netcoreapp3.0
Getting ready...
The template "ASP.NET Core Empty" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\app\app.csproj...
  Restore completed in 58.9 ms for C:\app\app.csproj.

Restore succeeded.
Execution Elapsed Time: 00:00:07.1002597
Executing: docker cp 3.0-create-web-132055381049528673:/app C:\repos\dotnet-docker\tests\Microsoft.DotNet.Docker.Tests\bin\Debug\netcoreapp2.1\webApp132055381049527235
Execution Elapsed Time: 00:00:00.2452418
Executing: docker container rm -f 3.0-create-web-132055381049528673
3.0-create-web-132055381049528673
Execution Elapsed Time: 00:00:00.1257637
Executing: docker build -t 3.0-build-132055381132018937 --target build --build-arg sdk_image=mcr.microsoft.com/dotnet/core-nightly/sdk:3.0-nanoserver-1809 --build-arg runtime_image=mcr.microsoft.com/dotnet/core-nightly/aspnet:3.0-nanoserver-1809 C:\repos\dotnet-docker\tests\Microsoft.DotNet.Docker.Tests\bin\Debug\netcoreapp2.1\webApp132055381049527235
Sending build context to Docker daemon   12.8kB

Step 1/10 : ARG sdk_image
Step 2/10 : ARG runtime_image
Step 3/10 : FROM $sdk_image as build
 ---> 5c4f744fbc67
Step 4/10 : EXPOSE 80
 ---> Running in c7909e0fd790
Removing intermediate container c7909e0fd790
 ---> 073b4734e3f2
Step 5/10 : WORKDIR app
 ---> Running in ba9d2e9ca70e
Removing intermediate container ba9d2e9ca70e
 ---> 83ababa4c8c1
Step 6/10 : COPY NuGet.config .
 ---> a126632c2b9f
Step 7/10 : COPY *.csproj .
 ---> 55cbb50aa4f5
Step 8/10 : RUN dotnet restore
 ---> Running in 79cc7d8623aa
  Restore completed in 71.03 ms for C:\app\app.csproj.
Removing intermediate container 79cc7d8623aa
 ---> 3fd9737945bc
Step 9/10 : COPY . .
 ---> 5d2b1938f1f6
Step 10/10 : RUN dotnet build
 ---> Running in f204da9d3901
Microsoft (R) Build Engine version 16.3.0-preview-19319-01+e79a81a53 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 47.38 ms for C:\app\app.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\3.0.100-preview7-012531\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(331,5): warning NETSDK1074: The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server). [C:\app\app.csproj]
  app -> C:\app\bin\Debug\netcoreapp3.0\app.dll

Build succeeded.

C:\Program Files\dotnet\sdk\3.0.100-preview7-012531\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(331,5): warning NETSDK1074: The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server). [C:\app\app.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:11.12
Removing intermediate container f204da9d3901
 ---> e5dda4abe504
Successfully built e5dda4abe504
Successfully tagged 3.0-build-132055381132018937:latest
Execution Elapsed Time: 00:00:27.3566254
Executing: docker run --name 3.0-app-run-132055381413639867 --rm -d -t -p 80 3.0-build-132055381132018937 dotnet run --urls http://0.0.0.0:80
0e07c536efc4b36a336551d06da58a9e06f390578cc01e2619884c86db0da9d2
Execution Elapsed Time: 00:00:01.5087560
Executing: docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" 3.0-app-run-132055381413639867
172.20.200.103
Execution Elapsed Time: 00:00:00.1139715
Request to http://172.20.200.103 failed - retrying: System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.

```

**Comment by mthalman** [comment]
I'm continuing to investigate this from a repro standpoint.

Note that the test which is failing is a nested container scenario.  That means the test runs a Docker container and within that container it creates a web project, builds a Docker image for that app, runs the app in a container (at this point the ASP.NET app is running in a container inside of the original container), and then back in the "outer" container it executes the HTTP GET call which is failing.

As part of my investigation, I've tried to manually run the scenario in a way that doesn't use nested containers.  So from my local box I created the project, published it, build a Docker image for it, and then at that point I run the app in a container.  Attempting to hit the app from my local box's browser succeeds.  Based on that, it would seem the nested container scenario is necessary or, at least, it's necessary for the client to be running in a container.  Possibly this indicates the issue is actually on the client side?

I'm going to attempt another scenario where I use the older drop of ASP.NET that was working for our tests but use the newer drop of the runtime for the client that's accessing the service.  If that fails, that would most likely indicate the regression occurred in the client runtime.

**Comment by mthalman** [comment]
It turns out that the container of the client that is attempting to send the GET request to the service is using a stable base image.  I was mistakenly thinking it was using the latest nightly drop of the runtime but it's not.  What this means is that the version of .NET running on the client has not changed and is not the cause of the regression.

**Comment by mthalman** [comment]
The latest drop of the SDK (3.0.100-preview7-012541) appears to have fixed this issue.  I'm just waiting for our full test pass to finish before closing this.

**Comment by mthalman** [comment]
Confirmed that the issue is fixed in latest drop.  Closing.
