### ISSUE TITLE
Blazor Array of date serialization converts wrong date

### ISSUE THREAD

**Issue by karthickthangasamy** [aspnet/AspNetCore#11497]
### Bug Description
In `interop.js` file, I have range of date objects in array and send to component side, which serializes the date one day before the expected date.

### To Reproduce
Run the below code example.

[`interop.js`]

```javascript
window.dateFunctions = {
  getDate: function (dotnetHelper) {
    var newObj = {};
    newObj["value"] = [new Date("06/20/2019"), new Date("06/30/2019")];
    dotnetHelper.invokeMethodAsync("JSInvokableMethod", newObj);
  }
};
```

[`Index.razor`]
```csharp
  [JSInvokable]
    public static void JSInvokableMethod(Dictionary<string, object> obj)
    {
        foreach (string key in obj.Keys)
        {
           // Update the daterange component here.
        }
    }
```
**Interop date values**

![image](https://user-images.githubusercontent.com/5012353/60021077-ec090200-96ae-11e9-8153-f1390a05d95f.png)

**Component date values**
![image](https://user-images.githubusercontent.com/5012353/60020938-9f252b80-96ae-11e9-856d-f4a9d1320297.png)

### Expected behavior
The date object should be exact match with both interop and razor component side values.

### DOTNET Info

```cmd
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by monterolebronhg** [comment]
Looking the values in .NET, the dates are being converted to UTC.

**Comment by Andrzej-W** [comment]
Are you using Blazor client side? Currently there is no support for time zones in Mono for WebAssembly.

**Comment by karthickthangasamy** [comment]
@Andrzej-W I am using Blazor server side.

**Comment by pranavkm** [comment]
Using a `Dictonary<string, object>` is going to bind to a loosely typed `JsonElement`. You could parse the fields from it if you'd like. Using a strongly typed model would definitely be a better alternative to avoid parsing tokens. If you must use a `Dictionary`, here's what you'd do to read these values:

```C#
public static void JSInvokableMethod(Dictionary<string, object> obj)
{
        var values = (JsonElement)obj["value"];
        date1 = values[0].GetDateTime();
        date2 = values[1].GetDateTime();
}
```

**Comment by karthickthangasamy** [comment]
@pranavkm : Is it workable, while we specifying `locale` in interop and send the date values with component.?

**Comment by pranavkm** [comment]
Sorry, I missed the bit where you asked about the timezone being wonky. Like @monterolebronhg noted, the values are in UTC. You could read it as a `DateTimeOffset` and call `ToLocalTime` on it. Does that help?

**Comment by karthickthangasamy** [comment]
Hi @pranavkm , I will investigate across multiple culture and update the details at the earliest.

**Comment by karthickthangasamy** [comment]
Hi @pranavkm ,

The below conversion of `DateTime` throws the below error in interop side.


```csharp
public void ComponentModelUpdate(Dictionary<string, object> obj)
        {            
            foreach (string key in obj.Keys)
            {
                if (this.NameSpace.Equals("DateRangePicker") && key.Equals("value"))
                {
                    var values = (JsonElement)obj[key];
                    var startDate = (new DateTimeOffset(values[0].GetDateTime(), TimeSpan.FromHours(0)).ToLocalTime().DateTime).ToString();
                    var endDate = (new DateTimeOffset(values[1].GetDateTime(), TimeSpan.FromHours(0)).ToLocalTime().DateTime).ToString();
                    obj[key] = new object[] {startDate, endDate};
                }       

                PropertyInfo Property = this.GetType().GetProperty(key);
                Type PropertyType = Property.PropertyType;
                Property.SetValue(this, this.ChangeType(obj[key], PropertyType), null);
            }
            this.StateHasChanged();
        }
```
**Error stack trace**
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at Syncfusion.EJ2.Blazor.BaseComponent.UpdateModel(Dictionary`2 obj) in D:\development\Source\gitlab\ej2\cwd\release\placeholder\Syncfusion.EJ2.Blazor\Base\Base.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at Syncfusion.EJ2.Blazor.BaseComponent.UpdateModel(Dictionary`2 obj) in D:\development\Source\gitlab\ej2\cwd\release\placeholder\Syncfusion.EJ2.Blazor\Base\Base.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (https://localhost:44360/_framework/blazor.server.js:8:21783)
    at https://localhost:44360/_framework/blazor.server.js:8:21434
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44360/_framework/blazor.server.js:8:21403)
    at https://localhost:44360/_framework/blazor.server.js:1:16653
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44360/_framework/blazor.server.js:1:16624)
    at e.processIncomingData (https://localhost:44360/_framework/blazor.server.js:1:14624)
    at e.connection.onreceive (https://localhost:44360/_framework/blazor.server.js:1:11165)
    at WebSocket.i.onmessage (https://localhost:44360/_framework/blazor.server.js:1:30454)
throwError @ ejs.interop.js:567
updateModel @ ejs.interop.js:232
async function (async)
updateModel @ ejs.interop.js:227
(anonymous) @ treemap.ts:2
merge @ treemap.ts:2
e.setProperties @ treemap.ts:2
t.setModelValue @ treemap.ts:2
t.changeTrigger @ treemap.ts:2
t.applyFunction @ treemap.ts:2
ejs.interop.js:567 System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'String'.
   at System.Text.Json.JsonDocument.GetArrayIndexElement(Int32 currentIndex, Int32 arrayIndex)
   at System.Text.Json.JsonElement.get_Item(Int32 index)
   at Syncfusion.EJ2.Blazor.BaseComponent.UpdateModel(Dictionary`2 obj) in D:\development\Source\gitlab\ej2\cwd\release\placeholder\Syncfusion.EJ2.Blazor\Base\Base.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
Error: System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'String'.
   at System.Text.Json.JsonDocument.GetArrayIndexElement(Int32 currentIndex, Int32 arrayIndex)
   at System.Text.Json.JsonElement.get_Item(Int32 index)
   at Syncfusion.EJ2.Blazor.BaseComponent.UpdateModel(Dictionary`2 obj) in D:\development\Source\gitlab\ej2\cwd\release\placeholder\Syncfusion.EJ2.Blazor\Base\Base.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (https://localhost:44360/_framework/blazor.server.js:8:21783)
    at https://localhost:44360/_framework/blazor.server.js:8:21434
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44360/_framework/blazor.server.js:8:21403)
    at https://localhost:44360/_framework/blazor.server.js:1:16653
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44360/_framework/blazor.server.js:1:16624)
    at e.processIncomingData (https://localhost:44360/_framework/blazor.server.js:1:14624)
    at e.connection.onreceive (https://localhost:44360/_framework/blazor.server.js:1:11165)
    at WebSocket.i.onmessage (https://localhost:44360/_framework/blazor.server.js:1:30454)
```

**Comment by Andrzej-W** [comment]
Error message tells you everything: Collection was modified; enumeration operation may not execute.
```c#
obj[key] = new object[] {startDate, endDate};
```

**Comment by karthickthangasamy** [comment]
@Andrzej-W : Yes, converting the date objects with `DateTimeOffset` is not possible with the context of `DateRangePicker` component rendering.
