### ISSUE TITLE
My Service throw an this exception sometimes. I do not find any solution to solve it. anybody can help me！

### ISSUE THREAD

**Issue by tarekgh** [aspnet/AspNetCore#11501]
_From @Rabbit021 on Friday, June 21, 2019 2:51:05 AM_

```
info: Microsoft.AspNetCore.Server.Kestrel[20]
      Connection id "0HLNFSN1JBVNR" request processing ended abnormally.
System.IO.FileNotFoundException: Could not find file 'Microsoft.AspNetCore.Server.Kestrel.Core.resources'.
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.AspNetCore.Server.Kestrel.Core.CoreStrings.GetString(String name, String[] formatterNames)
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.GetException(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.ThrowRequestRejected(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.EnsureHostHeaderExists()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

_Copied from original issue: dotnet/corefx#38745_

**Comment by tarekgh** [comment]
_From @Clockwork-Muse on Friday, June 21, 2019 3:16:28 AM_

Unfortunately, this is (probably) the wrong repo.  You _might_ have more luck on [AspNetCore](https://github.com/aspnet/AspNetCore) or StackOverflow, but you need to provide way more details.
For one thing, the exception is pretty clearly stating `FileNotFoundException` - have you verified that the listed file exists?

**Comment by Tratcher** [comment]
Please share a sample application that reproduces this problem.

What language is the operating system set to?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
