### ISSUE TITLE
RedisHubLifetimeManager OnDisconnectedAsync Exception

### ISSUE THREAD

**Issue by Coder3333** [aspnet/AspNetCore#11551]
I have a scenario where my SignalR hub and client are working just fine when I run inside Visual Studio on my Windows machine, but when I host my hub on Linux PCF, I get this error when my client tries to connect to the hub.

```
 fail: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[3]
Failed disposing connection nT7rFrB0J23JHgBwibeE2w.
System.NullReferenceException: Object reference not set to an instance of an object.
 at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.OnDisconnectedAsync(HubConnectionContext connection)
at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteApplication(ConnectionDelegate connectionDelegate, HttpConnectionContext connection)
at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
at System.IO.Pipelines.Pipe.GetReadAsyncResult()
at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
at Microsoft.AspNetCore.Http.Connections.Internal.Transports.ServerSentEventsTransport.ProcessRequestAsync(HttpContext context, CancellationToken token)
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully)
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully)
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully)
```

The only place in OnDisconnectedAsync that looks like it could produce a NullReferenceException is this:

```
            var feature = connection.Features.Get<IRedisFeature>();
            var groupNames = feature.Groups;

```
Under what circumstances would "feature" be null?  I do not have this problem with StackExchange Redis when I run the same code locally on Windows.

**Comment by anurse** [comment]
Can you collect server-side logs using the [guidance in our documentation](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2)?

Also, are you able to ping the redis node from the Linux machine/container/etc.?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
