### ISSUE TITLE
[Blazor] Unhandled exception. System.ArgumentException: Comments cannot be stored in a JsonDocument

### ISSUE THREAD

**Issue by enricoreich** [aspnet/AspNetCore#11600]
### Describe the bug
I using the latest SDK (3.0.100-preview7-012627) and created a simple Blazor Server-Side App with
`dotnet new blazorserverside`, build it and run it and then I get this error:

```
Unhandled exception. System.ArgumentException: Comments cannot be stored in a JsonDocument, only the Skip and Disallow comment handling modes are supported. (Parameter 'readerOptions')
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(Exception e)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at BlazorServerSideApp1.Program.Main(String[] args) in D:\Workspaces\_playground\Blazor\BlazorServerSideApp1\Program.cs:line 18
```

Program.cs Line 18:
![Screenshot_1](https://user-images.githubusercontent.com/316637/60197566-ea227880-983f-11e9-8896-5daf673dceee.png)

### To Reproduce
1. create a new Blazor Server-Side app with `dotnet new blazorserverside -n {nameOfProject}`
2. run `dotnet build`
3. run `dotnet run`

### Expected behavior
Kestrel should run without any error.

### Additional context
dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012627
 Commit:    86a2e1fec8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012627\

Host (useful for support):
  Version: 3.0.0-preview7-27826-01
  Commit:  d41f5ea7cc

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012627 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19325.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27826-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27826-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
cc @BrennanConroy

**Comment by BrennanConroy** [comment]
There are a couple breaking changes in corefx that we haven't consumed yet, and as a result weird things like this happen.

We'll be consuming the corefx changes later today and hopefully by tomorrow there will be a new sdk that works.

**Comment by enricoreich** [comment]
SDK 3.0.100-preview7-012687 is working so far. Thanks!
