### ISSUE TITLE
HubConnection with HttpTransportType.WebSockets StartAsync throws System.Net.WebSockets.WebSocketException : Unable to connect to the remote server

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore#11673]
### Describe the bug
Failure the connect to SignalR Hub using `HubConnection.StartAsync` with `HttpTransportType.WebSockets` option. It works fine from Javascript client.
### To Reproduce
1. Using this version of ASP.NET Core '...'
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.204
 Commit:    8757db13ec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.204/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.204 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
2. Run this code '....'
```
        [Fact]
        public async Task ReceiveMessageTest()
        {
            string echo = string.Empty;
            string message = "Integration Testing in Microsoft AspNetCore SignalR";
            IWebHostBuilder webHostBuilder = new WebHostBuilder()
                            .ConfigureServices(services => services.AddSignalR())
                            .Configure(app => app.UseSignalR(routes => routes.MapHub<ChatHub>("/chatHub", options => options.Transports = HttpTransportType.WebSockets)));
            TestServer server = new TestServer(webHostBuilder);
            HubConnection connection = new HubConnectionBuilder()
                            .WithUrl("http://localhost/chatHub", HttpTransportType.WebSockets, o => {
                                o.HttpMessageHandlerFactory = _ => server.CreateHandler();
                                o.Transports = HttpTransportType.WebSockets;
                                o.SkipNegotiation = true;
                            }).Build();
            connection.On<string>("ReceiveMessage", i => echo = i);
            await connection.StartAsync();
            await connection.InvokeAsync("ReceiveMessage", message);
            Assert.False(string.IsNullOrEmpty(echo));
            Assert.Equal(message, echo);
        }
```
3. With these arguments '....'
```
[xUnit.net 00:00:02.67]     Web.Api.IntegrationTests.SignalR.ChatHubTests.ReceiveMessageTest [FAIL]
Failed   Web.Api.IntegrationTests.SignalR.ChatHubTests.ReceiveMessageTest
Error Message:
 System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
Stack Trace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at Web.Api.IntegrationTests.SignalR.ChatHubTests.ReceiveMessageTest() in /usr/src/AspNetCoreApiStarter/src/Tests/Web.Api.IntegrationTests/SignalR/ChatHubTests.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
```
### Expected behavior
Expect it to works as in the case without using `HttpTransportType.WebSockets`. The application works fine from the browser though using the Javascript client.
```
var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub", {
    skipNegotiation: true,
    transport: signalR.HttpTransportType.WebSockets,
    accessTokenFactory: () => this.getToken()//document.getElementById("tokenInput").value
}).configureLogging(signalR.LogLevel.Trace).build();
```
### Additional context
Include the output of `dotnet --info`

**Comment by anurse** [comment]
To be clear, you're trying to connect to a `TestServer` instance and it's failing? That would be expected since SignalR doesn't currently support `TestServer`. The `HttpMessageHandlerFactory` on `HubConnectionOptions` isn't used for WebSockets (since WebSockets don't use the `HttpClient` API). So unfortunately this is expected behavior for now.

The recommended approach for testing a SignalR service is to launch Kestrel in-process and connect to it, in order to simulate a functioning WebSocket environment.

**Comment by khteh** [comment]
Any reference for doing that? I mean launching the Kerstrel in-process to test Signalr with websocket transport.

**Comment by anurse** [comment]
> Why and how would websocket transport be different in using HubConnection for testing?

Because the actual .NET Core APIs are different. `HttpClient` is used for everything except WebSockets. To use WebSockets, the [`ClientWebSocket`](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netframework-4.8) API must be used (`HttpClient` cannot perform the WebSocket handshake).

> Any reference for doing that? I mean launching the Kerstrel in-process to test Signalr with websocket transport.

We do it in our own tests, here: https://github.com/aspnet/AspNetCore/blob/master/src/SignalR/common/testassets/Tests.Utils/InProcessTestServer.cs#L81

Basically the gist is this:

1. Configure a `WebHost` using `http://127.0.0.1:0` as the URL:

```csharp
var host = new WebHostBuilder()
    .Configure(appBuilder => { /* configure SignalR, etc. here */ })
    .UseKestrel()
    .UseUrls(url)
    .UseContentRoot(Directory.GetCurrentDirectory())
    .Build();
```

2. Start the server in a background thread:

```csharp
await host.StartAsync();
```

3. Get the URL:

```csharp
var url = host.ServerFeatures.Get<IServerAddressesFeature>().Addresses.Single();
```

4. Use that url for testing.

Also, to be clear, I do agree this isn't the ideal situation. I've filed https://github.com/aspnet/AspNetCore/issues/11888 to track that specific improvement.
