### ISSUE TITLE
Can no longer run net48 web application after installing .Net Core 3 SDK

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#11823]
_From @Almenit on Friday, June 28, 2019 1:38:23 PM_

We have a Web application using .net 48 and ASP.Net Core. I tried to update to .Net Core 3 using the  3.0.100-preview6-012264 SDK. I manage to get that to work. When a later change back to the old branch (using net48). I can build the application but when I run it I get an  System.Reflection.ReflectionTypeLoadException with loader exceptions: Could not load file or assembly 'System.Runtime, Version=4.2.1.0. 

I tried to uninstall the 3.0.100-preview6-012264 SDK reinstall .net 48 SDK and 2.2 the .Net Core SDK. But still the same error.

``` Application startup exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Capish.Reflect.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\Repos\Reflect\Source\Capish.Reflect.Web\Startup.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[15:34:20 FTL] Application startup exception
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Capish.Reflect.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\Repos\Reflect\Source\Capish.Reflect.Web\Startup.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[15:34:20 FTL] Host terminated unexpectedly
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.Extensions.DependencyInjection.MvcCoreMvcBuilderExtensions.AddControllersAsServices(IMvcBuilder builder)
   at Capish.Reflect.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\Repos\Reflect\Source\Capish.Reflect.Web\Startup.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()```

_Copied from original issue: dotnet/core-sdk#2693_

**Comment by anurse** [comment]
_From @livarcocc on Friday, June 28, 2019 3:51:34 PM_

Can you share your csproj? Have you tried to clean/restore/build/run?

**Comment by anurse** [comment]
_From @Almenit on Friday, June 28, 2019 5:35:03 PM_

Yes I have tried to clean/restore/build/run (even a hard reset from git)

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UserSecretsId>secret</UserSecretsId>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <Company>A</Company>
    <Product>B</Product>
    <Copyright>Copyright </Copyright>
    <Description>application</Description>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0.0</Version>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <LangVersion>latest</LangVersion>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratedItemPatterns>build/**</GeneratedItemPatterns>
    <InteropsItemPatterns>bin/Release/net48/win10-x64/x64/**</InteropsItemPatterns>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(GeneratedItemPatterns);$(InteropsItemPatterns)</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Our.Internal.net.48" Version="1.1.0.1560483453" />
    <PackageReference Include="Our.2.Internal.net.48" Version="1.0.4.12457" />
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="Dapper.Contrib" Version="1.50.4" />
    <PackageReference Include="Dapper.SqlBuilder" Version="1.50.4" />
    <PackageReference Include="Destructurama.JsonNet" Version="1.2.1" />
    <PackageReference Include="JSNLog" Version="2.28.0" />
    <PackageReference Include="MemBus" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.3" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
    <PackageReference Include="Rhino.Licensing" Version="1.3.0" />
    <PackageReference Include="Scrutor" Version="2.2.2" />
    <PackageReference Include="Serilog" Version="2.7.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="2.6.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.108" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Database\Scripts\1.sql" />
    <None Remove="Content\css\error.css" />
    <None Remove="Database\Scripts\2.sql" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\css\error.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Database\Scripts\2.sql" />
    <EmbeddedResource Include="Database\Scripts\1.sql" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TypeScript\Messages\ExceptionMessagesTemplate.tt">
      <LastGenOutput>ExceptionMessagesTemplate.cs</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="TypeScript\Messages\ExceptionMessagesTemplate.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExceptionMessagesTemplate.tt</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="TypeScript\Messages\ExceptionMessagesTemplate.cs">
      <DependentUpon>ExceptionMessagesTemplate.tt</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Update="Content\Languages\en-US.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Content\Languages\sv-SE.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm run publish" />

    <ItemGroup>
      <_GeneratedFiles Include="$(GeneratedItemPatterns)" />
      <ContentWithTargetPath Include="@(_GeneratedFiles->'%(FullPath)')" RelativePath="%(_GeneratedFiles.Identity)" TargetPath="%(_GeneratedFiles.Identity)" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <_InteropFiles Include="$(InteropsItemPatterns)" />
      <ContentWithTargetPath Include="@(_InteropFiles->'%(FullPath)')" RelativePath="%(_InteropFiles.Identity)" TargetPath="%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>
  </Target>
</Project>
```

**Comment by anurse** [comment]
_From @livarcocc on Friday, June 28, 2019 10:20:13 PM_

@anurse can you take a first stab at this?

**Comment by anurse** [comment]
@Almenit can you share a runnable sample application that reproduces the issue? If that's not feasible, would it be possible for you to privately share the build/publish outputs so we can see the specific assemblies?

**Comment by Almenit** [comment]
Sure I will try to do that. But it will take same time since I'm on holiday.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Let us know when you've been able to get a sample together we can re-open the issue and investigate further!
