### ISSUE TITLE
Avoid throwing an exception if CircuitHost is not set up in the Hub

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#11879]
If a client isn't set up correctly, we get an exception logged in the server as so:

```
[04:23:10.228]       Failed to invoke hub method 'BeginInvokeDotNetFromJS'.
[04:23:10.229] System.InvalidOperationException: The CircuitHost is null. This is due to an exception thrown during initialization.
[04:23:10.229]    at Microsoft.AspNetCore.Components.Server.ComponentHub.EnsureCircuitHost()
[04:23:10.230]    at lambda_method(Closure , Object , Object[] )
[04:23:10.230]    at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
[04:23:10.231]    at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
[04:23:10.232]    at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
[04:23:10.232]    at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamResponse, Boolean isStreamCall)
```

We should instead just log these as low level Debug statements. Regular clients should nearly never run in to this error.

**Comment by rynowak** [comment]
For clarity's sake, we don't want to turn these into exceptions because it allows a misbehaving client to flood logs.

**Comment by javiercn** [comment]
I did this as part of 4bbfd4dd0af0f2ec475fd969e3015524af1f96e0
