### ISSUE TITLE
Docker runtime is not able to binding gRPC service

### ISSUE THREAD

**Issue by xgenvn** [aspnet/AspNetCore#11899]
### Describe the bug
- It's able to build and run gRPC using default template under Windows, but cannot work using docker image build.

### Logs
```
todo-service_1  | crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
todo-service_1  |       Application startup exception
todo-service_1  | System.InvalidOperationException: Error binding gRPC service 'TodoService'.
todo-service_1  |  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
todo-service_1  |  ---> System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithDisplayName(Microsoft.AspNetCore.Builder.IEndpointConventionBuilder, System.String)'.
todo-service_1  |    at Grpc.AspNetCore.Server.Internal.GrpcServiceBinder`1.AddMethodCore(IMethod method, RequestDelegate requestDelegate, List`1 metadata)
todo-service_1  |    at Grpc.AspNetCore.Server.Internal.GrpcServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
todo-service_1  |    at TodoPackage.TodoService.BindService(ServiceBinderBase serviceBinder, TodoServiceBase serviceImpl) in /app/obj/Release/netcoreapp3.0/TodoGrpc.cs:line 98
todo-service_1  |    --- End of inner exception stack trace ---
todo-service_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
todo-service_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.ReflectionBind[TService](ServiceBinderBase binder, TService service)
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder, Action`1 configureOptions)
todo-service_1  |    --- End of inner exception stack trace ---
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder, Action`1 configureOptions)
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder)
todo-service_1  |    at CoreGrpcCI.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints) in /app/Startup.cs:line 36
todo-service_1  |    at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
todo-service_1  |    at CoreGrpcCI.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /app/Startup.cs:line 37
todo-service_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
todo-service_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
todo-service_1  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
todo-service_1  | Unhandled exception. System.InvalidOperationException: Error binding gRPC service 'TodoService'.
todo-service_1  |  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
todo-service_1  |  ---> System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Microsoft.AspNetCore.Builder.RoutingEndpointConventionBuilderExtensions.WithDisplayName(Microsoft.AspNetCore.Builder.IEndpointConventionBuilder, System.String)'.
todo-service_1  |    at Grpc.AspNetCore.Server.Internal.GrpcServiceBinder`1.AddMethodCore(IMethod method, RequestDelegate requestDelegate, List`1 metadata)
todo-service_1  |    at Grpc.AspNetCore.Server.Internal.GrpcServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
todo-service_1  |    at TodoPackage.TodoService.BindService(ServiceBinderBase serviceBinder, TodoServiceBase serviceImpl) in /app/obj/Release/netcoreapp3.0/TodoGrpc.cs:line 98
todo-service_1  |    --- End of inner exception stack trace ---
todo-service_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
todo-service_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.ReflectionBind[TService](ServiceBinderBase binder, TService service)
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder, Action`1 configureOptions)
todo-service_1  |    --- End of inner exception stack trace ---
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder, Action`1 configureOptions)
todo-service_1  |    at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder)
todo-service_1  |    at CoreGrpcCI.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints) in /app/Startup.cs:line 36
todo-service_1  |    at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
todo-service_1  |    at CoreGrpcCI.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /app/Startup.cs:line 37
todo-service_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
todo-service_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
todo-service_1  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
todo-service_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
todo-service_1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
todo-service_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
todo-service_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
todo-service_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
todo-service_1  |    at CoreGrpcCI.Program.Main(String[] args) in /app/Program.cs:line 11
grpc_todo-service_1 exited with code 139
```

### Additional Information

Dockerfile
```
#FROM mcr.microsoft.com/dotnet/core-nightly/aspnet:3.0
FROM mcr.microsoft.com/dotnet/core-nightly/sdk:3.0-bionic AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
COPY NuGet.config ./
RUN dotnet restore

# copy everything else and build app
COPY . ./
WORKDIR /app
RUN dotnet publish -c Release -o out

# FROM mcr.microsoft.com/dotnet/core-nightly/aspnet:3.0 as runtime
# WORKDIR /app
# COPY --from=build /app/out ./

ENTRYPOINT ["dotnet", "/app/out/CoreGrpcCI.dll"]
```

I have tried several different versions but not been able to make it work.
The normal build in Windows works fine.

**Comment by xgenvn** [comment]
#### Updated:
- My working version under Windows is built using netcore3-preview5. Upgrading to preview6 throws the same issue.

**Comment by xgenvn** [comment]
Closed.
Fixed by updating packages to:
```
    <PackageReference Include="Grpc.AspNetCore.Server" Version="0.1.21-pre1" />
    <PackageReference Include="Google.Protobuf" Version="3.8.0" />

    <PackageReference Include="Grpc.Tools" Version="1.21.0" PrivateAssets="All" />
```
