### ISSUE TITLE
Decide if server-side Blazor needs limits on how many events can be delivered and the max size for events

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#12003]

**Comment by rynowak** [comment]
Do you have any data or examples of tests that help us understand the priority of this?

**Comment by javiercn** [comment]
In process, so far with a client I can cause exceptions on the server

```
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'BeginInvokeDotNetFromJS'.
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
 ---> System.IO.InvalidDataException: Deserializing object of the `String` type for 'argument' failed.
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at MessagePack.MessagePackReader.GetStringLengthInBytesSlow(Byte code)
   at Microsoft.AspNetCore.Components.Server.BlazorPack.BlazorPackHubProtocol.DeserializeObject(MessagePackReader& reader, Type type, String field) in C:\work\AspNetCore\src\Components\Server\src\BlazorPack\BlazorPackHubProtocol.cs:line 474
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Server.BlazorPack.BlazorPackHubProtocol.DeserializeObject(MessagePackReader& reader, Type type, String field) in C:\work\AspNetCore\src\Components\Server\src\BlazorPack\BlazorPackHubProtocol.cs:line 474
   at Microsoft.AspNetCore.Components.Server.BlazorPack.BlazorPackHubProtocol.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes) in C:\work\AspNetCore\src\Components\Server\src\BlazorPack\BlazorPackHubProtocol.cs:line 258
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Server.BlazorPack.BlazorPackHubProtocol.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes) in C:\work\AspNetCore\src\Components\Server\src\BlazorPack\BlazorPackHubProtocol.cs:line 265
   at Microsoft.AspNetCore.Components.Server.BlazorPack.BlazorPackHubProtocol.CreateInvocationMessage(MessagePackReader& reader, IInvocationBinder binder, Int32 itemCount) in C:\work\AspNetCore\src\Components\Server\src\BlazorPack\BlazorPackHubProtocol.cs:line 123
```
And I get the memory from the server to grow up to 3GB

**Comment by rynowak** [comment]
> In process, so far with a client

Doesn't SignalR enforce a default limit on the message size from a client?

How will an external client run code in process on a deployed application?

**Comment by javiercn** [comment]
> In process, so far with a client

I meant with 1 client.


> Doesn't SignalR enforce a default limit on the message size from a client?

Yes, I'm playing within those rules. Sending events with 31K

**Comment by rynowak** [comment]
Ok good, this seems relevant then 👍

**Comment by mkArtakMSFT** [comment]
Closing this as we've found out that things look good enough and we don't need to do anything here.
