### ISSUE TITLE
The "FindAssembliesWithReferencesTo" task failed unexpectedly after Visual Studio 2019 update

### ISSUE THREAD

**Issue by BretMishler** [aspnet/AspNetCore#12070]
I keep a vanilla copy of a brand new server+client Blazor project following the instructions on [Microsofts docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio) so that way when something breaks after an update in a larger project, I can come to this one to try and more easily troubleshoot.

It looks something like this: https://github.com/BretMishler/LoanCalc

As you can see, other than the little controller I added to play with, it's pretty vanilla and has worked fine. It's been a little over a week since I've tried running it and since that time, the only thing that has changed has been an update to Visual Studio 2019 (maybe two?). 

Now, when I run the project, I get this error which causes the solution to not build:

```
Error MSB4018 The "FindAssembliesWithReferencesTo" task failed unexpectedly. System.IO.FileNotFoundException: Could not find file 'C:\Users\bmishl\source\repos\BretMishler\LoanCalc\LoanCalc.Client\bin\Debug\netstandard2.0\LoanCalc.Client.dll'.
File name: 'C:\Users\bmishl\source\repos\BretMishler\LoanCalc\LoanCalc.Client\bin\Debug\netstandard2.0\LoanCalc.Client.dll'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.AspNetCore.Razor.Tasks.ReferenceResolver.GetReferences(String file)
   at Microsoft.AspNetCore.Razor.Tasks.ReferenceResolver.Resolve(ClassifiedAssemblyItem classifiedItem)
   at Microsoft.AspNetCore.Razor.Tasks.ReferenceResolver.ResolveAssemblies()
   at Microsoft.AspNetCore.Razor.Tasks.FindAssembliesWithReferencesTo.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	LoanCalc.Server	C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets	53	
```

Also to note is that when I go through the steps to make a new solution, only Blazor (server-side) shows up. Client side is missing as an option, though normally I've been creating the project in the command line anyways.

**Comment by vishnupv** [comment]
I am having the same issue. I think my issue have something to do with Dot Net framework being lower.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BretMishler.
The error you're receiving here is actually a bit confusing, and we plan to address that as part of https://github.com/aspnet/AspNetCore/issues/11226.
The actual issue is that the dependency failed to build, so you will have to find what actually have failed during that build.
