### ISSUE TITLE
Method of transferring app to server causes error in grpc_csharp_ext.x64.dll

### ISSUE THREAD

**Issue by steveoh** [aspnet/AspNetCore#12101]
### Describe the bug

I am using npm, grunt, and dotnet to built and deploy a `dotnet new react` project on osx. When this pipeline runs, the project fails to start with a 502.5 error. If I go to the server and execute `dotnet app.dll` I get a strange error.

#### Stack trace

```shell
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: Error loading native library "C:\...\runtimes/win/native\grpc_csharp_ext.x64.dll".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSink..ctor(GoogleCloudLoggingSinkOptions sinkOptions, MessageTemplateTextFormatter messageTemplateTextFormatter, Int32 batchSizeLimit, TimeSpan period)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSinkExtensions.GoogleCloudLogging(LoggerSinkConfiguration loggerConfiguration, GoogleCloudLoggingSinkOptions sinkOptions, Nullable`1 batchSizeLimit, Nullable`1 period, String outputTemplate)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSinkExtensions.GoogleCloudLogging(LoggerSinkConfiguration loggerConfiguration, String projectId, String resourceType, String logName, Dictionary`2 labels, Dictionary`2 resourceLabels, Boolean useSourceContextAsLogName, Boolean useJsonOutput, String googleCredentialJson, String serviceName, String serviceVersion, Nullable`1 batchSizeLimit, Nullable`1 period, String outputTemplate)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at app.Program.Main(String[] args) in /Users/.../src/Program.cs:line 17
```

#### Somewhat related issues?

https://github.com/grpc/grpc/issues/11914
https://github.com/grpc/grpc/issues/12570

### Reproduce

Currently, I use npm scripts to run 

1. `dotnet publish -c Release`
1. `npm build` to build the react app 
1. grunt-contrib-compress to compress the `bin/release/netcoreapp2.2/publish/` folder
1. grunt-ssh then pushes an `app_offline.htm` the file to a windows 2016 server running openssh to stop the app. 
1. grunt-ssh sends the publish zip and unzips the project overwriting the old app.

The strangest part is if I RDP into the server and copy the files from the same publish folder the application starts as expected.

What could possibly be causing the above error in the compression, file transfer, and uncompression process?

**Comment by davidfowl** [comment]
This isn't related to ASP.NET Core or GRPC. It looks like an issue with the serilog GCP logging sink which happens to be using the native interop C# grpc implementation.  The issue should be moved to this repository https://github.com/manigandham/serilog-sinks-googlecloudlogging

**Comment by steveoh** [comment]
Thanks for looking.
