### ISSUE TITLE
Getting started with Entity FRamework Persist Keys for dataprotection

### ISSUE THREAD

**Issue by djhaanpaa** [aspnet/AspNetCore#12333]
Trying to setup entity framework storage for asp.net dataprotection api
Results in the following

```
: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.6-servicing-10079 initialized 'AppDatabaseContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=DeltaCIM, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (98ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (98ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (87ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
info: Microsoft.EntityFrameworkCore.Migrations[20405]
      No migrations were applied. The database is already up to date.
fail: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[48]
      An error occurred while reading the key ring.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking[TEntity](IQueryable`1 source)
   at Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.EntityFrameworkCoreXmlRepository`1.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
info: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionStartupFilter[0]
      Key ring failed to load during application startup.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsNoTracking[TEntity](IQueryable`1 source)
   at Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.EntityFrameworkCoreXmlRepository`1.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.Internal.DataProtectionStartupFilter.Configure(Action`1 next)
Hosting environment: Development
Content root path: /Users/dhaanpaa/Projects/***-***
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

1. Using this version of ASP.NET Core '2.2.301'
2. Run this code 

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddDbContext<AppDatabaseContext>(options =>
            {
                if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Production")
                {
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), builder =>
                    {
                        builder.EnableRetryOnFailure();
                        builder.MigrationsAssembly(typeof(AppDatabaseContext).Assembly.FullName);
                    });

                }
                else
                {
                    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), builder =>
                    {
                        builder.EnableRetryOnFailure();
                        builder.MigrationsAssembly(typeof(AppDatabaseContext).Assembly.FullName);
                    });
                }

            });




            services.AddOptions();

            // Token acquisition service based on MSAL.NET
            // and chosen token cache implementation
            // Token acquisition service based on MSAL.NET
            // and chosen token cache implementation
            services.AddAzureAdV2Authentication(Configuration)
                .AddMsal(new string[] {Constants.ScopeUserRead})
                .AddSqlAppTokenCache(
                    new MSALSqlTokenCacheOptions(Configuration.GetConnectionString("DefaultConnection")))
                .AddSqlPerUserTokenCache(
                    new MSALSqlTokenCacheOptions(Configuration.GetConnectionString("DefaultConnection")));

            // Add Graph
            services.AddGraphService(Configuration);

            services.AddManagerServices();

            services.AddHttpContextAccessor();
            services.AddSession();
            services.AddMvc(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();
                    options.Filters.Add(new AuthorizeFilter(policy));
                }).AddJsonOptions(options =>
                    options.SerializerSettings.ContractResolver =
                        new Newtonsoft.Json.Serialization.DefaultContractResolver())
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.BuildServiceProvider().GetService<AppDatabaseContext>().Database.Migrate();


            services.AddDataProtection()
                .SetApplicationName("***")
                .SetDefaultKeyLifetime(TimeSpan.FromDays(7))
                .PersistKeysToDbContext<AppDatabaseContext>();
        }
```

3. See error

### Expected behavior
The application will work

### Additional context
dhaanpaa$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.301
 Commit:    70d6be0814

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.301/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by djhaanpaa** [comment]
This is connecting to an azure sql server

**Comment by AndrewNikolin** [comment]
I'm facing exactly the same issue now with the same stacktrace and exception

**Comment by AndrewNikolin** [comment]
@djhaanpaa hi! looks i've solved the problem. can you share the code of your AppDatabaseContext class?

**Comment by djhaanpaa** [comment]
public class AppDatabaseContext : DbContext, IDataProtectionKeyContext
    {
        protected AppDatabaseContext()
        {
        }

        public AppDatabaseContext(DbContextOptions<AppDatabaseContext> options) : base(options)
        {
        }
        /// <summary>
        /// The app token cache table
        /// </summary>
        public DbSet<AppTokenCache> AppTokenCache { get; set; }

        /// <summary>
        /// The user token cache table
        /// </summary>
        public DbSet<UserTokenCache> UserTokenCache { get; set; }

        /// ...
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<TenantRegistrationRequest> TenantRegistrationRequests { get; set; }
        public DbSet<DataProtectionKey> DataProtectionKeys { get; }
    }

**Comment by AndrewNikolin** [comment]
@djhaanpaa just the same problem I had, you missed to add `set;` property on DataProtectionKeys

**Comment by djhaanpaa** [comment]
Added set and it now works @AndrewNikolin

**Comment by csharpfritz** [comment]
Hey friends, if the correct configuration for the `IDataProtectionKeyContext` should have the `set;` accessor provided as well, can we add that to the interface so that everyone gets this implementation correctly configured in the Entity Framework context?
