### ISSUE TITLE
App crashes in release/hosted mode but not in Visual Studio

### ISSUE THREAD

**Issue by Kool-Koder** [aspnet/AspNetCore#12396]
Somehow my app connection to database fails once it is exported out of Visual Studio 2019. However, it works fine inside VS2019, whereby I can connect and read the values inside the Database.

The stack trace seen here throws the exception all the way to DBInitializer, then up to Program.cs. The code structure is very similar to the tutorial provided by Microsoft. Thank you.

```
An error occurred creating the DB for Identity
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
```

**Comment by davidfowl** [comment]
Looks like a missing or incorrect connection string.

**Comment by Kool-Koder** [comment]
Hmm the interesting part is it runs inside Visual Studio though. Is there a major difference in development and release mode which will affect the connection strings? Thank you!

**Comment by davidfowl** [comment]
Its likely nothing to do with debug/release mode, it's likely the fact that you're running in "production" mode. Where are your settings?

**Comment by Kool-Koder** [comment]
Which settings should I show?

**Comment by davidfowl** [comment]
Do you have code in Startup.cs reading a connection string? Any calls to GetConnectionString?

**Comment by Kool-Koder** [comment]
This 2 codes are from Startup.cs. While debugging in Visual Studio, I can see the connection String.
```
//Identity Db Context
services.AddDbContext<ApplicationDbContext>(options =>
options.UseSqlServer(
GetRdsConnectionStringIdentity()));
```

```
private string GetRdsConnectionStringIdentity()
{
      string hostname = Configuration.GetValue<string>("RDS_HOSTNAME");
      string port = Configuration.GetValue<string>("RDS_PORT");
      string dbname = "ASPNETIdentityUser";
      string username = Configuration.GetValue<string>("RDS_USERNAME");
      string password = Configuration.GetValue<string>("RDS_PASSWORD");
      return $"Data Source={hostname},{port};Initial Catalog={dbname};User ID={username};Password={password};";
}
```

In the release mode after it is exported, following the stack trace, this seems to be the error. The error is the same error as I have originally posted.

In Program.cs, it will call DbInitializer to check the database and stuff.
`DbInitializer.InitializeIdentity(contextIdentity);`

This is the DBInitializer section and it is failing the moment it tries to check if the database is created.
```
public static void InitializeIdentity(ApplicationDbContext context)
        {
            context.Database.EnsureCreated();

            if (context.AspNetUsers.Any())
            {
                return;   // DB has been seeded
            }
        }
```

**Comment by Kool-Koder** [comment]
More information to help log this issue. This is a .NET CORE 2.2 App. So the original project, I tried to access the database when it is hosted but it doesn't work. It works locally when running in VS2019. I then proceeded to test with an older project which was originally 2.1 but upgraded to 2.2. It works and can connect to the database even when hosted. Next I create a new project from the base template and added in the least amount of codes needed to test the database connection. However it didn't work.

It seems like there may be a bug with the latest project. It works inside Visual Studio, but it does not work when hosted.

**Comment by davidfowl** [comment]
It just sounds like maybe those configuration settings may be null in production. Did you set `RDS_HOSTNAME`, `RDS_PORT`, `RDS_USERNAME` and `RDS_PASSWORD`?

**Comment by Kool-Koder** [comment]
Hmm. Yes I did. I got an update. I messed around with some of the codes in Startup.cs, add some exception handling here and there, no new code additions, re-hosted and it works now. I didn't manage to trace down the root cause... A pretty weird bug.

**Comment by metalglove** [comment]
I had the same problem yesterday, but a restart of the SQL server fixed this for me.

**Comment by Kool-Koder** [comment]
Hmm upon tracing further the root cause for me is that it seems that the configuration file is not exported in a published/hosted app?

Example for this line of code when working in VS I can retrieve the data. However in published mode it doesn't seem to. So I played around with the code and return a hardcoded string for the DB name instead of relying on Configuration files. So far it seems to be 100% stable after the change.

But would that be any security implications for hard coding the SQL connection string into the codes itself? Thank you.

`string hostname = Configuration.GetValue<string>("RDS_HOSTNAME");`

**Comment by metalglove** [comment]
Check the File Properties for your appSettings.json file and make sure *Copy to Output Directory* is set to *Copy if newer*. This will make sure it is copied to your output directory. What I like to do in my projects is to have a try-catch for loading the configuration.
```csharp
IConfiguration configuration;
try
{
  configuration = ConfigurationLoader.GetConfiguration("appSettings");
}
catch (Exception)
{
  Console.WriteLine("Please check if you have a valid appSettings.json!");
  CancellationTokenSource.Cancel();
  return;
}
```

**Comment by Kool-Koder** [comment]
I see. Thanks for sharing. Will take a look at that. :)

**Comment by Pilchie** [comment]
Closing since it's been 7 days since the last comment.  Any more needed here?
