### ISSUE TITLE
Unhandled exception after migrating to preview7

### ISSUE THREAD

**Issue by mihaimyh** [aspnet/AspNetCore#12493]
Upgrading a server-side blazor app to preview 7 throws the following exception when navigating to a component:

```
Microsoft.AspNetCore.SignalR.HubConnectionContext: Information: Completed connection handshake. Using HubProtocol 'blazorpack'.
Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer: Warning: Unhandled exception rendering component: Method not found: 'Void Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddMultipleAttributes(Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,!!0>>)'.

System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddMultipleAttributes(Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,!!0>>)'.
   at BlazorStrap.Util.DynamicElement.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Server.ComponentHub: Warning: Unhandled Server-Side exception

System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddMultipleAttributes(Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,!!0>>)'.
   at BlazorStrap.Util.DynamicElement.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
```

**Comment by mihaimyh** [comment]
Closing this since the exception is thrown by libraries not yet updated to preview 7.
