### ISSUE TITLE
Microsoft.AspNetCore.Authentication.Negotiate handler returns 500 error if user enters invalid credentials.

### ISSUE THREAD

**Issue by igor-tk** [aspnet/AspNetCore#12566]
### Description
Microsoft.AspNetCore.Authentication.Negotiate handler returns 500 error (instead of 401) if user enters invalid credentials. 

### To Reproduce
1. ASP.NET Core - 'aspnetcore-runtime-3.0.0-preview7' (Windows, Linux, x64 )
2. Open browser and go to page secured with Microsoft.AspNetCore.Authentication.Negotiate handler. When browser asks for user credentials enter wrong credentials.
3. Server returns 500 error. User cannot enter credentials anymore.

### Expected behavior
If server returns 500 error code browser caches user credentials and if they were wrong user cannot enter valid credetials any more until browser is restarted. Expected behavior: return 401 in that case so that user could enter credentials again. 
And, in my opinion, log contains too many errors for controlled behavior like that.

### Log from server
```
2019-07-25 13:26:10.346 +03:00 [ERR] An exception occurred while processing the authentication request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x8009030C): The logon attempt failed
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(String incomingBlob)
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
2019-07-25 13:26:10.382 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x8009030C): The logon attempt failed
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(String incomingBlob)
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2019-07-25 13:26:10.388 +03:00 [ERR] An exception was thrown attempting to execute the error handler.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (9): The storage control block address is invalid.
   at System.Net.NTAuthentication.get_AssociatedName()
   at System.Net.Security.NegotiateStreamPal.GetIdentity(NTAuthentication context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetIdentity()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
2019-07-25 13:26:10.397 +03:00 [ERR] Connection id "0HLOGT7OB5ATV", Request id "0HLOGT7OB5ATV:00000003": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x8009030C): The logon attempt failed
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(String incomingBlob)
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by blowdart** [comment]
What browser are you using? 

Negotiate is mean for intranets, it's there for integrated auth, not for exposing to non-domain joined clients.

@Tratcher - despite the "misuse" we should be reprompting.

**Comment by Tratcher** [comment]
Mitigation: Implement the OnAuthenticationFailed event and skip the error.
https://github.com/aspnet/AspNetCore/blob/7a496ec162daffd034740e11935fdf61e8beb06e/src/Security/Authentication/Negotiate/src/NegotiateHandler.cs#L194-L200
```
                options.Events = new NegotiateEvents()
                {
                    OnAuthenticationFailed = context =>
                    {
                        context.SkipHandler();
                        return Task.CompletedTask;
                    }
                };
```

**Comment by anurse** [comment]
We'll repro and investigate a bit in preview 9, but it's likely a fix won't come until 3.1.

**Comment by igor-tk** [comment]
> What browser are you using?
> 
> Negotiate is mean for intranets, it's there for integrated auth, not for exposing to non-domain joined clients.
> 
> @Tratcher - despite the "misuse" we should be reprompting.

I use Google Chrome 75. All tests were made in intranet. All machines were joined to domain. If user authenticated without prompt for credentials it's ok. When I set "Prompt for user name and password" in browser settings and enter wrong credentials I get described issue. IE11 still prompts for credentials again, but log has strange message:

 Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (9): The storage control block address is invalid.
   at System.Net.NTAuthentication.get_AssociatedName()
   at System.Net.Security.NegotiateStreamPal.GetIdentity(NTAuthentication context)

If I deploy web site on domain joined linux machine  (Debian) I can successfully  authenticate without password. But when I set "Prompt for user name and password" or use URL with full domain name (cross domain, trusted forests, same user) I got prompt for credentials. If I enter wrong credentials I get 500 error, described issue, but another log:

[ERR] An unhandled exception has occurred while executing the request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - An unsupported mechanism was requested.
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)

**Comment by blowdart** [comment]
IE shouldn't be prompting ever, that's super weird. Does Edgework?

@Tratcher did we test with the deprecated browsers?

**Comment by Tratcher** [comment]
> @Tratcher did we test with the deprecated browsers?

Minimally. Though I read this "IE11 still prompts for credentials again, but log has strange message" as still applying to the wrong-password scenario and IE handling it better than the others.

**Comment by igor-tk** [comment]
> Does Edge work?

Edge prompts for credentials 3 times (like IE11).

**Comment by igor-tk** [comment]
> Mitigation: Implement the OnAuthenticationFailed event and skip the error.
> 
> ```
>                 options.Events = new NegotiateEvents()
>                 {
>                     OnAuthenticationFailed = context =>
>                     {
>                         context.SkipHandler();
>                         return Task.CompletedTask;
>                     }
>                 };
> ```

This workaround does not help - still get 500 error in browser.

**Comment by igor-tk** [comment]
New info. When deployed on linux (joined to AD) and user enters valid credentials server returns 500. Log has message:

 An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - An unsupported mechanism was requested.
at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)

Is it another bug? 

Without prompt for user credentials (automatic login) it works. Tried with Chrome, IE11, Edge

**Comment by Tratcher** [comment]
> > Mitigation: Implement the OnAuthenticationFailed event and skip the error.
> > ```
> >                 options.Events = new NegotiateEvents()
> >                 {
> >                     OnAuthenticationFailed = context =>
> >                     {
> >                         context.SkipHandler();
> >                         return Task.CompletedTask;
> >                     }
> >                 };
> > ```
> 
> This workaround does not help - still get 500 error in browser.

Ah, there's a secondary exception:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (9): The storage control block address is invalid.
   at System.Net.NTAuthentication.get_AssociatedName()
   at System.Net.Security.NegotiateStreamPal.GetIdentity(NTAuthentication context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetIdentity() in D:\github\AspNetCore\src\Security\Authentication\Negotiate\src\Internal\ReflectedNegotiateState.cs:line 88
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync() in D:\github\AspNetCore\src\Security\Authentication\Negotiate\src\NegotiateHandler.cs:line 254
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync() in D:\github\AspNetCore\src\Security\Authentication\Core\src\AuthenticationHandler.cs:line 138
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme) in D:\github\AspNetCore\src\Http\Authentication.Core\src\AuthenticationService.cs:line 77
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in D:\github\AspNetCore\src\Security\Authentication\Core\src\AuthenticationMiddleware.cs:line 54
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) in D:\github\AspNetCore\src\Middleware\Diagnostics\src\DeveloperExceptionPage\DeveloperExceptionPageMiddleware.cs:line 94
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 24.3119ms 500 text/plain
```

Here's an alternate mitigation:
```
                    options.Events = new NegotiateEvents()
                    {
                        OnAuthenticationFailed = context =>
                        {
                            context.Response.StatusCode = 401;
                            context.HandleResponse();
                            return Task.CompletedTask;
                        }
                    };
```

**Comment by Tratcher** [comment]
Note to self: before invoking OnAuthenticationFailed we should clear the connection state and _negotiateState. The secondary exception above is caused by accessing _negotiateState after it has already failed.

**Comment by Tratcher** [comment]
Good news: I can get granular errors that translate to 401 or 400 on Windows.
Bad news: Linux does not surface any granular error codes, only text.

**Comment by igor-tk** [comment]
> Here's an alternate mitigation:
> 
> ```
>                     options.Events = new NegotiateEvents()
>                     {
>                         OnAuthenticationFailed = context =>
>                         {
>                             context.Response.StatusCode = 401;
>                             context.HandleResponse();
>                             return Task.CompletedTask;
>                         }
>                     };
> ```

Tried this mitigattion on Windows, with Chrome.
Server returns 401 several times but browser didn't prompt for user credentials. If  I reload the page server returns 500 untill i restart ASP.NET Core service.

**Comment by Tratcher** [comment]
> If I reload the page I get 500 untill i restart ASP.NET Core service.

Or restart the browser, correct? Negotiate uses persisted connection state.

**Comment by igor-tk** [comment]
Not sure. Check again on monday.

**Comment by Tratcher** [comment]
Verification note: Make sure to test this with the corefx change.

**Comment by igor-tk** [comment]
.NET Core SDK 3.0.100-preview7-012821, self-contained app with mitigation, Chrome.

Windows - server returns 401 2 times, browser does not prompt for user credentials. Browser restart helps.

Linux - server returns 401 1 time, browser does not prompt for user credentials. Page refresh helps.
