### ISSUE TITLE
Unable to start Kestrel - System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by stephenschwan** [aspnet/AspNetCore#12573]
Random start up error after a restart of app service.  A restart is required to fix the issue.

**Steps to reproduce the behavior:**
- transient, cannot reproduce on command, but happens consistently
- running asp.net core 2.2 with Azure S2 App Service. 
- out of process hosting
- not all instances will experience, can be just 1 out of x instances after restart

**Error:**
```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Listen(Int32 backlog)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Listen(Int32 backlog)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Microsoft.Eis.InboundService.Program.Main(String[] args) in D:\a\1\s\InboundService\InboundService\Program.cs:line 15
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
Hosting environment: Production
Content root path: D:\home\site\wwwroot
Now listening on: http://127.0.0.1:23508
Application started. Press Ctrl+C to shut down.
Application is shutting down...
```

**Comment by dazinator** [comment]
Just experienced the same thing, using VS 2019 latest preview release, with a solution on preview-6 (global.json)

**Comment by jkotalik** [comment]
This feels like ANCM out of process is giving a port to the app and the app can't listen to it. However, it's odd that the app said it was able to listen to http://127.0.0.1:23508. Are these logs from the same process, or from different processes? ANCM will try to restart the app multiple times, so it should eventually succeed.

Do you have any event logs from ANCM here?

**Comment by stephenschwan** [comment]
Based on the event logs, it looks like the third try did succeed (and the stack trace above).

So, maybe this is something I don't need to worry about as it will eventually resolve itself.

**start - 7/19**
```
 <Event>
        <System>
            <Provider Name="IIS AspNetCore Module V2"/>
            <EventID>1001</EventID>
            <Level>4</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2019-07-19T16:35:12Z"/>
            <EventRecordID>20200468</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD00155D4CDD6D</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application '/LM/W3SVC/1905298837/ROOT' started process '19892' successfully and process '0' is listening on port '23508'.</Data>
            <Data>Process Id: 15088.</Data>
            <Data>File Version: 12.2.19081.4. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 5cb615fcbe8559e49042e93394008077e30454c0</Data>
        </EventData>
    </Event>
```
**shutdown - 7/24**
```
<Event>
        <System>
            <Provider Name="IIS AspNetCore Module V2"/>
            <EventID>1030</EventID>
            <Level>4</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2019-07-24T17:16:13Z"/>
            <EventRecordID>454643937</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD00155D4CDD6D</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application '/LM/W3SVC/1905298837/ROOT' with physical root 'D:\home\site\wwwroot\' shut down process with Id '19892' listening on port '23508'</Data>
            <Data>Process Id: 15088.</Data>
            <Data>File Version: 12.2.19081.4. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 5cb615fcbe8559e49042e93394008077e30454c0</Data>
        </EventData>
    </Event>
```

**Comment by jkotalik** [comment]
> So, maybe this is something I don't need to worry about as it will eventually resolve itself.

Yeah, I believe so. From what I can tell, the process is always logging to the same file. The first attempt fails due to a port already in use, but the second time succeeds. 

As long as that instance wasn't returning invalid responses, this is expected and would resolve itself. Can you see if before the first event log (the one where it started on port 23508), ANCM wrote an event log where it said something along the lines of failed to start the application?

**Comment by stephenschwan** [comment]
I looked at our synthetic traffic etc and did not see any failed requests (500's) during this time period.  I think it worked as stated.  I have attached the event log.

[eventlog.txt](https://github.com/aspnet/AspNetCore/files/3433166/eventlog.txt)

**Comment by anurse** [comment]
This is mostly expected (but unfortunate) behavior based on the random port colliding with an existing binding. ANCM should be doing the right thing and re-starting and picking a new port. It sounds like that's the case, so I'm closing this. Let me know if I'm misinterpreting!

**Comment by ddobric** [comment]
Hi all,

I would be careful with closing of this issue. Since I use v2.2, I'm getting this error very often and cannot speak about coincidence. Sometimes even machine restart doesn't help.

Thanks

**Comment by tweek82** [comment]
Hi all,

We are heaving troubles with Azure App Services replacing instances for our .NET Core 2.1 web API. See also this issue. Today it escalated again and I learned about the eventlog.xml in the Kudo portal.
This shows the following logs:

> dotnet.exe
> CoreCLR Version: 4.6.27817.1
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
>    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.Listen(Int32 backlog)
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.&lt;&gt;c__DisplayClass22_0`1.&lt;&lt;StartAsync&gt;g__OnBind|0&gt;d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)

For what we've seen now, this happens the most when Azure replaces our instances. See also this issue I've raised: https://github.com/aspnet/AspNetCore/issues/13866

**Comment by tweek82** [comment]
@anurse because comments on closed issues might not be tracked, see my previous comment. Can you point us in the right direction on this?

**Comment by anurse** [comment]
@tweek82 I'd suggest you open a new issue, for exactly the reason you mention (closed issues don't get a lot of attention). I'm on leave until Monday and not really able to investigate further. Opening a new issue ensures it'll get my attention when I'm back, and even before then it ensures the whole team sees it.

**Comment by joeangry** [comment]
This might be completely unrelated but adding ``UseIIS()`` fixed it for me.
