### ISSUE TITLE
Blazor _Imports.razor Not Found when using CIFS Mount on Docker for Windows

### ISSUE THREAD

**Issue by caleblloyd** [aspnet/AspNetCore#12663]
I have a Blazor project that I'm running with Docker for Windows.  Source code is mounted from the Windows host to the Container using CIFS (the standard way that Docker for Windows does mounts):

```
# mount | grep cifs
//10.0.75.1/C on /dotnet type cifs (rw,relatime,vers=3.02,sec=ntlmsspi,cache=strict,username=User,domain=Domain,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0777,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```

The project fails to build inside of the Docker container, complaining about a missing `_Imports.razor` file:

```
# dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19329-01+d31fdbf01 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 35.97 ms for /dotnet/src/Project/Project.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  Could not find file '/dotnet/src/Project/_Imports.razor'.
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectItem.Read()
     at Microsoft.AspNetCore.Razor.Language.RazorSourceDocument.ReadFrom(RazorProjectItem projectItem)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.GetImportSourceDocuments(IReadOnlyList`1 importItems, Boolean suppressExceptions)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.CreateCodeDocumentCore(RazorProjectItem projectItem, Action`1 configureParser, Action`1 configureCodeGeneration)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.CreateCodeDocumentCore(RazorProjectItem projectItem)
     at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
     at Microsoft.AspNetCore.Razor.Tools.GenerateCommand.<>c__DisplayClass46_0.<GenerateCode>b__0(Int32 i)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
  
Build FAILED.

/usr/share/dotnet/sdk/3.0.100-preview7-012821/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets(106,5): error : rzc generate exited with code 1. [/dotnet/src/Project/Project.csproj]
    0 Warning(s)
    1 Error(s)
```

The file is present, however:

```
cat /dotnet/src/Project/_Imports.razor
@using System.Net.Http
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Layouts
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.JSInterop
@using Project.Shared
```

When I use strace to inspect, I see 3 concurrent `openat` calls on the file.  1 of the calls succeeds while the other 2 return `ENOENT`.

```
# strace -f dotnet build 2>&1 | grep -A 100 _Import | grep openat 
[pid  1657] openat(AT_FDCWD, "/dotnet/src/Project/_Imports.razor", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid  1654] openat(AT_FDCWD, "/dotnet/src/Project/_Imports.razor", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid  1647] openat(AT_FDCWD, "/dotnet/src/Project/_Imports.razor", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid  1654] <... openat resumed> )      = -1 ENOENT (No such file or directory)
[pid  1647] <... openat resumed> )      = -1 ENOENT (No such file or directory)
[pid  1657] <... openat resumed> )      = 66
```

If I copy the project directory off of the CIFS mount it builds fine.

Although it appears to be a CIFS driver issue, I think that running projects on Docker for Windows or CIFS mounts on Linux is a pretty valid use case.  I've never had problems running`dotnet build` in Docker for Windows with a CIFS mount before.

Dotnet Version: 3.0.0-preview7
Docker Image: `mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview7`

**Comment by davidfowl** [comment]
If you use the .NET file APIs directly does it work? Blazor isn’t doing anything special.

**Comment by caleblloyd** [comment]
I am not doing anything special- this is just the `dotnet build` erroring out with a basic Blazor template. Compiling fails.

**Comment by mkArtakMSFT** [comment]
@stephentoub do you know who would be best fitted to see whether this is a corefx bug or not?

**Comment by stephentoub** [comment]
> @stephentoub do you know who would be best fitted to see whether this is a corefx bug or not?

Based on the above strace, this doesn't look like something corefx is causing.  It's asking for the file, and the OS is coming back with an error, which is dutifully reported.

Even so, cc: @JeremyKuhne, @wfurt.

**Comment by stephentoub** [comment]
> I've never had problems running `dotnet build` in Docker for Windows with a CIFS mount before.

When did this repro start reproing? Did it work successfully in a previous .NET Core 3.0 preview?  Did it work successfully with .NET Core 2.2?

**Comment by wfurt** [comment]
This can be also msbuild issue. You can try to use 
`export UseSharedCompilation=false` @caleblloyd
The strace certainly looks suspicious and that is beyond .Net.

**Comment by caleblloyd** [comment]
Thanks for the help everyone.  Tried using `export UseSharedCompilation=false` but it did not change anything.

I am encountering the error on a Surface Pro 4.  Tried to recreate on my Windows Desktop and could not, everything works fine there.  Both running Windows 10 19.03, same set of Features enabled, both running Docker Desktop version 2.0.0.3.

Guess it's just one of those baffling errors that something on the system level is causing.  Agree that it's out of scope for msbuild/CoreFX, I'll go ahead and close.  Hopefully WSL2 will eliminate the need for the CIFS mount and will remove the chance for this error condition entirely.
