### ISSUE TITLE
[Blazor] Broken E2E tests

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#12831]
Seems like there are a bunch of broken E2E tests in components. I've started noticing it after I rebased. @SteveSandersonMS @rynowak any idea? They are about 17 broken tests.

![image](https://user-images.githubusercontent.com/6995051/62369950-12a82d00-b4e6-11e9-9cba-b31388a653d0.png)

```
[2019-08-02T12:22:28.487Z] Error: System.InvalidOperationException: Unable to set property 'BoolAttributeBefore' on object of type 'BasicTestApp.DuplicateAttributesOnElementChildComponent'. The error was: Unable to cast object of type 'System.String' to type 'System.Boolean'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Boolean'.
   at Microsoft.AspNetCore.Components.Reflection.MemberAssignment.PropertySetter`2.SetValue(Object target, Object value) in C:\work\AspNetCore3\src\Components\Components\src\Reflection\MemberAssignment.cs:line 61
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, IPropertySetter writer, String parameterName, Object value) in C:\work\AspNetCore3\src\Components\Components\src\Reflection\ComponentProperties.cs:line 99
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, IPropertySetter writer, String parameterName, Object value) in C:\work\AspNetCore3\src\Components\Components\src\Reflection\ComponentProperties.cs:line 103
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target) in C:\work\AspNetCore3\src\Components\Components\src\Reflection\ComponentProperties.cs:line 73
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target) in C:\work\AspNetCore3\src\Components\Components\src\ParameterView.cs:line 233
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters) in C:\work\AspNetCore3\src\Components\Components\src\ComponentBase.cs:line 180
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters) in C:\work\AspNetCore3\src\Components\Components\src\Rendering\ComponentState.cs:line 134
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex) in C:\work\AspNetCore3\src\Components\Components\src\RenderTree\RenderTreeDiffBuilder.cs:line 898
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex) in C:\work\AspNetCore3\src\Components\Components\src\RenderTree\RenderTreeDiffBuilder.cs:line 867
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex) in C:\work\AspNetCore3\src\Components\Components\src\RenderTree\RenderTreeDiffBuilder.cs:line 743
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) in C:\work\AspNetCore3\src\Components\Components\src\RenderTree\RenderTreeDiffBuilder.cs:line 247
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree) in C:\work\AspNetCore3\src\Components\Components\src\RenderTree\RenderTreeDiffBuilder.cs:line 30
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment) in C:\work\AspNetCore3\src\Components\Components\src\Rendering\ComponentState.cs:line 69
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in C:\work\AspNetCore3\src\Components\Components\src\Rendering\Renderer.cs:line 563
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue() in C:\work\AspNetCore3\src\Components\Components\src\Rendering\Renderer.cs:line 412
```

**Comment by rynowak** [comment]
Fixed here: https://github.com/aspnet/AspNetCore/pull/12098
