### ISSUE TITLE
Blazor client-hosted project activating server controller with parameterised constructor returns HTTP 500

### ISSUE THREAD

**Issue by DaTribe** [aspnet/AspNetCore#13036]
### Bug
Using the out of the box client-hosted Blazor template, when registering entries into the DI container and using the registered entry in a constructor on the Server an HTTP 500 status is returned due to the container failing to activate the constructor parameter despite it being registered in the container.

### Steps to reproduce the behavior:
1. Using ASP.NET Core SDK 3.0.100-preview7-012821
2. Using Visual Studio 2019 16.3.0 Preview 1
3. Install Blazor templates using "dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview7.19365.7"
4. Created ASP.NET Core application --> Blazor client-hosted 
5. Create a contract & implementation (IContract, Contract)
6. Register contract in DI container (IServicesCollection) in Startup.cs in the Server project. services.AddTransient<IContract, Contract>()
7. Add a constructor to SampleDataController with IContract as parameter.

### Expected behavior
When an API method is called the controller should be created and the action invoked.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DaTribe.
What's the error you're facing? Also, it would help to have a repro for this so we can have a look.

**Comment by DaTribe** [comment]
Thank you for addressing the issue @mkArtakMSFT.

Here is a repo demonstrating the issue: https://github.com/AvantPrime/BlazorDI

![BlazorDITest-Errors](https://user-images.githubusercontent.com/1212376/62927294-26894400-bdae-11e9-8db6-8df3bc95c274.PNG)

**Comment by pranavkm** [comment]
@DaTribe your app has a compile error (`IMenu` isn't defined), but once I got past that everything looked fine. Could you look at your app's server logs and see what the actual exception is when you call  the controller action?

**Comment by DaTribe** [comment]
Thanks for checking @pranavkm. I may need better glasses.

The issue is multiple constructors with a single parameter.

`Category: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
EventId: 1
RequestId: 80000085-0007-fd00-b63f-84710c7967bb
RequestPath: /weatherforecast
SpanId: |a38b8309-47c09ddc92b5013a.
TraceId: a38b8309-47c09ddc92b5013a
ParentId: 

An unhandled exception has occurred while executing the request.

Exception: 
System.InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'BlazorTest.Server.Controllers.WeatherForecastController'. There should only be one applicable constructor.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.TryFindMatchingConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.CreateActivator(ControllerActionDescriptor descriptor)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.CreateControllerFactory(ControllerActionDescriptor descriptor)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`
My visual studio shows the changes checked in but the repo has IMenu. I am not sure if that is me or a VS 2019 preview issue.

![Visual Studio GIT issue](https://user-images.githubusercontent.com/1212376/63011458-49842880-be80-11e9-8974-6c52ec3cb6fa.PNG)
