### ISSUE TITLE
Kestrel Debug.Assert

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#13069]
While running tests locally (in debug on macOS Catalina) a Debug.Assert was triggered.

At the time of running that would be:
https://github.com/aspnet/AspNetCore/blob/8c02467b4a218df3b1b0a69bceb50f5b64f482b1/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs#L101

```
Process terminated. Assertion failed.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream.OnRequestProcessingEnded() in /Users/test/Downloads/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs:line 101
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream`1.Execute() in /Users/test/Downloads/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Http2/Http2StreamOfT.cs:line 22
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

cc @Tratcher @halter73

**Comment by Tratcher** [comment]
@jkotalik there may be a race checking decrement.

**Comment by jkotalik** [comment]
Well that isn't good....

**Comment by anurse** [comment]
Since this is a Debug Assert, I think this fits the tell-mode bar even though this is in "product code".

**Comment by BrennanConroy** [comment]
Fixed by https://github.com/aspnet/AspNetCore/pull/13134
