### ISSUE TITLE
Local windows authentication with HttpClient over HTTPS in ASP.NET service does not work

### ISSUE THREAD

**Issue by igor-tk** [aspnet/AspNetCore#13160]
Http call (HttpClient) from server where ASP.NET Core service with windows auth is hosted returns 500 error. Service uses Microsoft.AspNetCore.Authentication.Negotiate for windows security. Remote calls to this service work, local don't. 

To Reproduce

1. Windows Server 2016 Standard, domain joined, Microsoft.NETCore.App 3.0.0-preview8-28405-07, Microsoft.AspNetCore.App 3.0.0-preview8.19405.7, apache 2.4 as reverse proxy + TLS, service has SPN: HTTP/myserver, TLS certificate is valid.

2. Run this code:

`var url = "https://myserver/nego/user-info";
var httpClientHandler = new System.Net.Http.HttpClientHandler();
var cred = CredentialCache.DefaultNetworkCredentials;
httpClientHandler.Credentials = cred;
var httpClient = new System.Net.Http.HttpClient(httpClientHandler, true);
var req = new System.Net.Http.HttpRequestMessage(System.Net.Http.HttpMethod.Get, url);
var res = httpClient.SendAsync(req).Result;`

3. Server returns 500 error

Service log:

2019-08-15 10:11:21.617 +03:00 [DBG] Connection id "0HLP19V3BA9CP" accepted.
2019-08-15 10:11:21.623 +03:00 [DBG] Connection id "0HLP19V3BA9CP" started.
2019-08-15 10:11:21.715 +03:00 [INF] Request starting HTTP/1.1 GET http://127.0.0.1:9444/nego/user-info  
2019-08-15 10:11:21.718 +03:00 [DBG] Wildcard detected, all requests with hosts will be allowed.
2019-08-15 10:11:21.732 +03:00 [DBG] The request path /nego/user-info does not match a supported file type
2019-08-15 10:11:21.769 +03:00 [DBG] Initializing Razor view compiler with compiled view: '/Views/Home/Index.cshtml'.
2019-08-15 10:11:21.769 +03:00 [DBG] Initializing Razor view compiler with compiled view: '/Views/Shared/Error.cshtml'.
2019-08-15 10:11:21.769 +03:00 [DBG] Initializing Razor view compiler with compiled view: '/Views/Shared/_Layout.cshtml'.
2019-08-15 10:11:21.769 +03:00 [DBG] Initializing Razor view compiler with compiled view: '/Views/_ViewImports.cshtml'.
2019-08-15 10:11:21.769 +03:00 [DBG] Initializing Razor view compiler with compiled view: '/Views/_ViewStart.cshtml'.
2019-08-15 10:11:21.806 +03:00 [DBG] 1 candidate(s) found for the request path '/nego/user-info'
2019-08-15 10:11:21.811 +03:00 [DBG] Endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)' with route pattern 'nego/user-info' is valid for the request path '/nego/user-info'
2019-08-15 10:11:21.817 +03:00 [DBG] Request matched endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)'
2019-08-15 10:11:21.849 +03:00 [DBG] AuthenticationScheme: Negotiate was not authenticated.
2019-08-15 10:11:21.876 +03:00 [INF] Authorization failed.
2019-08-15 10:11:21.880 +03:00 [DBG] Challenged 401 Negotiate
2019-08-15 10:11:21.880 +03:00 [INF] AuthenticationScheme: Negotiate was challenged.
2019-08-15 10:11:21.916 +03:00 [INF] Request finished in 212.1988ms 401 
2019-08-15 10:11:21.918 +03:00 [DBG] Connection id "0HLP19V3BA9CP" received FIN.
2019-08-15 10:11:21.937 +03:00 [DBG] Connection id "0HLP19V3BA9CP" sending FIN because: "The client closed the connection."
2019-08-15 10:11:21.937 +03:00 [DBG] Connection id "0HLP19V3BA9CP" disconnecting.
2019-08-15 10:11:21.943 +03:00 [DBG] Connection id "0HLP19V3BA9CP" stopped.
2019-08-15 10:11:21.972 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" accepted.
2019-08-15 10:11:21.973 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" started.
2019-08-15 10:11:21.974 +03:00 [INF] Request starting HTTP/1.1 GET http://127.0.0.1:9444/nego/user-info  
2019-08-15 10:11:21.974 +03:00 [DBG] The request path /nego/user-info does not match a supported file type
2019-08-15 10:11:21.977 +03:00 [DBG] 1 candidate(s) found for the request path '/nego/user-info'
2019-08-15 10:11:21.977 +03:00 [DBG] Endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)' with route pattern 'nego/user-info' is valid for the request path '/nego/user-info'
2019-08-15 10:11:21.977 +03:00 [DBG] Request matched endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)'
2019-08-15 10:11:22.011 +03:00 [INF] Incomplete Negotiate handshake, sending an additional 401 Negotiate challenge.
2019-08-15 10:11:22.012 +03:00 [INF] Request finished in 37.8185ms 401 
2019-08-15 10:11:22.012 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" disconnecting.
2019-08-15 10:11:22.012 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" received FIN.
2019-08-15 10:11:22.012 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" stopped.
2019-08-15 10:11:22.013 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" sending FIN because: "The Socket transport's send loop completed gracefully."
2019-08-15 10:11:22.014 +03:00 [DBG] Connection id "0HLP19V3BA9CR" accepted.
2019-08-15 10:11:22.014 +03:00 [DBG] Connection id "0HLP19V3BA9CR" started.
2019-08-15 10:11:22.015 +03:00 [INF] Request starting HTTP/1.1 GET http://127.0.0.1:9444/nego/user-info  
2019-08-15 10:11:22.015 +03:00 [DBG] The request path /nego/user-info does not match a supported file type
2019-08-15 10:11:22.015 +03:00 [DBG] 1 candidate(s) found for the request path '/nego/user-info'
2019-08-15 10:11:22.015 +03:00 [DBG] Endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)' with route pattern 'nego/user-info' is valid for the request path '/nego/user-info'
2019-08-15 10:11:22.015 +03:00 [DBG] Request matched endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)'
2019-08-15 10:11:22.070 +03:00 [ERR] An exception occurred while processing the authentication request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(String incomingBlob)
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
2019-08-15 10:11:22.373 +03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(String incomingBlob)
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2019-08-15 10:11:22.413 +03:00 [DBG] The request path /Home/Error does not match a supported file type
2019-08-15 10:11:22.413 +03:00 [DBG] 1 candidate(s) found for the request path '/Home/Error'
2019-08-15 10:11:22.413 +03:00 [DBG] Endpoint 'Service.Controllers.HomeController.Error (Service)' with route pattern '{controller=Home}/{action=Index}/{id?}' is valid for the request path '/Home/Error'
2019-08-15 10:11:22.413 +03:00 [DBG] Request matched endpoint 'Service.Controllers.HomeController.Error (Service)'
2019-08-15 10:11:22.417 +03:00 [ERR] An exception was thrown attempting to execute the error handler.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (9): The storage control block address is invalid.
   at System.Net.NTAuthentication.get_AssociatedName()
   at System.Net.Security.NegotiateStreamPal.GetIdentity(NTAuthentication context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetIdentity()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
2019-08-15 10:11:22.426 +03:00 [ERR] Connection id "0HLP19V3BA9CR", Request id "0HLP19V3BA9CR:00000001": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError)
   at Microsoft.AspNetCore.Authentication.Negotiate.ReflectedNegotiateState.GetOutgoingBlob(String incomingBlob)
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-08-15 10:11:22.442 +03:00 [INF] Request finished in 427.0865ms 500 
2019-08-15 10:11:22.442 +03:00 [DBG] Connection id "0HLP19V3BA9CR" disconnecting.
2019-08-15 10:11:22.442 +03:00 [DBG] Connection id "0HLP19V3BA9CR" stopped.
2019-08-15 10:11:22.442 +03:00 [DBG] Connection id "0HLP19V3BA9CR" sending FIN because: "The Socket transport's send loop completed gracefully."

Additional context
Service is behind apache (2.4) reverse proxy, hosted on the same server, configured for TLS, connection pooling in apache is disabled.

If I use browser (Chrome 76) and go to secured URL, browser prompts for user credentials (thought it shouldn't), I enter credentials, browser receives an error status from the server - failed. When I refresh the page, I have already logged in.

Server log:

Connection id "0HLP19V3BA9DO" accepted.
2019-08-15 12:15:03.188 +03:00 [DBG] Connection id "0HLP19V3BA9DO" started.
2019-08-15 12:15:03.189 +03:00 [INF] Request starting HTTP/1.1 GET http://127.0.0.1:9444/nego/user-info?_=1565860503129  
2019-08-15 12:15:03.189 +03:00 [DBG] The request path /nego/user-info does not match a supported file type
2019-08-15 12:15:03.189 +03:00 [DBG] 1 candidate(s) found for the request path '/nego/user-info'
2019-08-15 12:15:03.189 +03:00 [DBG] Endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)' with route pattern 'nego/user-info' is valid for the request path '/nego/user-info'
2019-08-15 12:15:03.189 +03:00 [DBG] Request matched endpoint 'Service.Controllers.NegoController.GetUserInfo (Service)'
2019-08-15 12:15:03.190 +03:00 [DBG] AuthenticationScheme: Negotiate was not authenticated.
2019-08-15 12:15:03.190 +03:00 [INF] Authorization failed.
2019-08-15 12:15:03.190 +03:00 [DBG] Challenged 401 Negotiate
2019-08-15 12:15:03.190 +03:00 [INF] AuthenticationScheme: Negotiate was challenged.
2019-08-15 12:15:03.191 +03:00 [DBG] Connection id "0HLP19V3BA9DO" received FIN.
2019-08-15 12:15:03.191 +03:00 [DBG] Connection id "0HLP19V3BA9DO" sending FIN because: "The client closed the connection."
2019-08-15 12:15:03.191 +03:00 [DBG] Connection id "0HLP19V3BA9DO" disconnecting.
2019-08-15 12:15:03.191 +03:00 [INF] Request finished in 0.9561000000000001ms 401 
2019-08-15 12:15:03.191 +03:00 [DBG] Connection id "0HLP19V3BA9DO" stopped.

**Comment by blowdart** [comment]
What happens if you remove the reverse proxy? Kerberos isn't meant to go through proxies

**Comment by igor-tk** [comment]
Without revers proxy it's ok. 

> Kerberos isn't meant to go through proxies

Why remote calls with reverse proxy work? Same pattern with java service behind proxy works.

I cannot understand documentation:

[https://docs.microsoft.com/ru-ru/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#kestrel](url)

It's ucnclear: I can or I cannot use proxy and ASP.NET Core with Windows authentication. If I use persisted connection with proxy and Kestrel I have another issue. So now I have issues with either cases.

**Comment by blowdart** [comment]
If you put a proxy in the way of what is essentially a connection based authentication mechanism then the proxy has to do the authentication, then pass on the information in a way the final service understands. It's the same with certificates.

@Rick-Anderson can we get the docs updated to indicate no proxies for both Kerberos/Negotiate and also Certificate auth?

**Comment by Tratcher** [comment]
Here's the break:
```
2019-08-15 10:11:22.011 +03:00 [INF] Incomplete Negotiate handshake, sending an additional 401 Negotiate challenge.
2019-08-15 10:11:22.012 +03:00 [INF] Request finished in 37.8185ms 401
2019-08-15 10:11:22.012 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" disconnecting.
2019-08-15 10:11:22.012 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" received FIN.
2019-08-15 10:11:22.012 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" stopped.
2019-08-15 10:11:22.013 +03:00 [DBG] Connection id "0HLP19V3BA9CQ" sending FIN because: "The Socket transport's send loop completed gracefully."
```
The auth is stateful and needs to finish the handshake on the same connection, but the connection is being closed before the final leg of the handshake. Probably the proxy doing this? 

But yeah, win auth and proxies make a bad combo. The auth can be cached per connection but you'd need to ensure you had strong connection affinity between the front and back end.

**Comment by igor-tk** [comment]
So if I would have load balancer (or any other proxy) in front of my reverse proxy I need to ensure strong connection affinity between them also?

**Comment by blowdart** [comment]
Well, given that kerberos/Windows authentication is meant for INTRANETS and you don't really ever want kerberos tokens going wild over the internet due to security concerns you shouldn't be needing a proxy or load balancer at all.

**Comment by igor-tk** [comment]
I need high availability web service in intranet with windows authentication (kerberos) without Windows Failover Cluster. So as I can use same programs in Linux deployment. How I can avoid using load balancer (using NLB instead of WFC is recommended)? Besides, I have many REST services spread over several servers (in intranet) and I wish client apps have access through one single HTTP endpoint. So now, it seems that I can't do that with kerberos.

**Comment by blowdart** [comment]
That's an architectural discussion outside of our control or knowledge I'm afraid. Either the load balancer does the authentication and then passes the user details down in a header which you then pick apart (custom code for custom configurations), or you switch to ADFS 2019 and ODIC, and bounce people through that. Bonus here is that'd work with cloud migrations too.

**Comment by blowdart** [comment]
As it's been a week, and the behaviour is expected and due to architecture outside of core's control I'm going to close this.
