### ISSUE TITLE
ChannelReader<T> method in Hub with CancellationToken throws

### ISSUE THREAD

**Issue by emilmuller** [aspnet/AspNetCore#13191]
```
public ChannelReader<ApiTypedData<LogInResponseType>> LogIn(string username, byte[] passwordHash, string baseUrl, string fastLoginPassword, CancellationToken cancellationToken)
{
    var channel = Channel.CreateUnbounded<ApiTypedData<LogInResponseType>>();
    _ = LogInAsync(channel.Writer, username, passwordHash, baseUrl, fastLoginPassword, cancellationToken);
    return channel.Reader;
}

async Task LogInAsync(ChannelWriter<ApiTypedData<LogInResponseType>> writer, string username, byte[] passwordHash, string baseUrl, string fastLoginPassword, CancellationToken cancellationToken)
{
    // ...
}
```
Declaring the method above causes the following exception to be thrown when invoking in the browser (JavaScript):

```
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'LogIn'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.Invoke(HubMethodDescriptor descriptor, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamedInvocation)
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher:Error: Failed to invoke hub method 'LogIn'.
```

JavaScript:

```
this.hubConnection.stream("LogIn", username, passwordHash, location.origin, null).subscribe({
    next: (item) => {
        console.log("next", item);
    },
    complete: () => {
        console.log("complete")
    },
    error: (err) => {
        console.log("err", err);
    }});
```

**If I remove the CancellationToken parameter from the back-end code, it works, and the exception is not thrown.**

I have configured my hub to use MessagePack.

`<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="1.1.5" />`

**Comment by BrennanConroy** [comment]
Instead of null as the last argument could you try an empty string? There might be a check we're missing here

**Comment by emilmuller** [comment]
@BrennanConroy I can confirm that does indeed fix the problem :)

**Comment by BrennanConroy** [comment]
Hopefully that works as a workaround for you for now :)

**Comment by emilmuller** [comment]
Yes, it does. Thanks for your help!

**Comment by anurse** [comment]
Once this lands, we can consider this for 3.1 backport.
