### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Builder.AuthorizationAppBuilderExtensions' from assembly 'Microsoft.AspNetCore.Authorization, Version=3.0.0.0

### ISSUE THREAD

**Issue by thangchung** [aspnet/AspNetCore#13230]
### Describe the bug
I have got the exception when using `docker-compose` to build the standard Web template in .NET Core 3.0 Preview 8

```
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.AuthorizationAppBuilderExtensions' from assembly 'Microsoft.AspNetCore.Authorization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

### To Reproduce
1. Using Visual Studio 2019 v16.3.1 Preview 2.0
2. Create the Standard Web Application with Api option which has WeatherControler + Docker supports 
3. Run on local, everything is okay
4. Write docker-compose with the script as below

```
weatherserver:
    image: weatherserver
    build:
      context: .
      dockerfile: ./samples/WeatherServer/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
```

5. Run `docker-compose build weatherserver` ==> everything is still okay
6. Run `docker-compose up` ==> got the exception that 

```
weatherserver_1  | crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
weatherserver_1  |       Application startup exception
weatherserver_1  | System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.AuthorizationAppBuilderExtensions' from assembly 'Microsoft.AspNetCore.Authorization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
weatherserver_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
weatherserver_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
weatherserver_1  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
weatherserver_1  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
weatherserver_1  | Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.AuthorizationAppBuilderExtensions' from assembly 'Microsoft.AspNetCore.Authorization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
weatherserver_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
weatherserver_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
weatherserver_1  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
weatherserver_1  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
weatherserver_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
weatherserver_1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
weatherserver_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
weatherserver_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
weatherserver_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
weatherserver_1  |    at WeatherServer.Program.Main(String[] args) in /src/samples/WeatherServer/Program.cs:line 17
```

### Expected behavior
Expecting that it works correctly because this is a standard template which I didn't modify any code in there

I use Windows 10 + Docker for Desktop to run Docker and Docker Compose

**Comment by rynowak** [comment]
A `TypeLoadException` usually means that there's some kind of binary-mismatch. Are you referencing any packages that are built for previous preview releases of .NET?
