### ISSUE TITLE
System.Text.Json: collection type Dictionary<int, ...> is not supported

### ISSUE THREAD

**Issue by fvi1234** [aspnet/AspNetCore#13332]
A controller cannot return a Dictionary keyed with int anymore, causing  Dictionary<int, *> to have to be needlessly converted when serializing to Json

### To Reproduce
1. Using Microsoft.NETCore.App 3.0.0-preview7
2. Have this controller method:

        [HttpGet("Foo")]
        public Dictionary<int, string> GetFoo()
        {
            return new Dictionary<int, string> { { 0, "aaa" }, { 1, "bbb" }, { 2, "ccc" } };
        }

3. Get exception:
    System.NotSupportedException: The collection type 'System.Collections.Generic.Dictionary`2[System.Int32,System.String]' is not supported.
       at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
       at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
       at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
       at System.Text.Json.JsonClassInfo.AddPolicyProperty(Type propertyType, JsonSerializerOptions options)
       at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
       at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
       at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
       at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type type, JsonSerializerOptions options, CancellationToken cancellationToken)
       at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
       at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

### Expected behavior
The expected result would be (as it was in AspNetCore 2):
    {
      "0": "aaa",
      "1": "bbb",
      "2": "ccc"
    }

**Comment by pranavkm** [comment]
Thanks for the issue report @fvi1234. This is being tracked as part of https://github.com/dotnet/corefx/issues/40120. In the meanwhile you could

a) look at the suggestion here: https://github.com/dotnet/corefx/issues/40120#issuecomment-519648806
b) Use Json.NET in MVC: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#jsonnet-support
