### ISSUE TITLE
HTTP2: Client and server disagree on active stream count

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#13406]
Issue found during HTTP2 stress testing. One HttpClient is sending multiple requests in parallel, then canceling them via RST_STREAM sent to the server. For an unknown reason the server and client disagree on the active stream count, and the sever eventually sends RST_STREAM (REFUSED_STREAM) and GOAWAY (STREAM_CLOSED). This issue eventually leads to https://github.com/aspnet/AspNetCore/issues/13405.

Client and server should agree on the active stream count and the client should wait to send new requests, without error.

Wireshark log: https://www.dropbox.com/s/5ndspth4t0qjyj6/clientreset-error.zip?dl=0

Exception on the client:

```
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: The request was aborted.
---> System.IO.IOException: The response ended prematurely, with at least 9 additional bytes expected.
   at System.Net.Http.Http2Connection.ReadAtLeastAsync(Stream stream, Memory`1 buffer, Int32 minReadBytes)
   at System.Net.Http.Http2Connection.EnsureIncomingBytesAsync(Int32 minReadBytes)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.SendAsync(HttpClient client, HttpRequestMessage message)
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseHeadersAsync()
```

Repo is currently not public. Contact @JamesNK or @Tratcher for the repo source code and instruction.

**Comment by jkotalik** [comment]
So https://github.com/aspnet/AspNetCore/pull/12704 was supposed to fix this issue. There may be a case we aren't covering.

**Comment by Tratcher** [comment]
Indeed. #12704 was focused on the server terminating the request, but the new repro is focused on client aborts. A quick look through the code shows we did account for client RSTs, but maybe we missed something else.

**Comment by JamesNK** [comment]
This is a bug but not a critical one. 3.1 fix?

**Comment by Tratcher** [comment]
Theory: The client has a race where it can cancel a stream, decrement its count, but not send a RST_STREAM. The server still considers the stream open and you exceed the stream limit.

Repro logs. I set the connection limit to 1, send two requests, and cancel one of them (the delay=100 request).
```
// Good:
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" received HEADERS frame for stream ID 2545 with length 31 and flags END_STREAM, END_HEADERS
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET http://localhost:5005/?delay=100
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" received RST_STREAM frame for stream ID 2545 with length 4 and flags 0x0
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" received HEADERS frame for stream ID 2547 with length 29 and flags END_STREAM, END_HEADERS
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 111.1166ms 200
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET http://localhost:5005/?delay=0
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" sending HEADERS frame for stream ID 2547 with length 76 and flags END_HEADERS
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" sending DATA frame for stream ID 2547 with length 21 and flags NONE
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" sending HEADERS frame for stream ID 2547 with length 27 and flags END_STREAM, END_HEADERS
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.2761ms 200
// Bad:
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" received HEADERS frame for stream ID 2549 with length 31 and flags END_STREAM, END_HEADERS
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET http://localhost:5005/?delay=100
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" received HEADERS frame for stream ID 2551 with length 29 and flags END_STREAM, END_HEADERS
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" sending HEADERS frame for stream ID 2549 with length 76 and flags END_HEADERS
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" sending DATA frame for stream ID 2549 with length 23 and flags NONE
trce: Microsoft.AspNetCore.Server.Kestrel[37]
      Connection id "0HLPC0DDKPENV" sending HEADERS frame for stream ID 2549 with length 33 and flags END_STREAM, END_HEADERS
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1106537.7128ms 200
```

```

            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
            using var client = new HttpClient
            {
                BaseAddress = new Uri("http://localhost:5005"),
                DefaultRequestVersion = HttpVersion.Version20
            };
            for (int i = 0; i < 1000; i++)
            {
                // Send a second one that will cancel
                var r2Task = client.GetAsync("?delay=100", new CancellationTokenSource(50).Token);

                // Send one request normally
                var r1Task = client.GetAsync("?delay=0");

                try
                {
                    var r1 = await r1Task;
                    r1.EnsureSuccessStatusCode();
                }
                catch (Exception ex)
                {
                    Console.WriteLine("R1 fail: " + ex.Message);
                }

                try
                {
                    var r2 = await r2Task;
                    r2.EnsureSuccessStatusCode();
                }
                catch (OperationCanceledException)
                {
                    Console.WriteLine("R2 canceled");
                }
                catch (Exception ex)
                {
                    Console.WriteLine("R2 fail: " + ex);
                }
            }
```
```
            app.Run(async context =>
            {
                var delay = context.Request.Query["delay"].ToString();
                if (!string.IsNullOrEmpty(delay))
                {
                    await Task.Delay(int.Parse(delay));
                }
                await context.Response.WriteAsync($"Hello World! {context.Request.Protocol} {delay}");
            });
```

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#40663
