### ISSUE TITLE
[Blazor] Unable to set xxxChanged (cast error)

### ISSUE THREAD

**Issue by epsitec** [aspnet/AspNetCore#13408]
### Describe the bug
A Razor component (`PasswordField`) exposes a property `[Parameter] public string Password` and an associated `[Parameter] public Action<string> PasswordChanged` property. When using the component and trying to bind its `Password` field, the runtime throws an `InvalidOperationException` because it tries to cast the handler from `EventCallback<string>` to `Action<string>`:

```
System.InvalidOperationException: Unable to set property 'passwordChanged' on object of type 'Epsitec.Passport.Components.Shared.PassportField'. The error was: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback`1[System.String]' to type 'System.Action`1[System.String]'.
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback`1[System.String]' to type 'System.Action`1[System.String]'.
   at Microsoft.AspNetCore.Components.Reflection.MemberAssignment.PropertySetter`2.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, IPropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, IPropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitPrerenderer.CircuitHost_UnhandledException(Object sender, UnhandledExceptionEventArgs e)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.Renderer_UnhandledException(Object sender, Exception e)
   at Microsoft.AspNetCore.Components.Web.Rendering.RemoteRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitPrerenderer.CircuitHost_UnhandledException(Object sender, UnhandledExceptionEventArgs e)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.Renderer_UnhandledException(Object sender, Exception e)
   at Microsoft.AspNetCore.Components.Web.Rendering.RemoteRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToPendingTasks(Task task)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
...
```

### Source code used
File `PassportField.razor`:

```razor
<input id="pass"
       type="@(this.ShowPassword ? "text" : "password")"
       placeholder="votre mot de passe"
       required
       @bind="@Password"
       @bind:event="oninput" />
<a id="show"
   @onclick="@this.ToggleShowPassword"
   title="Afficher le mot de passe">
    <i class="fal @(this.ShowPassword ? "fa-eye" : "fa-eye-slash")"></i>
</a>

@code {
    bool ShowPassword { get; set; }

    [Parameter]
    public string Password
    {
        get
        {
            return this.password ?? "";
        }
        set
        {
            if (this.password != value)
            {
                this.password = value;
                this.PasswordChanged?.Invoke (value);
            }
        }
    }

    [Parameter]
    public Action<string>? PasswordChanged { get; set; }

    private void ToggleShowPassword()
    {
        this.ShowPassword = !this.ShowPassword;
    }

    private string? password;
}
```

Used by this code:
```razor
// ... 
<PassportField @bind-password="@Password" />
// ...
...
@code {
    // ...
    string? Password
    {
        get; set;
    }
    // ...
}
```

### Expected behavior
The code used to work with older previews; it definitely does not work in **preview8**.

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.100-preview-007354 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007363 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by epsitec** [comment]
@rynowak as you've asked... let me know if you need to access the full source code.

**Comment by epsitec** [comment]
@pranavkm your suggestion does not work, as I need to be able to `Invoke()` the `PasswordChanged` callback from the _property setter_ and with `EventCallback<T>` the only option I have is to `AsyncInvoke()` it.

I can't implement the property setter asynchronously! Or did I miss something here?

**Comment by epsitec** [comment]
So basically doing this is considered a valid practice with Blazor:
```cs
_ = this.PasswordChanged.InvokeAsync(value);
```
I feel bad not handling exceptions which might be thrown asynchronously.

**Comment by epsitec** [comment]
@rynowak can you confirm that this is considered as a _good practice_?

**Comment by rynowak** [comment]
I would expect your code to look like:

```razor
<input id="pass"
       type="@(this.ShowPassword ? "text" : "password")"
       placeholder="votre mot de passe"
       required
       value="@Password"
       @oninput="PasswordChange" />
```

Is there a reason why you're not doing that?

**Comment by epsitec** [comment]
@rynowak I can't get it to work with _preview 8_.

* If I don't change `PasswordChanged` signature to be simply `EventCallback` (getting rid of `?` and `<string>`), the `@oninput="PasswordChanged"` does not compile.
* If I update the signature, then I get a crash at runtime: unable to cast object of type `EventCallback<string>` to `EventCallback`.

**Comment by epsitec** [comment]
@rynowak any idea why your suggest solution does not work? What would the signature of `PasswordChanged` be? And how would you make sure that the binding works at runtime?

**Comment by rynowak** [comment]
Sorry for the delay, it was a holiday weekend here. 

I think I've been giving you confusing answers thus far. Here's a sample that works, and properly routes errors. 

```
<input id="pass"
       type="@(this.ShowPassword ? "text" : "password")"
       placeholder="votre mot de passe"
       required
       value="@Password"
       @oninput="@OnPasswordChanged" />
<a id="show"
   @onclick="@this.ToggleShowPassword"
   title="Afficher le mot de passe">
    <i class="fal @(this.ShowPassword ? "fa-eye" : "fa-eye-slash")"></i>
</a>

@code {
    bool ShowPassword { get; set; }

    [Parameter]
    public string Password
    {
        get
        {
            return this.password ?? "";
        }
        set
        {
            if (this.password != value)
            {
                this.password = value;
            }
        }
    }

    [Parameter]
    public EventCallback<string> PasswordChanged { get; set; }

    private void ToggleShowPassword()
    {
        this.ShowPassword = !this.ShowPassword;
    }

    private string password;

    private Task OnPasswordChanged(ChangeEventArgs e)
    {
        Password = (string)e.Value;
        return PasswordChanged.InvokeAsync(Password);
    }
}

```

**Comment by rynowak** [comment]
Reopening this for consideration. I'd like to see if there's a way we can make `OnPasswordChanged` unnecessary in this case (chained bind)

**Comment by rynowak** [comment]
@epsitec - I hope you don't mind, I'm proposing to use a simplified version of your code in our docs https://github.com/aspnet/AspNetCore.Docs/issues/14144

**Comment by epsitec** [comment]
@rynowak no prblême, you are welcome to use it!

**Comment by rynowak** [comment]
Filed a docs issue for the current solution to this. Moving to backlog to track future improvements.

**Comment by mkArtakMSFT** [comment]
This is now addressed as part of the @bind:get and @bind:set work: https://learn.microsoft.com/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0
