### ISSUE TITLE
SignalR MaximumReceiveMessageSize

### ISSUE THREAD

**Issue by kofifus** [aspnet/AspNetCore#13466]
My previous code was:

```
app.UseSignalR((options) =>{
  options.MapHub<Pages.Hubs.ClientsHub>("/hubs/clientshub", configureOptions => {
      configureOptions.TransportMaxBufferSize = 999999;
      configureOptions.ApplicationMaxBufferSize = 999999;
  });
});
```

Which worked fine with long buffers.

I now upgraded to preview 8 and changed my code to:
```
app.UseEndpoints((options) => {
  options.MapHub<ClientsHub>("/hubs/clientshub", configureOptions => {
    configureOptions.TransportMaxBufferSize = 999999;
    configureOptions.ApplicationMaxBufferSize = 999999;
  });
});
```

but SignalR no longer handles big buffers, I get:

```
System.IO.InvalidDataException: The maximum message size of 32768B was exceeded. The message size can be configured in AddHubOptions.
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

I looked at many threads and found recommendations to use `MaximumReceiveMessageSize`

However if I try:
```
app.UseEndpoints((options) =>{
  options.MapHub<ClientsHub>("/hubs/clientshub", configureOptions => {
    configureOptions.MaximumReceiveMessageSize = 102400000;
  });
});
```

I get :

> Error	CS1061	'HttpConnectionDispatcherOptions' does not contain a definition for 'MaximumReceiveMessageSize' and no accessible extension method 'MaximumReceiveMessageSize' accepting a first argument of type 'HttpConnectionDispatcherOptions' could be found

There seems to be very little documentation for this - What is the current (preview8) correct way to increase the buffer size for SignalR ?

**Comment by kofifus** [comment]
Thanks @BrennanConroy ! is that instead or in addition to UseEndpoints ?

**Comment by kofifus** [comment]
Thanks ! is there still a need for  `TransportMaxBufferSize` and `ApplicationMaxBufferSize` ?

**Comment by kofifus** [comment]
thanks!

**Comment by kofifus** [comment]
Is there a maximum for `MaximumReceiveMessageSize` ? 
Is there a value that makes it unlimited ?

**Comment by kofifus** [comment]
Thanks! please add this to the documentation
(SignalR is wonderful, thanks for the work...)
