### ISSUE TITLE
Collection type unsupported error in .NET Core 3.0

### ISSUE THREAD

**Issue by shravan2x** [aspnet/AspNetCore#13597]
This exception occurs when I ported my MVC project to .NET Core 3.0 preview8. It seems to be some issue with the new JSON serializer since it worked before with Json.NET before and even works now with `AddNewtonsoftJson()`.

```
System.NotSupportedException: The collection type 'System.Collections.Generic.Dictionary`2[System.Guid,<>f__AnonymousType9`7[System.String,System.String,System.String,System.Nullable`1[System.DateTime],System.Nullable`1[System.Int64],System.UInt32,System.Nullable`1[System.UInt32]]]' on '<>f__AnonymousType8`2[System.Int32,System.Collections.Generic.Dictionary`2[System.Guid,<>f__AnonymousType9`7[System.String,System.String,System.String,System.Nullable`1[System.DateTime],System.Nullable`1[System.Int64],System.UInt32,System.Nullable`1[System.UInt32]]]].videos' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type type, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce
1. Unsure, the error doesn't give me stack trace so I can't debug too well.

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc
```

**Comment by BrennanConroy** [comment]
It looks like you're trying to serialize a `Dictionary<GUID, anonymous>` which isn't supported by System.Text.Json at this time.

>When serializing, only `Dictionary<string, TValue>`

From https://github.com/dotnet/corefx/issues/40120#issuecomment-519333400

**Comment by shravan2x** [comment]
IMO this is a serious limitation in the new serializer. Will it be resolved by the 3.0 release?

Im curious as to why we switched to the new one when Json.NET worked well in all cases. If its just for performance, would it serve users better to make the newer serializer be made opt-in instead?

**Comment by BrennanConroy** [comment]
If you'd like to read about the reasoning you can take a look at https://github.com/dotnet/announcements/issues/90

And we do provide a plug-in for Newtonsoft so you can use it if you so wish.

**Comment by shravan2x** [comment]
The discussion there makes sense, though I still feel like it's being rushed into AspNetCore before the API matures.
