### ISSUE TITLE
System.Text.Json Guid deserialization error handling

### ISSUE THREAD

**Issue by simonholt** [aspnet/AspNetCore#13811]
### Describe the bug
During deserialization of objects which contain GUIDs, malformed GUIDs trigger a 500 response rather than a 400.

This looks very much like #11790, but may be a special case for GUIDs.

Possibly also related to #8474 and #10033

(If using a GUID as part of a route (i.e. /api/myentity/{id}) then malformed GUIDs trigger a 400 as expected, and as they did in previous versions of the framework)

### To Reproduce
Tested in 3.0 preview 9.

Create a new WebAPI project using the 3.0 template.

Add the following to the controller:
```
        public class BadSample
        {
            public Guid Test { get; set; }
        }

        [HttpPost]
        public IActionResult Example(BadSample data) => Ok(data.Test);
```

Now post a message to the controller with a body like this:

{
	"Test": "bad-value"
}

Under 2.2, you would get a 400 result ""Error converting value \"bad-value\" to type 'System.Guid'. Path 'Test', line 2, position 20.""

Under 3.0, you get a 500 Internal Server Error with the following stack trace
```
System.FormatException: The JSON value is not in a supported Guid format.
   at System.Text.Json.Utf8JsonReader.GetGuid()
   at System.Text.Json.Serialization.Converters.JsonConverterGuid.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
### Expected behavior
Invalid GUID should trigger a "Bad Request" (400) response with a ProblemDetails object, not an Internal server error.

### Additional context
SDK Version: 3.0.100-preview9-014004
Runtime: Microsoft.NETCore.App 3.0.0-preview9-19423-09

**Comment by pranavkm** [comment]
Thanks for the report. 

@ahsonkhan \ @steveharter, looks like this needs to use `ThrowHelper` so that the exception can be wrapped as a `JsonException` instance:

https://github.com/dotnet/corefx/blob/39d8cf14b1eaf2d7678d1399bc903a0e547cce26/src/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.TryGet.cs#L440-L448

**Comment by ahsonkhan** [comment]
@pranavkm - yep, that's precisely the issue. I have submitted a fix for this. We should discuss whether this issue meets the 3.0 bar at this point.

**Comment by pranavkm** [comment]
Closing this as it's fixed in `master`. @ahsonkhan do you need an issue to track porting this to 3.1?

**Comment by ahsonkhan** [comment]
> do you need an issue to track porting this to 3.1?

That would be great. Copying this issue to corefx would be sufficient (we can apply the 3..0.x milestone - https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.x).

**Comment by pranavkm** [comment]
Filed https://github.com/dotnet/corefx/issues/41032 to track fixing this for the next release. Thanks everyone!
