### ISSUE TITLE
Unhandled ConnectionAbortedException

### ISSUE THREAD

**Issue by stelian56** [aspnet/AspNetCore#13837]
On two occasions, 1 month apart, our 2.2 ASP.NET application crashed due to the unhandled exception below:
Microsoft.AspNetCore.Connections.ConnectionAbortedException: 'The Socket transport's send loop completed gracefully.' Stack trace found by process dump analysis with Visual Studio:
`at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
at System.IO.Pipelines.PipeCompletion.ThrowLatchedException() in E:\A\_work\207\s\corefx\src\System.IO.Pipelines\src\System\IO\Pipelines\PipeCompletion.cs:line 116
at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) in E:\A\_work\207\s\corefx\src\System.IO.Pipelines\src\System\IO\Pipelines\Pipe.cs:line 772
at System.IO.Pipelines.Pipe.GetReadAsyncResult() in E:\A\_work\207\s\corefx\src\System.IO.Pipelines\src\System\IO\Pipelines\Pipe.cs:line 765
at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.RawStream.<ReadAsyncInternal>d__24.MoveNext() in /_/src/Kestrel.Core/Adapter/Internal/RawStream.cs:line 145
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 193
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable_1.ConfiguredValueTaskAwaiter.GetResult() in E:\A\_work\644\s\src\mscorlib\shared\System\Runtime\CompilerServices\ConfiguredValueTaskAwaitable.cs:line 168
at System.Net.FixedSizeReader.<ReadPacketAsync>d__1.MoveNext() in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\FixedSizeReader.cs:line 57
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
at System.Net.Security.SslState.ThrowIfExceptional() in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 101
at System.Net.Security.SslState.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 453
at System.Net.Security.SslState.CheckOldKeyDecryptedData(Memory_1 buffer) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 534
at System.Net.Security.SslState.HandleQueuedCallback(Object& queuedStateRequest) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 1387
at System.Net.Security.SslState.FinishHandshakeRead(Int32 newState) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 1192
at System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 1448
at System.Net.Security.SslState.RehandshakeCompleteCallback(IAsyncResult result) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\Security\SslState.cs:line 1833
at System.Net.LazyAsyncResult.Complete(IntPtr userToken) in E:\A\_work\286\s\corefx\src\Common\src\System\Net\LazyAsyncResult.cs:line 428
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken) in E:\A\_work\286\s\corefx\src\Common\src\System\Net\LazyAsyncResult.cs:line 384
at System.Net.AsyncProtocolRequest.CompleteUserWithError(Exception e) in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\HelperAsyncResults.cs:line 135
at System.Net.FixedSizeReader.<ReadPacketAsync>d__1.MoveNext() in E:\A\_work\286\s\corefx\src\System.Net.Security\src\System\Net\FixedSizeReader.cs:line 74
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in E:\A\_work\644\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 167
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\644\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
at System.Threading.ThreadPoolWorkQueue.Dispatch() in E:\A\_work\644\s\src\mscorlib\src\System\Threading\ThreadPool.cs:line 588`

We have not been able to reproduce the error. We believe that the exception was thrown from a ASP.NET worker thread since the stack trace contains no reference to our application code.

**Comment by shirhatti** [comment]
Could you please share the process dump you've collected this us to further investigate?

My email address is on my GitHub profile

**Comment by stelian56** [comment]
The *.dmp file is too large for an email attachment (9.5 GB). I can share it with you through a Google drive. Please advise or suggest an alternative.

**Comment by shirhatti** [comment]
Sure. Can you zip before sharing? Dmps usually compress very well
