### ISSUE TITLE
Process crash when raising an error in "async void" method

### ISSUE THREAD

**Issue by PawelGerr** [aspnet/AspNetCore#13867]
Calling a method `void A()` that calls `async void B()` in a controller crashes the ASP.NET Core process if `B` raises an error.

Make a GET request using the url `http://localhost:5000/test` to be able to reproduce the issue.

## csproj-File
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.2</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.7" />
    </ItemGroup>

</Project>
```

## Program.cs incl. the controller
```
using System;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace AspnetCoreCrash
{
   class Program
   {
      static void Main(string[] args)
      {
         WebHost.CreateDefaultBuilder()
                .ConfigureServices(services => services.AddMvc()
                                                       .AddApplicationPart(typeof(TestController).Assembly))
                .Configure(app => app.UseMvc())
                .Build()
                .Run();
      }
   }

   [Route("[controller]")]
   public class TestController : Controller
   {
      [HttpGet]
      public IActionResult Test()
      {
         RaiseEvent();

         return Ok("ok");
      }

      private void RaiseEvent() => RaiseEventVoidAsync();

      private async void RaiseEventVoidAsync() => throw new Exception("Error!");
   }
}
```
## Raised exception inside .NET
```
System.Exception: Error!
   at AspnetCoreCrash.TestController.RaiseEventVoidAsync() in C:\Projects\Tests\ConsoleApp4\AspnetCoreCrash\Program.cs:line 36
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallback.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.402\

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @PawelGerr.
Why are you interested in having `async void`?

**Comment by DAllanCarr** [comment]
> Async void methods have different error-handling semantics. When an exception is thrown out of an async Task or async Task<T> method, that exception is captured and placed on the Task object. With async void methods, there is no Task object, so any exceptions thrown out of an async void method will be raised directly on the SynchronizationContext that was active when the async void method started.

http://blogs.microsoft.co.il/dorony/2013/10/30/async-void-methods-can-crash-your-process/
