### ISSUE TITLE
Post and return 500 after upgrade to 3.0 priview-9

### ISSUE THREAD

**Issue by Cuiqs76** [aspnet/AspNetCore#13920]
Error:

Post  and return 500 after upgrade to 3.0 priview-9

Code | Details
--
   [HttpGet]
        [Route("{id:Guid}")]
        [ProducesResponseType((int)HttpStatusCode.NotFound)]
        [ProducesResponseType((int)HttpStatusCode.BadRequest)]
        public async Task<ActionResult> GetByIdAsync(Guid id )
        {
            var item= await  _productRepository.GetByIdAsync(id);

            if (item == null)
            {
                return NotFound(new { Message = $"Item with id {item.Id} not found." });
            }

            return Ok(item);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<ActionResult> CreateAsync([FromBody]ProductCreateInput input)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var item = new Product(input.Code, lnput.Name,input.Description,input.Model,input.DrawingNo);

            await  _productRepository.AddAsync(item);

            return CreatedAtAction(nameof(GetByIdAsync), new { id = item.Id }, item.Id);           
        }
--

### To Reproduce
1. Using this version of ASP.NET Core '3.0- preview-9'
2. Run this code ' https://localhost:5001/api/Products '
3. With these arguments '....'
4. See error  return 500. 

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLPN6PD2AT1K", Request id "0HLPN6PD2AT1K:0000000B": An unhandled exception was thrown by the application.
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 6818.2970000000005ms 500

**Comment by Hulkstance** [comment]
I had a similar problem that I couldn't find a related solution. I just added:

```
app.UseEndpoints(endpoints =>
{
	endpoints.MapDefaultControllerRoute();
});
```

Hope it helps someone.
