### ISSUE TITLE
Design time builds can explode if other builds in progress

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14328]
Details over here: https://github.com/OmniSharp/omnisharp-vscode/issues/3213

**Comment by genne** [comment]
This happens to me almost every time I switch branch. Any updates on fixing?

Exception details are more or less the same as in linked issue, but triggered by an `OnDeleted` callback:
```
Unhandled Exception: System.InvalidOperationException: The operation cannot be completed because a build is already in progress.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Execution.BuildManager.BeginBuild(BuildParameters parameters)
   at Microsoft.Build.Execution.BuildManager.Build(BuildParameters parameters, BuildRequestData requestData)
   at Microsoft.Build.Execution.ProjectInstance.Build(String[] targets, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ILoggingService loggingService, Int32 maxNodeCount, IDictionary`2& targetOutputs)
   at Microsoft.AspNetCore.Razor.OmniSharpPlugin.DefaultProjectInstanceEvaluator.Evaluate(ProjectInstance projectInstance) in /_/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectInstanceEvaluator.cs:line 86
   at Microsoft.AspNetCore.Razor.OmnisharpPlugin.MSBuildProjectManager.RazorDocumentChanged(RazorFileChangeEventArgs args) in /_/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectManager.cs:line 112
   at Microsoft.AspNetCore.Razor.OmniSharpPlugin.MSBuildProjectDocumentChangeDetector.FileSystemWatcher_RazorDocumentEvent(String filePath, String projectDirectory, ProjectInstance projectInstance, RazorFileChangeKind changeKind) in /_/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectDocumentChangeDetector.cs:line 126
   at Microsoft.AspNetCore.Razor.OmniSharpPlugin.MSBuildProjectDocumentChangeDetector.<>c__DisplayClass7_0.<ProjectLoaded>b__1(Object sender, FileSystemEventArgs args) in /_/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectDocumentChangeDetector.cs:line 86
   at System.IO.FileSystemWatcher.OnDeleted(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by NTaylorMullen** [comment]
This will be fixed in the next release 😄
