### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Internal.ApiDescriptionActionData

### ISSUE THREAD

**Issue by hanxinimm** [aspnet/AspNetCore#14454]
异常信息 Could not load type 'Microsoft.AspNetCore.Mvc.Internal.ApiDescriptionActionData' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.D:\ProgramData\SF\default\Fabric\work\Applications\CustomerAppType_App1430\Labor.Customer.StatelessWebApiQueryServicePkg.Code.1.0.0\Labor.Customer.StatelessWebApiQueryService.dll 内部异常 D:\ProgramData\SF\default\Fabric\work\Applications\CustomerAppType_App1430\Labor.Customer.StatelessWebApiQueryServicePkg.Code.1.0.0\Labor.Customer.StatelessWebApiQueryService.dll 异常来源 Hunter.ApiDocs.ApiExplorerD:\ProgramData\SF\default\Fabric\work\Applications\CustomerAppType_App1430\Labor.Customer.StatelessWebApiQueryServicePkg.Code.1.0.0\Labor.Customer.StatelessWebApiQueryService.dll 异常堆栈    at Hunter.ApiDocs.ApiExplorer.DefaultApiDescriptorProvider.OnProvidersExecuting(ApiDescriptorProviderContext context)
   at Hunter.ApiDocs.ApiExplorer.ApiGroupDescriptorCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Hunter.ApiDocs.ApiExplorer.ApiGroupDescriptorCollectionProvider.get_ApiGroupDescriptors()
   at Hunter.ApiDocs.ApiGateway.ApiGatewayDocsProvider`4.CreateApiActions(IApiGroupDescriptorCollectionProvider apiGroupCollectionDescriptor)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hunter.ApiDocs.ApiGateway.ApiGatewayDocsProvider`4.GetApiDocs()
   at Hunter.ApiDocs.ApiGateway.ApiGatewayDocsMiddleware`4.Invoke(HttpContext httpContext)
   at Hunter.ApiGateway.ApiDiscovery.ApiDiscoverMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"

**Comment by javiercn** [comment]
@hanxinimm Thanks for contacting us.

Can you provide a github repository with a repro project and detailed steps to reproduce the issue?

**Comment by hanxinimm** [comment]
@javiercn 

Microsoft.AspNetCore.Mvc.Core 3.0.0 is not contain type Microsoft.AspNetCore.Mvc.Internal.ApiDescriptionActionData 
how can i get Microsoft.AspNetCore.Mvc.ApiExplorer 3.0.0 nuget package

**Comment by pranavkm** [comment]
@hanxinimm there are a couple of breaking changes in ASP.NET Core 3.0. See https://github.com/aspnet/Announcements/issues/326, https://github.com/aspnet/Announcements/issues/325. The type was made `internal` since it's an internal implementation detail and `Microsoft.AspNetCore.Mvc.ApiExplorer` is no longer being produced.

That said, to target ASP.NET Core 3.0 in your library, you'll need a `FrameworkReference` to `Microsoft.AspNetCore.App`. Please follow our migration instructions to update your projects: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30. For the API - `ApiDescriptionActionData` in question, you would need to recompile the library to use `ApiDescription` instead. https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc.Abstractions/src/ApiExplorer/ApiDescription.cs#L21-L24 is likely what you need.
