### ISSUE TITLE
PortablePdbReader/ExceptionDetailsProvider may throw an exception which causes problems in callers like DeveloperExceptionPageMiddleware

### ISSUE THREAD

**Issue by cremor** [aspnet/AspNetCore#14609]
### Describe the bug
`PortablePdbReader.GetPdbPath()` calls `PEReader.ReadDebugDirectory()` but doesn't handle exceptions that this call might throw. This in turn will then cause problems for callers higher up in the call stack, like `DeveloperExceptionPageMiddleware` or [Hellang.Middleware.ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails) which call it via `ExceptionDetailsProvider.GetDetails`.

### To Reproduce
1. Using version 2.2 or 3.0 of ASP.NET Core
2. Add a reference to [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess/) to the project (the current version is 19.3.1, future versions might not be affected)
3. Add the packages `Microsoft.Extensions.StackTrace.Sources` and `Microsoft.Extensions.TypeNameHelper.Sources` (via https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json)
4. Run this code:
``` cs
try
{
    // Trigger an exception inside Oracle.ManagedDataAccess.dll
    using (var conn = new OracleConnection())
    {
        conn.Open();
    }
}
catch (Exception ex)
{
    var provider = new ExceptionDetailsProvider(env.ContentRootFileProvider, 10);
    foreach (var detail in provider.GetDetails(ex))
    {
        // Would do something with 'detail' here.
    }
}
```
5. See this exception in the DeveloperExceptionPage:
```
System.BadImageFormatException: Invalid directory size.
   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath(String assemblyPath) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\PortablePdbReader.cs:line 99
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetMetadataReader(String assemblyPath) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\PortablePdbReader.cs:line 72
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\PortablePdbReader.cs:line 27
   at Microsoft.Extensions.StackTrace.Sources.StackTraceHelper.GetFrames(Exception exception) in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\StackFrame\StackFrame\StackTraceHelper.cs:line 61
   at Microsoft.Extensions.StackTrace.Sources.ExceptionDetailsProvider.GetDetails(Exception exception)+MoveNext() in C:\Users\Username\.nuget\packages\microsoft.extensions.stacktrace.sources\3.0.0-preview-181114-06\contentFiles\cs\netstandard1.0\Microsoft.Extensions.StackTrace.Sources\ExceptionDetails\ExceptionDetails\ExceptionDetailsProvider.cs:line 30
```
6. Remove the try-catch block around the code that triggers the exception.
7. See that the DeveloperExceptionPage is empty. Instead the following exception is written to the output window:
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An exception was thrown attempting to display the error page.

System.BadImageFormatException: Invalid directory size.
   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetPdbPath(String assemblyPath)
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.GetMetadataReader(String assemblyPath)
   at Microsoft.Extensions.StackTrace.Sources.PortablePdbReader.PopulateStackFrame(StackFrameInfo frameInfo, MethodBase method, Int32 IlOffset)
   at Microsoft.Extensions.StackTrace.Sources.StackTraceHelper.GetFrames(Exception exception)
   at Microsoft.Extensions.StackTrace.Sources.ExceptionDetailsProvider.GetDetails(Exception exception)+MoveNext()
   at Microsoft.AspNetCore.Diagnostics.RazorViews.ErrorPage.ExecuteAsync()
   at Microsoft.Extensions.RazorViews.BaseView.ExecuteAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Expected behavior
No exception should be thrown while getting the details of another exception. If the exception details can't be collected, show as many details as possible, but don't fail.

### Additional context
It is important to use [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess/) to reproduce the problem. [Oracle.ManagedDataAccess.Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/) will **not** cause the problem! It looks like Oracle.ManagedDataAccess is obfuscated and I assume that causes the exception in `PEReader.ReadDebugDirectory()`.
To explain why I use the non-core version of Oracle.ManagedDataAccess: I initially found this in an solution that runs ASP.NET Core 2.2 on .NET Framework 4.7.1

Output of `dotnet --info`:
```
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100
 Commit:    04339c3a26

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by anurse** [comment]
It seems reasonable to do a special-case `try..catch` around this and just print out less detail. Looks like @khellang is looking at that :).
