### ISSUE TITLE
 HTTP Error 500.30 - ANCM In-Process Start Failure & System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Mmatiasn** [aspnet/AspNetCore#14641]
### Describe the bug
I'm currently able to host my dotnet core 2.2 web api application on my local machine in IISExpress or IISLocal. When I deployed to my Windows Server 2012 R2 Standard I started getting HTTP Error 500.30 - ANCM In-Process Start Failure. I ran the executatable since it's an in process build and got this error: System.IO.FileNotFoundException: The configuration file 'ds
config.Production.json' was not found and is not optional. The physical path is
'D:\inetpub\wwwroot\CSDDocusign\dsconfig.Production.json'. The problem is that the file was coped to that directory and it has read permission for everyone.

### To Reproduce
1. Using version 2.2 of ASP.NET Core

### Expected behavior
If it runs on both IISExpress and IISLocal it should work on my web server.

### Additional context
D:\inetpub\wwwroot\CSDDocusign>dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

D:\inetpub\wwwroot\CSDDocusign>DocuSignAPI.exe

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'ds
config.Production.json' was not found and is not optional. The physical path is
'D:\inetpub\wwwroot\CSDDocusign\dsconfig.Production.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean
reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 provide
rs)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateE
xception& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at DocuSignAPI.Program.Main(String[] args) in C:\Users\MYACCOUNT\Source\DocuSi
gnAPI\Dev\DocuSignAPI\DocuSignAPI\Program.cs:line 20

**Comment by Mmatiasn** [comment]
Yep, the file was actually not there... The file that was there was actually dsconfig.Development.json. Thankfully I didn't waste anyone's time :)
