### ISSUE TITLE
Bad responses: Json, Plaintext

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#14655]
Some scenarios return errors:

| Scenario | Environment | Last Run | Errors |
| -------- | ----------- | -------- | ------ |
| Json | Windows, Physical, https, HttpSys | 10/1/19 8:50:52 PM +00:00 | 2301638 |
| Plaintext | Windows, Physical, https, HttpSys | 10/1/19 8:49:40 PM +00:00 | 2334748 |

[Logs](https://aka.ms/aspnet/benchmarks/jenkins)

**Comment by Pilchie** [comment]
@sebastienros ?

**Comment by davidfowl** [comment]
@sebastienros something that would be helpful here would be the run number for each environment.

```
[03:25:52.780] System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BenchmarksDriver.Program.Run(Uri serverUri, Uri[] clientUris, String sqlConnectionString, ServerJob serverJob, String session, String description, Int32 iterations, Int32 exclude, String shutdownEndpoint, TimeSpan span, List`1 downloadFiles, Boolean fetch, String fetchDestination, Boolean collectR2RLog, String traceDestination, CommandOption outputFileOption, CommandOption sourceOption, CommandOption scriptFileOption, CommandOption markdownOption, CommandOption writeToFileOption, Nullable`1 requiredOperatingSystem, CommandOption saveOption, CommandOption diffOption) in /var/jenkins_home/workspace/trend_citrine_windows/src/BenchmarksDriver/Program.cs:line 1217
New job  on 'http://<redacted>': -n Plaintext --webHost KestrelSockets --description Trend/Latest -j /var/jenkins_home/workspace/trend_citrine_windows/build/../src/Benchmarks/benchmarks.plaintext.json -i 3
The specified server url 'http://<redacted>' is invalid or not responsive.
```

**Comment by sebastienros** [comment]
This scenario doesn't work at all, and it's been months apparently. We might not have fixed it as the same time @jkotalik worked on IIS. We need to investigate if we still care about these scenarios.

**Comment by anurse** [comment]
@davidfowl 's error isn't the correct one. It's getting 404s.

**Comment by sebastienros** [comment]
Fixed with guidance from @Tratcher, the windows IP had changed and the certs config needed to reflect that.
