### ISSUE TITLE
await HttpRequestStreamReader.ReadToEndAsync throws when AllowSynchronousIO is set to false

### ISSUE THREAD

**Issue by mterhorst** [aspnet/AspNetCore#14734]
### Describe the bug
When this is set.
```C#
KestrelServerOptions.AllowSynchronousIO = false;
```
The following code throws exception `System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.`.
```C#
[HttpPost("~/example")]
public async Task<IActionResult> Example()
{
	using (var sr = new HttpRequestStreamReader(Request.Body, Encoding.UTF8))
	{
		var body = await sr.ReadToEndAsync();
	}

	return Ok();
}
```

### To Reproduce
1. Using VS 16.3.2 and ASP.NET Core sdk 3.0.100
2. Create API project and copy demonstrated code.
3. Run.

### Expected behavior
We should expect when `AllowSynchronousIO` is set to `false`,  that the demonstrated async code works without throwing the exception.

### Additional context
```.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download```

**Comment by Tratcher** [comment]
What's the full call stack of the exception?

**Comment by mterhorst** [comment]
Full call stack.
```
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextReader.Read(Span`1 buffer)
   at System.IO.TextReader.<>c.<ReadAsyncInternal>b__17_0(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.TextReader.ReadToEndAsync()
   at Example.Controllers.ApiController.Example() in C:\Playground\Example\Example\Controllers\ApiController.cs:line 19
```

**Comment by Tratcher** [comment]
Hmm, TextReader.ReadToEndAsync doesn't use ReadAsync, it has to be overridden independently.
https://github.com/dotnet/corefx/blob/72318ba71ad317141b2c0125c3850bce4a133d25/src/Common/src/CoreLib/System/IO/TextReader.cs#L211-L228
https://github.com/dotnet/corefx/blob/72318ba71ad317141b2c0125c3850bce4a133d25/src/Common/src/CoreLib/System/IO/TextReader.cs#L257-L265

**Comment by mterhorst** [comment]
Replacing te `HttpRequestStreamReader` with the following does work...
```C#
using (TextReader tr = new StringReader("example"))
{
	var s = await tr.ReadToEndAsync();
}
```

**Comment by Tratcher** [comment]
StringReader doesn't access the request body.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/AspNetCore/issues/13834.

**Comment by anurse** [comment]
Looks like #13834 covers this (though it wasn't super clear from the original content so I updated it). I'm going to close this as a duplicate.

**Comment by dbarkwell** [comment]
I ran into the same issue. I solved it by using a PipeReader.

var reader = PipeReader.Create(context.HttpContext.Request.Body);

**Comment by davidfowl** [comment]
That’s not how you solve this issue

**Comment by dbarkwell** [comment]
@davidfowl sorry, I wasn't trying to solve it. I was just offering a suggestion that worked for me.

I ended up with that code because I've recently been reading up on the documentation you posted on pipelines.
