### ISSUE TITLE
InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNetCore.Authentication.Google'

### ISSUE THREAD

**Issue by scalablecory** [aspnet/AspNetCore#14796]
_From @nefcanto on Sunday, October 6, 2019 1:16:11 PM_

# Issue Title

I upgraded VS2019 Community Edition, from 16.2.something to 16.3.2. The upgrade took a couple of minutes, then a restart, then building my web project, and then I saw this error:

InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNetCore.Authentication.Google'

# General

This is the stack trace:

```
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.AspNetCore.Authentication.Google'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.FindView(ActionContext actionContext, PartialViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor.ExecuteAsync(ActionContext context, PartialViewResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Based on some other issues, I added this line of code:
    `<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`

But it made no difference.

What should I do?

**Note:** Please note that I've not used Google authentication at all. All of our authentication is written by our own team and we are not even familiar with this package.

_Copied from original issue: dotnet/core#3557_

**Comment by blowdart** [comment]
Is this an existing project or a new one from a template?

What are you dependencies? Please post your project.json

**Comment by nefcanto** [comment]
It's an existing project, that we created from empty template a year ago.

We don't have project.json of course. We have Web.config file. And we're using `targets` files as build configuration mixins. 

Here's the csproj file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AssemblyName>HolismData.YogaWeb.AdminPanel</AssemblyName>
    <RootNamespace>HolismData.YogaWeb.AdminPanel</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Update="Scripts\MenuItems.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Import Project="$(HolismProjectsRoot)\Microfrontend\ProjectAdminPanel.targets" />
  <Import Project="$(HolismProjectsRoot)\Framework\ProjectReusableWeb.targets" />
  <Import Project="$(HolismProjectsRoot)\EntityWeb\ProjectAdminPanel.targets" />
  <Import Project="$(HolismProjectsRoot)\TaxonomyWeb\ProjectAdminPanel.targets" />

  <ItemGroup>
    <Content Update="Scripts\YogaInitializer.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
```

Each of these `targets` files include some files as links and reference some DLL files and NuGet packages, etc. But besides that, here are the important parts of build configuration that is included via these `targets` files:

This is root `Project.targets` file that all projects inherit from:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!--<OutputPath>.\bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>-->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    <PackageReference Include="morelinq" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Holism.Framework">
      <HintPath>$(HolismProjectsRoot)\Framework\Packages\Holism.Framework.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Holism.Validation">
      <HintPath>$(HolismProjectsRoot)\Framework\Packages\Holism.Validation.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Holism.Normalization">
      <HintPath>$(HolismProjectsRoot)\Framework\Packages\Holism.Normalization.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.2.4" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="$(SolutionDir)\Settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```


This is `ProjectWeb.targets' file that all web projects inherit from:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
	<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
    <!--<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Views\**\*.js" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Scripts\**\*.js" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Styles\**\*.css" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Images\**\*.*" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Fonts\**\*.*" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Holism.Mvc">
      <HintPath>$(HolismProjectsRoot)\Framework\Packages\Holism.Mvc.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="taskkill /f /fi &quot;pid gt 0&quot; /im dotnet.exe" IgnoreExitCode="true" IgnoreStandardErrorWarningFormat="true" />
  </Target>

</Project>
```

**Comment by nefcanto** [comment]
Please note that I have not changed even one line of code. All I've done was to upgrade Visual Studio to 16.3.2, and rebuild my web projects.

**Comment by nefcanto** [comment]
Well, I tried to compare the outcome (bin folder) of an old .NET Core 2.2 project, with the same upgraded .NET Core 3.0 project. I found out that a lot of DLL files are not getting copied into the output directly. The reason? It's because of [breaking changes to `FrameworkReference` in .NET 3.0.](https://github.com/aspnet/Announcements/issues/325).

So, for now, what I did was to create a list of all DLL files that are necessary to be copied into the output directory as a `targets` file, and include it in my `ProjectWeb.targets`  base targets file. It solved my problem, until I upgrade my infrastructure to .NET Core 3.0.

**Comment by pranavkm** [comment]
@nefcanto thanks for your issue report. We made some changes to the SDK to avoid copying reference assemblies, required for runtime compilation, where it previously always copied it. Typically projects targeting netcoreapp2.x should remain unaffected, but we assume that these projects target the Web or the Razor SDK since that's what we recommend targeting. In your case, I notice there are a couple of references to the `Microsoft.NET.Sdk` SDK which might explain why you're running in to this issue.

If you have a minimal app that reproduces the problem, it would help investigating this further. In the meanwhile, you have a couple of options,

a) In the web project that you're building add `<PreserveCompilationReferences>true</PreserveCompilationReferences>`. This is the flag that the SDK uses to determine if ref assemblies need to be copied to the build output directory
b) Attempt to change the SDK in your projects to `Microsoft.NET.SDK`
