### ISSUE TITLE
Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by higor-correa** [aspnet/AspNetCore#14833]
Hey, I am having the following issue when starting my WebApi with Core 3.0
I've been looking in closed issues and found this [8254](https://github.com/aspnet/AspNetCore/issues/8254) that were fixed in [this PR](https://github.com/aspnet/AspNetCore/pull/8437) but i'm still having this error and i'm not using Ocelot.

Could anyone help me?

```
System.TypeLoadException: 'Could not load type 'Microsoft.Extensions.DependencyInjection.MvcJsonMvcCoreBuilderExtensions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
```

**Comment by higor-correa** [comment]
Actually I'm using these lines that is throwing this exception and without `AddJsonFormatters` it's all good. What should i use instead of it?
```
services.AddMvcCore()
        .AddApiExplorer()
        .AddJsonFormatters()
```

**Comment by pranavkm** [comment]
Hi @higor-correa there was a [breaking change](https://github.com/aspnet/Announcements/issues/325) in .NET Core 3.0 to remove Newtonsoft.Json from the shared framework. `AddJsonFormatters` was one of the affected APIs. You're likely seeing this error because you have a project that is compiled against ASP.NET Core 2.x (or earlier), but running against .NET Core 3.0.

Can you give us some more details about what you're trying to do here? Is this a library project that targets multiple versions of ASP.NET Core? Do you need to use Json.Net in your applications or do the System.Text.Json based formatters introduced in 3.0 suffice?

**Comment by higor-correa** [comment]
@pranavkm in company I work we have a class library in dotnet standard containing all api's controllers and we use use 2 startups WebApi (Core and Framework). And these 3 lines that I mentioned are from our standard library.

I think that we must take another approach to configure "same" WebApi to both (Core and Framework).

Do you think I'm thinking right?

**Comment by pranavkm** [comment]
> I think that we must take another approach to configure "same" WebApi to both (Core and Framework).

Yeah, that might be a good option to go with here. See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-libraries-via-multi-targeting for ways to cross-compile your library to continue supporting multiple versions of .NET Core.
