### ISSUE TITLE
ASP.NET Core 3.0 - "Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.String]' to type 'System.Collections.IList

### ISSUE THREAD

**Issue by niemyjski** [aspnet/AspNetCore#14855]
### Describe the bug
I'm running into this really weird behavior when trying to upgrade to with asp.net core 3.0 and use the new serializer. The `SystemTextJsonInputFormatter.ReadRequestBodyAsync` seems to be throwing this exception and I'm at a loss (I've enabled source debugging and I can't get it to hit any code after the `ResourceInvoker` and didn't have time to pull in all the source):

```
System.Net.Http.HttpRequestException : Expected status code Created but received status code InternalServerError (Internal Server Error).
{"message":"Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.String]' to type 'System.Collections.IList'.","is_error":true,"detail":"   
at System.Text.Json.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Utf8JsonReader& reader, Boolean setPropertyDirectly)  
at System.Text.Json.JsonSerializer.HandleEndArray(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack) 
at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)   
at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatter


----


33:13.43493 I:Diagnostics - Request starting HTTP/1.1 POST http://localhost/api/v2/tokens application/json; charset=utf-8 
33:13.58845 I:DefaultAuthorizationService - Authorization was successful.
33:13.60239 I:EndpointMiddleware - Executing endpoint 'Exceptionless.App.Controllers.API.TokenController.PostAsync (Exceptionless.Web)'
33:13.62541 I:ControllerActionInvoker - Route matched with {action = "Post", controller = "Token"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[Exceptionless.Web.Models.ViewToken]] PostAsync(Exceptionless.Web.Models.NewToken) on controller Exceptionless.App.Controllers.API.TokenController (Exceptionless.Web).
33:16.35146 I:ObjectResultExecutor - Executing ObjectResult, writing value of type 'Exceptionless.Web.Utility.Handlers.ApiError'.
33:16.41809 I:ControllerActionInvoker - Executed action Exceptionless.App.Controllers.API.TokenController.PostAsync (Exceptionless.Web) in 2762.0513ms
33:16.41872 I:EndpointMiddleware - Executed endpoint 'Exceptionless.App.Controllers.API.TokenController.PostAsync (Exceptionless.Web)'
33:16.42189 I:Diagnostics - Request finished in 2986.945ms 500 application/json; charset=utf-8


```

I've written a serializer test to ensure that the model can be round tripped:
```cs
    public class NewToken {
        public NewToken() {
            Scopes = new HashSet<string>();
        }

        public string OrganizationId { get; set; }
        public string ProjectId { get; set; }
        public string DefaultProjectId { get; set; }
        public HashSet<string> Scopes { get; set; }
        public DateTime? ExpiresUtc { get; set; }
        public string Notes { get; set; }
    }

        [Fact]
        public void CanSerializeSimpleModel() {
            var token = new NewToken {
                OrganizationId = "TEST_ORG_ID",
                ProjectId = "TEST_PROJECT_ID",
                Scopes = new HashSet<string> { "Client", "User" }
            };

            string json = System.Text.Json.JsonSerializer.Serialize(token);
            _logger.LogInformation(json);
            var token2 = System.Text.Json.JsonSerializer.Deserialize<NewToken>(json);
        }
```

Here is the model that's being [posted](https://github.com/exceptionless/Exceptionless/blob/feature/elastic7/tests/Exceptionless.Tests/Controllers/TokenControllerTests.cs#L31-L35)
```cs
new NewToken {
                   OrganizationId = "TEST_ORG_ID",
                   ProjectId ="TEST_PROJECT_ID",
                   Scopes = new HashSet<string> { "Client", "User" }
               }
```
To a controller that looks like this:
```cs
[HttpPost]
public Task<ActionResult<Object>> PostAsync(NewToken token) {
}
```

with serializer settings defined as:
```cs
            options.AllowTrailingCommas = true;
            options.DictionaryKeyPolicy = null;
            options.IgnoreNullValues = true;
            options.IgnoreReadOnlyProperties = false;
            options.PropertyNameCaseInsensitive = true;
            options.PropertyNamingPolicy = new SnakeCaseJsonNamingPolicy();
            options.ReadCommentHandling = JsonCommentHandling.Skip;
            options.WriteIndented = false;
```

### To Reproduce
1. Using this version of ASP.NET Core:  `3.0.100`
2. Run this code ' as shown above

I removed the scopes property from the model and it worked on my end. So something definitely todo with serialization but it's just odd that it works when I do it directly as the test shown above.

### Expected behavior

There should not be any issues with posting the model.

### Additional context
Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by pranavkm** [comment]
@niemyjski do you have a minimal repro you could share?

@ahsonkhan \ @layomia does this ring a bell?

**Comment by niemyjski** [comment]
@pakrym not yet but if you clone the exceptionless repo you can run the single test (https://github.com/exceptionless/Exceptionless/blob/feature/elastic7/tests/Exceptionless.Tests/Controllers/TokenControllerTests.cs#L31-L35) I linked to that's pretty minimal. I'll try creating a sample and link it here

**Comment by niemyjski** [comment]
@pranavkm  Ok I created a super simple file -> new project sample here: https://github.com/niemyjski/aspnet-serializer-issue

and posted it with ` curl -d '{"organizationId":"value1", "scopes":["value2"]}' -H "Content-Type: application/json" -X POST http://localhost:5000/token`

```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.String]' to type 'System.Collections.IList'.
   at System.Text.Json.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Utf8JsonReader& reader, Boolean setPropertyDirectly)
   at System.Text.Json.JsonSerializer.HandleEndArray(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Host: localhost:5000
Referer: http://localhost:5000/token
User-Agent: PostmanRuntime/7.17.1
Content-Length: 48
Postman-Token: 375ff808-cd03-4250-812f-229426d40ec8
```

**Comment by niemyjski** [comment]
@pranavkm / @ahsonkhan / @layomia let me know if you need any additional information, this seems to be my last blocking issue.

**Comment by layomia** [comment]
I'm taking a look at this to see if this issue needs to be raised in corefx.

**Comment by Pilchie** [comment]
@layomia any update here?

**Comment by Rambalac** [comment]
Core 3.0 does not deserialize Json array as HashSet in the model. Looks like it expects that any json array should be IList. Workaround is to make model as IList.
Strange, because System.Text.Json does not have such HashSet issue by default.

**Comment by layomia** [comment]
This issue has been fixed in release/3.1 (https://github.com/dotnet/corefx/pull/41523). cc @pranavkm 

@niemyjski, can you please use the 3.1-preview1 (or master) build and verify the fix?

https://www.nuget.org/packages/System.Text.Json/4.7.0-preview1.19504.10

You can reference the latest master System.Text.Json NuGet package from https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

**Comment by Pilchie** [comment]
Closing the issue here.  @pranavkm can you verify with a recent 3.1 build?

**Comment by niemyjski** [comment]
Awesome thanks!
