### ISSUE TITLE
SignalR System.Threading.Tasks.Extensions

### ISSUE THREAD

**Issue by MikeRavenelle** [aspnet/AspNetCore#14857]
### Describe the bug
On Ubuntu, SignalR Client 3.0.0 attempts to load System.Threading.Tasks.Extensions 4.2.0. Which results in a System.IO.FileNotFoundException. This does not occur on Windows. The application runs correctly on the Windows platform.

### To Reproduce
1. Using this version of ASP.NET Core '3.0'  on Ubuntu 18.04
2. Attempt to make a SignalR Connection to a hub that does not exist.

### Expected behavior
SignalR connection fails but does not throw a exception for not finding System.Thread.Tasks.Extensions Version=4.2.0.0

### Error
```
Main execution failed, Exception System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
)
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilderHttpExtensions.WithUrlCore(IHubConnectionBuilder hubConnectionBuilder, Uri url, Nullable`1 transports, Action`1 configureHttpConnection)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilderHttpExtensions.WithUrl(IHubConnectionBuilder hubConnectionBuilder, String url)

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ExceptionSignalR.Test.StartAsync(CancellationToken cancellationToken) in
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
```
### Workaround
To get around this problem for now I reverted all my projects to use SignalR Client 1.1.0.

**Comment by MikeRavenelle** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
	<LangVersion>7.1</LangVersion>
    <ApplicationIcon />
    <StartupObject>Example.Example.Program</StartupObject>
	<TrimUnusedDependencies>true</TrimUnusedDependencies>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>RELEASE;NETCOREAPP;NETCOREAPP2_1;RELEASE;NETCOREAPP;NETCOREAPP2_1</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>RELEASE;NETCOREAPP;NETCOREAPP2_1;RELEASE;NETCOREAPP;NETCOREAPP2_1</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;CONSOLEAPP</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>TRACE;DEBUG;CONSOLEAPP</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.0.0" />
    <PackageReference Include="NLog.Extensions.Hosting" Version="1.6.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.8.6" />
	<PackageReference Include="Microsoft.Packaging.Tools.Trimming" Version="1.1.0-preview1-26619-01" />
	<PackageReference Include="System.ServiceProcess.ServiceController" Version="4.6.0" />
  <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.0.0" />
  <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Example.Common.Models\Example.Common.Models.csproj" />
    <ProjectReference Include="..\Example.Common\Example.Common.csproj" />
    <ProjectReference Include="..\Example.Core\Example.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Example.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by anurse** [comment]
> 	<PackageReference Include="Microsoft.Packaging.Tools.Trimming" Version="1.1.0-preview1-26619-01" />

This is a little suspicious. The trimmer can sometimes over-trim assemblies. Does the issue repro if you remove this dependency?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
