### ISSUE TITLE
Assigning IHostBuilder.Build().GetTestServer() to TestServer throws System.InvalidCastException

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore#14873]
### Describe the bug
Since WebHostBuilder is going to be deprecated and there is no document to describe it's replacement for building TestServer, I am trying the following to build TestServer for my integration tests:
```
var hostbuilder = Host.CreateDefaultBuilder().ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<MyStartup>().ConfigureServices(ConfigureServices));

//_server = new TestServer(hostbuilder); ASP.Net Core 2.2 code!
_server = hostbuilder.Build().GetTestServer(); // XXX: Hack for ASP.Net Core 3.0
```
and it throws runtime exception:
```
   System.InvalidCastException : Unable to cast object of type 'Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer' to type 'Microsoft.AspNetCore.TestHost.TestServer'.
```
https://github.com/aspnet/AspNetCore.Docs/issues/14962
### To Reproduce
1. Using this version of ASP.NET Core '...' 3.0
2. Run this code '....'
3. With these arguments '....'

### Expected behavior
Expect `IHostBuilder.Build().GetTestServer()` to return TestServer object for integration tests.
### Additional context
Include the output of `dotnet --info`
```
$ dn --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet-3.0.100/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet-3.0.100/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet-3.0.100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet-3.0.100/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by khteh** [comment]
I get the same exception with this line of code:
```
HttpClient client = hostbuilder.Build().GetTestClient();
```

**Comment by Kahbazi** [comment]
You need to use `WebApplicationFactory` for creating `TestServer`. Here's the document link.
[Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#basic-tests-with-the-default-webapplicationfactory)

**Comment by javiercn** [comment]
`(TestServer)factory.Services.GetRequiredService<IServer>()`

**Comment by Kahbazi** [comment]
@javiercn I believe this is the code that causing the InvalidCastException in the first place.
https://github.com/aspnet/AspNetCore/blob/master/src/Hosting/TestHost/src/HostBuilderTestServerExtensions.cs#L22

**Comment by javiercn** [comment]
@Tratcher Thoughts?

@khteh Can you provide a link to a github repo with a minimal repro project and detailed steps to reproduce the issue so that we can investigate?

**Comment by khteh** [comment]
@javiercn, just use the code snippet provided in my original post.

```
var hostbuilder = Host.CreateDefaultBuilder().ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<MyStartup>().ConfigureServices(i => i.AddLogging()));
```

**Comment by Kahbazi** [comment]
@khteh Did you try `WebApplicationFactory`? 

``` 
var factory = new WebApplicationFactory<Program>(); TestServer testServer = factory.Server; 
```

**Comment by khteh** [comment]
@kahbazi, how do you use a diff Startup class from the one used by Program.cs in this case?

**Comment by khteh** [comment]
`WebApplicationFactory` works as usual without the exception. I can `new TestServer(webHostBuilder);`. If this is the right factory class to use for 3.0, I will stick with it.

**Comment by khteh** [comment]
@javiercn @Kahbazi According to https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio, "HostBuilder replaces WebHostBuilder". That's why I tried to use `IHostBuilder` to instantiate `TestServer`. Instantiating `TestServer` with IWebHostBuilder` works as usual.

**Comment by Kahbazi** [comment]
If you want to use `HostBuilder`, you can also extend `WebApplicationFactory` and create a `IHostBuilder` that suits your needs.

```
public class YourApplicationFactory : WebApplicationFactory<YourApplicationFactory>
{
    protected override IHostBuilder CreateHostBuilder()
    {
        return Host.CreateDefaultBuilder()
            .ConfigureWebHostDefaults(webBuilder =>
            {
                // use whatever config you want here
                webBuilder.UseStartup<Startup>();
            });
    }
}
```

```
var factory = new YourApplicationFactory ();
TestServer testServer = factory.Server; 
```

**Comment by Tratcher** [comment]
When using HostBuilder you need to add the TestServer a different way:
https://github.com/aspnet/AspNetCore/blob/cf16b4b53847fc4aa54c0484cac53de07afd4c8d/src/Hosting/TestHost/test/TestServerTests.cs#L53-L62

Or use WebApplicationFactory.

**Comment by khteh** [comment]
@Tratcher 's solution works. So what I missed were:

(1) `UseTestServer()` 
(2) `StartAsync()`
(3) `host.GetTestServer()` WITHOUT the `Build()` in between.

**Comment by khteh** [comment]
@Kahbazi Your solution works for the `WebApplicationFactory` I have successfully replaced `ConfigureWebHost` with `CreateHostBuilder` and used the **SAME** `CustomWebApplicationFactory` for both RESTful Web API and SignalR end-to-end integration tests. However, I still fail to use it with GRPC. Here is the exception that I get:
```
..fail: Grpc.Net.Client.Internal.GrpcCall[6]                                                                                                                                                                       
      Error starting gRPC call.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.SendAsync(HttpRequestMessage request)
fail: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Cancelled', Message: 'Error starting gRPC call.'.
                                                                                                                                                                                                                   [xUnit.net 00:01:48.55]     Web.Api.IntegrationTests.Services.AccountsServiceIntegrationTests.CanRegisterUserWithValidAccountDetails [FAIL]
                                                                                                                                                                                                                     X Web.Api.IntegrationTests.Services.AccountsServiceIntegrationTests.CanRegisterUserWithValidAccountDetails [1m 43s]
  Error Message:
   Grpc.Core.RpcException : Status(StatusCode=Cancelled, Detail="Error starting gRPC call.")
  Stack Trace:
     at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseAsync()
   at Web.Api.IntegrationTests.Services.AccountsServiceIntegrationTests.CanRegisterUserWithValidAccountDetails() in /usr/src/AspNetCoreApiStarter/test/Web.Api.IntegrationTests/Services/AccountsServiceIntegrationTests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
```
If you are interested, I can share with you my repo and you can help investigate. Thanks.

**Comment by Tratcher** [comment]
@khteh how are you connecting the Grpc client to the TestServer?

The test server doesn't open real sockets, it uses a mock in-memory transport.

**Comment by khteh** [comment]
```
    public class CustomGrpcServerFactory<TStartup> : WebApplicationFactory<Startup>
    {
        public ServiceProvider ServiceProvider {get; private set;}
        protected override IHostBuilder CreateHostBuilder()
        {
            Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "IntegrationTests");
            string contentRootFull = Path.GetFullPath(Directory.GetCurrentDirectory());
            IConfigurationRoot config = new ConfigurationBuilder()
                .SetBasePath(contentRootFull)
                .AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.Development.json", true, true)
                .AddEnvironmentVariables().Build();
            GrpcConfig grpcConfig = config.GetSection(nameof(GrpcConfig)).Get<GrpcConfig>();
            return Host.CreateDefaultBuilder()
                    .ConfigureWebHostDefaults(webBuilder =>
                    {
                        // use whatever config you want here
                        webBuilder.UseStartup<Startup>()
                            .UseTestServer()
                            .ConfigureServices(services =>
                            {
                                // Create a new service provider.
                                var serviceProvider = new ServiceCollection()
                                    .AddEntityFrameworkInMemoryDatabase().AddLogging()
                                    .BuildServiceProvider();
                                services.AddGrpcClient<AccountsClient>(new Uri(grpcConfig.Endpoint));
                                    //.AddInterceptor(() => new LoggingInterceptor());
                                    //.AddHttpMessageHandler(() => ClientTestHelpers.CreateTestMessageHandler(new HelloReply()));
                                services.AddGrpcClient<AuthClient>(new Uri(grpcConfig.Endpoint));
                                    //.EnableCallContextPropagation();
<snip>
```
```
    public class AccountsServiceIntegrationTests : IClassFixture<CustomGrpcServerFactory<Startup>>
    {
        private ServiceProvider _serviceProvider;
        public AccountsServiceIntegrationTests(CustomGrpcServerFactory<Startup> factory)
        {
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.SystemDefault;
            factory.CreateClient();
            _serviceProvider = factory.ServiceProvider;
        }

        [Fact (Skip = "Pending investigation: https://github.com/aspnet/AspNetCore.Docs/issues/14905")]
        public async Task CanRegisterUserWithValidAccountDetails()
        {
            AccountsClient client = _serviceProvider.GetRequiredService<AccountsClient>();
            Assert.NotNull(client);
            // Act
            RegisterUserResponse response = await client.RegisterAsync(new RegisterUserRequest() {
<snip>
```

**Comment by Tratcher** [comment]
Yeah, that's trying to use the real HttpClient, not the test one. You need to replace the HttpClientHandler with the test one. See `TestServer.CreateHandler()`.

**Comment by khteh** [comment]
I use the following:
```
        public IHttpClientBuilder AddGrpcClient<TClient>(IServiceCollection services, Uri uri) where TClient : global::Grpc.Core.ClientBase
        {
            //HttpMessageHandler handler = Server.CreateHandler();
            return services.AddGrpcClient<TClient>(o => {o.Address = uri;})
                .ConfigurePrimaryHttpMessageHandler(() => Server.CreateHandler())
                .AddPolicyHandler(GetRetryPolicy());
        }
```
without the https self-signed cert manual accept code snippet (How to configure it?)

And get a new exception now:
```
Microsoft.Hosting.Lifetime: Information: Hosting environment: IntegrationTests
Microsoft.Hosting.Lifetime: Information: Content root path: /usr/src/AspNetCoreApiStarter/src/Web.Api
System.Net.Http.HttpClient.AccountsClient.LogicalHandler: Information: Start processing HTTP request POST https://localhost:5000/Web.Api.IntegrationTests.Accounts.Accounts/Register
System.Net.Http.HttpClient.AccountsClient.ClientHandler: Information: Sending HTTP request POST https://localhost:5000/Web.Api.IntegrationTests.Accounts.Accounts/Register
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2 POST https://localhost:5000/Web.Api.IntegrationTests.Accounts.Accounts/Register application/grpc 
Web.Api.Startup: Information: {"Method":"POST","Scheme":"https","PathBase":"","Path":"/Web.Api.IntegrationTests.Accounts.Accounts/Register","LocalIP":null,"IP":null,"Host":"localhost:5000","ContentLength":0,"ContentType":"application/grpc","QueryString":"","Protocol":"HTTP/2","X_Forwarded_For":null,"X_Forwarded_Proto":null,"X_Forwarded_Host":null,"X_Original_For":null,"X_Original_Proto":null,"X_Original_Host":null}
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'gRPC - gRPC - Unimplemented service'
Grpc.AspNetCore.Server.Internal.ServerCallHandlerFactory: Information: Service 'Web.Api.IntegrationTests.Accounts.Accounts' is unimplemented.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'gRPC - gRPC - Unimplemented service'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 1142.5921ms 200 application/grpc
System.Net.Http.HttpClient.AccountsClient.ClientHandler: Information: Received HTTP response after 1239.2782ms - OK
System.Net.Http.HttpClient.AccountsClient.LogicalHandler: Information: End processing HTTP request after 1307.0527ms - OK
Grpc.Net.Client.Internal.GrpcCall: Error: Call failed with gRPC error status. Status code: 'Unimplemented', Message: 'Service is unimplemented.'.
```

**Comment by khteh** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/14905

**Comment by Tratcher** [comment]
> without the https self-signed cert manual accept code snippet (How to configure it?)

You don't need to configure that, there are no certificates when using TestServer.

**Comment by khteh** [comment]
I believe the exception happens due to namespaces. I will investigate and feedback soon.

**Comment by khteh** [comment]
Yes, it was due to `csharp_namespace` - both the sever and the test client have to use the same namespace. However that result in a lot of warnings when both the server and the test client projects are built from the same solution which I have to ignore in the .csproj.
