### ISSUE TITLE
signalr c# client in corporate network

### ISSUE THREAD

**Issue by denis-ya** [aspnet/AspNetCore#15010]
I published simple web app (from quick start guide) in Azure. C# client works fine when I run it from home network. But when I run the client from corporate network I get handshake error. What can be a reason why I have this behavior? I also tried to use recommended corporate proxy without any success.

**Web app**
```
services.AddSignalR();
...
app.UseEndpoints(endpoints => {
    endpoints.MapHub<ClockHub>("/clock");
...
public class ClockHub : Hub<IClock>
{
    public async Task GetTime()
    {
        await Clients.All.ReportTime(DateTime.UtcNow);
    }
}

public interface IClock
{
    Task ReportTime(DateTime dateTime);
}
``` 

**Client**
```
var connection = new HubConnectionBuilder()
               .WithUrl("https://webapplication .azurewebsites.net:443/clock")
                .Build();

connection.On<DateTime>("ReportTime", (datetime) => {
     Console.WriteLine($"Server time: {datetime}");
 });

await connection.StartAsync();

await connection.InvokeAsync("GetTime");
```

I also found that in corporate network my VS2019 cannot connect to internet (Azure publish, update nuget packages etc.) before I added changes to devenv.exe.config

```
<system.net>
    <defaultProxy useDefaultCredentials="true" enabled="true">
      <proxy usesystemdefault="True" />
    </defaultProxy>
...
```

**So, this is a corporate network log (handshake error)**
```
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[40]
      Registering handler for client method 'ReportTime'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[41]
      Starting HubConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[1]
      Starting HttpConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[8]
      Establishing connection with server at 'https://webapplication .azurewebsites.net/clock'.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[9]
      Established connection 'e_5quTu4nAw6XQzLTPXYRg' with the server.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[7]
      Starting transport 'ServerSentEvents' with Url: https://webapplication .azurewebsites.net/clock?id=e_5quTu4nAw6XQzLTPXYRg.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[1]
      Starting transport. Transfer mode: Text.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[3]
      Starting receive loop.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[9]
      Received 10605 bytes. Parsing SSE frame.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[4]
      Receive loop stopped.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[100]
      Starting the send loop.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[102]
      Send loop canceled.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[101]
      Send loop stopped.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[18]
      Transport 'ServerSentEvents' started.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[3]
      HttpConnection Started.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[24]
      Using HubProtocol 'json v1'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[28]
      Sending Hub Handshake.
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[35]
      The underlying connection closed while processing the handshake response. See exception for details.
System.IO.IOException: The server disconnected before the handshake could be started.
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[43]
      Error starting connection.
System.IO.IOException: The server disconnected before the handshake could be started.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__58.MoveNext()
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[4]
      Disposing HttpConnection.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[6]
      Transport is stopping.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[2]
      Transport stopped.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[6]
      HttpConnection Disposed.
```

**This is a home network log**
```
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[40]
      Registering handler for client method 'ReportTime'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[41]
      Starting HubConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[1]
      Starting HttpConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[8]
      Establishing connection with server at 'https://webapplication .azurewebsites.net/clock'.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[9]
      Established connection 'ApOxhle-glPF_PVZ99pgbw' with the server.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[7]
      Starting transport 'ServerSentEvents' with Url: https://webapplication .azurewebsites.net/clock?id=ApOxhle-glPF_PVZ99pgbw.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[1]
      Starting transport. Transfer mode: Text.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[3]
      Starting receive loop.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[9]
      Received 3 bytes. Parsing SSE frame.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[100]
      Starting the send loop.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[18]
      Transport 'ServerSentEvents' started.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[3]
      HttpConnection Started.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[24]
      Using HubProtocol 'json v1'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[28]
      Sending Hub Handshake.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[103]
      Sending 32 bytes to the server using url: https://webapplication .azurewebsites.net/clock?id=ApOxhle-glPF_PVZ99pgbw.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[9]
      Received 13 bytes. Parsing SSE frame.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[7]
      Passing message to application. Payload size: 3.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[39]
      Handshake with server complete.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[104]
      Message(s) sent successfully.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[47]
      Receive loop starting.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[59]
      Sending PingMessage message.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[103]
      Sending 11 bytes to the server using url: https://webapplication .azurewebsites.net/clock?id=ApOxhle-glPF_PVZ99pgbw.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[60]
      Sending PingMessage message completed.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[44]
      HubConnection started.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[3]
      Registering Invocation ID '1' for tracking.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[5]
      Sending InvocationMessage message '1'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[6]
      Sending InvocationMessage message '1' completed.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[104]
      Message(s) sent successfully.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[103]
      Sending 64 bytes to the server using url: https://webapplication .azurewebsites.net/clock?id=ApOxhle-glPF_PVZ99pgbw.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[9]
      Received 132 bytes. Parsing SSE frame.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[7]
      Passing message to application. Payload size: 122.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[56]
      Processing 122 byte message from server.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[104]
      Message(s) sent successfully.
Server time: 15.10.2019 9:39:41
```

**Comment by anurse** [comment]
> System.IO.IOException: The server disconnected before the handshake could be started.
>    at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__80.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__58.MoveNext()

This usually happens because an intermediate proxy is interfering with the connection. Does your corporate network have a proxy? You mentioned one in your config. Does that proxy support WebSockets or long-running requests like Server-Sent Events?

**Comment by denis-ya** [comment]
> This usually happens because an intermediate proxy is interfering with the connection. Does your corporate network have a proxy? You mentioned one in your config. Does that proxy support WebSockets or long-running requests like Server-Sent Events?

Yes, the network has a known proxy. It definitely supports WebSockets. I played with SignalR 2.2 some time ago, but used Cloud Foundry platform and it was succeed. How I can check long-running requests support?

As I said, I tried to use the proxy 

```
var proxy = new WebProxy("http://corporate-proxy:port");
var connection = new HubConnectionBuilder()
                        .WithUrl(urlHub, h => {
                            h.Proxy = proxy;
                        })
```

In this case I get another error (Unexpected '\n' in message)

```
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[40]
      Registering handler for client method 'ReportTime'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[41]
      Starting HubConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[1]
      Starting HttpConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[8]
      Establishing connection with server at 'https:// .azurewebsites.net/clock'.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[9]
      Established connection 'kKrt-XmrtDWlO73s2qLfXg' with the server.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[7]
      Starting transport 'ServerSentEvents' with Url: https:// .azurewebsites.net/clock?id=kKrt-XmrtDWlO73s2qLfXg.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[1]
      Starting transport. Transfer mode: Text.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[3]
      Starting receive loop.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[100]
      Starting the send loop.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[18]
      Transport 'ServerSentEvents' started.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[3]
      HttpConnection Started.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[24]
      Using HubProtocol 'json v1'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[28]
      Sending Hub Handshake.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[103]
      Sending 32 bytes to the server using url: https:// .azurewebsites.net/clock?id=kKrt-XmrtDWlO73s2qLfXg.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[9]
      Received 4096 bytes. Parsing SSE frame.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[4]
      Receive loop stopped.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[102]
      Send loop canceled.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[101]
      Send loop stopped.
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[35]
      The underlying connection closed while processing the handshake response. See exception for details.
System.FormatException: Unexpected '\n' in message. A '\n' character can only be used as part of the newline sequence '\r\n'
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsMessageParser.ParseMessage(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined, Byte[]& message)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport.<ProcessEventStream>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__80.MoveNext()
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[43]
      Error starting connection.
System.FormatException: Unexpected '\n' in message. A '\n' character can only be used as part of the newline sequence '\r\n'
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsMessageParser.ParseMessage(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined, Byte[]& message)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport.<ProcessEventStream>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__58.MoveNext()
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[4]
      Disposing HttpConnection.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[6]
      Transport is stopping.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport[2]
      Transport stopped.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[6]
      HttpConnection Disposed.

```

**Comment by davidfowl** [comment]
> Yes, the network has a known proxy. It definitely supports WebSockets. I played with SignalR 2.2 some time ago, but used Cloud Foundry platform and it was succeed. How I can check long-running requests support?

If you're running in app service, you need to turn on websockets explicitly:

![image](https://user-images.githubusercontent.com/95136/66907116-ace42100-efbd-11e9-905f-b5a9de272f78.png)

> In this case I get another error (Unexpected '\n' in message)

Your proxy might be returning something else (like an HTTP response).

**Comment by denis-ya** [comment]
> If you're running in app service, you need to turn on websockets explicitly:

Websockets were in Off state, but it works from my home network without any issues. I tried to switch On but still have the same behavior.

> > In this case I get another error (Unexpected '\n' in message)
> 
> Your proxy might be returning something else (like an HTTP response).

Are there any ideas how I can handle this?

**Comment by anurse** [comment]
Can you collect a network trace (see the [guide in our docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-3.0#network-traces)) from the client side so we can see what behavior the proxy is producing? The trace will include the complete content of your requests, so if you are concerned about disclosing confidential information, let me know and we can provide an alternate mechanism to share the trace.

**Comment by halter73** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
