### ISSUE TITLE
NullReferenceException on adding policy

### ISSUE THREAD

**Issue by msmolka** [aspnet/AspNetCore#15142]
### Describe the bug
Adding two policies dynamically from different request but at the same time causing `NullReferenceException`

### To Reproduce
1. Using this version of ASP.NET Core '2.2.0' on .NET Fremework 4.7.2
2. following custom provider class.

```c#
public class AuthorizationPolicyProvider : DefaultAuthorizationPolicyProvider
    {
        #region Fields

        private readonly AuthorizationOptions options;

        #endregion

        #region Constructors and Destructors

        public AuthorizationPolicyProvider(IOptions<AuthorizationOptions> options) : base(options)
            => this.options = options.Value;

        #endregion

        #region Public Methods

        /// <inheritdoc/>
        public override async Task<Microsoft.AspNetCore.Authorization.AuthorizationPolicy> GetPolicyAsync(string policyName)
        {
            // Check static policies first
            Microsoft.AspNetCore.Authorization.AuthorizationPolicy policy = await base.GetPolicyAsync(policyName);

            if (policy == null)
            {
                string requirement = $"Requirements.{policyName}Requirement";
                Type type = Type.GetType(requirement);

                if ((type != null) && typeof(IAuthorizationRequirement).IsAssignableFrom(type))
                {
                    var reqInstance = (IAuthorizationRequirement)Activator.CreateInstance(type);

                    var builder = new AuthorizationPolicyBuilder();
                    builder.AddRequirements(reqInstance);

                    policy = builder.Build();

                    // Add policy to the AuthorizationOptions, so we don't have to re-create it each time
                    this.options.AddPolicy(policyName, policy);
                }
                else
                {
                    throw new ArgumentException(string.Format(Exceptions.AuthorizationPolicyProvider_UnknownPolicy, requirement));
                }
            }

            return policy;
        }


```

### Expected behavior
On app start occasionally `this.options.AddPolicy(policyName, policy);` throws `NullReferenceException`. It should never throw this error. it is uknown and inside api.

**Comment by davidfowl** [comment]
Are you sure the exception isn't coming from your code? Do you have a callstack?

**Comment by msmolka** [comment]
@davidfowl 
here:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.AspNetCore.Authorization.AuthorizationOptions.AddPolicy(String name, AuthorizationPolicy policy)
   at Security.AuthorizationPolicyProvider.<GetPolicyAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidfowl** [comment]
You're modifying a singleton state on a per call basis without locks.

```
this.options.AddPolicy(policyName, policy);
```

You shouldn't be doing this.

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.
