### ISSUE TITLE
Can't comment out atttributes

### ISSUE THREAD

**Issue by Joebeazelman** [aspnet/AspNetCore#15439]
I tried to comment out the attribute using the razor comment syntax:

```
<svg id="template" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 651 442" @*@onmousedown="@OnDesignPanelClicked"*@>
```

Upon execution, it interpreted the commented area as regular Blazor code:

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@*@onmousedown="@OnDesignPanelClicked"*@' is not a valid attribute name.
System.InvalidOperationException: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@*@onmousedown="@OnDesignPanelClicked"*@' is not a valid attribute name.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'juq2BjFD4RL46PNRh3SetydfRBC3OCZTupfYCpRWu2U'.
System.AggregateException: One or more errors occurred. (InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@*@onmousedown="@OnDesignPanelClicked"*@' is not a valid attribute name.)
 ---> System.InvalidOperationException: InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@*@onmousedown="@OnDesignPanelClicked"*@' is not a valid attribute name.
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/_blazor'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 417.2702ms 101 
```

**Comment by javiercn** [comment]
@Joebeazelman Thanks for contacting us.

@NTaylorMullen @ajaybhargavb Is this supproted in Razor in the middle of a tag?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen if this turns out something we need to fix or add support for, we'll consider that for 5.0 timeframe.

**Comment by Joebeazelman** [comment]
It may well be an existing issue with razor, but I can't think of a single case where block comments are interpreted in other mainstream programming languages.

**Comment by mrpmorris** [comment]
Seeing as you are inside html the moment you write `<`, have you tried using html comment notation instead?

**Comment by datvm** [comment]
This is still an issue in .NET 7, at least for Blazor:

![image](https://github.com/dotnet/aspnetcore/assets/6388546/8456d5cd-e4a4-4917-9160-a74377d571c8)

Trying to run the above code anyway results in this error:

> Failed to execute 'setAttribute' on 'Element': '@* @ref="mnuIdref" *@' is not a valid attribute name.
