### ISSUE TITLE
Using EnableRewind with XML Formatters throws

### ISSUE THREAD

**Issue by mareklinka** [aspnet/AspNetCore#16728]
### Describe the bug
In ASP.NET Core 3.0 enabling request rewind when also using the XmlSerializer formatter leads to an exception `Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.`.

### To Reproduce
1. Create a fresh ASP.NET Core 3 Web API project
2. Add support for the XmlSerializer formatter
3. Enable rewind on all requests
4. Create a POST action with body on a controller
5. Invoke the post action

### Expected behavior
The request is propagated to the controller and action.

### Exception stack
```
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadByte()
   at Microsoft.AspNetCore.Mvc.Infrastructure.NonDisposableStream.ReadByte()
   at System.Xml.EncodingStreamWrapper.ReadBOMEncoding(Boolean notOutOfBand)
   at System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)
   at System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at System.Xml.XmlDictionaryReader.CreateTextReader(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerInputFormatter.CreateXmlReader(Stream readStream, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/xml
Accept: */*
Accept-Encoding: gzip, deflate
Host: localhost:5001
User-Agent: PostmanRuntime/7.19.0
Content-Length: 46
Postman-Token: f58f0246-e814-441c-82f6-c5e22ffff4e7

```

### Workaround
It is possible to circumvent the issue by allowing synchronous IO on the requests in question. However, this is suboptimal as it can impact performance and stability of the system.

### Repro code
[XmlRepro.zip](https://github.com/aspnet/AspNetCore/files/3796518/XmlRepro.zip)

The question is whether this can be resolved in a better way. I guess the old XmlSerializer formatter is not made to use asynchronous APIs?

**Comment by javiercn** [comment]
@mareklinka thanks for contacting us.

@Tratcher Can you help out here?

**Comment by pranavkm** [comment]
This is likely a dup of https://github.com/aspnet/AspNetCore/issues/16615. In 3.0, using `EnableRewind` or `EnableBuffering` requires the stream to be drained (or for sync IO to be allowed): 

```C#
app.Use(async (context, next) => 
{
    context.Request.EnableBuffering();
    await context.Request.Body.DrainAsync();
    context.Request.Body.Position = 0;
    await next(context);
});
```

^ I haven't tried compiling the code, but this should be the gist of it. Starting in 3.1-preview2, you should no longer need to do this.
