### ISSUE TITLE
EnableBuffering not working on 3.1 preview 2

### ISSUE THREAD

**Issue by aidbal** [aspnet/AspNetCore#16871]
As a reference to #14396, I have upgraded our project to 3.0. I still get Cannot access a closed stream exception. Everything works as expected with 2.2 .net core.

Startup.cs
``` C#
...
services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
...
```

The middleware in which exception occurs
```C#

        public async Task InvokeAsync(HttpContext httpContext)
        {
                ...
                httpContext.Request.EnableBuffering();

                var request = httpContext.Request;
                var stopWatch = Stopwatch.StartNew();
                var requestTime = DateTime.UtcNow;
                var requestBodyContent = await ReadRequestBodyAsync(request);
                var originalBodyStream = httpContext.Response.Body;
                await using var responseBody = new MemoryStream();
                var response = httpContext.Response;
                response.Body = responseBody;
                await _next(httpContext).ConfigureAwait(false);
                stopWatch.Stop();

                var responseBodyContent = await ReadResponseBodyAsync(response);
                await responseBody.CopyToAsync(originalBodyStream);
                ...
        }

        private static async Task<string> ReadRequestBodyAsync(HttpRequest request)
        {
            var buffer = new byte[Convert.ToInt32(request.ContentLength)];
            await request.Body.ReadAsync(buffer, 0, buffer.Length);
            var bodyAsText = Encoding.UTF8.GetString(buffer);
            request.Body.Seek(0, SeekOrigin.Begin);

            return bodyAsText;
        }

        private static async Task<string> ReadResponseBodyAsync(HttpResponse response)
        {
            response.Body.Seek(0, SeekOrigin.Begin);
            using var streamReader = new StreamReader(response.Body);
            var bodyAsText = await streamReader.ReadToEndAsync();
            response.Body.Seek(0, SeekOrigin.Begin);

            return bodyAsText;
        }
```
The exception being thrown
```
[15:48:15 ERR] [2019-11-06 13:48:15] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   ...
```

### Further technical details
- ASP.NET Core version -  3.1.100-preview2-014569
- Output of `dotnet --info`
```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview2-014569\

Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91

.NET Core SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pranavkm** [comment]
@aidbal any chance you could provide a minimal repro for this issue? https://github.com/aspnet/AspNetCore/issues/14396 was about attempting to read the Request body after MVC had processed JSON content. This one looks different - it looks like something's disposed the request stream before it gets to MVC.

**Comment by aidbal** [comment]
Sure, I'll try to make one.

**Comment by aidbal** [comment]
I managed to figure it out on my own as I was creating repro.  It turns out that that code was not working in 2.2 as well. After fiddling around a bit, I narrowed it down to the function which reads the request body. After changing it to the following, everything works as expected.

Thanks for the tips ;)

``` C#
        public async Task InvokeAsync(HttpContext httpContext)
        {
                ...
                httpContext.Request.EnableBuffering();

                var request = httpContext.Request;
                var stopWatch = Stopwatch.StartNew();
                var requestTime = DateTime.UtcNow;

                var requestBodyContent = await ReadRequestBodyAsync(request);
                var originalResponseBodyStream = httpContext.Response.Body;

                await using var responseBody = new MemoryStream();
                httpContext.Response.Body = responseBody;

                await _next(httpContext);
                var responseBodyContent = await ReadResponseBodyAsync(httpContext.Response);
                await responseBody.CopyToAsync(originalResponseBodyStream);

                stopWatch.Stop();
                ...
        }

        private static async Task<string> ReadRequestBodyAsync(HttpRequest request)
        {
            request.Body.Seek(0, SeekOrigin.Begin);
            var bodyAsText = await new StreamReader(request.Body).ReadToEndAsync();
            request.Body.Seek(0, SeekOrigin.Begin);

            return bodyAsText;
        }

        private static async Task<string> ReadResponseBodyAsync(HttpResponse response)
        {
            response.Body.Seek(0, SeekOrigin.Begin);
            var bodyAsText = await new StreamReader(response.Body).ReadToEndAsync();
            response.Body.Seek(0, SeekOrigin.Begin);

            return bodyAsText;
        }
```

**Comment by aidbal** [comment]
I am not sure if it belongs here, but if you leave the code as the following:
```C#
            using var reader = new StreamReader(request.Body);
            var bodyAsText = await reader.ReadToEndAsync();
```
it fails with Cannot access a closed stream exception. If you remove 'using' statement and leave the code with possible memory leak, it works
```C#
            var bodyAsText = await new StreamReader(request.Body).ReadToEndAsync();
```

**Comment by pranavkm** [comment]
@aidbal you should configure `StreamReader` to not close the stream being read on `Dispose`: https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=netframework-4.8#System_IO_StreamReader__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_System_Int32_System_Boolean_
