### ISSUE TITLE
blazorwasm stops working when target netstandard2.1

### ISSUE THREAD

**Issue by hez2010** [aspnet/AspNetCore#16887]
### Describe the bug
If we change `TargetFramework` form `netstandard2.0` to `netstandard2.1`, blazor will stop working and cannot load at all.

### To Reproduce
```
dotnet new blazorwasm
```
change `TargetFramework` to `netstandard2.1`
```
dotnet run
```
Access https://localhost:5001

Got exception:
```
Uncaught (in promise) Error: System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Blazor.Services.WebAssemblyJSRuntime' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Components.ElementReferenceJsonConverter' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1ac7bd0 + 0x0000e> in <1adcbc7e4a1349008160f49e975e8377>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1aa2fe8 + 0x00092> in <1adcbc7e4a1349008160f49e975e8377>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1aa2850 + 0x00034> in <1adcbc7e4a1349008160f49e975e8377>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1aa2158 + 0x0002a> in <1adcbc7e4a1349008160f49e975e8377>:0 
  at Microsoft.AspNetCore.Components.ElementReferenceJsonConverter..cctor () <0x1a93160 + 0x00006> in <d068548f4bed4735a420364730909718>:0 
   --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.Blazor.Services.WebAssemblyJSRuntime..ctor () <0x1a5f978 + 0x00014> in <d068548f4bed4735a420364730909718>:0 
  at Microsoft.AspNetCore.Blazor.Services.WebAssemblyJSRuntime..cctor () <0x1a5f658 + 0x00000> in <d068548f4bed4735a420364730909718>:0 
   --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder.CreateServiceProvider () <0x1a5e1b8 + 0x00028> in <d068548f4bed4735a420364730909718>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder.Build () <0x1a46708 + 0x00028> in <d068548f4bed4735a420364730909718>:0 
  at Blazor.Program.Main (System.String[] args) <0x1a05860 + 0x0000c> in <24dfced9dcc449c1b47785aa2a9b572f>:0 
    at Object.callMethod (https://localhost:5001/_framework/blazor.webassembly.js:1:43571)
    at Object.callEntryPoint (https://localhost:5001/_framework/blazor.webassembly.js:1:43149)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:38568
    at https://localhost:5001/_framework/blazor.webassembly.js:1:36931
    at Object.next (https://localhost:5001/_framework/blazor.webassembly.js:1:37036)
    at i (https://localhost:5001/_framework/blazor.webassembly.js:1:35782)
```

### Further technical details
- ASP.NET Core version: 3.1 preview 2
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014569
 Commit:    4bd5d24d87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100-preview2-014569\

Host (useful for support):
  Version: 3.1.0-preview2.19525.6
  Commit:  5672978d91

.NET Core SDKs installed:
  3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@hez2010 thanks for contacting us.

We are in the process of supporting netstandard2.1 there's an ongoing PR and this will be available in the future.
