### ISSUE TITLE
Unable to disable Antiforgery Validation forced on .net core app

### ISSUE THREAD

**Issue by HolyOne** [aspnet/AspNetCore#17064]
I did not enable Antiforgery Validation on my Startup but my forms return error 400 if I do not add 
@Html.AntiForgeryToken() to my html form.

I do not want to use AntiForgeryToken globally but I am unable to find any solution for this.
Is there even a way to disable anti forgery completely?

`
[16:42:49 INF] Route matched with {page = "/Index", area = "Modbus", action = "", controller = ""}. Executing page /Index
[16:42:49 INF] Antiforgery token validation failed. The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
[16:42:49 INF] Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
[16:42:49 INF] Executing HttpStatusCodeResult, setting HTTP status code 400`

**Comment by pranavkm** [comment]
Razor Pages are protected by antiforgery tokens by default. You can use the [IgnoreAntiforgeryTokenAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.ignoreantiforgerytokenattribute?view=aspnetcore-3.0) filter to disable XSRF protection for your pages, either by decorating it on individual pages, or by adding the filter globally.

**Comment by HolyOne** [comment]
I have already tried that but no luck.

Note: I tested my code in a Form under a razor library Area. 

`       
            services.AddRazorPages().AddRazorPagesOptions(options =>
            {
                options.Conventions.ConfigureFilter(new IgnoreAntiforgeryTokenAttribute());
            })
`

I also tried
