### ISSUE TITLE
Reading HttpContext.ResponseBody in custom middleware

### ISSUE THREAD

**Issue by nuno-tiago-reis** [aspnet/AspNetCore#17104]
Hello, I'm attempting to write a custom middleware that reads both the request and response body from the http context and logs them.
I've successfully read the request body but for the response body I'm getting the following error:

```
[2019-11-14 19:08:40 EROR] Microsoft.AspNetCore.Server.Kestrel
Connection id ""0HLR96O3GGIOJ"", Request id ""0HLR96O3GGIOJ:00000001"": An unhandled exception was thrown by the application.
{"EventId": {"Id": 13, "Name": "ApplicationError"}, "RequestId": "0HLR96O3GGIOJ:00000001", "RequestPath": "/api/profile", "SpanId": "|a1767aea-4fbb75086a5ff91d.", "TraceId": "a1767aea-4fbb75086a5ff91d", "ParentId": ""}
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at Common.Logging.HttpContextLoggingMiddleware.GetResponseBody(HttpContext context) in D:\Documents\Repositories\emsa-med-identity-management\IdentityManagement\Modules\Common\Common\Common\Logging\HttpContextLoggingMiddleware.cs:line 243
   at Common.Logging.HttpContextLoggingMiddleware.Invoke(HttpContext context) in D:\Documents\Repositories\emsa-med-identity-management\IdentityManagement\Modules\Common\Common\Common\Logging\HttpContextLoggingMiddleware.cs:line 88
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Since I'm replacing the underlying stream it be readable right?
Here is the code I'm using:

``` C#
var originalBodyStream = context.Response.Body;

try
{
	var memoryBodyStream = new MemoryStream();

	context.Response.Body = memoryBodyStream;

	await this.Next.Invoke(context);

	memoryBodyStream.Seek(0, SeekOrigin.Begin);
	string body = await new StreamReader(memoryBodyStream).ReadToEndAsync();
	memoryBodyStream.Seek(0, SeekOrigin.Begin);

	await memoryBodyStream.CopyToAsync(originalBodyStream);

	return body;
}
finally
{
	context.Response.Body = originalBodyStream;
}
```

### Further technical details
- ASP.NET Core version: 3.0.0
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App
```
- Visual Studio Community 2019

**Comment by Tratcher** [comment]
@javiercn only use the area-hosting label for items that are actually in the Microsoft.AspNetCore.Hosting package/namespace. Most request processing items belong in area-Servers.

**Comment by Tratcher** [comment]
@nuno-tiago-reis some components used to write to the response body like StreamWriter/StreamReader also dispose the stream unless you pass them a flag not to. In your case you'll need to either change what is disposing the stream or wrap your memory stream to prevent Dispose from being called.

**Comment by nuno-tiago-reis** [comment]
Thanks for your suggestion.

Thanks to it I was able to find out it was the WebMarkupMin middleware that was closing the stream and managed to fix the issue.

Thanks again 👍
