### ISSUE TITLE
Blazor Wasm stuck on startup after update to 3.1 Preview 3

### ISSUE THREAD

**Issue by Knarzi** [aspnet/AspNetCore#17129]
I updated my Blazor Wasm Client from Dotnet Core 3.0 to 3.1 Preview 3. Now, when i start the client i got the following error message:

```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Blazor.Services.WebAssemblyJSRuntime' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Components.ElementReferenceJsonConverter' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1df54a0 + 0x0000e> in <0f07585cda034495a8a1c3ac71cf9d1a>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1dcea30 + 0x00092> in <0f07585cda034495a8a1c3ac71cf9d1a>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1dce298 + 0x00034> in <0f07585cda034495a8a1c3ac71cf9d1a>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) <0x1dcdbb0 + 0x0002a> in <0f07585cda034495a8a1c3ac71cf9d1a>:0 
  at Microsoft.AspNetCore.Components.ElementReferenceJsonConverter..cctor () <0x1dcda28 + 0x00006> in <460473d95e86450691afa1fe6603e868>:0 
   --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.Blazor.Services.WebAssemblyJSRuntime..ctor () <0x1d889e0 + 0x00014> in <460473d95e86450691afa1fe6603e868>:0 
  at Microsoft.AspNetCore.Blazor.Services.WebAssemblyJSRuntime..cctor () <0x1d886c0 + 0x00000> in <460473d95e86450691afa1fe6603e868>:0 
   --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder.CreateServiceProvider () <0x1d87230 + 0x00028> in <460473d95e86450691afa1fe6603e868>:0 
  at Microsoft.AspNetCore.Blazor.Hosting.WebAssemblyHostBuilder.Build () <0x1d6e478 + 0x00028> in <460473d95e86450691afa1fe6603e868>:0 
  at LHHi.ADManagement.Client.Program.Main (System.String[] args) <0x1d2ccc0 + 0x0000c> in <87ed679a516a4f02a33a90ad601c78a6>:0 
    at Object.callMethod (http://localhost:5000/_framework/blazor.webassembly.js:1:39563)
    at Object.callEntryPoint (http://localhost:5000/_framework/blazor.webassembly.js:1:39141)
    at http://localhost:5000/_framework/blazor.webassembly.js:1:34236
    at http://localhost:5000/_framework/blazor.webassembly.js:1:32392
    at Object.next (http://localhost:5000/_framework/blazor.webassembly.js:1:32497)
    at i (http://localhost:5000/_framework/blazor.webassembly.js:1:31243)
callMethod @ blazor.webassembly.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
u @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
p @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
```
Apart from updating the package sources, I did not make any changes to the source code.

**Comment by mikesisti** [comment]
for other folks -- .NET Standard 2.1 -> 2.0 fixes this error
