### ISSUE TITLE
HostingAbstractionsHostExtensions.Run: OperationCanceledException: The operation was canceled.

### ISSUE THREAD

**Issue by sepehr1014** [aspnet/AspNetCore#17221]
We sometimes get the crash below.

```
Application: dotnet.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 3.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Pasaj.Program.Main(String[] args) in C:\Web\Patogh\Patogh\Program.cs:line 20
```

```
Faulting application name: dotnet.exe, version: 3.0.19.46305, time stamp: 0x5d7bb03a
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2791, time stamp: 0x5c5a4180
Exception code: 0xe0434352
Fault offset: 0x0000000000034078
Faulting process id: 0xfd88
Faulting application start time: 0x01d59e41aa3cb9c2
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b9784a19-c56c-4320-b67e-22cda20f6ddc
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: C:\Program Files\dotnet\dotnet
P2: 3.0.19.46305
P3: 5d7bb03a
P4: System.Private.CoreLib
P5: 4.700.19.46205
P6: cb50a32b
P7: 1e1f
P8: 10
P9: System.OperationCanceled
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_C__Program Files_1a60acf789ebe206a7eba52abbe4e7d01c3634_58b55f8a_eff89115

Analysis symbol: 
Rechecking for solution: 0
Report Id: b9784a19-c56c-4320-b67e-22cda20f6ddc
Report Status: 4
Hashed bucket: 
```

Here's our Program.cs

```
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.AddExceptionLogger();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureKestrel(serverOptions =>
                    {
                        // Set properties and call methods on options
                        serverOptions.Limits.MinRequestBodyDataRate = new MinDataRate(24, TimeSpan.FromSeconds(30));
                        serverOptions.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(10);
                    })
                    .UseStartup<Startup>();
                });
    }
```

### Further technical details
- ASP.NET Core 3.0
- OutOfProcess hosting model

**Comment by Tratcher** [comment]
This means your application was attempting to gracefully shut down but failed to do so within the default time period (5 seconds).

A) Why was the application shutting down?
B) What prevented it from finishing? Long running requests?

**Comment by sepehr1014** [comment]
@Tratcher 
We haven't set any recycling policies. We just get crashes often and see these errors in the Event Log. How can I investigate why the app was shutting down?
At any given time, we have thousands of clients connected using web sockets. That might be preventing it from finishing.

**Comment by Tratcher** [comment]
An app would only normally be shut down by
A) an external CTL+C or
B) something inside the app calling IApplicationLifetime.StopApplication.

That said, you're using IIS and that can trigger the CTL+C shutdown code if it wants. It might do this if
A) It sees file changes
B) It has a regularly scheduled recycle
C) The app is idle

Is this running on your own servers or on a hosting provider?
