### ISSUE TITLE
Flaky test: Rebuild_Success_RecreatesManifestAndCache

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#17233]
https://dev.azure.com/dnceng/public/_build/results?buildId=431839&view=ms.vss-test-web.build-test-results-tab&runId=13675208&resultId=100195&paneView=debug

```
System.TimeoutException : command '$F:\\workspace.4\\_work\\1\\s\\.dotnet\\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp31PackageVersion=3.1.0 /p:MicrosoftNetCompilersToolsetPackageVersion=3.4.0-beta4-19568-04 /p:RuntimeAdditionalRestoreSources=F:\\workspace.4\\_work\\1\\s\\src\\Razor\\test\\Microsoft.NET.Sdk.Razor.Test\\..\\testapps\\TestPackageRestoreSource /p:_RazorBuildServerPipeName=\"a5878d28-be43-476b-8060-a669be370f27\" /t:Build /p:Configuration=Debug /restore' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.4.0-preview-19475-01+497296502 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

F:\\workspace.4\\_work\\1\\s\\.dotnet\\sdk\\3.1.100-preview1-014400\\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp31PackageVersion=3.1.0 /p:MicrosoftNetCompilersToolsetPackageVersion=3.4.0-beta4-19568-04 /p:RuntimeAdditionalRestoreSources=F:\\workspace.4\\_work\\1\\s\\src\\Razor\\test\\Microsoft.NET.Sdk.Razor.Test\\..\\testapps\\TestPackageRestoreSource /p:_RazorBuildServerPipeName=a5878d28-be43-476b-8060-a669be370f27 /p:Configuration=Debug /restore /t:Build .\\AppWithPackageAndP2PReference.csproj
Restore completed in 15.12 sec for C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\x0hwd4is.saf\\ClassLibrary2\\ClassLibrary2.csproj.
Restore completed in 14.98 sec for C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\x0hwd4is.saf\\ClassLibrary\\ClassLibrary.csproj.
Restore completed in 15.9 sec for C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\x0hwd4is.saf\\AppWithPackageAndP2PReference\\AppWithPackageAndP2PReference.csproj.
You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
 You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
 ClassLibrary -> C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\x0hwd4is.saf\\ClassLibrary\\bin\\Debug\\netcoreapp3.1\\ClassLibrary.dll
 ClassLibrary -> C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\x0hwd4is.saf\\ClassLibrary\\bin\\Debug\\netcoreapp3.1\\ClassLibrary.Views.dll

   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind, String localPackageCache) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 59
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Rebuild_Success_RecreatesManifestAndCache() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by jkotalik** [comment]
Similar issue: Build_GeneratesStaticWebAssetsManifest_Success_CreatesManifest
https://dev.azure.com/dnceng/public/_build/results?buildId=432173&view=ms.vss-test-web.build-test-results-tab&runId=13686422&resultId=100025&paneView=debug

```
System.TimeoutException : command '$F:\\workspace.2\\_work\\1\\s\\.dotnet\\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp31PackageVersion=3.1.0 /p:MicrosoftNetCompilersToolsetPackageVersion=3.4.0-beta4-19568-04 /p:RuntimeAdditionalRestoreSources=F:\\workspace.2\\_work\\1\\s\\src\\Razor\\test\\Microsoft.NET.Sdk.Razor.Test\\..\\testapps\\TestPackageRestoreSource /p:_RazorBuildServerPipeName=\"75920bd6-e35e-4598-ba84-c8ede9b5c455\" /t:Build /p:Configuration=Debug /restore' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.4.0-preview-19475-01+497296502 for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\\workspace.2\\_work\\1\\s\\.dotnet\\sdk\\3.1.100-preview1-014400\\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp31PackageVersion=3.1.0 /p:MicrosoftNetCompilersToolsetPackageVersion=3.4.0-beta4-19568-04 /p:RuntimeAdditionalRestoreSources=F:\\workspace.2\\_work\\1\\s\\src\\Razor\\test\\Microsoft.NET.Sdk.Razor.Test\\..\\testapps\\TestPackageRestoreSource /p:_RazorBuildServerPipeName=75920bd6-e35e-4598-ba84-c8ede9b5c455 /p:Configuration=Debug /restore /t:Build .\\AppWithPackageAndP2PReference.csproj\r\n Restore completed in 15.1 sec for C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\pnhlwou1.fxr\\ClassLibrary\\ClassLibrary.csproj.\r\n Restore completed in 14.99 sec for C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\pnhlwou1.fxr\\ClassLibrary2\\ClassLibrary2.csproj.\r\n Restore completed in 16.06 sec for C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\pnhlwou1.fxr\\AppWithPackageAndP2PReference\\AppWithPackageAndP2PReference.csproj.\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n ClassLibrary -> C:\\Users\\vsagent\\AppData\\Local\\Temp\\Razor\\pnhlwou1.fxr\\ClassLibrary\\bin\\Debug\\netcoreapp3.1\\ClassLibrary.dll\r\n
```

**Comment by javiercn** [comment]
@jkotalik this normally goes in the internal repo.

We already have an issue tracking this and an on-going investigation. I'm going to close this issue for the time being as it is being tracked elsewhere.

**Comment by jkotalik** [comment]
I don’t necessarily know if that’s going to be the process going forward, but glad there is something else tracking it. Mind linking me the issue?

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore-Internal/issues/2613
