### ISSUE TITLE
HPackDecodingException:  Index 79 is outside the bounds of the header field table.

### ISSUE THREAD

**Issue by jogibear9988** [aspnet/AspNetCore#17275]
### Describe the bug
I've a simple Kestrel App only used as a HTTP2 Server

I've two Pages (index.html and config.html) wich mostly load the same files (the config.html some more)

The index.html works, the config.html fails cause of this exception (some files are loaded till it fails)

info: Microsoft.AspNetCore.Server.Kestrel[31]
      Connection id "0HLRE0HSQNN80": HPACK decoding error while decoding headers for stream ID 47.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecodingException: Index 79 is outside the bounds of the header field table.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.DynamicTable.get_Item(Int32 index)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.GetHeader(Int32 index)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.GetHeader(Int32 index)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnIndexedHeaderField(Int32 index, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnByte(Byte b, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.Decode(ReadOnlySequence`1 data, Boolean endHeaders, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.DecodeHeadersAsync[TContext](IHttpApplication`1 application, Boolean endHeaders, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessHeadersFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

### Further technical details
- Microsoft.AspNetCore.Server.Kestrel - 2.2.0"
- Include the output of `dotnet --info`

	Host (useful for support):
	  Version: 3.0.1
	  Commit:  19942e7199

	.NET Core SDKs installed:
	  No SDKs were found.

	.NET Core runtimes installed:
	  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by jogibear9988** [comment]
My simple program looks like this...

Where MccHttpServer is a class Providing our HTTP Results...

	using MCC.WebSocket.Service.MccHttpServer;
	using Microsoft.AspNetCore.Builder;
	using Microsoft.AspNetCore.Hosting;
	using Microsoft.AspNetCore.Server.Kestrel.Core;
	using Microsoft.Extensions.Configuration;
	using Microsoft.Extensions.Logging;
	using Pluralsight.Crypto;
	using System;
	using System.IO;
	using System.Security.Cryptography.X509Certificates;

	namespace KestrelWebServer
	{
		class Program
		{
			public static Config Config;

			static void Main(string[] args)
			{
				var config = new ConfigurationBuilder()
						.SetBasePath(Directory.GetCurrentDirectory())
						.AddJsonFile("appsettings.json")
						.Build();

				Config = config.GetSection("config").Get<Config>();

				System.Security.Cryptography.X509Certificates.X509Certificate2 cert;
				using (CryptContext ctx = new CryptContext())
				{
					ctx.Open();
					cert = ctx.CreateSelfSignedCertificate(
						new SelfSignedCertProperties
						{
							IsPrivateKeyExportable = true,
							KeyBitLength = 4096,
							Name = new X500DistinguishedName("cn=localhost"),

							ValidFrom = DateTime.Today.AddDays(-1),
							ValidTo = DateTime.Today.AddYears(100),
						});
				}

				var host = new WebHostBuilder()
				   .UseContentRoot(Directory.GetCurrentDirectory())
				   .UseKestrel()
				   .ConfigureLogging(logging =>
				   {
					   logging.ClearProviders();
					   logging.AddConsole();
				   })
				   .ConfigureKestrel(options =>
				   {
					   options.Limits.Http2.MaxStreamsPerConnection = 10000;
					   options.ListenAnyIP(Config.Port, listenOptions =>
					   {
						   listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
						   listenOptions.UseHttps(cert);
					   });
				   })
				   .UseStartup<Startup>()
				   .Build();

				host.Run();

				Console.ReadLine();
			}
		}

		public class Startup
		{
			MccHttpServer _mccHttpServer;

			public Startup()
			{
				var path = Path.GetFullPath(Path.Combine(Environment.CurrentDirectory, Program.Config.Path));

				Console.WriteLine("");
				Console.WriteLine("MCC Kestrel Based HTTP Server - Serving Dir: " + path);
				Console.WriteLine("Listening on Port: 8443");
				Console.WriteLine("");

				_mccHttpServer = new MccHttpServer() { RootDirectory = () => path };
			}

			public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory lf)
			{
				app.Run(async (context) =>
				{
					var result = _mccHttpServer.GetFile(context.Request.Path, context.Request.Headers["Accept-Encoding"]);
					if (result.mime != null)
						context.Response.ContentType = result.mime;
					if (result.headers != null)
						foreach (var hd in result.headers)
						{
							context.Response.Headers[hd.Key] = hd.Value;
						}
					context.Response.StatusCode = (int)result.httpStatusCode;
					if (result.data != null)
						await context.Response.Body.WriteAsync(result.data, 0, result.data.Length);
				});
			}
		}
	}

**Comment by jogibear9988** [comment]
okay, works using aspnetcore 3.1

never saw that my nuget with kestrel only is not updatet to version 3
