### ISSUE TITLE
AspNetCore.Correlation.Google cookie not found

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/AspNetCore#17677]
After upgrading from 3.0 to 3.1 I have issues with the Google authentication. I have no cookie policy registered and this is how my authentication configuration looks like:

```c#
services
          .AddAuthentication(options =>
          {
            options.DefaultScheme = IdentityConstants.ApplicationScheme;
            options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
          })
          .AddGoogle(options =>
          {
            options.ClientId = _configurationOptions.Google.ClientId;
            options.ClientSecret = _configurationOptions.Google.ClientSecret;
            options.Scope.Add("https://www.googleapis.com/auth/userinfo.profile");
            options.SaveTokens = true;
          })
        .AddIdentityCookies(options =>
        {
          options.ApplicationCookie.Configure(a =>
          {
            a.Cookie.Name = ".AspNet.SharedCookie";
            a.Cookie.Domain = _configurationOptions.Domain;
          });
        });
```
And this is the error I get:
```
warn: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[15]
      '.AspNetCore.Correlation.Google.611LD72jlzagvpKikBe8B41IqHTqrvVnXZdWS9iuZd8' cookie not found.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLRR2LP0DVR7", Request id "0HLRR2LP0DVR7:00000001": An unhandled exception was thrown by the application.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)```

**Comment by blowdart** [comment]
What browser are you using? Have you implemented the [changes needed](https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/) to support older browsers?

**Comment by Tratcher** [comment]
Sharing a decrypted Fiddler trace is the best way to debug this class of issue.

**Comment by marcuslindblom** [comment]
@blowdart I use Chrome 78 and I have not implemented any support for older browsers.

**Comment by blowdart** [comment]
As Chris says a fiddler trace would be highly useful

**Comment by marcuslindblom** [comment]
Ok. I use macOS but I could try the mono version of Fiddler maybe

**Comment by blowdart** [comment]
Does it happen if a PC is hitting the web site? Or is this just in your local development?

**Comment by Tratcher** [comment]
Another way to capture a raw trace is with Kestrel's connection logger.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#connection-logging

**Comment by marcuslindblom** [comment]
@blowdart I have only tested this on my mac running in docker. If I just tested on my mac and it seems to work fine. So it seems to be only when I run the application in Docker.

**Comment by blowdart** [comment]
Oh then it's probably how keys are persisted. Does it happen when the container restarts but you still have the browser open?

**Comment by marcuslindblom** [comment]
@blowdart I just tested from a Windows machine running in parallels and worked just fine. So it seems to be when I access the application from chrome from my Mac. Firefox on my Mac works fine. Running the application locally works fine in all browsers so it seems to be a combination of running in docker and access the app from my Mac using chrome

**Comment by blowdart** [comment]
And the app is up all the time? There's no container restart? And you've cleared cookies and cache? And nothing in the logs?

**Comment by Tratcher** [comment]
Again, a network trace is one or a kestrel connection trace (linked above) is the first step to debug this.

**Comment by marcuslindblom** [comment]
@Tratcher Ok, I see. Where is the log file / dump stored when I configure the connection logging like this?

```
                    webBuilder.ConfigureKestrel(serverOptions =>
                    {
                        serverOptions.Listen(IPAddress.Any, 80, listenOptions =>
                        {
                            listenOptions.UseConnectionLogging();
                        });
                    });
```

**Comment by anurse** [comment]
@marcuslindblom it's in the application logs themselves (Console output by default, but you can configure other loggers). A network trace using a tool like [Fiddler](https://www.telerik.com/fiddler) is even better.

**Comment by marcuslindblom** [comment]
@anurse My web and api runs using https with external auth so I guess that fiddler can not be used to read the packages. And on macOS is't a bit problematic to use Fiddler but wireshark works but I'm not familiar with http debugging using Wireshark. When using this config.

```c#
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureLogging((_, factory) =>
                    {
                        factory.SetMinimumLevel(LogLevel.Debug);
                        factory.AddConsole();                    });
                    webBuilder.ConfigureKestrel(serverOptions =>
                    {
                        serverOptions.Listen(IPAddress.Any, 80, listenOptions =>
                        {
                            listenOptions.UseConnectionLogging();
                        });
                    });
                    webBuilder.UseStartup<Startup>();
                });
```

this is the only output in the console and I guess this is not what you are looking for...

```
warn: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[15]
      '.AspNetCore.Correlation.Google.Lwev0vfdTrLb0UiyvMYc-Kre7ov5pdt77YpUdj_juVY' cookie not found.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLRVK8G34BJ0", Request id "0HLRVK8G34BJ0:00000001": An unhandled exception was thrown by the application.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Tratcher** [comment]
Fiddler does have an option to decrypt https.

For UseConnectionLogging you'll need to turn the log level up to Trace.

**Comment by anurse** [comment]
Yeah, sorry I wasn't clear there, you can [configure Fiddler to decrypt HTTPS](https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/DecryptHTTPS).

Can you try using that or the connection logging (with the log level turned up to Trace as @Tratcher indicated)?

**Comment by marcuslindblom** [comment]
Here is a Trace from my container when the error occurs. 
[trace.log](https://github.com/aspnet/AspNetCore/files/3963689/trace.log)

**Comment by Tratcher** [comment]
Ah, you're using a proxy but it's not properly configured. The proxy is terminating https so the back-end app thinks the requests are using http. That causes the app to A) generate incorrect directs to http, and B) fail to mark cookies as 'Secure'.
See this doc about setting up forwarders for [nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#nginx-configuration) and then adding UseForwardedHeaders to consume them.

**Comment by marcuslindblom** [comment]
Ok. Does this has to do with any recent upgrade because I have used this configuration for the past six months running in AWS without any problems. Also why is this only happening in chrome on my mac?

**Comment by Tratcher** [comment]
We've been dealing with issues related to SameSite cookies for the last several releases. It's particularly bad on Mac and iOS, and Chrome is now making it worse. There are a lot of moving parts here, but I suspect if you get your Secure attribute fixed that should take care of it.

Background:
https://github.com/aspnet/Announcements/issues/318
https://github.com/aspnet/Announcements/issues/348
https://github.com/aspnet/Announcements/issues/390
https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

**Comment by marcuslindblom** [comment]
@Tratcher Ok I see. It does not seem to be easy to find the correct configuration and I can not make it work when I use exakt the configuration in the documentation. Maybe you could look at the config I ended up with.

My nginx configuration is located in `/etc/nginx/conf.d/default.conf` and the content is looks like this.

```
upstream api_server {
    server api;
}

upstream web_server {
    server web;
}

server {
    listen   80 default_server;
    # listen [::]:80 default_server deferred;
    return   444;
}

server {
    listen 80;
    listen [::]:80;
    server_name api.brickpile.local.computer;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name brickpile.local.computer;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name api.brickpile.local.computer;

    ssl_certificate         /etc/letsencrypt/live/brickpile.local/local.computer.crt;
    ssl_certificate_key     /etc/letsencrypt/live/brickpile.local/local.computer.key;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://api_server;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name brickpile.local.computer;

    http2_push_preload on;

    add_header Set-Cookie "session=1";
    add_header Link $resources;

    ssl_certificate         /etc/letsencrypt/live/brickpile.local/local.computer.crt;
    ssl_certificate_key     /etc/letsencrypt/live/brickpile.local/local.computer.key;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://web_server;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}

map $http_cookie $resources {
    "~*session=1" "";
    default "</static/main.css>; as=style; rel=preload, </static/other.css>; as=style; rel=preload, </fonts/inter.css>; as=style; rel=preload, </fonts/Inter-upright.var.woff2>; as=font; crossorigin; rel=preload";
}

gzip off;
```

This is how my `ConfigureServices` looks like for the API.
```c#
    public void ConfigureServices(IServiceCollection services)
    {

      var dataprotection = services.AddDataProtection()
          .SetApplicationName("SharedCookieApp")
          .PersistKeysToFileSystem(new DirectoryInfo(_configurationOptions.DataProtection));

      services
          .AddAuthentication(options =>
          {
            options.DefaultScheme = IdentityConstants.ApplicationScheme;
            options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
          })
          .AddGoogle(options =>
          {
            options.ClientId = _configurationOptions.Google.ClientId;
            options.ClientSecret = _configurationOptions.Google.ClientSecret;
            options.Scope.Add("https://www.googleapis.com/auth/userinfo.profile");
            options.SaveTokens = true;
          })
            .AddJwtBearer(options =>
            {
              options.Audience = JwtParameters.Audience;
              options.ClaimsIssuer = JwtParameters.Issuer;
              options.TokenValidationParameters = new TokenValidationParameters
              {
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(JwtParameters.SigningKey),
                ValidateIssuer = false,
                ValidateAudience = true
              };
            })
        .AddIdentityCookies(options =>
        {
          options.ApplicationCookie.Configure(a =>
          {
            a.Cookie.Name = ".AspNet.SharedCookie";
            a.Cookie.Domain = _configurationOptions.Domain;
          });
        });

      ConfigureRavenDbDocStore(services);

      services.AddIdentityCore<User>(options =>
      {
        options.Password.RequireDigit = true;
        options.Password.RequiredLength = 8;
        options.Password.RequireNonAlphanumeric = false;
        options.Password.RequireUppercase = true;
        options.Password.RequireLowercase = true;
      })
      .AddRoles<Raven.Identity.IdentityRole>()
      .AddRoleStore<RoleStore<Raven.Identity.IdentityRole>>()
      .AddUserStore<UserStore<User, Raven.Identity.IdentityRole>>()
      .AddSignInManager();

      services.AddControllers();

      services.AddCors(options =>
      {
        options.AddPolicy("AllowOrigin", builder =>
        {
          builder.AllowAnyMethod();
          builder.AllowAnyHeader();
          builder.WithOrigins(
            "https://brickpile.local.computer",
            "https://brickpile.app",
            "https://localhost:5003");
          builder.AllowCredentials();
        });
      });

      services.Configure<RouteOptions>(options =>
      {
        options.LowercaseUrls = true;
        options.AppendTrailingSlash = true;
      });

      services.AddApiVersioning(options =>
      {
        options.DefaultApiVersion = ApiVersion.Parse("1");
        options.AssumeDefaultVersionWhenUnspecified = true;
        options.ReportApiVersions = true;
        options.ApiVersionReader = new AcceptHeaderApiVersionReader();
      });

      services.AddSwaggerGen(c =>
      {
        c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
      });

      services.AddHealthChecks();
```

and this is my `Configure` section for the API

```c#
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }

      app.UseForwardedHeaders(new ForwardedHeadersOptions
      {
          ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
      });

      app.UseRouting();

      app.UseCors("AllowOrigin");

      app.UseCookiePolicy(); // Before UseAuthentication or anything else that writes cookies.
      app.UseAuthentication();
      app.UseAuthorization();

      app.UseSwagger();

      app.UseSwaggerUI(c =>
      {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
      });

      app.UseEndpoints(endpoints =>
      {
        endpoints.MapHealthChecks("/health", new HealthCheckOptions {
          ResponseWriter = WriteResponse
        });
        endpoints.MapControllers();
      });
    }
```

For what I can see the configuration looks correct but maybe some of my other settings interfere with `ForwardedHeaders` or something?

**Comment by Tratcher** [comment]
Check the troubleshooting section at the bottom.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#troubleshoot

UseForwardedHeaders is a strict about who it accepts forwarders from. See the KnownProxies option.

**Comment by marcuslindblom** [comment]
I just tried to print all headers with this setting on both my sites.

```c#
      services.Configure<ForwardedHeadersOptions>(options =>
      {
        options.KnownNetworks.Clear();
        options.KnownProxies.Clear();
      });
```

```c#
      app.UseForwardedHeaders(new ForwardedHeadersOptions
      {
          ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
      });
```
and this is the result:

**Web**
```
Request Method: GET
Request Scheme: http
Request Path: /home/index
Request Headers:
Cache-Control: no-cache
Connection: keep-alive
Pragma: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,sv;q=0.8
Cookie: session=1; session=1
Host: brickpile.local.computer
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
DNT: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 192.168.112.1
X-Forwarded-Proto: https
sec-fetch-dest: empty
sec-fetch-site: same-origin
sec-fetch-mode: same-origin

Request RemoteIp: ::ffff:192.168.112.6
```
**API**
```
Request Method: GET
Request Scheme: http
Request Path: /
Request Headers:
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,sv;q=0.8
Host: api.brickpile.local.computer
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
DNT: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 192.168.112.1
X-Forwarded-Proto: https
sec-ch-ua: Google Chrome 79
sec-fetch-dest: document
sec-fetch-user: ?1
sec-origin-policy: 0
sec-fetch-site: none
sec-fetch-mode: navigate

Request RemoteIp: ::ffff:192.168.112.6
```
The IP of my nginx container using this command `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 76f9e098dcf2` is `192.168.112.6`.

But I still get the same error?

**Comment by Tratcher** [comment]
UseForwardedHeaders isn't running, it would have removed the x-forwarded-headers when it applied them. The app logs should say why.

**Comment by marcuslindblom** [comment]
Ok. I finally solved it and this is what I did.

I configured the default network in my docker compose file like this:

```yaml
networks:
  default:
    ipam:
      config:
        - subnet: 172.16.1.0/24
```

Configured forward headers like this:
```c#
    public void ConfigureServices(IServiceCollection services)
    {

      services.Configure<ForwardedHeadersOptions>(options =>
      {
        options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
        options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("::ffff:172.16.1.0"), 120));
      });
    ...
}
```

And add `UseForwardHeaders` like this:
```c#
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }

      app.UseForwardedHeaders();
    ....
}
```

Now it seems to work properly.

Thanks for your patience and help 👍

**Comment by Tratcher** [comment]
`new IPNetwork(IPAddress.Parse("172.16.1.0"), 24)` should also work in 3.0+.

**Comment by anurse** [comment]
Closing, as this appears to be resolved. Let us know if that's not the case and we can continue investigating!
