### ISSUE TITLE
Can I know where TaskCanceledException exception was raised?

### ISSUE THREAD

**Issue by czd890** [aspnet/AspNetCore#17808]
In microsoft/dotnet:2.2-aspnetcore-runtime docker.

"Microsoft.AspNetCore.Server.Kestrel" throw "Connection id "0HLRU0PRILLB2", Request id "0HLRU0PRILLB2:0000000E": An unhandled exception was thrown by the application. System.Threading.Tasks.TaskCanceledException: A task was canceled.".

It not include any stacktrace infos.

If throw any exceptions in my application, it can output exception stacktrace info.

Can I know where this exception was raised?

**Comment by halter73** [comment]
Where are you getting the log message from? Is it possible you're not seeing the stacktrace info logged on the following lines. I get the following output from the console logger with the default configuration when I throw a TaskCanceledException from the end of the middleware in Kestrel's [sample project](https://github.com/aspnet/AspNetCore/blob/fde783911b0b671dc4307ef5bcb2a9bc5e4a51bf/src/Servers/Kestrel/samples/SampleApp/Startup.cs).

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLRVAM53K0VC", Request id "0HLRVAM53K0VC:00000001": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at SampleApp.Startup.<>c__DisplayClass0_0.<<Configure>b__1>d.MoveNext() in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\samples\SampleApp\Startup.cs:line 57
--- End of stack trace from previous location ---
   at SampleApp.Startup.<>c.<<Configure>b__0_0>d.MoveNext() in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\samples\SampleApp\Startup.cs:line 37
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 630
```

**Comment by czd890** [comment]
Sorry, It's ok, output to console is contains.
 I used `Nlog` to record logs, only the exception not stackstarce.
