### ISSUE TITLE
Provide better experience when the BodyReader is left in a reading state 

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#17840]
When middleware calls HttpContext.Request.BodyReader.ReadAsync() and exits without calling HttpContext.Request.BodyReader.AdvanceTo(), Kestrel will fail to read the following request while logging the following exception as a warning (at least for Content-Length HTTP/1.1 requests, not sure about others):

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Reading is already in progress.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult) in /_/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs:line 126
```

This is pretty common type of error when something throws in between calls to ReadAsync() and AdvanceTo() and AdvanceTo() isn't in a finally block.

It would be better if Kestrel logged a warning that explicitly tells the developer that there's a missing call to BodyReader.AdvanceTo(). Better yet would be to recover from this situation by draining the rest of the request despite the BodyReader being left in a bad state so that the connection can still be used for future requests.

We should also ensure Kestrel handles the BodyWriter being left in a bad state gracefully.

See #17723.

- ASP.NET Core version 3.1

**Comment by halter73** [comment]
#14727 is also related.

**Comment by strawberries73** [comment]
Hello, I am new to Open Source.  I would like to work on this issue.

**Comment by jkotalik** [comment]
@strawberries73 apologies, didn't see this notification. @halter73 I believe this issue is specifically about changing the error message for when we throw an exception during draining, right? I'd imagine an exception would be thrown here: https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs#L140, which would then be caught here https://github.com/dotnet/aspnetcore/blob/bda52f77aed9a7571bd7b0a003bc136ec6f73553/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs#L55. Changing that error message is what we'd need to do?

**Comment by halter73** [comment]
I think we should be tracking whether the BodyReader/BodyWriter was left in a reading/writing state without having to rely on catching an InvalidOperationException. It's confusing to log an "application" exception that the application had no opportunity to catch. I'm not quite sure what the log message should be. Maybe something like the following:

> BodyReader.ReadAsync() was called without a corresponding call to BodyReader.AdvanceTo(). This can often be fixed using try/finally.

**Comment by davidni** [comment]
@halter73 we are seeing the same exception referenced in this issue but I audited the code and found no direct uses of `Request.BodyReader`, so I thought I'd raise here in case that isn't the only way this can happen. Our repro is in IslandGateway, and (I think) the only component dealing directly with the request body is YARP. Any suggestions what might be going on here? We are investigating this as part of a weeks-long investigation into a reliability issue that impacts some cross-geo requests issued from a .NET 6.0.8 client to IslandGateway. We own both sides. In case these things are indeed related, the pattern we see is:
* Client observes: `IOException: The response ended prematurely while waiting for the next frame from the server`
* Server observes: `InvalidOperationException: Reading is already in progress`

Detailed exceptions follow. And to be clear, we have not yet established that the client errors and servers errors described here are correlated. This is just one hypothesis we are working through.

---

Example exception we see server-side:

```
Connection id "0HMKH7444S95V", Request id "0HMKH7444S95V:00003038": An unhandled exception was thrown by the application.

Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
   --- End of inner exception stack trace ---
```

---

Example exception we see client-side (as mentioned, we do not know if these are related or not):

```
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|57_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
(...)
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
   --- End of inner exception stack trace ---
(...)
```

**Comment by halter73** [comment]
I think YARP uses the BodyReader. Correct me if I'm wrong @Tratcher. Do you have trace-level logs on the server? That might tell you why the server aborted the connection.

It could be caused by a number of factors like a min rate limit timeout, ungraceful server shut down, or simply calling HttpContext.Abort().

**Comment by Tratcher** [comment]
YARP is all stream based. Pipelines didn't give us any additional functionality or throughput.
https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Forwarder/StreamCopier.cs

**Comment by halter73** [comment]
What runtime version is this on?

I think we fixed the stream wrappers to properly reset the PipeReader given certain errors like min rate limit timeout. The real error happened before the InvalidOperationException which indicates something (probably internal logic in Kestrel Streams if everything is really Stream-based) previously called PipeReader.ReadAsync() and successfully got a ReadResult but then never called PipeReader.AdvanceTo(). Usually, this is an uncaught exception between these two calls.

My guess is that the there was something like a min rate limit timeout that got logged at a lower severity first. That hen triggered this bug which is logged at a higher severity.

**Comment by halter73** [comment]
I just noticed something:

> Example exception we see server-side:
> ```
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
> ```

> Example exception we see client-side (as mentioned, we do not know if these are related or not):
> ```
>   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)`
> ```

Given the HTTP/1.x vs HTTP/2 here, I'm going to say these are unrelated.

**Comment by davidni** [comment]
@halter73 we faced this with .NET 6.0.8 and YARP 1.1.0

**Comment by halter73** [comment]
Then the likely reason for the InvalidOperationException is that I missed some corner case in Http1ContentLengthMessageBody in #16725. I'm not sure exactly what that would be, but please feel free to give it another look now that we know this exception is still possible with an Http1ContentLengthMessageBody and no direct usage of the PipeReader.

I figure whatever the issue is has to be some pretty low level to cause a failure at Kestrel's MessageBody layer. My guess is the client aborted the request given we don't see any client errors associated with this, but more detailed logging to show the error that led to the invalid state could probably clear that up.

**Comment by davidni** [comment]
> My guess is the client aborted the request

We have (non-definitive) evidence of the contrary -- among the first middlewares we run in our app, we have a telemetry middleware that, at the end of the pipeline, emits (among other things), the value of `HttpContext.RequestAborted`, and that was consistently `false` for all (including the last) request successfully processed in each incoming connection that eventually resulted in `InvalidOperationException: Reading is already in progress`.

Perhaps the cancellation could be coming from a request that never entered our middlewares? Or perhaps it fired right after but before the request completed? Seems unlikely given the volume that we encounter this.

**Comment by halter73** [comment]
> Perhaps the cancellation could be coming from a request that never entered our middlewares? Or perhaps it fired right after but before the request completed? Seems unlikely given the volume that we encounter this.

This exception should be logged after your middleware exits when Kestrel attempts to drain the request body. We know for a fact these are HTTP/1.x Content-Length requests with non-empty bodies based on the stack trace. Does this align with what the telemetry middleware is logging? Do we have enough logging to know how many bytes of the request body were consumed by YARP middleware before exiting? And whether there were any exceptions? Including OperationCanceledExceptions?

I'm suspicious of the following:

https://github.com/dotnet/aspnetcore/blob/2eb79b1bd1e57cdb3a95e709c2a4566db7249d9b/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestStream.cs#L118-L123

I'm pretty sure on a "real" PipeReader, you don't have to call AdvanceTo() if the ReadResult is canceled. You can just read again.

The problem is this isn't a real PipeReader. It's backed by Http1ContentLengthMessageBody which will return the ReadResult but leave `_isReading = true` and throw on the next Read/TryRead. We should probably unset _isReading here to avoid this and match the behavior of other PipeReaders.

https://github.com/dotnet/aspnetcore/blob/2eb79b1bd1e57cdb3a95e709c2a4566db7249d9b/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs#L94-L111

https://github.com/dotnet/aspnetcore/blob/2eb79b1bd1e57cdb3a95e709c2a4566db7249d9b/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs#L260-L282

That said, for this to happen, someone would have need to cancel a read on the BodyReader. That's what the `Interlocked.Exchange(ref _userCanceled, 0) == 1` is about. If it's just the connection-level PipeReader that was canceled to signal graceful shutdown or something. There also should be an OperationCanceledException logged somewhere.

So, I think this is *a* bug that could cause this exception if you call `BodyReader.CancelPendingRead()`. Or if the underlying connection PipeReader got canceled while there was examined-but-unconsumed data in the BodyReader. However, I don't think it's *the* bug that you're experiencing.

I welcome anyone else to try to comb through this logic to see what else could cause this error without using the PipeReader APIs directly.

@davidfowl @BrennanConroy

**Comment by MelbourneDeveloper** [comment]
I'm getting this error. This is my sample code:

```csharp
//This is an ASP .NET Core Minimal API that receives Webhook POST data
using System.Text;

var builder = WebApplication.CreateBuilder(args);

//Configure services
builder.Services.AddSingleton<IReceiveWebhook, ConsoleWebhookReceiver>();

var app = builder.Build();

app.UseHttpsRedirection();

//Listen for POST webhooks
app.MapPost("/webhook", async (HttpContext context, IReceiveWebhook receiveWebook) =>
{
    var responseJSON = await receiveWebook.ProcessRequest(
       Encoding.UTF8.GetString((await context.Request.BodyReader.ReadAsync()).Buffer));

    return responseJSON;
});

app.Run();

/// <summary>
/// An abstraction to process the POST request data that the webbook receives.
/// </summary>
public interface IReceiveWebhook
{
    Task<string> ProcessRequest(string requestBody);
}

/// <summary>
/// An implementation for IReceiveWebhook that writes to the console
/// </summary>
public class ConsoleWebhookReceiver : IReceiveWebhook
{
    /// <summary>
    /// Writes the POST request body to the console and returns JSON
    /// </summary>
    public async Task<string> ProcessRequest(string requestBody)
    {
        //This is where you would put your actual business logic for receiving webhooks

        Console.WriteLine($"Request Body: {requestBody}");

        return "{\"message\" : \"Thanks! We got your webhook\"}";
    }
}

/// <summary>
/// This is just a requirement for ASP .NET Core and testing this service
/// </summary>
public partial class Program { }
```

**Comment by halter73** [comment]
You cannot assume the entire body will be read in a single call to BodyReader.ReadAsync. You should read in a loop until ReadResult.IsCompleted is true.

**Comment by KrzysztofBranicki** [comment]
We also encountered same errors only with Error severity level
```
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
   --- End of inner exception stack trace ---
```
We are currently running .NET 7.0.409 (soon to be upgraded to 8) and Yarp.ReverseProxy 2.0.1
Is there any progress on this issue? Can we expect some improvement after upgrading to 8?

**Comment by rchoffardet** [comment]
To add additional information, I'm also experiencing this issue (last version of .NET 8).
We have a middleware that pretty much does what `HttpRequestRewindExtensions.EnableBuffering()` enables, except it copies the body content ahead of endpoint execution. This triggers the exception discussed in this thread:
> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
   --- End of inner exception stack trace ---
   
 However, If I try to use `HttpRequestRewindExtensions.EnableBuffering()` instead, it throws another exception during endpoint execution:
 > icrosoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

The second case seems to be a normal behavior, wherehas the first doesn't (Which is I believe, the whole point of this issue).
Is there a workaround? I tried to re-implement a way to copy the request's body to a stream while being sure to call `advanceTo` with no success. I tried to catch the exception in the middleware with no success either. 

Does someone have any tips?

**Comment by marekott** [comment]
I am using Yarp.ReverseProxy with 8.0.403 .NET and also encountered this error:
```
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.\n --->
System.InvalidOperationException: Reading is already in progress.\n   
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()\n   --- End of inner exception stack trace ---
```

I am not using request body pipe directly or `EnableBuffering` and still got this exception. Are there any plans for fixing it in a near future? @mkArtakMSFT @amcasey

**Comment by marekott** [comment]
Hi, after updating to 9.0.304 .NET the error still occurs:

```
"MessageTemplate": "Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": automatic draining of the request body failed because the body reader is in an invalid state.",
"Exception": "System.InvalidOperationException: Reading is already in progress.\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()"
"SourceContext": "Microsoft.AspNetCore.Server.Kestrel"
```

@davidfowl is there any ETA for resolving this issue?

**Comment by davidfowl** [comment]
Not that I'm aware of. Are you seeing this using YARP only?

**Comment by marekott** [comment]
Yes, related issue in YARP repo: https://github.com/dotnet/yarp/issues/2655

**Comment by rchoffardet** [comment]
I'm also still seeing this in .NET9, but we're not using YARP. (We have a middleware buffering requests and response, though)
