### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by Svek** [aspnet/AspNetCore#17862]
I am getting a really confusing error that I can't seem to resolve.  When running with the latest and running with `InProcess`

	<PropertyGroup>
	  <TargetFramework>netcoreapp3.1</TargetFramework>
	  <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
	</PropertyGroup>

It seems like when you try to run the following,

	public class Program
	{
		public static void Main(string[] args)
		{
			CreateHostBuilder(args).Build().Run();
		}

		public static IHostBuilder CreateHostBuilder(string[] args) =>
			Host.CreateDefaultBuilder(args)
				.ConfigureAppConfiguration((hostingContext, config) =>
				{
				})
				.ConfigureWebHostDefaults(webBuilder =>
				{
					webBuilder.ConfigureServices(services =>
					{
						services.AddControllersWithViews();
					})
					.Configure(app =>
					{
						var loggerFactory = app.ApplicationServices
							.GetRequiredService<ILoggerFactory>();
						var logger = loggerFactory.CreateLogger<Program>();
						var env = app.ApplicationServices.GetRequiredService<IWebHostEnvironment>();
						var config = app.ApplicationServices.GetRequiredService<IConfiguration>();

						logger.LogInformation("Logged in Configure");

						if (env.IsDevelopment())
						{
							app.UseDeveloperExceptionPage();
						}
						else
						{
							app.UseExceptionHandler("/Home/Error");
							app.UseHsts();
						}

						var configValue = config["MyConfigKey"];
					});
				});
			});
	}

_Source: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-3.1#configure-services-without-startup_

We get the following error...

	System.NullReferenceException
	  HResult=0x80004003
	  Message=Object reference not set to an instance of an object.
	  Source=Microsoft.AspNetCore.Server.IIS
	  StackTrace:
	   at Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.<>c__DisplayClass0_0.<UseIIS>b__2(IISServerOptions options)
	   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
	   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
	   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
	   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
	   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.get_Value()
	   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
	   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
	   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
	   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer..ctor(IISNativeApplication nativeApplication, IHostApplicationLifetime applicationLifetime, IAuthenticationSchemeProvider authentication, IOptions`1 options, ILogger`1 logger)
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
	   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
	   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
	   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
	   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
	   at Erx.OneCircle.Api.Program.Main(String[] args) in C:\Visual Studio Online\ERX\One Circle\Erx.OneCircle.Api\Program.cs:line 25

	  This exception was originally thrown at this call stack:
		Microsoft.AspNetCore.Hosting.WebHostBuilderIISExtensions.UseIIS.AnonymousMethod__2(Microsoft.AspNetCore.Builder.IISServerOptions)
		...
		[Call Stack Truncated]

**Comment by Tratcher** [comment]
Can you share the rest of your project so we can see your dependency versions?

**Comment by Svek** [comment]
I think I have been able to narrow down the issue. I was trying to replicate the problem in a new project and it didn't seem to reoccur. After doing a bit more digging around with dependencies in my former project I found that there was a reference to another class library, that has a reference to `Microsoft.AspNetCore` (v2.2.0).

If you update the project file to my example previously provided to this:

    <PropertyGroup>
      <TargetFramework>netcoreapp3.1</TargetFramework>
      <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    </ItemGroup>

The issue can be replicated.

**Comment by Tratcher** [comment]
That is certainly an issue. Remove all 2.x dependencies from your 3.x project.

**Comment by Svek** [comment]
Not to be overly opinionated on this -- but it seems a bit strange that there is no issues when running this with the `OutOfProcess` instead of using `InProcess`.

The debugging has been quite nightmarish to figure out the root cause.

**Comment by Tratcher** [comment]
You're supposed to remove the 2.2 dependencies for OutOfProcess too, it just happens to be a bigger problem when running InProcess.

**Comment by Svek** [comment]
Understood. I am just a bit frustrated with the migration path as it wasn't super intuitive where to locate the problem.

The class library that we are using has it's own `IWebHost` build process, which needs to create an instance of the [WebHost Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost?view=aspnetcore-3.1).

I cannot seem to find `Microsoft.AspNetCore.dll` available on Nuget for 3.1 -- what am I missing?

**Comment by Svek** [comment]
The class library that I am using creates an instance of `WebHost` which is part of `Microsoft.AspNetCore.App.dll (3.1)`. I'm a bit stumped on where to get that package...

I also tried to get `Microsoft.AspNetCore.App.Ref` with no success either.

**Comment by Svek** [comment]
My current workaround was to change the class library `csproj`
from

    <Project Sdk="Microsoft.NET.Sdk">

to

    <Project Sdk="Microsoft.NET.Sdk.Web">

and then throwing in an empty main method `static void Main() { }` to keep the compiler happy.

It would be great to know how to fix this properly.

**Comment by Svek** [comment]
Well... It turns out the only package that worked is `Microsoft.AspNetCore.TestHost`

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#remove-obsolete-package-references
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#framework-reference
https://devblogs.microsoft.com/aspnet/a-first-look-at-changes-coming-in-asp-net-core-3-0/
https://github.com/aspnet/Announcements/issues/325

**Comment by Svek** [comment]
Oh. That's perfect. The first link gave me the right answer.

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

Thank you!

**Comment by werddomain** [comment]
i have the same problem. But in my case the error has happen just after updating visual studio. I dod not change anything to the references.

**Comment by Svek** [comment]
You have to check for any rogue references to 2.x -- it was difficult for me to find the root cause, I feel your pain in that experience.
