### ISSUE TITLE
JSON Patch replace entire object

### ISSUE THREAD

**Issue by fabich** [aspnet/AspNetCore#17927]
### Describe the bug
JSON Patch implementation does not work as expected when trying to replace entire object.
Error: The target location specified by path segment '' was not found.

### To Reproduce
input:
```JSON
{
  "flightnumber": "3523",
  "dep": "YUL",
  "dest": "YYZ"
}
```

patch:
```JSON
[{
"op": "replace",
"path": "",
"value": {
  "flightnumber": "111",
  "dep": "YYC",
  "dest": "YUL"}
}
]
```

output:
```JSON
{
  "flightnumber": "111",
  "dep": "YYC",
  "dest": "YUL"
}
```
Test runs successful with json8 (https://github.com/sonnyp/JSON8):
https://json8.github.io/patch/demos/apply/

code example:
```C#
var flight = new FlightPatchDTO{...};
var patchDoc = new JsonPatchDocument<FlightPatchDTO>();
patchDoc.Replace(x => x, flight);

....
```

Error:
```C#
Microsoft.AspNetCore.JsonPatch.Exceptions.JsonPatchException : The target location specified by path segment '' was not found.
   at Microsoft.AspNetCore.JsonPatch.Internal.ErrorReporter.<>c.<.cctor>b__1_0(JsonPatchError error)
   at Microsoft.AspNetCore.JsonPatch.Adapters.ObjectAdapter.Replace(Operation operation, Object objectToApplyTo)
   at Microsoft.AspNetCore.JsonPatch.Operations.Operation`1.Apply(TModel objectToApplyTo, IObjectAdapter adapter)
   at Microsoft.AspNetCore.JsonPatch.JsonPatchDocument`1.ApplyTo(TModel objectToApplyTo, IObjectAdapter adapter)
   at Microsoft.AspNetCore.JsonPatch.JsonPatchDocument`1.ApplyTo(TModel objectToApplyTo)
```
### Further technical details
- ASP.NET Core version: netcoreapp2.2

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.
