### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake. : Cannot access a disposed object. Object name: 'FrameResponseStream'

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#2460]
_From @akash073 on Thursday, November 23, 2017 9:19:46 PM_

I am getting following exception in Microsoft.AspNetCore.WebSockets Version 1.0.2 .
 in
**if (socket.State == WebSocketState.Open) await socket.SendAsync(buffer: new ArraySegment<byte>(array: Encoding.ASCII.GetBytes(message), offset: 0, count: message.Length), messageType: WebSocketMessageType.Text, endOfMessage: true, cancellationToken: CancellationToken.None);**

.Message = The remote party closed the WebSocket connection without completing the close handshake. inner exception = System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FrameResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.ValidateState(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameDuplexStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer) stacktrace =    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<SendCloseFrameAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<CloseAsyncPrivate>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebsocketCoreApplicatonWithChatRoom.WebSocketConnectionManager.<RemoveSocket>d__5.MoveNext() in F:\My Private Repository\SmartShipWorks\WebsocketCoreApplicatonWithChatRoom\WebsocketCoreApplicatonWithChatRoom\Program.cs:line 75

I happens when connection is established but not used for 10-15 minutes . Working fine for simple bidirectional sending but happens infrequently .What is the problem ?  

_Copied from original issue: aspnet/WebSockets#212_

**Comment by aspnet-hello** [comment]
_From @kasper3 on Thursday, December 21, 2017 10:31:46 AM_

same issue as #207.

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, December 21, 2017 11:59:11 AM_

This is different from the original issue in #207 as far as I understand. The exception messages are different. This message was posted later in that thread, but it's caused by a different underlying issue.

This particular issue is generally caused by taking the `WebSocket` off to a background process and allowing the request to end. The `WebSocket` type **does not** hold the Request Stream open, so when you return from your middleware, the stream is closed out from under the socket.

See https://github.com/aspnet/WebSockets/issues/208 for more information on this issue. If you're going to process sockets in a background process, you need to ensure the middleware (or MVC controller, etc.) that accepts the socket doesn't return until you are done with that socket.

**Comment by aspnet-hello** [comment]
_From @kasper3 on Thursday, December 21, 2017 12:26:17 PM_

@anurse 


I am running my service app with `TaskScheduler.UnobservedTaskException` to catch these kinda exception. I don't see this exception until AFTER the disconnect. Say user was connected for 5 hours, there is no error. AFTER connection gets disconnected, I start getting these errors and they appear exactly the same amount of times as the number of connected-then-disconnected users/connections. The trouble is UnobservedTaskException keep capturing those Task failures with message `The remote party closed the WebSocket connection without completing the close handshake.` and `System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync` in stacktrace even if there is no new connections popping up (I totally banned the new connections on that system). The errors wont stop popping up until i restart the service. The errors won't stop logging and appear after every X-seconds over and over.

Seems to me like once after Close->Dispose of web socket, there is still some dangling ref somewhere in some underlying Task, that tries to access the socket and fails, then task goes into faulted state, TaskScheduler.UnobservedTaskException captures it and then after sometime that repeats.

Some GC'ness? some task that was supposed to be suffixed with ContinueWith but not? Anything else?

#### Steps to repro: Keep the app running and log errors in `TaskScheduler.UnobservedTaskException` event handler

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, December 21, 2017 6:53:17 PM_

How are you disconnecting the clients? Are they sending a proper WebSocket close frame? If not, this exception will occur. If you don't want it firing the `UnobservedTaskException` event, you have to catch it in your code (or just ignore it when it triggers that event). What's the full stack trace for the exception you're getting? That would help narrow down where the exception is coming from.

> AFTER connection gets disconnected, I start getting these errors and they appear exactly the same amount of times as the number of connected-then-disconnected users/connections

This seems exactly like the behavior I described above. If the connections aren't being gracefully shut down, any code waiting to Send or Receive on the socket will throw this exception. You have to suppress it in your own code if you don't want to see it logged.
