### ISSUE TITLE
WebSocketMiddleware should dispose the WebSocket when the pipeline exits

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCore#2854]
We get quite a few reports where developers have upgraded to a WebSocket , handed it off to a background thread for processing, and then allowed the application pipeline to exit. This causes the server to close the underlying connection and you get vague ObjectDisposedExceptions from WebSocket Send/Receive.

The cause of the problem could be made more clear by having the WebSocket middleware wrap the WebSocket when it's created, dispose that when the pipeline exits, set the state to Aborted, and providing more detailed exception messages for Send and Receive.

See https://github.com/aspnet/Home/issues/2462#issuecomment-363686888

@anurse

**Comment by anurse** [comment]
I'm in favor of this, but I do want to point out that this could be seen as a breaking change. It is theoretically possible for the WebSocket to remain usable after the middleware ends (if another middleware above WebSocket is still holding the connection open). With this change, as soon as the request leaves the WebSocket middleware, any send/receive actions would fail.

**Comment by anurse** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
It doesn't need to be when the middleware yields, we can do RegisterForDispose so it happens at the end of the request.

**Comment by anurse** [comment]
Sure, that would be a little nicer. I'm also filing a Kestrel bug because the exception message you get is super unclear and could easily be clarified.

**Comment by anurse** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/2299

**Comment by Tratcher** [comment]
RegisterForDispose executes after the response ends. We're trying to preempt those errors.

**Comment by anurse** [comment]
Thoughts on doing this in 3.0 @Tratcher @davidfowl ? It's a relatively simple change and 3.0 is a nice time to do this kind of breaking change.

My preference is to do it when the middleware yields to really enforce the idea that you need to block the pipeline. Technically `RegisterForDispose` would be sufficient though, since the idea is that you can't write to the WebSocket **after** the response ends.

**Comment by Tratcher** [comment]
I don't think RegisterForDispose would work well, most of the underlying state would already be disposed at that point and you'd already be subject to the ODE's people have reported. Doing it in the middleware would be more effective.

**Comment by davidfowl** [comment]
I don't think we should wrap the websocket to give better error messages. An ODE is fine.

**Comment by anurse** [comment]
We can start with an ODE. Changing an exception message (I don't think we'd change the type) is a less scary change if we decide we need it later.

**Comment by Tratcher** [comment]
Customers already get an ODE and they don't know why. The point would be to provide a more specific error.

**Comment by davidfowl** [comment]
Lets fix the error message and punt the issue then. The real problem here is docs.

**Comment by Tratcher** [comment]
We don't throw the ODE directly right now, it's from the underlying Kestrel resources. This issue is about how to insert something capable of producing a smarter error, such as a WebSocket rapper.

**Comment by anurse** [comment]
I'll do a quick investigation on how this looks right now and see what can be improved where. The ODE is coming from Kestrel IIRC, so if that error message becomes something like "Cannot write to response stream after middleware pipeline ends" that may make things clearer.

**Comment by anurse** [comment]
This is what you get now. Kinda seems good enough to me...

```
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.ObjectDisposedException: Cannot write to the response body, the response has completed.
Object name: 'HttpResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.<ValidateState>g__ThrowObjectDisposedException|14_0() in C:\Code\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpResponsePipeWriter.cs:line 112
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.ValidateState(CancellationToken cancellationToken) in C:\Code\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpResponsePipeWriter.cs:line 107
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in C:\Code\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpResponsePipeWriter.cs:line 67
   at System.IO.Pipelines.WriteOnlyPipeStream.WriteAsyncInternal(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in C:\Code\aspnet\AspNetCore\src\http\http\src\WriteOnlyPipeStream.cs:line 166
   at System.IO.Pipelines.WriteOnlyPipeStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in C:\Code\aspnet\AspNetCore\src\http\http\src\WriteOnlyPipeStream.cs:line 161
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpUpgradeStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken) in C:\Code\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpUpgradeStream.cs:line 165
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer)
   at EchoApp.Startup.Repeat(HttpContext context, WebSocket websocket, ILogger logger) in C:\Code\aspnet\AspNetCore\src\Middleware\WebSockets\samples\EchoApp\Startup.cs:line 94
```

**Comment by Tratcher** [comment]
It hasn't been. It doesn't help people discover how to use WebSockets correctly.

**Comment by anurse** [comment]
> It hasn't been.

I've only seen this reported with the old error which was just an ODE referring to `FrameResponseStream` or something. We fixed this in https://github.com/aspnet/KestrelHttpServer/pull/2305

Have we heard customer confusion issues since then?

**Comment by Tratcher** [comment]
Fair, I don't know of complaints since then.

**Comment by anurse** [comment]
Propose we close this and keep the wrapper idea in our back pocket in case customers come a knocking with this issue :).

**Comment by davidfowl** [comment]
And update the docs?

**Comment by anurse** [comment]
> And update the docs?

https://github.com/aspnet/AspNetCore.Docs/pull/12378
