### ISSUE TITLE
WebSockets failure when proxying v8 debugger protocol 

### ISSUE THREAD

**Issue by kumpera** [aspnet/AspNetCore#2930]
Hello everyone,

I'm using asp.net to proxy the v8 debugger protocol. It uses WebSockets.

I'm running into this exception that makes little sense to me. What could be causing it?
```
System.Net.WebSockets.WebSocketException: TODO, RESX: net_WebSockets_InvalidState; (Aborted,Open, CloseReceived)
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WsProxy.WsProxy.<Send>d__8.MoveNext() in /Users/kumpera/src/wasm/ws-proxy/WsProxy.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WsProxy.WsProxy.<SendEventInternal>d__17.MoveNext() in /Users/kumpera/src/wasm/ws-proxy/WsProxy.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WsProxy.WsProxy.<OnEvent>d__9.MoveNext() in /Users/kumpera/src/wasm/ws-proxy/WsProxy.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by kumpera** [comment]
It normally happens when the browser decides to send a large amount of data to the debugger.

**Comment by kumpera** [comment]
Hey @anurse,

The scenario is the v8 debugger being flooded with messages when the browser finishes loading a wasm file with debug data and decided to tell the debugger that there are a few thousand source files in the web page.

It works fine without the proxy, so there's something wrong somewhere in my setup (my code or asp.net core). 

I'll update to 2.1-preview1 to see if anything changes.

Meanwhile, while I reduce my thing to an usable repro, would some WireShark dumps help?

**Comment by anurse** [comment]
WireShark dumps would help a lot. The key is going to be figuring out who is terminating the connection and why. ASP.NET's WebSocket implementation adds almost nothing on top of the CoreFX ManagedWebSocket implementation (in fact, in 2.1-preview1, it is literally using the same code), so there may be an issue there.

Do you have a repro I can run locally?

**Comment by anurse** [comment]
Closing this as it's gotten very stale  :).
