### ISSUE TITLE
Line length limit 100 exceeded on multipart form request

### ISSUE THREAD

**Issue by richardhopton** [aspnet/AspNetCore#2939]
When making the following request on my mac: -

```
curl -X POST \
  http://localhost:8080/upload \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryRiOPcOCObfAkq1Aw' \
  -d '------WebKitFormBoundaryRiOPcOCObfAkq1Aw
Content-Disposition: form-data; name="uid"

1252154297730234145_18808100
------WebKitFormBoundaryRiOPcOCObfAkq1Aw
Content-Disposition: form-data; name="label"

interior
------WebKitFormBoundaryRiOPcOCObfAkq1Aw--'
```

Against the following controller method: -

```
[HttpPost]
public async Task<IActionResult> UploadAsync()
{
    if (!Request.ContentType.StartsWith("multipart/"))
        return BadRequest();

    var form = Request.Form;

    return Ok(form.Count);
}
```

I receive the following response: -
```
{"status":"Failure","errors":[{"code":"InternalServerError","exceptionMessage":"Line length limit 100 exceeded."}]}
```
If I wrap the Request.Form access in a try catch the following exception stack trace is throw: -

```
{System.IO.InvalidDataException: Line length limit 100 exceeded.
   at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.<ReadLineAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.<ReadAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.<DrainAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.WebUtilities.MultipartReader.<ReadNextSectionAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Form()
   at FileUploadTest.Controllers.UploadController.<UploadAsync>d__4.MoveNext() in /Users/richard/Source/file-upload-test/src/service/Controllers/UploadController.cs:line 50}
```

**Comment by richardhopton** [comment]
After debugging the bytes of the incoming request Body, it only has new line characters and no carriage returns which BufferedReadStream requires to delimiter lines.  It sounds like this needs to be changed.

**Comment by danielmeza** [comment]
Any update on this a I got this error to.

**Comment by Tratcher** [comment]
That format is invalid, what client is sending it?

**Comment by danielmeza** [comment]
@Tratcher I'm with  .NET Framework and reciving in a asp.net core site the library is from nuget

**Comment by Tratcher** [comment]
?? What software is sending invalid multipart requests to your server?

**Comment by danielmeza** [comment]
@Tratcher  a console app is reading datta from DB2 using oledb

**Comment by Tratcher** [comment]
I don't understand how DB2 relates to sending a multipart message. You're going to need to supply some sample code, preferrably as a runnable github repo.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
