### ISSUE TITLE
Broken test: AutobahnTests.AutobahnTestSuite

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#2969]
This test failed [on the ci](http://aspnetci/viewLog.html?buildId=422662&buildTypeId=XPlat_Windows_Win2008r2_Universe).

```
System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
---- System.IO.IOException : Authentication failed because the remote party has closed the transport stream.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount)
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount)
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.Autobahn.AutobahnTester.DeployTestAndAddToSpec(ServerType server, Boolean ssl, String environment, CancellationToken cancellationToken, Action`1 expectationConfig) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\Microsoft.AspNetCore.WebSockets.ConformanceTest\Autobahn\AutobahnTester.cs:line 173
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.AutobahnTests.AutobahnTestSuite() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\Microsoft.AspNetCore.WebSockets.ConformanceTest\AutobahnTests.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__44_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
------- Stdout: -------
| TestLifetime Information: Starting test AutobahnTestSuite
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=http://localhost:0, Publish=False
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet run --no-restore --framework netcoreapp2.1 -- --server.urls http://localhost:49352/  --server Microsoft.AspNetCore.Server.Kestrel
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=ManagedSockets
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 10468
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using launch settings from C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\AutobahnTestApp\Properties\launchSettings.json...
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using Kestrel, URL: http://localhost:49352/
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Starting Server for Scenario: Unknown
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: ManagedSockets
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\AutobahnTestApp
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://127.0.0.1:49352
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://127.0.0.1:49352/
| AutobahnTestApp:Kestrel:NoSSL:ManagedSockets Warning: Retry count 1..
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://127.0.0.1:49352/  
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 81.5628ms 200 
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=https://localhost:0, Publish=False
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet run --no-restore --framework netcoreapp2.1 -- --server.urls https://localhost:49416/  --server Microsoft.AspNetCore.Server.Kestrel
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=ManagedSockets
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 7468
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using launch settings from C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\AutobahnTestApp\Properties\launchSettings.json...
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using Kestrel, URL: https://localhost:49416/
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Starting Server for Scenario: Unknown
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using SSL with certificate: C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\AutobahnTestApp\bin\Release\netcoreapp2.1\TestResources\testCert.pfx
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: ManagedSockets
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: C:\BuildAgent\work\33bdfc1cae7b2a38\modules\WebSockets\test\AutobahnTestApp
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: https://127.0.0.1:49416
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: https://127.0.0.1:49416/
| AutobahnTestApp:Kestrel:SSL:ManagedSockets Warning: Retry count 1..
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: fail: Microsoft.AspNetCore.Server.Kestrel[0]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm
```

Future instances of this failure can be found on [this](http://aspnetci/httpAuth/app/rest/builds?locator=tag:SSLCommonAlgo,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)) list.

**Comment by ryanbrandenburg** [comment]
It also failed for a possibly different reason [here](http://aspnetci/viewLog.html?buildId=435409&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

```
Autobahn results did not meet expectations:
Case Kestrel|NoSSL|ManagedSockets:1.1.1. Expected 'NON-STRICT' or 'OK', but got 'FAILED'

Expected: True
Actual:   False
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.Autobahn.AutobahnTester.Verify(AutobahnResult result) in /_/test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Autobahn/AutobahnTester.cs:line 127
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.AutobahnTests.AutobahnTestSuite() in /_/test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
***** Text was not loaded fully because its' size exceeds 2 MB, see full log for the whole text *****
```

**Comment by ryanbrandenburg** [comment]
This is still happening on other tests, see [here](http://aspnetci/viewLog.html?buildId=474296&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
This is [still happening](http://aspnetci/viewLog.html?buildId=498180&buildTypeId=Releases_21Public_OsxUniverse):
```
Autobahn results did not meet expectations:
Case Kestrel|SSL|ManagedSockets:1.1.8. Expected 'NON-STRICT' or 'OK', but got 'FAILED'
Expected: True
Actual:   False
```

**Comment by anurse** [comment]
Closing this since RaaS is tracking failures in AspNetCore-Internal. If this is still happening, we can triage it there.
