### ISSUE TITLE
Use Proxy to youtube and get error 

### ISSUE THREAD

**Issue by WangCharlie** [aspnet/AspNetCore#3017]
here is the code.
```
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddProxy(options =>
            {
                options.MessageHandler = new HttpClientHandler
                {
                    AllowAutoRedirect = false,
                    UseCookies = true
                };

                options.PrepareRequest = (originalRequest, message) =>
                {
                    var host = GetHeaderValue(originalRequest, "X-Forwarded-Host") ?? originalRequest.Host.Host;
                    var port = GetHeaderValue(originalRequest, "X-Forwarded-Port") ?? originalRequest.Host.Port.Value.ToString(CultureInfo.InvariantCulture);
                    var prefix = GetHeaderValue(originalRequest, "X-Forwarded-Prefix") ?? originalRequest.PathBase;

                    message.Headers.Add("Access-Control-Allow-Origin", originalRequest.Scheme + "://" + originalRequest.Host.Host);
                    message.Headers.Add("X-Forwarded-Host", host);
                    if (!string.IsNullOrWhiteSpace(port)) message.Headers.Add("X-Forwarded-Port", port);
                    if (!string.IsNullOrWhiteSpace(prefix)) message.Headers.Add("X-Forwarded-Prefix", prefix);

                    return Task.FromResult(0);
                };
            });
        }

        private static string GetHeaderValue(HttpRequest request, string headerName)
        {
            return request.Headers.TryGetValue(headerName, out StringValues list) ? list.FirstOrDefault() : null;
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseWebSockets()
                //.Map("/youtubei",api=>api.RunProxy(new Uri("https://www.youtube.com")))
                .RunProxy(new Uri("https://www.youtube.com"));
        }
```
 
![image](https://user-images.githubusercontent.com/6106454/38226717-9ea25fca-372d-11e8-8419-e4eb79f0a3a9.png)

**Comment by Eilon** [comment]
@Tratcher - any idea on this? I'm not familiar with this stack trace so I haven't entirely convinced myself that this is even an issue with our Proxy stuff.

**Comment by Tratcher** [comment]
I doubt it, but I can't confirm without the original exception or translation.

Also Proxy is an unsupported prototype, please don't use it.

**Comment by WangCharlie** [comment]
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://173.254.231.65/  
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLCP6TCGJJ3F", Request id "0HLCP6TCGJJ3F:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Microsoft.AspNetCore.Proxy.Samples2.Startup.<>c.<ConfigureServices>b__0_1(HttpRequest originalRequest, HttpRequestMessage message) in D:\Source\Repos\Proxy\Microsoft.AspNetCore.Proxy.Samples2\Startup.cs:line 33
   at Microsoft.AspNetCore.Builder.ProxyExtensions.<ProxyRequest>d__3.MoveNext() in D:\Source\Repos\Proxy\src\Microsoft.AspNetCore.Proxy\ProxyExtensions.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 518.3235ms 500 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://173.254.231.65/  
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLCP6TCGJJ3G", Request id "0HLCP6TCGJJ3G:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Microsoft.AspNetCore.Proxy.Samples2.Startup.<>c.<ConfigureServices>b__0_1(HttpRequest originalRequest, HttpRequestMessage message) in D:\Source\Repos\Proxy\Microsoft.AspNetCore.Proxy.Samples2\Startup.cs:line 33
   at Microsoft.AspNetCore.Builder.ProxyExtensions.<ProxyRequest>d__3.MoveNext() in D:\Source\Repos\Proxy\src\Microsoft.AspNetCore.Proxy\ProxyExtensions.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 5.815ms 500

**Comment by Tratcher** [comment]
That's a different exception and it's coming from your own code. It looks like originalRequest.Host.Port.Value might not have a value which is expected when using default ports like 80 and 443.

**Comment by WangCharlie** [comment]
[Proxy.zip](https://github.com/aspnet/Home/files/1874298/Proxy.zip)
here is the solution include all codes.  i just want to use proxy for youtube.com site. and get error cors.
and some other error i can't figure out

**Comment by Eilon** [comment]
@WangCharlie did you end up figuring this out?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
