### ISSUE TITLE
JIT Compiler encountered an internal limitation while resolving a service with ILEmit backend enabled

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#3054]
https://github.com/aspnet/Home/issues/2737#issuecomment-381194729

```
System.InvalidProgramException: JIT Compiler encountered an internal limitation.
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
```

Seems like a bad codegen.

**Comment by pakrym** [comment]
Related: https://github.com/dotnet/coreclr/issues/14672

**Comment by pakrym** [comment]
> The jit allocates a new set of locals for each control flow join where there are values live in on the evaluation stack. Having stack depth in the 100s across 100s of branches quickly leads to 10,000s of temps and banging up against internal limits in the jit.

**Comment by davidfowl** [comment]
We need to figure out if we're going to keep the ref emit version of not 😄
