### ISSUE TITLE
Unix socket bidding with Owin not working

### ISSUE THREAD

**Issue by sterchelen** [aspnet/AspNetCore#3122]
Hi,

I'm trying to use unix socket with Owin and Nancy activated. With the `ListenUnixSocket()` all of my requests return `500` whereas with the standard tcp bidding `Listen()` everything is fine !
Here is the stack trace, thanks to `UseDeveloperExceptionPage()`:
```
   at Microsoft.AspNetCore.Owin.OwinEnvironment.<>c.<.ctor>b__2_50(IHttpConnectionFeature feature)
   at Microsoft.AspNetCore.Owin.OwinEnvironment.FeatureMap`1.<>c__DisplayClass2_0.<.ctor>b__0(Object feature)
   at Microsoft.AspNetCore.Owin.OwinEnvironment.FeatureMap.TryGet(HttpContext context, Object& value)
   at Microsoft.AspNetCore.Owin.OwinEnvironment.System.Collections.Generic.IDictionary<System.String,System.Object>.TryGetValue(String key, Object& value)
   at Nancy.Owin.NancyMiddleware.Get[T](IDictionary`2 env, String key)
   at Nancy.Owin.NancyMiddleware.<>c__DisplayClass2_1.<<UseNancy>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

My code that bind the unix socket :

```csharp
				var host = new WebHostBuilder()
					.UseKestrel(k =>
					{
						k.Listen(IPAddress.Any, port);
						if (!string.IsNullOrEmpty(kestrelSocketPath))
							k.ListenUnixSocket(kestrelSocketPath);
					})
					.UseContentRoot(Directory.GetCurrentDirectory())
					.UseStartup<Startup>()
					.Build();
```

Any ideas ?

Dotnet and owin version --> 2.0.2
Nancy --> 2.0.0

Thanks.

**Comment by khellang** [comment]
What is the actual exception type and message?

**Comment by sterchelen** [comment]
Type -> NullReferenceException
Message -> Object reference not set to an instance of an object
Stacktrace -> 
```
   at Microsoft.AspNetCore.Owin.OwinEnvironment.<>c.<.ctor>b__2_50(IHttpConnectionFeature feature)
   at Microsoft.AspNetCore.Owin.OwinEnvironment.FeatureMap`1.<>c__DisplayClass2_0.<.ctor>b__0(Object feature)
   at Microsoft.AspNetCore.Owin.OwinEnvironment.FeatureMap.TryGet(HttpContext context, Object& value)
   at Microsoft.AspNetCore.Owin.OwinEnvironment.System.Collections.Generic.IDictionary<System.String,System.Object>.TryGetValue(String key, Object& value)
   at Nancy.Owin.NancyMiddleware.Get[T](IDictionary`2 env, String key)
   at Nancy.Owin.NancyMiddleware.<>c__DisplayClass2_1.<<UseNancy>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Owin.WebSocketAcceptAdapter.<>c__DisplayClass6_0.<<AdaptWebSockets>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by khellang** [comment]
> Hmm, it assumes IPs and ports are always available.

Yes, looks like the Nancy middleware [pulls `server.RemoteIpAddress`](https://github.com/NancyFx/Nancy/blob/a082f042297ce75350a964947b0195d3c038a623/src/Nancy/Owin/NancyMiddleware.cs#L79) for all requests. This should probably be more resilient.

Not sure if there's anything to do in the OWIN adapter? I guess there could be better error handling there as well, or provide dummy values out of the box.

**Comment by Tratcher** [comment]
The adapter could return null rather than throwing.

**Comment by khellang** [comment]
Ah, well, [Nancy actually uses `TryGetValue` and falls back to `default(T)`](https://github.com/NancyFx/Nancy/blob/a082f042297ce75350a964947b0195d3c038a623/src/Nancy/Owin/NancyMiddleware.cs#L167-L171) if the key doesn't exist, so it should handle missing values. 

I guess the fix here is to make sure the adapter doesn't throw.

**Comment by sterchelen** [comment]
In fact ! 
Setting IPaddresses to dummy values resolve my issue :
```csharp
context.Connection.LocalIpAddress = new IPAddress(new byte[] {0, 0, 0, 0});
					context.Connection.RemoteIpAddress = new IPAddress(new byte[] {0, 0, 0, 0});
```

Thank you.

**Comment by anurse** [comment]
Sounds like there are sufficient workarounds for this scenario. Closing.
