### ISSUE TITLE
Http.Internal.DefaultHttpRequest Get Query null exception

### ISSUE THREAD

**Issue by peacecwz** [aspnet/AspNetCore#3321]
I developed an API and It's working on Docker, Nginx and Kube. I tried load test and i got this exception in internal http

## **StackTrace**

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.get_Query()
   at Microsoft.AspNetCore.Mvc.ModelBinding.QueryStringValueProviderFactory.CreateValueProviderAsync(ValueProviderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.<CreateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextExceptionFilterAsync>d__23.MoveNext()
```

I looked HttpAbstractions and i found QueryFeature and got null exception

**Comment by Tratcher** [comment]
- Does it happen on every request or randomly?
- What's the request URL?

We've only seen problems like this when there are multiple threads accessing the request concurrently. This is usually accidental, such as by using `async void` methods.

**Comment by peacecwz** [comment]
Actually it happend in two request. When it was in load test. There are %2 of 500 request per seconds.
Request Url is like this "/installment-restrictions/max?categoryIds=234,224543,423113" and it returned as async Task<IActionResult>

I looked HttpAbstractions repository and i seen QueryFeature and Cache Feature. When Request called it. It's getting null in someone request. Why did it happend? How Can I fix it?

**Comment by Tratcher** [comment]
Can you make a small project to share on github that reproduces the same issue?

**Comment by peacecwz** [comment]
Okey i will make it. Actually i just seen this exception in load test and i wouldn't like to see it in production

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/Home/issues/3219

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.
