### ISSUE TITLE
DistrubutedSession error: A severe error occurred on the current command. The results, if any, should be discarded. Operation cancelled by user. 

### ISSUE THREAD

**Issue by john-luke-laue** [aspnet/AspNetCore#3479]
I'm getting an error in DistributedSession. The source of the error seems to come from Cancellation tokens. 
There was discussion on quieting some of the noisy logs coming from cancellation tokens here in [Session Issue 189](https://github.com/aspnet/Session/issues/189)

I'm wondering if the same can be done for this error? Or, if not, how can I handle this error myself?

I'll keep trying, but so far, I'm unable to reproduce.

**Exception Message:** A severe error occurred on the current command. The results, if any, should be discarded. Operation cancelled by user. 
**Stack trace:** 
```
System.Data.SqlClient.SqlException (0x80131904): A severe error occurred on the current command.  The results, if any, should be discarded. Operation cancelled by user.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.SqlServer.SqlServerCache.d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.DistributedSession.d__32.MoveNext()
```

The IIS logs also show this message in addition to stack trace: _Session cache read exception_

I found [a test that tests for this message](https://github.com/aspnet/Session/blob/1869bd09fabb7ba2b9cdf457fbd5f7eaf6592bea/test/Microsoft.AspNetCore.Session.Tests/SessionTests.cs#L595), if that helps.

asp.net core 2.1
MVC site with DistributedSqlServerCache. Session is backed by SqlServer.

**Comment by Tratcher** [comment]
What's the actual exception type?

**Comment by john-luke-laue** [comment]
@Tratcher updated the stack trace in my previous post to include it.
But here it is again: 
**System.Data.SqlClient.SqlException (0x80131904):** A severe error occurred on the current command.  The results, if any, should be discarded. Operation cancelled by user.

**Comment by ReVolly** [comment]
Same issue in our environment.

**Comment by russelkrause** [comment]
Same issue also now appears in our environment after upgrading Microsoft.AspNetCore.Session from 2.0.2 to 2.1.1.

**Comment by russelkrause** [comment]
On review - stack trace is different in my case - any date scheduled to resolve this issue, or is there a work around?  The error is filling our log files.

Error closing the session.
System.Data.SqlClient.SqlException (0x80131904): Operation cancelled by user.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.<GetCacheItemAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.<RefreshCacheItemAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.SqlServer.SqlServerCache.<RefreshAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.DistributedSession.<CommitAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
ClientConnectionId:81bfe738-81ad-4373-b91d-facfe5728c54

**Comment by Tratcher** [comment]
There was a related change where we downgraded the severity of this warning. https://github.com/aspnet/Session/issues/189

That said, we should remove RequestAborted from CommitAsync.
https://github.com/aspnet/Session/blob/9e4b6a5e4a8d4c789b627a37b0342dad45c87b6c/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L117

**Comment by russelkrause** [comment]
Odd - I am still seeing the stack trace above reported at the ERROR level in "Microsoft.AspNetCore.Session" Version="2.1.1" though it was reported as included in 2.1.0-preview, or do I have this wrong?

**Comment by shirhatti** [comment]
@Tratcher Do you still want to make the change to CommitAsync?

**Comment by Tratcher** [comment]
Yes

**Comment by FinkoAI** [comment]
I've the same issue in our environment. Is there any way to avoid this exception at least temporary. An also, what is the initial reason of this issue?

**Comment by phehr2** [comment]
Same issue in our environment

**Comment by marc-mueller** [comment]
We are currently also facing this error. Any idea what is causing this?

```
ail: Microsoft.AspNetCore.Session.SessionMiddleware[1]
      Error closing the session.
System.Data.SqlClient.SqlException (0x80131904): A severe error occurred on the current command.  The results, if any, should be discarded.
Operation cancelled by user.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.GetCacheItemAsync(String key, Boolean includeValue, CancellationToken token)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.RefreshCacheItemAsync(String key, CancellationToken token)
   at Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RefreshAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
ClientConnectionId:xxxxxxxxxxx
ClientConnectionId before routing:xxxxxxxxxx
Routing Destination:xxxxxx.xxxxxx.xxxxxxxxxx.worker.database.windows.net,11026
```

Thanks
Marc

**Comment by Tratcher** [comment]
That usually means the client disconnected, causing the session commit to be aborted.

@anurse we do need to address this, it's causing a lot of unnecessary noise.

**Comment by knoxi** [comment]
@Tratcher : we have the same exception as Marc has. 
In our service we are using [Distributed SQL Server Cache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2) and there the entry in the cache table is missing because of this exception.
Correct me if I'm wrong but as I interpreted you answer, I looks we could ignore this exception. Does this now have an influence on the current session (session state not written) or does it not have any impact?

**Comment by Tratcher** [comment]
Correct, if the user disconnects before their session is saved then it will not be saved. I've changed this in 3.0.0-preview8 to not check for user disconnects here.

One workaround is to call Session.CommitAsync in app code without RequestAborted.
