### ISSUE TITLE
Create User and add to a role

### ISSUE THREAD

**Issue by karelz** [aspnet/AspNetCore#3571]
_From @PardeepBhandari on September 28, 2018 12:39_

I am using asp.net core 2.1  I am sending a authorized request to web api and I am getting error

```
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Identity.UserStoreBase`5.SetPasswordHashAsync(TUser user, String passwordHash, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdatePasswordHash(IUserPasswordStore`1 passwordStore, TUser user, String newPassword, Boolean validatePassword)
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at StarPickupMVC.api.Accounts.ApplicationUsersController.RegisterMain(Account model, Int32 id, String RandomPassword) in E:\StarPickupMVC\StarPickupMVC\api\Accounts\ApplicationUsersController.cs:line 173
```

and some time I get error while attaching user to role

code is 
```c#
   [AllowAnonymous]
        [HttpPost]
        [Route("api/Register")]  //client
        public async Task<IActionResult> Register([FromBody] Account model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var sql = $"SELECT Top 1 * FROM Otp Where Mobileno = '{model.Mobile1}' " +
                            $"And CountryCode = '{model.CountryCode}' And ValidUpto >= '{DateTime.Now.ToString("dd-MMM-yyyy HH:mm:ss")}' Order By ValidUpto Desc";

                    var otps = _context.OTP
                        .FromSql(sql)
                        .ToList();

                    if (otps[0].OTPNumber == model.OTP)
                    {
                        return await RegisterMain(model, 0);
                    }
                }
                catch (Exception e)
                {
                    string Msg = e.Message;
                }
            }

            // If we got this far, something failed, redisplay form
            return new ObjectResult("-1");
        }


        [Authorize(Roles = "Driver", AuthenticationSchemes = "Bearer")]
        [HttpPost]
        [Route("api/RegisterCustomer")]
        public async Task<IActionResult> RegisterCustomer([FromBody] Account model)
        {

            if (ModelState.IsValid)
            {
                var randompassword = Cnv.GenerateRandomPassword();
                return await RegisterMain(model, 0, randompassword);
            }

            // If we got this far, something failed, redisplay form
            return new ObjectResult("-1");
        }

        //Used in Register, RegisterCustomer
        public async Task<IActionResult> RegisterMain(Account model, int id, string RandomPassword = "")
        {
            if (RandomPassword.Trim().Length > 0)
            {
                model.Password = RandomPassword;
                model.ConfirmPassword = RandomPassword;
                model.LastName = RandomPassword;
            }

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    bool CreateUserSuccess = false;
                    Account account = null;
                    ApplicationUser user = null;

                    if (id == 0)
                    {
                        user = new ApplicationUser { UserName = model.CountryCode + model.Mobile1, Email = model.Email, AccountName = model.AccountName };
                        var result = await _userManager.CreateAsync(user, model.Password);
                        if (result.Succeeded)
                        {
                            //here we tie the new user to the role
                            await _userManager.AddToRoleAsync(user, "CLIENT");

                            account = new Account();
                            CreateUserSuccess = true;
                        }
                    }
                    else
                    {
                        account = _context.Account.FirstOrDefault(u => u.ID == id);
                        CreateUserSuccess = true;
                    }

                    if (CreateUserSuccess)
                    {
                        account.AccountName = model.AccountName;
                        account.AddressLine1 = model.AddressLine1;
                        account.AddressLine2 = model.AddressLine2;
                        account.City = model.City;
                        account.Suburb = model.Suburb;
                        account.State = model.State;

                        if (id == 0)
                        {
                            account.CountryCode = model.CountryCode;
                            account.Mobile1 = model.Mobile1;
                            account.Email = user.Email;

                            account.AspNetUserID = user.Id;
                            account.AccountTypeID = 5;
                            account.GroupID = 1;

                            account.RegionID = model.RegionID;
                            account.MiddleName = model.MiddleName;
                            account.LastName = model.LastName;


                            UserAddress addressresult = CommonFunctions.GEOCodeAddress(model.Suburb + " " + model.City + " " + model.State, "", "");
                            account.Latitude = addressresult.Longitude;
                            account.Longitude = addressresult.Latitude;



                        }
                        else
                        {
                            account.Latitude = model.Longitude;
                            account.Longitude = model.Latitude;

                            // _context.Entry(user).State = EntityState.Modified;

                        }

                        //@@@@@@@@@@@@@@@@


                        _context.Account.Add(account);
                        _context.SaveChanges();

                        user.AccountID = Cnv.MyInt(account.ID);
                        _context.ApplicationUser.Update(user);
                        _context.SaveChanges();

                        return new ObjectResult(user.Id);
                    }

                    scope.Complete();

                }
                catch (Exception e)
                {
                    scope.Dispose();
                    string Msg = e.Message;
                }
            }

            // If we got this far, something failed, redisplay form
            return new ObjectResult("-1");
        }
```

currently error is in RegisterMain

_Copied from original issue: dotnet/corefx#32529_

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
@ajcvickers is there any caveats to using transaction scopes like this with EF?  That's the only thing that looks a bit different

**Comment by Eilon** [comment]
As an aside, it appears that the code that @PardeepBhandari  posted might be vulnerable to a [SQL injection](https://en.wikipedia.org/wiki/SQL_injection) attack:

```c#
                    var sql = $"SELECT Top 1 * FROM Otp Where Mobileno = '{model.Mobile1}' " +
                            $"And CountryCode = '{model.CountryCode}' And ValidUpto >= '{DateTime.Now.ToString("dd-MMM-yyyy HH:mm:ss")}' Order By ValidUpto Desc";
```

**Comment by ajcvickers** [comment]
@HaoK The main caveat is that not all database providers support ambient transactions--see https://github.com/aspnet/EntityFramework.Docs/issues/906

Also, as @Eilon says, that use of string interpolation is not safe--see https://github.com/aspnet/EntityFrameworkCore/issues/10080

**Comment by HaoK** [comment]
So the cancellation token being triggered means the request is getting aborted because its hooked up to RequestAborted.  Identity uses the request scoped DbContext so if Create is running after the request has finished you would see issues like this
