### ISSUE TITLE
Correlation Failed Error - Local IIS Redirects back from middleware as HTTP

### ISSUE THREAD

**Issue by j-hurst** [aspnet/AspNetCore#3615]
I am trying to debug a .NET Core MVC application locally that runs through my local IIS.  I have the ASP.NET Core developer certificate set as my HTTPS certificate in IIS.  However, I continue to get a correlation failed error in the OpenIdConnectHandler.

I am using IdentityServer with an external provider pointed at Azure AD, and I know the authentication is authenticating the user based on those logs.  It has to be on redirect back to the application.  The only thing I see is in the logs is in Microsoft.AspNetCore.Hosting.Internal.WebHost there is HTTP get, but I am using UseHttpsRedirection.  How would that just HTTP and not HTTPS?

Any help would be greatly appreaciated.

**Below are my logs from the web application on starting debugging:**
```
[09:47:06 Debug] Microsoft.AspNetCore.Hosting.Internal.WebHost
Hosting starting

[09:47:06 Warning] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository
Using an in-memory repository. Keys will not be persisted to storage.

[09:47:06 Warning] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver
Repository contains no viable default key. Caller should generate a key with immediate activation.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider
Policy resolution states that a new key should be added to the key ring.

[09:47:06 Information] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
Creating key "2e0f791a-20df-4017-a060-b4086a666b3a" with creation date "2018-10-11T13:47:06.1822019+00:00", activation date "2018-10-11T13:47:06.1761673+00:00", and expiration date "2019-01-09T13:47:06.1761673+00:00".

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
Descriptor deserializer type for key "2e0f791a-20df-4017-a060-b4086a666b3a" is 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
No key escrow sink found. Not writing key "2e0f791a-20df-4017-a060-b4086a666b3a" to escrow.

[09:47:06 Warning] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
No XML encryptor configured. Key "2e0f791a-20df-4017-a060-b4086a666b3a" may be persisted to storage in unencrypted form.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
Key cache expiration token triggered by 'CreateNewKey' operation.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
Found key "2e0f791a-20df-4017-a060-b4086a666b3a".

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver
Considering key "2e0f791a-20df-4017-a060-b4086a666b3a" with expiration date "2019-01-09T13:47:06.1761673+00:00" as default key.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.TypeForwardingActivator
Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory
Opening CNG algorithm 'AES' from provider 'null' with chaining mode CBC.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory
Opening CNG algorithm 'SHA256' from provider 'null' with HMAC.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider
Using key "2e0f791a-20df-4017-a060-b4086a666b3a" as the default key.

[09:47:06 Debug] Microsoft.AspNetCore.DataProtection.Internal.DataProtectionStartupFilter
Key ring with default key "2e0f791a-20df-4017-a060-b4086a666b3a" was loaded during application startup.

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcJsonOptions
Compatibility switch AllowInputFormatterExceptionMessages in type MvcJsonOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcOptions
Compatibility switch AllowCombiningAuthorizeFilters in type MvcOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcOptions
Compatibility switch AllowBindingHeaderValuesToNonStringModelTypes in type MvcOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcOptions
Compatibility switch AllowValidatingTopLevelNodes in type MvcOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcOptions
Compatibility switch InputFormatterExceptionPolicy in type MvcOptions is using default value "AllExceptions"

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcOptions
Compatibility switch SuppressBindingUndefinedValueToEnumType in type MvcOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.RazorPages.RazorPagesOptions
Compatibility switch AllowAreas in type RazorPagesOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.RazorPages.RazorPagesOptions
Compatibility switch AllowMappingHeadRequestsToGetHandler in type RazorPagesOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.MvcViewOptions
Compatibility switch SuppressTempDataAttributePrefix in type MvcViewOptions is using default value false

[09:47:06 Debug] Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory
Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider","Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]

[09:47:06 Debug] Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer
Failed to locate the development https certificate at 'null'.

[09:47:06 Debug] Microsoft.AspNetCore.Hosting.Internal.WebHost
Hosting started

[09:47:06 Debug] Microsoft.AspNetCore.Hosting.Internal.WebHost
Loaded hosting startup assembly Company.Web.UI.WebApp.vNext

[09:47:06 Debug] Microsoft.AspNetCore.Hosting.Internal.WebHost
Loaded hosting startup assembly Microsoft.AspNetCore.Server.IISIntegration

[09:47:06 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E83" started.

[09:47:06 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E84" started.

[09:47:06 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request starting HTTP/1.1 GET http://localhost/WebApp  

[09:47:06 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request starting HTTP/1.1 DEBUG http://localhost/WebApp  0

[09:47:06 Debug] Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware
Wildcard detected, all requests with hosts will be allowed.

[09:47:06 Debug] Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware
Wildcard detected, all requests with hosts will be allowed.

[09:47:06 Verbose] Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware
All hosts are allowed.

[09:47:06 Verbose] Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware
All hosts are allowed.

[09:47:06 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E83" completed keep alive response.

[09:47:06 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request finished in 43.592ms 200 

[09:47:06 Debug] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: Cookies was not authenticated.

[09:47:06 Debug] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware
The request path  does not match a supported file type

[09:47:07 Debug] Microsoft.AspNetCore.Routing.RouteBase
Request successfully matched the route with name 'default' and template '{controller=Main}/{action=Index}/{id?}'.

[09:47:07 Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Route matched with {action = "Index", controller = "Main"}. Executing action Company.Web.UI.WebApp.vNext.Controllers.MainController.Index (Company.Web.UI.WebApp.vNext)

[09:47:07 Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Execution plan of authorization filters (in the following order): ["Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"]

[09:47:07 Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Execution plan of resource filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter"]

[09:47:07 Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Execution plan of action filters (in the following order): ["Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648)","Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter"]

[09:47:07 Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Execution plan of exception filters (in the following order): ["None"]

[09:47:07 Debug] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Execution plan of result filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter"]

[09:47:07 Verbose] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Authorization Filter: Before executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.

[09:47:07 Information] Microsoft.AspNetCore.Authorization.DefaultAuthorizationService
Authorization failed.

[09:47:07 Verbose] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Authorization Filter: After executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.

[09:47:07 Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.

[09:47:07 Verbose] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Before executing action result Microsoft.AspNetCore.Mvc.ChallengeResult.

[09:47:07 Information] Microsoft.AspNetCore.Mvc.ChallengeResult
Executing ChallengeResult with authentication schemes ([]).

[09:47:07 Verbose] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
Entering Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler's HandleUnauthorizedAsync.

[09:47:07 Verbose] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
Using properties.RedirectUri for 'local redirect' post authentication: 'https://localhost/WebApp'.

[09:47:07 Verbose] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector
Performing protect operation to key "2e0f791a-20df-4017-a060-b4086a666b3a" with purposes ('C:\Repos\WebApp\WebAppSolution\Company.Web.UI.WebApp.vNext', 'Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler', 'System.String', 'OpenIdConnect', 'v1').

[09:47:07 Verbose] Microsoft.AspNetCore.CookiePolicy.CookiePolicyMiddleware
Needs consent: false.

[09:47:07 Debug] Microsoft.AspNetCore.CookiePolicy.CookiePolicyMiddleware
Cookie '.AspNetCore.OpenIdConnect.Nonce.CfDJ8Bp5Dy7fIBdAoGC0CGpmazpXcabPCGQ97zDXLtovr0OiyWIHzIh2GLv7i9RmMV2GXZoQypRAMQEusjPR6B273_SAkZTrR7hpCcjujFqb3X3Q-VbGh4zReJyfWSuTLold6azElzraA2EAp3-ITb4svce5fKEmLeciM-k-pBrRpuqYQMe4gir3K2PcjkCZh_a2FkxzyJT9-6fdagJjOb1WoH4m9GYep0P91wNRZJJcKoXmDTvMPujpmwjdsVrJz4tP0_S8iV8KkTdIBjYzjSMoGh4' same site mode upgraded to 'lax'.

[09:47:07 Debug] Microsoft.AspNetCore.CookiePolicy.CookiePolicyMiddleware
Cookie '.AspNetCore.Correlation.OpenIdConnect.jiOTeB1RbzBv3VmkOyAvKzvRmtQjy1vxwgJf1EVYSPE' same site mode upgraded to 'lax'.

[09:47:07 Verbose] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector
Performing protect operation to key "2e0f791a-20df-4017-a060-b4086a666b3a" with purposes ('C:\Repos\WebApp\WebAppSolution\Company.Web.UI.WebApp.vNext', 'Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler', 'OpenIdConnect', 'v1').

[09:47:07 Information] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
AuthenticationScheme: OpenIdConnect was challenged.

[09:47:07 Verbose] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
After executing action result Microsoft.AspNetCore.Mvc.ChallengeResult.

[09:47:07 Information] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker
Executed action Company.Web.UI.WebApp.vNext.Controllers.MainController.Index (Company.Web.UI.WebApp.vNext) in 489.1274ms

[09:47:07 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E84" completed keep alive response.

[09:47:07 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request finished in 783.5348ms 302 

[09:47:08 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request starting HTTP/1.1 POST http://localhost/WebApp/signin-oidc application/x-www-form-urlencoded 2752

[09:47:08 Verbose] Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware
All hosts are allowed.

[09:47:08 Verbose] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
Entering Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler's HandleRemoteAuthenticateAsync.

[09:47:08 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E83", Request id "0HLHFG04A8E83:00000002": started reading request body.

[09:47:08 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E83", Request id "0HLHFG04A8E83:00000002": done reading request body.

[09:47:08 Verbose] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector
Performing unprotect operation to key "2e0f791a-20df-4017-a060-b4086a666b3a" with purposes ('C:\Repos\WebApp\WebAppSolution\Company.Web.UI.WebApp.vNext', 'Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler', 'OpenIdConnect', 'v1').

[09:47:08 Verbose] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
MessageReceived: '?code=**code**&id_token=**idtoken**&access_token=**accesstoken**&token_type=Bearer&expires_in=3600&scope=openid%20profile%20offline_access&session_state=**session**'.

[09:47:08 Warning] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
'.AspNetCore.Correlation.OpenIdConnect.jiOTeB1RbzBv3VmkOyAvKzvRmtQjy1vxwgJf1EVYSPE' cookie not found.

[09:47:08 Information] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
Error from RemoteAuthentication: Correlation failed..

[09:47:08 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

[09:47:08 Debug] Microsoft.AspNetCore.Server.Kestrel
Connection id "0HLHFG04A8E83" completed keep alive response.

[09:47:08 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request finished in 113.983ms 500 text/html; charset=utf-8
```

**Comment by j-hurst** [comment]
Below is my Configure, and ConfigureServices in Startup.  I will try and get a fiddler trace posted shortly.

```
public void ConfigureServices(IServiceCollection services)
{
	JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

	services.AddHttpContextAccessor();

	services.AddAuthentication(options =>
	{
		options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
		options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
	})
		.AddCookie(options =>
		{
			CookieBuilder cookieBuilder = new CookieBuilder();
			cookieBuilder.SecurePolicy = CookieSecurePolicy.Always;
			options.Cookie = cookieBuilder;

			options.ExpireTimeSpan = new TimeSpan(5, 0, 0);
			options.SlidingExpiration = true;
		})
		.AddOpenIdConnect(options =>
		{
			options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
			options.Authority = Configuration.GetValue<string>("Authentication:AuthorityUrl");
			options.ClientId = Configuration.GetValue<string>("Authentication:ClientId");
			options.ClientSecret = Configuration.GetValue<string>("Authentication:ClientSecret");
			options.CallbackPath = "/signin-oidc";

			options.ResponseType = "code id_token token";
			options.Scope.Add("roles");
			options.Scope.Add("offline_access");

			options.SaveTokens = true;
			options.UseTokenLifetime = false;

			options.Events.OnTokenValidated = async func =>
			{
				ClaimsIdentity claimsIdentity = new ClaimsIdentity(func.Principal.Identity.AuthenticationType,
					IdentityModel.JwtClaimTypes.Name, IdentityModel.JwtClaimTypes.Role);

				// get user info data
				var userInfoClient = new UserInfoClient(new Uri(func.Options.Authority + "/connect/userinfo").ToString());
				var userInfo = await userInfoClient.GetAsync(func.ProtocolMessage.AccessToken);
				claimsIdentity.AddClaims(userInfo.Claims);

				// get the refresh and access token
				var tokenClient = new TokenClient(func.Options.Authority + "/connect/token", options.ClientId, options.ClientSecret);
				var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(func.ProtocolMessage.Code,
					Configuration.GetValue<string>("Authentication:RedirectUrl"));

				string expiration = DateTime.SpecifyKind(DateTime.UtcNow.AddSeconds(tokenResponse.ExpiresIn), DateTimeKind.Utc).ToString("o");

				// keep the id_token for logout
				claimsIdentity.AddClaim(new Claim("id_token", func.ProtocolMessage.IdToken));

				// add the refresh token
				claimsIdentity.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));

				// add access token for APIs
				claimsIdentity.AddClaim(new Claim("access_token", tokenResponse.AccessToken));

				// keep track of access token expiration
				claimsIdentity.AddClaim(new Claim("expires_at", expiration));

				func.Principal = new ClaimsPrincipal(claimsIdentity);
			};

			options.Events.OnRedirectToIdentityProvider = func =>
			{
				if (func.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectRequestType.Authentication)
				{
					func.ProtocolMessage.MaxAge = Configuration.GetValue<string>("Authentication:TokenMaxAge");
				}

				return Task.CompletedTask;
			};

			options.Events.OnRedirectToIdentityProviderForSignOut = func =>
			{
				if (func.ProtocolMessage.RequestType == Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectRequestType.Logout)
				{
					Claim idTokenHint = func.HttpContext.User.FindFirst("id_token");
					if (idTokenHint != null)
					{
						func.ProtocolMessage.IdTokenHint = idTokenHint.Value;
					}
				}

				return Task.CompletedTask;
			};
		});

	services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	if (env.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
	}
	else
	{
		app.UseHsts();
	}

	app.UseWebOptimizer();

	app.UseHttpsRedirection();
	app.UseAuthentication();
	app.UseStaticFiles();
	app.UseCookiePolicy();

	app.UseMvc(routes =>
	{
		routes.MapRoute(
			name: "default",
			template: "{controller=Main}/{action=Index}/{id?}");
	});
}
```

**Comment by Tratcher** [comment]
See this bit of the [template](https://github.com/aspnet/Templating/blob/6abfd75b0f5378ec99ad6047fc961efa2da72834/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L56-L61) about configuring the cookie samesite policy.

**Comment by Tratcher** [comment]
Other notes:
- Don't replace the CookieBuilder, mutate the existing one.
- Saving tokens as claims is discouraged, there's a separate [API](https://github.com/aspnet/HttpAbstractions/blob/3fe17b9faf0ae413ecd5bea1d42c784854acfb57/src/Microsoft.AspNetCore.Authentication.Abstractions/TokenExtensions.cs) for that.
- Move UseAuthentication after UseCookiePolicy
- My other comments from https://github.com/aspnet/AspNetCore/issues/3615#issuecomment-428997565

**Comment by j-hurst** [comment]
Thanks for the help; configuring the cookie samesite policy did the trick.  And I cleaned up some of my startup code.
