### ISSUE TITLE
Test failure: AutobahnTestSuite

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3617]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=576132&buildTypeId=Releases_21Public_UbuntuUniverse) with the following error:

```
Autobahn results did not meet expectations:
Case Kestrel|SSL|ManagedSockets:3.2. Expected 'NON-STRICT' or 'OK', but got 'FAILED'
Expected: True
Actual:   False
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.Autobahn.AutobahnTester.Verify(AutobahnResult result) in /_/test/Microsoft.AspNetCore.WebSockets.ConformanceTest/Autobahn/AutobahnTester.cs:line 128
   at Microsoft.AspNetCore.WebSockets.ConformanceTest.AutobahnTests.<AutobahnTestSuite>d__2.MoveNext() in /_/test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [2018-10-12T01:15:23] TestLifetime Information: Starting test AutobahnTestSuite
| [2018-10-12T01:15:23] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=http://localhost:0, Publish=False
| [2018-10-12T01:15:23] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet run --no-build -c Release --framework netcoreapp2.0 -- --server.urls http://localhost:43405/  --server Microsoft.AspNetCore.Server.Kestrel
| [2018-10-12T01:15:23] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=ManagedSockets
| [2018-10-12T01:15:23] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-10-12T01:15:23] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 12808
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using launch settings from /mnt/work/33bdfc1cae7b2a38/modules/WebSockets/test/AutobahnTestApp/Properties/launchSettings.json...
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using Kestrel, URL: http://localhost:43405/
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Starting Server for Scenario: Unknown
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: ManagedSockets
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /mnt/work/33bdfc1cae7b2a38/modules/WebSockets/test/AutobahnTestApp
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://127.0.0.1:43405
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [2018-10-12T01:15:24] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://127.0.0.1:43405/
| [2018-10-12T01:15:24] AutobahnTestApp:Kestrel:NoSSL:ManagedSockets Warning: Retry count 1..
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://127.0.0.1:43405/  
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 108.086ms 200 
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=https://localhost:0, Publish=False
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet run --no-build -c Release --framework netcoreapp2.0 -- --server.urls https://localhost:55219/  --server Microsoft.AspNetCore.Server.Kestrel
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=ManagedSockets
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 12861
| [2018-10-12T01:15:25] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using launch settings from /mnt/work/33bdfc1cae7b2a38/modules/WebSockets/test/AutobahnTestApp/Properties/launchSettings.json...
| [2018-10-12T01:15:26] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Using Kestrel, URL: https://localhost:55219/
| [2018-10-12T01:15:26] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Starting Server for S
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.1.

CC @Eilon (because the bot doesn't know who else to pick)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
@muratg / @anurse - can you please take a look?

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=576605&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 11:26:42 AM:
- AutobahnTestSuite

**Comment by anurse** [comment]
I don't really have cycles for this right now.

**Comment by muratg** [comment]
@mikaelm12 Can you take an initial look?
