### ISSUE TITLE
Test failure: BasePathIsNotPrefixedBySlashSlashQuestionMark

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3694]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=33412) with the following error:

```
[Test Collection Cleanup Failure (IISTestSiteCollection)]: System.AggregateException : Operation did not succeed after 280 retries (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped ye
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 30 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=33412) on release/2.2 at 8:05:26 PM:
- ReadAndWriteInterleaved
- ProvidesAccessToServerVariables
- ReturnsNullForUndefinedServerVariable
- CanSetAndReadVariable
- GetLongEnvironmentVariable
- ServerHeaderIsOverriden
- ClientDisconnectCallbackStress
- GetServerVariableDoesNotCrash
- AddResponseHeaders_HeaderValuesAreSetCorrectly
- TestValidWriteOperations
- (And 20 more test failures in this build)

**Comment by Eilon** [comment]
Looks like MAX_PATH errors:

```
2018-10-22T20:41:18.0418531Z Fail to upload 'D:\a\1\s\artifacts\logs\testlogs\IISExpress.FunctionalTests\netcoreapp2.2\ClientCertificateTests\HttpsClientCert_GetCertInformation-Server_IISExpress,_TFM_netcoreapp2.2,_Type_Portable,_Arch_x64,_ANCM_V1,_Host_OutOfProcess.log' due to 'TF400889: The following path contains more than the allowed 259 characters: artifacts-Windows-Release/logs/testlogs/IISExpress.FunctionalTests/netcoreapp2.2/ClientCertificateTests/HttpsClientCert_GetCertInformation-Server_IISExpress,_TFM_netcoreapp2.2,_Type_Portable,_Arch_x64,_ANCM_V1,_Host_OutOfProcess.log. Specify a shorter path.'.
2018-10-22T20:41:18.0419026Z Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: TF400889: The following path contains more than the allowed 259 characters: artifacts-Windows-Release/logs/testlogs/IISExpress.FunctionalTests/netcoreapp2.2/ClientCertificateTests/HttpsClientCert_GetCertInformation-Server_IISExpress,_TFM_netcoreapp2.2,_Type_Portable,_Arch_x64,_ANCM_V1,_Host_OutOfProcess.log. Specify a shorter path. ---> Microsoft.TeamFoundation.InvalidPathException: TF400889: The following path contains more than the allowed 259 characters: artifacts-Windows-Release/logs/testlogs/IISExpress.FunctionalTests/netcoreapp2.2/ClientCertificateTests/HttpsClientCert_GetCertInformation-Server_IISExpress,_TFM_netcoreapp2.2,_Type_Portable,_Arch_x64,_ANCM_V1,_Host_OutOfProcess.log. Specify a shorter path.
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.<UploadFileAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.<UploadAsync>d__14.MoveNext()
```

@BrennanConroy - did you come up with a trick for these?

**Comment by BrennanConroy** [comment]
Yeah, everyone affected by this needs to upgrade their logging dependency.

**Comment by Eilon** [comment]
Who is 'everyone' and how do we make this happen?

**Comment by BrennanConroy** [comment]
Well if our bot updated dependencies correctly over the weekend it should have been fixed for everyone.

@natemcmaster

**Comment by Eilon** [comment]
Our bot does not update dependencies in release/2.2 at this time because it's mostly noise. But I guess for this it's not.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 30 failures [with about the same error](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=33811) on release/2.2 at 12:56:18 AM:
- ReadAndWriteSlowConnection
- GetExistingEnvironmentVariable
- GetUniqueEnvironmentVariable
- ConsumePartialBody
- GetLongEnvironmentVariable
- PassesThroughCompression
- ReadAndWriteInterleaved
- ErrorCodeIsSetForExceptionDuringRequest
- ReadSetHeaderWrite
- GetServerVariableDoesNotCrash
- (And 20 more test failures in this build)

**Comment by BrennanConroy** [comment]
This is no longer a max path issue. @pakrym for IIS failures

**Comment by jkotalik** [comment]
Will be fixed by https://github.com/aspnet/IISIntegration/pull/1547
