### ISSUE TITLE
System.TypeLoadException 'Microsoft.Win32.RegistryKey' Version=4.1.1.0 at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver

### ISSUE THREAD

**Issue by AdamSchumph** [aspnet/AspNetCore#3701]
We have created an ASP.Net Core 2.1.3 website targeting .Net Framework 4.7.2 that crashes during startup.
> Windows Server 2016; Version 1607 (OS Build 14393.2248)
> IIS Version 10.0.14393.0
> ASP.Net Core 2.1.3
> .Net Framework 4.7.2

Here is the exception that is thrown during startup:
```
Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.Win32.RegistryKey' from assembly 'Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.AspNetCore.DataProtection.RegistryPolicyResolver..ctor(IActivator activator)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at OurWeb.Program.Main(String[] args) in D:\a\1\s\Web\OurWeb\Program.cs:line 11
```

A couple of highlights from the website's deps.json file (if they help):
```
"runtimeTarget": {
	"name": ".NETFramework,Version=v4.7.2/win7-x86",
	"signature": "90686bc84d8f39dc437b1c58e0610e43da0506af"
},
"compilationOptions": {
	"defines": [
	  "TRACE",
	  "RELEASE",
	  "NETFRAMEWORK",
	  "NET472"
	],
	"languageVersion": "",
	"platform": "AnyCPU",
},
  "targets": {
    ".NETFramework,Version=v4.7.2": {
      "OURWeb/1.0.0": {
        "dependencies": {
          "Microsoft.ApplicationInsights.AspNetCore": "2.5.0",
          "Microsoft.AspNetCore": "2.1.3",

          "Microsoft.AspNetCore.DataProtection": "2.1.1",
          "Microsoft.AspNetCore.DataProtection.Abstractions": "2.1.1",

          "Microsoft.Win32.Registry": "4.5.0",

        },
	},
	"Microsoft.AspNetCore.DataProtection/2.1.1": {
		"dependencies": {
			"Microsoft.AspNetCore.Cryptography.Internal": "2.1.1",
			"Microsoft.AspNetCore.DataProtection.Abstractions": "2.1.1",
			"Microsoft.AspNetCore.Hosting.Abstractions": "2.1.1",
			"Microsoft.Extensions.DependencyInjection.Abstractions": "2.1.1",
			"Microsoft.Extensions.Logging.Abstractions": "2.1.1",
			"Microsoft.Extensions.Options": "2.1.1",
			"Microsoft.Win32.Registry": "4.5.0",
			"System.Security.Cryptography.Xml": "4.5.0",
			"System.Security.Principal.Windows": "4.5.0"
		},
		"compile": {
			"lib/netstandard2.0/Microsoft.AspNetCore.DataProtection.dll": {}
		}
	},
```

In the OurWeb.deps.json file there is no mention of Microsoft.Win32.RegistryKey 4.1.1.0. From everything I have researched, Microsoft.AspNetCore.DataProtection 2.1.1 requires Microsoft.Win32.RegistryKey 4.5.0 - yet crashes saying it can't find v 4.1.1

And finally dotnet --info:
```
C:\>dotnet --info

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by AdamSchumph** [comment]
I was able to resolve the issue by installing ASP.Net Core 2.1.4 Runtime & Hosting Bundle on the server. While I cannot confirm exactly what the issue was, I suspect it was incompatible versioning between my dev environment and the hosting environment.
