### ISSUE TITLE
Test failure: FrameworkNotFoundExceptionLogged_File

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3767]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=585637&buildTypeId=XPlat_Windows_Win7_Universe) with the following error:

```
System.AggregateException : One or more errors occurred. (Unable to find non-empty debug log files. Tried: C:\BuildAgent\temp\buildTmp\tmp72C2.tmp, aspnetcore-debug.log) (Operation did not succeed after 288 retries (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than one element) (Sequence contains more than on
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by Eilon** [comment]
Seeing errors like this:

```
[15:06:27]F:			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken] System.AggregateException : An error occurred while writing to logger(s).
---- System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
[15:06:27]F:			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken]    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 168
   at Microsoft.AspNetCore.Testing.CompositeKestrelTrace.NotAllConnectionsClosedGracefully() in /_/test/shared/CompositeKestrelTrace.cs:line 99
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StopAsync>d__22.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StopAsync>d__22.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Kestrel.Core/KestrelServer.cs:line 221
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.Dispose() in /_/test/shared/TransportTestHelpers/TestServer.cs:line 129
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken>d__6.MoveNext() in /_/test/Kestrel.Transport.FunctionalTests/ResponseTests.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 69
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
```

```
| [34.642s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests Debug: Some connections failed to close gracefully during server shutdown.
| [34.644s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests Debug: Server shutdown exception
| System.AggregateException: An error occurred while writing to logger(s). ---> System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
|    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 69
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    --- End of inner exception stack trace ---
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
|    at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 168
|    at Microsoft.AspNetCore.Testing.CompositeKestrelTrace.NotAllConnectionsClosedGracefully() in /_/test/shared/CompositeKestrelTrace.cs:line 99
|    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StopAsync>d__22.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 210
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StopAsync>d__31.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
| ---> (Inner Exception #0) System.Exception: Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
|    at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 69
|    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)<---
| [34.663s] TestLifetime Information: Finished test WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken-http://127.0.0.1:0 in 34.641253s
[15:06:27]F:			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken] System.AggregateException : An error occurred while writing to logger(s).
---- System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. 
[15:06:27]F:			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken]    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Kestrel.Core/Internal/Infrastructure/KestrelTrace.cs:line 168
   at Microsoft.AspNetCore.Testing.CompositeKestrelTrace.NotAllConnectionsClosedGracefully() in /_/test/shared/CompositeKestrelTrace.cs:line 99
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StopAsync>d__22.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StopAsync>d__22.MoveNext() in /_/src/Kestrel.Core/KestrelServer.cs:line 176
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Kestrel.Core/KestrelServer.cs:line 221
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.Dispose() in /_/test/shared/TransportTestHelpers/TestServer.cs:line 129
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken>d__6.MoveNext() in /_/test/Kestrel.Transport.FunctionalTests/ResponseTests.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/test/shared/TestApplicationErrorLogger.cs:line 69
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
[15:06:27]i:		 [VSTest] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.RemoteIPv4Address
[15:06:27]i:			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.RemoteIPv4Address] [Test Output]
| [0.001s] TestLifetime Information: Starting test RemoteIPv4Address at 2018-10-30T22:04:45
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.003s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHUMDNJK881" started.
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:57857/  
| [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHUMDNJK881" completed keep alive response.
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.3602ms 200 
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.004s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLHUMDNJK881" received FIN.
| [0.004s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLHUMDNJK881" sending FIN because: "The client closed the connection."
| [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHUMDNJK881" disconnecting.
| [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHUMDNJK881" stopped.
| [0.005s] TestLifetime Information: Finished test RemoteIPv4Address in 0.0033155s
[15:06:27]i:		 [VSTest] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.IgnoreNullHeaderValues
[15:06:27]i:			 [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.IgnoreNullHeaderValues] [Test Output]
| [0.000s] TestLifetime Information: Starting test IgnoreNullHeaderValues-Location-- at 2018-10-30T22:04:49
| [0.001s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.001s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.001s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
```

@muratg can you assign?

**Comment by muratg** [comment]
@Tratcher could you take a look please?

**Comment by Tratcher** [comment]
https://github.com/aspnet/KestrelHttpServer/pull/3066 has already fixed these.

**Comment by Tratcher** [comment]
@HaoK @pakrym did you get the Identity Logging issues fixed as well?

@pakrym Is that IIS test failure related?

**Comment by jkotalik** [comment]
This looks IIS related.
