### ISSUE TITLE
Test failure: StartsWithWebConfigVariationsPortable

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3895]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests.StartsWithWebConfigVariationsPortable(String scenario) in /_/test/Common.FunctionalTests/Inprocess/StartupTests.cs:line 360
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.002s] TestLifetime Information: Starting test StartsWithWebConfigVariationsPortable-App in bin subdirectory full path to dll at 2018-11-06T10:09:11
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes\unix\lib\netcoreapp2.0
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes\unix\lib
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes\unix
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes\win\lib\netcoreapp2.0
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes\win\lib
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes\win
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\runtimes
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc\wwwroot
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\e898b8effc3b4449bc08875786ea7fdc
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.022s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.024s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.dll
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.exe
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.pdb
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.044s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.050s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.Extensions.Configuratio
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)
