### ISSUE TITLE
Test failure: StartsWithDotnetOnThePath

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3898]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Hello World
Actual:   <!DOCTYPE html>\r\n<html lang="en-US" xmlns···
          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.AssertStarts(IISDeploymentResult deploymentResult, String path) in /_/test/Common.FunctionalTests/Utilities/Helpers.cs:line 44
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests.StartsWithDotnetOnThePath(String path) in /_/test/Common.FunctionalTests/Inprocess/StartupTests.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test StartsWithDotnetOnThePath-dotnet at 2018-11-06T10:09:09
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes\unix\lib\netcoreapp2.0
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes\unix\lib
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes\unix
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes\win\lib\netcoreapp2.0
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes\win\lib
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes\win
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\runtimes
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c\wwwroot
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\71435cfd89c84e45b2e284bf91b9336c
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.dll
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.exe
| [0.025s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.pdb
| [0.027s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.045s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Mi
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- StartsWithDotnetLocationWithoutExe
