### ISSUE TITLE
Test failure: LargeResponseBodyTest_CheckAllResponseBodyBytesWritten

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3908]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LargeResponseBodyTests.LargeResponseBodyTest_CheckAllResponseBodyBytesWritten(Int32 query) in /_/test/Common.FunctionalTests/Inprocess/LargeResponseBodyTests.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 68 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- ConfigurationChangeForcesChildProcessRestart
- TestInvalidReadOperations
- TestInvalidReadOperations
- LargeResponseBodyTest_CheckAllResponseBodyBytesWritten
- EnvVarInWebConfig_Valid
- TestInvalidWriteOperations
- StartsWithWebConfigVariationsPortable
- LargeResponseBodyTest_CheckAllResponseBodyBytesWritten
- StartsWithWebConfigVariationsPortable
- LargeResponseBodyTest_CheckAllResponseBodyBytesWritten
- (And 58 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 75 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- TestInvalidReadOperations
- TestInvalidReadOperations
- TestValidReadOperations
- LargeResponseBodyTest_CheckAllResponseBodyBytesWritten
- TestInvalidWriteOperations
- LargeResponseBodyTest_CheckAllResponseBodyBytesWritten
- StartsWithWebConfigVariationsPortable
- StartsWithWebConfigVariationsPortable
- TestInvalidReadOperations
- TestInvalidReadOperations
- (And 65 more test failures in this build)
