### ISSUE TITLE
Test failure: CheckStdoutWithLargeWrites_TestSink

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3910]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
Assert.Equal() Failure
Expected: InternalServerError
Actual:   OK
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.AssertFailsToStart(IISDeploymentResult deploymentResult) in /_/test/Common.FunctionalTests/Inprocess/StartupExceptionTests.cs:line 81
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites_TestSink(String mode) in /_/test/Common.FunctionalTests/Inprocess/StartupExceptionTests.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test CheckStdoutWithLargeWrites_TestSink-CheckOversizedStdOutWrites at 2018-11-06T10:08:52
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes\unix\lib\netcoreapp2.0
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes\unix\lib
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes\unix
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes\win\lib\netcoreapp2.0
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes\win\lib
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes\win
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\runtimes
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff\wwwroot
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\d29502da76024d5ba99da865fc786eff
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.022s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.dll
| [0.024s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.exe
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.pdb
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.044s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.045s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Mi
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 24 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- CheckStdoutWithLargeWrites_LogFile
- CheckStdoutWithLargeWrites_TestSink
- CustomErrorCodeWorks
- LogsStartupExceptionExitError
- CustomErrorCodeWorks
- LogsUnexpectedThreadExitError
- CheckStdoutWithLargeWrites_LogFile
- CheckUnicodePipe
- DetectsOverriddenServer
- StartupStress
- (And 14 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 27 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- StartupStress
- IncludesAdditionalErrorPageTextInProcessStartupFailure_CorrectString
- CustomErrorCodeWorks
- CustomErrorCodeWorks
- CheckStdoutWithLargeWrites_TestSink
- CustomErrorCodeWorks
- CheckStdoutWithLargeWrites_LogFile
- CheckStdoutWithLargeWrites_LogFile
- CustomErrorCodeWorks
- CheckStdoutWithLargeWrites_TestSink
- (And 17 more test failures in this build)
