### ISSUE TITLE
Test failure: ShutdownTimeoutIsApplied

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3911]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
No entries matched by 'Failed to gracefully shutdown application 'MACHINE/WEBROOT/APPHOST/.*?'.'
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.AssertSingleEntry(String regexString, IEnumerable`1 entries) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 68
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.VerifyEventLogEvents(IISDeploymentResult deploymentResult, String[] expectedRegexMatchString) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 52
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests.ShutdownTimeoutIsApplied() in /_/test/Common.FunctionalTests/Inprocess/StartupTests.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ShutdownTimeoutIsApplied at 2018-11-06T10:09:59
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes\unix\lib\netcoreapp2.0
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes\unix\lib
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes\unix
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes\win\lib\netcoreapp2.0
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes\win\lib
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes\win
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\runtimes
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee\wwwroot
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\19d1986cda9344f1a7286028fc5e22ee
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.027s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.dll
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.exe
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.pdb
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.041s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.050s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.052s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.054s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.054s] Mi
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 2 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- ShutdownTimeoutIsApplied
- ShutdownTimeoutIsApplied

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 3 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- ShutdownTimeoutIsApplied
- ShutdownTimeoutIsApplied
- ShutdownTimeoutIsApplied
