### ISSUE TITLE
Test failure: GlobalVersion_EnvironmentVariableWorks

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3912]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.UnauthorizedAccessException : Access to the path 'C:\BuildAgent\temp\buildTmp\tmpEEFA.tmp' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.GlobalVersionTests.GlobalVersion_EnvironmentVariableWorks() in /_/test/Common.FunctionalTests/OutOfProcess/GlobalVersionTests.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test GlobalVersion_EnvironmentVariableWorks at 2018-11-06T10:12:33
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes\unix\lib\netcoreapp2.0
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes\unix\lib
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes\unix
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes\win\lib\netcoreapp2.0
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes\win\lib
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes\win
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\runtimes
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f\wwwroot
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\003bf3d7ed83429a82f03b077191c67f
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.016s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.021s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.022s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.025s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.027s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.HttpOverrides.dll
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.pdb
| [0.041s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.xml
| [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Core.dll
| [0.044s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.dll
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Https.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
| [0.050s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.050s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.Extensions.Configuration.Abstractions.dll
| [0.053s] Microsoft.A
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588632&buildTypeId=XPlat_Windows_Win7_Universe) on master at 1:31:38 AM:
- GlobalVersion_EnvironmentVariableWorks
