### ISSUE TITLE
Test failure: AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3914]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.InvalidOperationException : Didn't get response that satisfies predicate after 10 retries
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.RetryRequestAsync(HttpClient client, String uri, Func`2 predicate) in /_/test/Common.FunctionalTests/Utilities/Helpers.cs:line 123
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AssertRunning(IISDeploymentResult deploymentResult) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 267
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks(HostingModel hostingModel) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks-InProcess at 2018-11-06T10:13:46
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes\unix\lib\netcoreapp2.0
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes\unix\lib
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes\unix
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes\win\lib\netcoreapp2.0
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes\win\lib
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes\win
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\runtimes
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5\wwwroot
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying static.txt
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\7600e1bb836e427ea7557cc80c0f7cb5
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.027s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.dll
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.exe
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.pdb
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.041s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.050s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.052s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.053s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.054s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.Abstractions.d
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
