### ISSUE TITLE
Test failure: AppOfflineAddedAndRemovedStress

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3916]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.InvalidOperationException : Didn't get response that satisfies predicate after 10 retries
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.RetryRequestAsync(HttpClient client, String uri, Func`2 predicate) in /_/test/Common.FunctionalTests/Utilities/Helpers.cs:line 123
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AssertRunning(IISDeploymentResult deploymentResult) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 267
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AssertStarts(HostingModel hostingModel) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 262
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineAddedAndRemovedStress(HostingModel hostingModel) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test AppOfflineAddedAndRemovedStress-OutOfProcess at 2018-11-06T10:05:38
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes\unix\lib\netcoreapp2.0
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes\unix\lib
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes\unix
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes\win\lib\netcoreapp2.0
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes\win\lib
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes\win
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\runtimes
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12\wwwroot
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\261c79750ad448de8e4adeb375e37c12
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.018s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.020s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.021s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.024s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.025s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.HttpOverrides.dll
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.dll
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.pdb
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.xml
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Core.dll
| [0.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.dll
| [0.041s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Https.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
| [0.044s] Microsof
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 13 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- AppOfflineAddedAndRemovedStress
- RequestAbortedTokenFires
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
- ClientDisconnectCallbackStress
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_InProcess
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_InProcess
- RequestAbortedTokenFires
- ClientDisconnectCallbackStress
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
- (And 3 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 17 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
- AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks
- AppOfflineAddedAndRemovedStress
- AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks
- AppOfflineAddedAndRemovedStress
- RequestAbortedTokenFires
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
- ClientDisconnectCallbackStress
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_InProcess
- AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
- (And 7 more test failures in this build)
