### ISSUE TITLE
Test failure: StartupMessagesAreLoggedIntoDefaultDebugLogFile

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3921]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests.AssertLogs(String logPath) in /_/test/Common.FunctionalTests/LogFileTests.cs:line 238
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests.StartupMessagesAreLoggedIntoDefaultDebugLogFile(TestVariant variant) in /_/test/Common.FunctionalTests/LogFileTests.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test StartupMessagesAreLoggedIntoDefaultDebugLogFile-Server: IIS, TFM: netcoreapp2.2, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess at 2018-11-06T10:21:25
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes\unix\lib\netcoreapp2.0
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes\unix\lib
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes\unix
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes\win\lib\netcoreapp2.0
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes\win\lib
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes\win
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\runtimes
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0\wwwroot
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying static.txt
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\9551f613d0dc4d06898ad933993e1cd0
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.024s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.dll
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.exe
| [0.027s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.pdb
| [0.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.044s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.052s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.052s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.Abstractions.dll
| [0.052s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.Binder.dll
| [0.058s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer De
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 3 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588632&buildTypeId=XPlat_Windows_Win7_Universe) on master at 1:31:38 AM:
- Gets500_30_ErrorPage
- StartupMessagesAreLoggedIntoDebugLogFile
- StartupMessagesAreLoggedIntoDefaultDebugLogFile

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 5 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- Gets500_30_ErrorPage
- StartupMessagesAreLoggedIntoDebugLogFile
- StartupMessagesAreLoggedIntoDefaultDebugLogFileWhenEnabledWithEnvVar
- StartupMessagesAreLoggedIntoDefaultDebugLogFile
- StartupMessagesLogFileSwitchedWhenLogFilePresentInWebConfig
