### ISSUE TITLE
Test failure: ReadSetHeaderWrite

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3925]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.InvalidOperationException : The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.SynchronousReadAndWriteTests.ReadSetHeaderWrite() in /_/test/Common.FunctionalTests/Inprocess/SynchronousReadAndWriteTests.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ReadSetHeaderWrite at 2018-11-06T10:13:19
| [0.004s] FIXTURE:HttpTestSite Debug: Method: POST, RequestUri: 'http://localhost:49907/SetHeaderFromBody', Version: 2.0, Content: System.Net.Http.StringContent, Headers:
|                                      {
|                                        Content-Type: text/plain; charset=utf-8
|                                      }
| [0.005s] FIXTURE:HttpTestSite Warning: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                        {
|                                          Server: Microsoft-IIS/7.5
|                                          Date: Tue, 06 Nov 2018 10:13:18 GMT
|                                          Content-Type: text/html
|                                          Content-Length: 2549
|                                        }
| [0.005s] FIXTURE:HttpTestSite Warning: <!DOCTYPE html>
|                                        <html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
|                                            <head>
|                                                <meta charset="utf-8" />
|                                                <title> HTTP Error 500.0 - ANCM In-Process Handler Load Failure </title>
|                                                <style>
|                                                    body {
|                                                        font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
|                                                        font-size: .813em;
|                                                        color: #222;
|                                                        background-color: #fff;
|                                                    }
|                                                    h1, h2, h3, h4, h5 {
|                                                        /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
|                                                        font-weight: 100;
|                                                    }
|                                                    h1 {
|                                                        color: #44525e;
|                                                        margin: 15px 0 15px 0;
|                                                    }
|                                                    h2 {
|                                                        margin: 10px 5px 0 0;
|                                                    }
|                                                    h3 {
|                                                        color: #363636;
|                                                        margin: 5px 5px 0 0;
|                                                    }
|                                                    code {
|                                                        font-family: Consolas, "Courier New", courier, monospace;
|                                                    }
|                                                    body .titleerror {
|                                                        padding: 3px 3px 6px 3px;
|                                                        display: block;
|                                                        font-size: 1.5em;
|                                                        font-weight: 100;
|                                                    }
|                                                    a {
|                                                        color: #1ba1e2;
|                                                        text-decoration: none;
|                                                    }
|                                                        a:hover {
|                                                            color: #13709e;
|                                                            text-decoration: underline;
|                                                        }
|                                                    li {
|                                                        margin: 5px;
|                                                    }
|                                                </style>
|                                            </head>
|                                            <body>
|                                                <h1> HTTP Error 500.0 - ANCM In-Process Handler Load Failure </h1>
|                                                <h2> Common causes of this issue: </h2>
|                                                <ul>
|                                                    <li> The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found. </li>
|                                                    <li> The in process request handler, Microsoft.AspNetCore.Server.IIS, was not referenced in the application. </li>
|                                                    <li> ANCM could not find dotnet. </li>
|                                                </ul>
|                                                <h2> Troubleshooting steps: </h2>
|                                                <ul>
|                                                    <li> Check the system event log for erro
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- ReadSetHeaderWrite
