### ISSUE TITLE
Test failure: CheckUnicodePipe

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3930]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
No entries matched by 'Application '/LM/W3SVC/1/ROOT' with physical root 'C:\\BuildAgent\\temp\\buildTmp\\a53f0b38dd834cacb2fc89f9031f7a43\\' hit unexpected managed background thread exit, exit code = '12'. Last 4KB characters of captured stdout and stderr logs:
(.*)彡⾔(.*)'
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.AssertSingleEntry(String regexString, IEnumerable`1 entries) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 68
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.VerifyEventLogEvent(IISDeploymentResult deploymentResult, String expectedRegexMatchString) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 24
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LogPipeTests.CheckUnicodePipe() in /_/test/Common.FunctionalTests/Inprocess/LogPipeTests.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test CheckUnicodePipe at 2018-11-06T10:17:37
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes\unix\lib\netcoreapp2.0
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes\unix\lib
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes\unix
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes\win\lib\netcoreapp2.0
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes\win\lib
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes\win
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\runtimes
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43\wwwroot
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying static.txt
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\a53f0b38dd834cacb2fc89f9031f7a43
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.dll
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.exe
| [0.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.pdb
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.041s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.044s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.045s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.052s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.054s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.055s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.056s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.057s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.058s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsof
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- CheckUnicodePipe
