### ISSUE TITLE
Test failure: StartupTimeoutIsApplied

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3933]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
No entries matched by 'Application '/LM/W3SVC/1/ROOT' with physical root 'C:\\BuildAgent\\temp\\buildTmp\\912c20e9003548979073b124ddcb4988\\' failed to load clr and managed application. Managed server didn't initialize after 1000 ms.'
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.AssertSingleEntry(String regexString, IEnumerable`1 entries) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 68
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.VerifyEventLogEvents(IISDeploymentResult deploymentResult, String[] expectedRegexMatchString) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 52
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests.StartupTimeoutIsApplied() in /_/test/Common.FunctionalTests/Inprocess/StartupTests.cs:line 261
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.002s] TestLifetime Information: Starting test StartupTimeoutIsApplied at 2018-11-06T10:46:25
| [0.020s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes\unix\lib\netcoreapp2.0
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes\unix\lib
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes\unix
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes\win\lib\netcoreapp2.0
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes\win\lib
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes\win
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\runtimes
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988\wwwroot
| [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying static.txt
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\912c20e9003548979073b124ddcb4988
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.055s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.057s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.dll
| [0.058s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.exe
| [0.060s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.pdb
| [0.061s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.062s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.064s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.065s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
| [0.066s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.069s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.070s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.071s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.072s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.077s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.078s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.079s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.ResponseCompression.dll
| [0.080s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.082s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.083s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.084s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.WebUtiliti
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588632&buildTypeId=XPlat_Windows_Win7_Universe) on master at 1:31:38 AM:
- StartupTimeoutIsApplied

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- StartupTimeoutIsApplied
