### ISSUE TITLE
Test failure: RunClientTests

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#3981]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=589601&buildTypeId=Releases_22xPublic_HighSierraOsxUniverse) with the following error:

```
System.TimeoutException : command '$npm test' timed out after 00:03:00.
   at FunctionalTests.ProcessManager.<>c__DisplayClass1_0.<RunProcessAsync>b__0(Task t) in /_/test/FunctionalTests/ProcessManager.cs:line 55
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at FunctionalTests.CorsMiddlewareFunctionalTests.RunClientTests() in /_/test/FunctionalTests/CorsMiddlewareFunctionalTest.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.023s] TestLifetime Information: Starting test RunClientTests at 2018-11-08T04:34:50
| [0.017s] TestLifetime Information: Starting test RunClientTests at 2018-11-08T04:34:50
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [0.046s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/CORS/samples/SampleDestination/bin/Release/netcoreapp2.2/SampleDestination.dll --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [0.050s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_CONTENTROOT=/Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/CORS/samples/SampleDestination
| [0.064s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 33033
| [1.992s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: SampleDestination.Startup[0]
| [1.992s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Setting up CORS middleware to allow clients on http://aspnetcis-Mini.guest.corp.microsoft.com:9001
| [2.232s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| [2.233s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/CORS/samples/SampleDestination/bin/Release/netcoreapp2.2
| [2.233s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://[::]:9000
| [2.235s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [2.243s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://[::]:9000/
| [2.250s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [2.251s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/CORS/samples/SampleOrigin/bin/Release/netcoreapp2.2/SampleOrigin.dll --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [2.251s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [2.251s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2.251s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_CONTENTROOT=/Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/CORS/samples/SampleOrigin
| [2.254s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 33034
| [3.936s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Hosting environment: Production
| [3.937s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Content root path: /Users/aspnetci/Documents/buildAgent/work/e37dd45d8cd1eaf4/modules/CORS/samples/SampleOrigin/bin/Release/netcoreapp2.2
| [3.937s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://[::]:9001
| [3.937s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://[::]:9002
| [3.937s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [3.937s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://[::]:9002/
| [180.603s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| [180.603s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 GET http://aspnetcis-mini.guest.corp.microsoft.com:9001/  
| [180.867s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCor
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC Eilon

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/3981
