### ISSUE TITLE
Enable EventLog by default for all unhandled errors in ASP.NET core apps hosted on Azure App Service

### ISSUE THREAD

**Issue by puneetg1983** [aspnet/AspNetCore#4131]
All azure app services have a lightweight Eventlog.xml file which contains Events emitted by apps. All the un-handled ASP.NET (classic) exceptions go to this file and this file resides in d:\home\logfiles\eventlog.xml

I realized that ASP.NET core has AddEventLog() method under Microsoft.Extensions.Logging.EventLog. I tried adding that nuget package to test app and loggerFactory.AddEventLog() method in my app and then threw an exception in my page like this

```
public class IndexModel : PageModel
    {
        public void OnGet()
        {
            throw new ApplicationException("Lets see if you got this somewhere");

        }
    }
```

and this got logged in our eventlog.xml like this which is cool enough

```
<Event>
        <System>
            <Provider Name="Application"/>
            <EventID>1</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2018-09-26T12:26:19Z"/>
            <EventRecordID>409387984</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF90A48C</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
An unhandled exception has occurred while executing the request.

System.ApplicationException: Lets see if you got this somewhere
   at TestEventLog.Pages.IndexModel.OnGet() in C:\Users\puneetg\source\repos\TestEventLog\TestEventLog\Pages\Index.cshtml.cs:line 14
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)</Data>
        </EventData>
    </Event>
```
The ASK is to have this enabled by default for LogLevel Error \ Warning (which ever catches the default errors) so that these errors get logged in the EventLog.xml file and people have something to look for in case they have no logging configured.

Azure App Services support team gets many asp.net core cases where the customers don't have any logging and this can enabled by default can be very useful.  If this is enabled, we will also be able to build some diagnostics on top of this as we are currently doing for classic ASP.NET

Wanted to throw this ask out to see if this can be a possibility.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by puneetg1983** [comment]
@mkArtakMSFT - I believe this is **implemented** already by @davidfowl
