### ISSUE TITLE
Sporadic issue on DataProtection while running on the CI

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#4167]
### Describe the bug
While investigating a build hang we discovered that the hang was being triggered by an sporadic exception happening inside data protection. See the callstack below for details. DataProtection wasn't causing the hang, but the exception triggered from it was causing it. While we have fixed the root cause of the hang, I suspect we'll see this issue surface as flaky tests in MVC.

```csharp
System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---&gt; System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()&#x2B;MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider.SaveTempData(HttpContext context, IDictionary`2 values) in /_/src/Microsoft.AspNetCore.Mvc.ViewFeatures/CookieTempDataProvider.cs:line 101
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TempDataDictionary.Save() in /_/src/Microsoft.AspNetCore.Mvc.ViewFeatures/TempDataDictionary.cs:line 166
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.SaveTempData(IActionResult result, ITempDataDictionaryFactory factory, IList`1 filters, HttpContext httpContext) in /_/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Filters/SaveTempDataFilter.cs:line 149
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter.&lt;&gt;c__DisplayClass3_0.&lt;OnResourceExecuting&gt;b__0(Object state) in /_/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Filters/SaveTempDataFilter.cs:line 66
   at Microsoft.AspNetCore.TestHost.ResponseFeature.&lt;&gt;c__DisplayClass24_0.&lt;&lt;OnStarting&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ResponseFeature.FireOnSendingHeadersAsync()
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.ReturnResponseMessageAsync()
   at Microsoft.AspNetCore.TestHost.ResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at BasicWebSite.Controllers.TempDataController.SetTempDataResponseWrite() in D:\a\1\s\test\WebSites\BasicWebSite\Controllers\TempDataController.cs:line 70
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult() in /_/.nuget/packages/microsoft.extensions.objectmethodexecutor.sources/3.0.0-preview-181106-14/contentFiles/cs/netstandard1.0/Microsoft.Extensions.ObjectMethodExecutor.Sources/ObjectMethodExecutorAwaitable.cs:line 87
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ActionMethodExecutor.cs:line 135
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync() in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ControllerActionInvoker.cs:line 357
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync() in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ControllerActionInvoker.cs:line 294
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContext context) in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ControllerActionInvoker.cs:line 402
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted) in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ControllerActionInvoker.cs:line 268
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ControllerActionInvoker.cs:line 384
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter() in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ResourceInvoker.cs:line 792
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContext context) in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ResourceInvoker.cs:line 1143
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted) in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ResourceInvoker.cs:line 745
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ResourceInvoker.cs:line 122
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync() in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/ResourceInvoker.cs:line 80
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

This was ASP.NET Core 3.0

**Comment by natemcmaster** [comment]
My hunch: there is a race condition with other tests using data protection. We need to update the key storage location for all test projects using dataprotection to avoid conficts between tests.

```c#
    services.AddDataProtection()
        .PersistKeysToFileSystem(new DirectoryInfo($"{AppContext.BaseDirectory}/tmp-keys/"));
```

**Comment by javiercn** [comment]
Isn't it a bug though? You could probably run into this just by using multiple threads, couldn't you?

**Comment by natemcmaster** [comment]
Sure, there might be a bug here to handle concurrent access on xml files, but that's not likely to be resolved easily. I think our tests should be updated because, as is, the tests have a dependency on machine state. Machine state is one of the enemies of reliable tests.

**Comment by javiercn** [comment]
@natemcmaster Agree, for that we can make the tests just use ephemeral keys tbh, but we probably want to figure out what's going on there as our customers might also be experiencing that.

**Comment by FlukeFan** [comment]
FYI,  I just got this:

https://ci.appveyor.com/project/FlukeFan/luciddotnet/builds/20763134

**Comment by BrennanConroy** [comment]
This should be fixed by https://github.com/aspnet/AspNetCore/pull/10990
