### ISSUE TITLE
Unable to use nswag generated C# client in Blazor server side.

### ISSUE THREAD

**Issue by iAmBipinPaul** [aspnet/AspNetCore#4360]
### Describe the bug
When injecting nswag generated c# client in `index.cshtml`  getting exception.

Registered services in `startup.cs`
 ```
services.AddSingleton<WeatherForecastService>();
            services.AddSingleton<HttpClient>();
            services.AddScoped<Client, Client>(); //nswag generated c# client
```
```
Microsoft.AspNetCore.SignalR.HubConnectionContext:Information: Completed connection handshake. Using HubProtocol 'messagepack'.
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Blazor.Server.BlazorHub:Warning: Unhandled Server-Side exception

System.InvalidOperationException: Unable to resolve service for type 'System.String' while attempting to activate 'BlazorServerSide.ServiceProxy.Client'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
```

After registering System.string as Singleton.
```
services.AddSingleton<System.String>();
            services.AddSingleton<WeatherForecastService>();
            services.AddSingleton<HttpClient>();
            services.AddScoped<Client, Client>();
```

```
Microsoft.AspNetCore.Blazor.Server.BlazorHub:Warning: Unhandled Server-Side exception

System.InvalidOperationException: No constructor for type 'System.String' can be instantiated using services from the service container and default values.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
```

Source code https://github.com/iAmBipinPaul/BlazorServerSide

## SDK 
 Version:   2.1.500
 Commit:    b68b931422

**Comment by rynowak** [comment]
I'm assuming your client code is here: https://github.com/iAmBipinPaul/BlazorServerSide/blob/master/src/BlazorServerSide.ServiceProxy/ServiceProxyClient.cs#L19

You will need to register a factory function to use this type with DI. It's trying to resolve a string from the DI container - which it won't be able to do. You need to provide the `baseUrl` to the constructor.

I would imagine it will looking something like this:

```
services.AddScoped<Client>(s => return new Client(baseUrl: null, s.GetRequiredService<HttpClient>());
```
