### ISSUE TITLE
Setting an invalid Transfer-Encoding response header sometimes kills the connection instead of responding with a 500 status

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#4382]
### Describe the bug

Setting a Transfer-Encoding response header which is invalid for a given request or response (e.g. 204/205/304 responses and HEAD requests) without manually writing to or flushing the response body kills the connection instead of responding with a 500 status code.

### To Reproduce
1. Targeting ASP.NET Core 2.2 (though this bug likely existed earlier), add the following middleware:

```C#
app.Run(context =>
{
    context.Response.StatusCode = 204;
    context.Response.Headers["Transfer-Encoding"] = "chunked";
    return Task.CompletedTask;
});
```
2. Run the app and test the endpoint by making a GET request. If you have a project reference to Kestrel.Core, make sure you run the app in release mode to avoid a Debug.Assert.
4. See a connection reset error.

### Expected behavior
A 500 response. This can be observed if you make a slight change to the above middleware to manually flush the response body:

```C#
app.Run(context =>
{
    context.Response.StatusCode = 204;
    context.Response.Headers["Transfer-Encoding"] = "chunked";
    return context.Response.Body.FlushAsync();
});
```

### Additional context
Here are what the server logs look like when this bug is hit:

```
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLIPIMQJ59NK" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLIPIMQJ59NL" started.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLIPIMQJ59NK", Request id "0HLIPIMQJ59NK:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Setting the header Transfer-Encoding is not allowed on responses with status code 204.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 1209
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 207
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.SetErrorResponseHeaders(Int32 statusCode) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 1245
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 1171
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceEndAwaited()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 597
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in C:\dev\aspnet\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 465
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLIPIMQJ59NK" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLIPIMQJ59NK" sending FIN because: "The Socket transport's send loop completed gracefully."
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
```

**Comment by muratg** [comment]
Related: https://github.com/aspnet/AspNetCore/issues/4388

**Comment by davidfowl** [comment]
@halter73 I assume this still repros?

**Comment by gfr-g** [comment]
I started working on this issue, doing some preliminary research.

The problem seems to be related to the fact that setting the `HttpProtocol.StatusCode` property when the flag `HasResponseStarted` is `true` is considered invalid. 
`HasResponseStarted` is true when the request processing is at the stage `RequestProcessingStatus.HeadersCommitted`.
The request processing status is set in the `HttpProtocol. ProduceStart` method.

Here is where I have some doubts about the semantic of `HeadersCommitted`. In the ProduceStart method, the stage is set before actually calling the `CreateResponseHeaders`. I didn't dig much further on why this is the case, but it seems somewhat unintuitive, would you mind detailing the semantic of these stages?

Following the intuition, I tried setting the stage **after** the call to `CreateResponseHeaders` and this seems to fix the issue (all the tests pass, but I'm not sure there's something specifically covering these cases, I will take a better look at everything of course).

**Comment by zeohhh** [comment]
I'd like to work on this issue.

I traced the current behavior to `HttpProtocol.ProduceStart(bool appCompleted)`. It marks the response as `HeadersCommitted` before calling `CreateResponseHeaders(appCompleted)`.

When the application completes without explicitly starting/flushing the response, an invalid `Transfer-Encoding` on a non-body response is detected inside `CreateResponseHeaders(true)`. `RejectInvalidResponse` then attempts to replace the response with a 500 via `SetErrorResponseHeaders`, but changing the status code fails because the response is already considered started.

My initial plan is to:

1. Add a functional regression test covering app completion without an explicit flush/start, verifying that invalid `Transfer-Encoding` on non-body responses results in a 500 response rather than terminating the connection.
2. Move the transition to `HeadersCommitted` until after response header creation/validation succeeds, while keeping it before `Output.WriteResponseHeaders`.
3. Verify the existing explicit `FlushAsync`/`StartAsync` error behavior remains unchanged.

I'll keep the change focused and include coverage for the relevant non-body response cases.
