### ISSUE TITLE
Microsoft.Aspnetcore ModelBinding throw Cannot access a closed Stream with .NET Core 2.1

### ISSUE THREAD

**Issue by HuUncle** [aspnet/AspNetCore#4543]
```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Micro.AspNetCore.Middleware.RequestHandlerMiddleware.Invoke(HttpContext context)
   at Micro.AspNetCore.Middleware.ErrorLogMiddleware.Invoke(HttpContext context)
```

When I using under code , modelbinding throw System.ObjectDisposedException: Cannot access a closed Stream exception。

```C#
var postRequest = new HttpRequestMessage(HttpMethod.Post, "/Supplier/Goods/SaveSpec");
            postRequest.Headers.Add("User-Agent", "csharp");
            postRequest.Headers.Add("Accept", "application/json, text/plain, */*");
            postRequest.Content = new StringContent(
                JsonConvert.SerializeObject(new GoodsSpecModel
                {
                    Name = "TestName",
                    Sort = 1
                }), Encoding.UTF8, "application/json");

            postRequest.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            var response = _fixture.Client.SendAsync(postRequest).Result;
            response.EnsureSuccessStatusCode();
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            var content = await response.Content.ReadAsStringAsync();
            Assert.NotEmpty(content);
```

**Comment by davidfowl** [comment]
What does the server side code look like?

PS: Why are you using .Result here:

```
var response = _fixture.Client.SendAsync(postRequest).Result;
```

Change this to await:

```
var response = await _fixture.Client.SendAsync(postRequest);
```

**Comment by HuUncle** [comment]
@davidfowl 
I was using this code 
`var response = await _fixture.Client.SendAsync(postRequest);`
but it's throw same exception , this is my full code。
The exception occur only in when I use xunit integrate tests

  ```
   public class StoreControllerTest : IClassFixture<TestServerFixture>
    {
        private readonly TestServerFixture _fixture;

        public StoreControllerTest(TestServerFixture fixture)
        {
            _fixture = fixture;
        }

        [Fact]
        public async Task SaveSpec()
        {
            var postRequest = new HttpRequestMessage(HttpMethod.Post, "/Supplier/Goods/SaveSpec");
            postRequest.Headers.Add("User-Agent", "csharp");
            postRequest.Headers.Add("Accept", "application/json, text/plain, */*");
            postRequest.Content = new StringContent(
                JsonConvert.SerializeObject(new GoodsSpecModel
                {
                    Name = "TestName",
                    Sort = 1
                }), Encoding.UTF8, "application/json");
            postRequest.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            var response = await _fixture.Client.SendAsync(postRequest);
            response.EnsureSuccessStatusCode();
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            var content = await response.Content.ReadAsStringAsync();
            Assert.NotEmpty(content);
        }
}
```

```
    public class TestServerFixture : IDisposable
    {
        private readonly TestServer _testServer;
        public readonly HttpClient Client;

        public TestServerFixture()
        {
            var builder = new WebHostBuilder()
                .UseEnvironment("Development")
                .UseStartup<Startup>();

            _testServer = new TestServer(builder);
            Client = _testServer.CreateClient();
        }

        public void Dispose()
        {
            Client?.Dispose();
            _testServer?.Dispose();
        }
    }
```

**Comment by HuUncle** [comment]
I find this exception caused by  I create custom LoggingProvider :
` loggerFactory.AddMicroLog(app, "Supplier.API");`

the custom logger seems like and the default log level  is Debug  :

```
 public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
        {
            if (!IsEnabled(logLevel)) return;

            string message = string.Empty;
            if (formatter != null)
            {
                message = formatter(state, exception);
            }

            var entry = new LogEntry
            {
                EventId = eventId,
                DateTime = DateTime.UtcNow,
                ProjectName = _projectName,
                Category = _categoryName,
                Message = message,
                Level = logLevel
            };

            var context = _httpContextAccessor.HttpContext;
            if (context != null)
            {
                entry.TraceIdentifier = context.TraceIdentifier;
                entry.UserName = context.User.Identity.Name;
                var request = context.Request;
                entry.ContentLength = request.ContentLength;
                entry.ContentType = request.ContentType;
                entry.Host = request.Host.Value;
                entry.IsHttps = request.IsHttps;
                entry.Method = request.Method;
                entry.Path = request.Path;
                entry.PathBase = request.PathBase;
                entry.Protocol = request.Protocol;
                entry.QueryString = request.QueryString.Value;
                entry.Scheme = request.Scheme;
                //entry.Cookies = request.Cookies;
                //entry.Headers = request.Headers;
            }

            if (exception != null)
            {
                entry.Exception = exception.ToString();
                entry.ExceptionMessage = exception.Message;
                entry.ExceptionType = exception.GetType().Name;
                entry.StackTrace = exception.StackTrace;
            }

            GetRequestBody(entry);

            _logStore.Post(entry);
        }


        private void GetRequestBody(LogEntry entry)
        {
            try
            {
                var context = _httpContextAccessor.HttpContext;
                if (context != null)
                {
                    if (context.Request?.Body.Length > 0)
                    {
                        _httpContextAccessor.HttpContext.Request.Body.Position = 0;
                        var body = string.Empty;
                        using (var reader = new StreamReader(context.Request.Body, Encoding.UTF8))
                        {
                            body = reader.ReadToEndAsync().Result;
                        }
                        entry.Body = body;
                    }
                }
            }
            catch
            {

            }
        }
```

**Comment by HuUncle** [comment]
@davidfowl   hello david,
I read these links and I used suggestion code , but it can't solve this problem 。

and  I use this code fix this problem 

```
if (context?.Request?.Body?.Length > 0)
{
    context.Request.Body.Seek(0, SeekOrigin.Begin);
    using (var reader = new StreamReader(context.Request.Body, Encoding.UTF8))
    {
        var body  = await reader.ReadToEndAsync();
        entry.Body = body;
        context.Request.Body.Seek(0, SeekOrigin.Begin);// again set stream position equals 0
    }
}
```

**Comment by mkArtakMSFT** [comment]
Closing as it seems you were able to resolve this.
