### ISSUE TITLE
Address problems loading `System.Threading` in dotnet-getdocument inside man

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#4915]
#### Is this a Bug or Feature request?
Bug that's part of #7947

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project)
1. download https://github.com/dougbu/CodeGeneration repo
2. install relevant tools and packages locally
3. `dotnet build` in repo's ClientConsole folder

##### Expected
Smooth build

##### Actual
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
     at System.Console.get_IsOutputRedirected()
     at Microsoft.Extensions.ApiDescription.Client.Program.Main(String[] args)
```

#### Description of the problem
Since builds from the root of the project work much better, it appears something goes awry when the ClientConsole project builds the p2p references. Need to see if, for example, the build from root builds the web site projects differently.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
See the features/client.code.generation branch branch. That work is intended for the 2.2 Preview 3 milestone.

**Comment by dougbu** [comment]
Closing because I have not seen this issue recently.
