### ISSUE TITLE
Crit: Microsoft.AspNetCore.Server.Kestrel.Unable to start Kestrel.

### ISSUE THREAD

**Issue by johnmelodyme** [aspnet/AspNetCore#4956]
First when I deploy the API to the localhost:5001, all work fine until I put everything together in the server. I did dotnet publish the project. before this I sudo scp - r the (all files) relevant project to the server's /home . dotnet build && dotnet run, and all work fine. I came to mind that that wasn't a good idea for uploading all files without compounding it. Then I did only upload the 'Publish' folder which had already a 'compound' . \
I'm planning to deploy in my server 

![asdas](https://user-images.githubusercontent.com/44691957/49983170-f9c12a80-ff9b-11e8-9f95-70287578287c.png)

```root@Ubuntu:/tmp/myserver/publish# ls
appsettings.Development.json  johnTestBO.deps.json  johnTestBO.pdb                 web.config
appsettings.json              johnTestBO.dll        johnTestBO.runtimeconfig.json
root@Ubuntu:/tmp/myserver/publish# ASPNETCORE_URLS=http://209.97.160.230:5001/api/value dotnet johnTestBO.dll
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at johnTestBO.Program.Main(String[] args) in /home/example/johnTestBO/Program.cs:line 18
Aborted (core dumped)
root@Ubuntu:/tmp/myserver/publish#

**Comment by SteveStrongBAH** [comment]
Right out of the box, I get this error on a unchanged aps.net core app  running docker .   what is going on?

**Comment by SteveStrongBAH** [comment]
![image](https://user-images.githubusercontent.com/19686538/50739802-0871ba80-11b3-11e9-97ec-37c1859871cc.png)

**Comment by anurse** [comment]
@SteveStrongBAH your error appears to be different (note it says "Address already in use" whereas the original says "A path base can only be configured using...". If you're still hitting this issue can you file a new issue? It sounds like something is binding to port 80 in your container already.

@johnmelodyme What are you trying to do with `ASPNETCORE_URLS` here? When hosting on Kestrel that value can only specify the root of the domain (`http://localhost:5001/` for example) and can't include path segments. If you want to strip off path segments for things like routing, you can use the [PathBase middleware](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.usepathbaseextensions.usepathbase?view=aspnetcore-2.2).

**Comment by anurse** [comment]
@johnmelodyme You can also use the [`Map` middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1#use-run-and-map) to create "sub apps" that run at a specific path in your app.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
