### ISSUE TITLE
app.UseWebpackDevMiddleware throw error

### ISSUE THREAD

**Issue by martonx** [aspnet/AspNetCore#5185]
At app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions { HotModuleReplacement = true });

I got this error after npm package updated from 2.0.3 to 3.0.0 and my Asp.Net Core app updated from 2.0 to 2.1.

NodeInvocationException: Error: Cannot find module 'webpack-dev-middleware'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at attachWebpackDevMiddleware (C:\work\Traveller\Traveller.Web.Portal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:72:13)
    at C:\work\Traveller\Traveller.Web.Portal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:271:25
    at Array.forEach (<anonymous>)
    at Server.<anonymous> (C:\work\Traveller\Traveller.Web.Portal\node_modules\aspnet-webpack\WebpackDevMiddleware.js:234:36)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1394:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by mkArtakMSFT** [comment]
We're closing this issue as it seems the issue has been resolved. Thanks @mattvperry!
