### ISSUE TITLE
ASP.NET Core 2.1 fails with react / CRA template on start

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#5217]
_From @ajensenwaud on May 25, 2018 11:19_

I created a new ASP.NET Core 2.1 app (on Linux x64 / Ubuntu) and am now trying to get it to work in Development mode. I used the react / CRA template following this guide: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore2x

I got the following error when startintg:

```
aj@kennedy ~/romp $ export ASPNETCORE_ENVIRONMENT=Development
aj@kennedy ~/romp $ dotnet run                               
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/home/aj/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Microsoft.AspNetCore.SpaServices[0]
      Starting create-react-app server on port 41269...
Hosting environment: Development
Content root path: /home/aj/romp
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.SpaServices[0]
      > romp@0.1.0 start /home/aj/romp/ClientApp
      > rimraf ./build && react-scripts start
      
      Starting the development server...
      
fail: Microsoft.AspNetCore.SpaServices[0]
      events.js:165
      
npmfail: Microsoft.AspNetCore.SpaServices[0]
            throw er; // Unhandled 'error' event
            ^
      
      Error: watch /home/aj/romp/ClientApp/public ENOSPC
          at FSWatcher.start (fs.js:1402:19)
          at Object.fs.watch (fs.js:1428:11)
          at createFsWatchInstance (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:37:15)
          at setFsWatchListener (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
          at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:228:14)
          at FSWatcher.NodeFsHandler._handleDir (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:407:19)
          at FSWatcher.<anonymous> (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:455:19)
          at FSWatcher.<anonymous> (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:460:16)
          at FSReqWrap.oncomplete (fs.js:171:5)
      Emitted 'error' event at:
          at FSWatcher._handleError (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/index.js:257:10)
          at createFsWatchInstance (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:39:5)
          at setFsWatchListener (/home/aj/romp/ClientApp/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:80:15)
          [... lines matching original stack trace ...]
          at FSReqWrap.oncomplete (fs.js:171:5)
      npm ERR! code ELIFECYCLE
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! errno 1
      
npmfail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! romp@0.1.0 start: `rimraf ./build && react-scripts start`
      
npm ERR!fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! Exit status 1
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! 
      npm ERR! Failed at the romp@0.1.0 start script.
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
      
fail: Microsoft.AspNetCore.SpaServices[0]
      npm ERR! A complete log of this run can be found in:
      
^CApplication is shutting down...```

OK, fine, so rimraf and react-scripts npms were missing. I installed them manually + globally using npm 
install rimraf react-scripts --global

Issue persisted. 

I then read somewhere there is a potential issue with number of open filehandles on Linux. The following helped: 
```aj@kennedy ~/romp $ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p```

And then it appears to compile + react the React midldleware. Is there an issue on Linux? 




_Copied from original issue: dotnet/core#1594_

**Comment by WereDev** [comment]
Found on the previous thread as well was this tidbit (missed it on my first read through).  It did seem to help.

> @ajensenwaud +1
> 
> > I then read somewhere there is a potential issue with number of open filehandles on Linux. The following helped:
> > $ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

Thinking that 524288 is likely excessive (not sure how many watchers a system really needs) I did some additional digging.  Ubuntu (and likely other linux distros) have a default of 8192.  I doubled this with the above command to 16384 and dotnet run worked like a charm.  Not sure what dotnet is trying to all watch as I definitely don't have that many files in my app.  Only think I can think of is that it's trying to watch node_modules as well which seems excessive.

For others who are looking into this. be careful if you run that command (or run it multiple times) as it's adding a line to /etc/sysctl.conf so you could be adding duplicates with different values.  I definitely had to do some clean up after running through some tests on my system.
