### ISSUE TITLE
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException : Cannot find module

### ISSUE THREAD

**Issue by thiagomajesk** [aspnet/AspNetCore#5219]
Hi, I just began experimenting with the NodeServices lib and I'm getting the following error:

My goal here is to create a less transpiler that can be called from other projects. 
I'm using a test project as entry point to test the functionality, but I don't know what is wrong (I could guess something related to the paths, but I don't know what is the expected behavior).

**`dotnet test` result:**

```
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException : Cannot find module 'C:\Users\usr\Source\Repos\Packer\Packer.Test\Fixtures\app\var less = require('less');

module.exports = function (result, input) {
    var options = {};
    less.render(input, options, function (error, output) {
        result.stream = output;
    });
}'
Error: Cannot find module 'C:\Users\usr\Source\Repos\Packer\Packer.Test\Fixtures\app\var less = require('less');

module.exports = function (result, input) {
    var options = {};
    less.render(input, options, function (error, output) {
        result.stream = output;
    });
}'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at C:\Users\usr\AppData\Local\Temp\potjf3xy.4jb:109:34
    at IncomingMessage.<anonymous> (C:\Users\usr\AppData\Local\Temp\potjf3xy.4jb:133:38)
    at IncomingMessage.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Rastreamento de pilha:
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   at Packer.Core.Recipes.LessTranspiler.RunAsyn(String publicRoot, String projectRoot) in C:\Users\usr\Source\Repos\Packer\Packer.Core\Recipes\LessTranspiler.cs:line 22
   at Packer.Test.Recipes.LessTranspilerTest.Should_Transpile_Less_Manifest() in C:\Users\usr\Source\Repos\Packer\Packer.Test\Recipes\LessTranspilerTest.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
```

I have this minimal repro here: [Packer.zip](https://github.com/aspnet/JavaScriptServices/files/2190101/Packer.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as this doesn't align with our long-term plans in this area. You can read more details about our vision for this area at https://github.com/aspnet/AspNetCore/issues/12890.
