### ISSUE TITLE
import not working in NodeServices

### ISSUE THREAD

**Issue by andrewb273** [aspnet/AspNetCore#5270]
I'm using `Microsoft.AspNetCore.NodeServices v2.1.1` to call a js script from c#, and I'm able to do that successfully, but when I change
```
var React = require('react');
```
to
```
import React from 'react';
```
I get an exception:

```
NodeInvocationException: Unexpected token import
[...]/Scripts/Render.js:2
import React from 'react';
^^^^^^

SyntaxError: Unexpected token import
at createScript (vm.js:74:10)
at Object.runInThisContext (vm.js:116:10)
at Module._compile (module.js:533:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at /private/var/folders/sv/fh862tvn1mb0hy3h71x3y4_c0000gn/T/kcwjl1il.fmt:109:34
```

Are `import` & `export` ES6 features not supported?

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
