### ISSUE TITLE
Flaky test: ServerThrowsHubExceptionIfHubMethodCannotBeResolved

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5378]
```
2018-11-07T01:14:17.6673524Z   Failed   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionIfHubMethodCannotBeResolved(hubProtocolName: "json", transportType: ServerSentEvents, hubPath: "/hubT")
2018-11-07T01:14:17.7696292Z   Error Message:
2018-11-07T01:14:17.8599913Z    System.Exception : 1 error(s) logged.
2018-11-07T01:14:17.8604620Z   Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests - 0 - System.TimeoutException from test
2018-11-07T01:14:17.9082298Z   ===================
2018-11-07T01:14:17.9084668Z   System.TimeoutException: Operation in ServerThrowsHubExceptionIfHubMethodCannotBeResolved timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:477
2018-11-07T01:14:17.9085040Z      at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 38
2018-11-07T01:14:17.9085688Z      at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionIfHubMethodCannotBeResolved(String hubProtocolName, HttpTransportType transportType, String hubPath) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 477
2018-11-07T01:14:17.9085957Z      at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionIfHubMethodCannotBeResolved(String hubProtocolName, HttpTransportType transportType, String hubPath) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 490
2018-11-07T01:14:17.9086213Z   ===================
2018-11-07T01:14:17.9086418Z   Stack Trace:
2018-11-07T01:14:17.9086622Z      at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/VerifyNoErrorsScope.cs:line 65
2018-11-07T01:14:17.9087002Z      at Microsoft.AspNetCore.SignalR.Tests.FunctionalTestBase.MultiDisposable.Dispose() in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/FunctionalTestBase.cs:line 67
2018-11-07T01:14:17.9087707Z      at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionIfHubMethodCannotBeResolved(String hubProtocolName, HttpTransportType transportType, String hubPath) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 491
2018-11-07T01:14:17.9088030Z   --- End of stack trace from previous location where exception was thrown ---
2018-11-07T01:14:17.9088244Z   Standard Output Messages:
2018-11-07T01:14:17.9088501Z    | [0.001s] TestLifetime Information: Starting test ServerThrowsHubExceptionIfHubMethodCannotBeResolved-json-ServerSentEvents-/hubT at 2018-11-07T01:14:03
2018-11-07T01:14:17.9088765Z    | [0.000s] TestLifetime Information: Starting test ServerThrowsHubExceptionIfHubMethodCannotBeResolved_json_ServerSentEvents_hubT at 2018-11-07T01:14:03
2018-11-07T01:14:17.9089018Z    | [0.002s] Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer Information: Starting test server...
2018-11-07T01:14:17.9089272Z    | [0.008s] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager Information: User profile is available. Using 'C:\Users\VssAdministrator\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
2018-11-07T01:14:17.9089545Z    | [0.042s] Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer Information: Test Server started
2018-11-07T01:14:17.9089793Z    | [2.539s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:1951/hubT/negotiate  0
2018-11-07T01:14:17.9090051Z    | [2.540s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1.443ms 200 application/json
2018-11-07T01:14:17.9090305Z    | [5.472s] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Information: DRAtsB9HHWP-FBwzHVmjEw - Starting transport. Transfer mode: Text.
2018-11-07T01:14:17.9090787Z    | [5.473s] Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests Error: System.TimeoutException from test
2018-11-07T01:14:17.9091000Z    | System.TimeoutException: Operation in ServerThrowsHubExceptionIfHubMethodCannotBeResolved timed out at /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:477
2018-11-07T01:14:17.9091537Z    |    at System.Threading.Tasks.TaskExtensions.OrTimeout(Task task, TimeSpan timeout, String memberName, String filePath, Nullable`1 lineNumber) in /_/test/Microsoft.AspNetCore.SignalR.Tests.Utils/TaskExtensions.cs:line 38
2018-11-07T01:14:17.9092054Z    |    at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionIfHubMethodCannotBeResolved(String hubProtocolName, HttpTransportType transportType, String hubPath) in /_/test/Microsoft.AspNetCore.SignalR.Client.FunctionalTests/HubConnectionTests.cs:line 477
2018-11-07T01:14:17.9092441Z    | [5.476s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://127.0.0.1:1951/hubT?id=DRAtsB9HHWP-FBwzHVmjEw  
2018-11-07T01:14:17.9092757Z    | [5.554s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: DRAtsB9HHWP-FBwzHVmjEw - HttpConnection Started.
2018-11-07T01:14:17.9092929Z    | [5.554s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: DRAtsB9HHWP-FBwzHVmjEw - Using HubProtocol 'json v1'.
2018-11-07T01:14:17.9093126Z    | [5.560s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://127.0.0.1:1951/hubT?id=DRAtsB9HHWP-FBwzHVmjEw  32
2018-11-07T01:14:17.9093284Z    | [5.560s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.3107ms 200 text/plain
2018-11-07T01:14:17.9093477Z    | [5.560s] Microsoft.AspNetCore.SignalR.HubConnectionContext Information: DRAtsB9HHWP-FBwzHVmjEw - DRAtsB9HHWP-FBwzHVmjEw - Completed connection handshake. Using HubProtocol 'json'.
2018-11-07T01:14:17.9093637Z    | [5.561s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: DRAtsB9HHWP-FBwzHVmjEw - HubConnection started.
2018-11-07T01:14:17.9093817Z    | [5.561s] Microsoft.AspNetCore.Http.Connections.Client.Internal.ServerSentEventsTransport Information: DRAtsB9HHWP-FBwzHVmjEw - Transport is stopping.
2018-11-07T01:14:17.9094105Z    | [5.562s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: DRAtsB9HHWP-FBwzHVmjEw - HttpConnection Disposed.
2018-11-07T01:14:17.9094274Z    | [5.562s] Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer Information: Shutting down test server
2018-11-07T01:14:17.9094456Z    | [5.564s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 88.099ms 200 text/event-stream
2018-11-07T01:14:17.9094743Z    | [5.564s] Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer Information: Test server shut down
2018-11-07T01:14:17.9094930Z    | [5.564s] TestLifetime Information: Finished test ServerThrowsHubExceptionIfHubMethodCannotBeResolved_json_ServerSentEvents_hubT in 5.5634203s
2018-11-07T01:14:17.9095104Z    | [5.733s] TestLifetime Information: Finished test ServerThrowsHubExceptionIfHubMethodCannotBeResolved-json-ServerSentEvents-/hubT in 5.7320045s
```

Flaked out in https://dnceng.visualstudio.com/public/_build/results?buildId=40811&view=logs

**Comment by ryanbrandenburg** [comment]
Assigning to @muratg to triage out.
