### ISSUE TITLE
Test failure: MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetCore#5428]
This test [fails](http://aspnetci/viewLog.html?buildId=528510&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Exception : Process exited with code 1
StdErr: 
StdOut: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\u001d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\u001d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\u001d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj]
Build FAILED.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\u001d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\u001d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\u001d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:03.01
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 150
   at Templates.Test.Helpers.AspNetProcess..ctor(ITestOutputHelper output, String workingDirectory, String projectName, String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/AspNetProcess.cs:line 70
   at Templates.Test.TemplateTestBase.StartAspNetProcess(String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 212
   at Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthImpl(String targetFrameworkOverride, String languageOverride, Boolean noHttps) in /_/test/Templates.Test/MvcTemplateTest.cs:line 73
------- Stdout: -------
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe new mvc --debug:custom-hive "C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\.templateengine" -lang F# [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04]
The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.
Processing post-creation actions...
Running 'dotnet restore' on C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj...
  Restoring packages for C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj...
  Generating MSBuild file C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\obj\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj.nuget.g.props.
  Generating MSBuild file C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\obj\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj.nuget.g.targets.
  Restore completed in 1 sec for C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj.
Restore succeeded.
Building ASP.NET application...
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe build --no-restore -c Debug [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04]
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\x1d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\x1d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\x1d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj]
Build FAILED.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\x1d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\x1d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\x1d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, is this still blocked? Seems like we had no reports for quite a while now.

**Comment by ryanbrandenburg** [comment]
This may or may not still be happening, we don't know because Templating tests [aren't running](https://github.com/aspnet/AspNetCore/issues/4321).

**Comment by ryanbrandenburg** [comment]
Tests still aren't running automatically, but we did do a manual pass and these tests worked then. I'll close this out and if we still have a problem when https://github.com/aspnet/AspNetCore/issues/4321 reopens a new issue will be created.
