### ISSUE TITLE
Build Error when referencing a bunch of standard libraries

### ISSUE THREAD

**Issue by TFTomSun** [aspnet/AspNetCore#5492]
First of all: Thanks for the great work. I love that project and I want to support it as much as i can.

I started with a simple Blazor (not hosted) project and referenced some of my existing .net standard projects incl. some 3rd party packages like selenium (WebDriver and WebDriver.Support) and Docker.DotNet.

When I try to build the app I get the following build error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/illink/illink.dll" -c link -u link -t --verbose  -d "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/mono/bcl/" -d "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/mono/bcl/Facades/" -o "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Development\Git\Nuget\packages\docker.dotnet\3.125.1\lib\netstandard2.0\Docker.DotNet.dll" -a "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor\0.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.browser\0.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.csharp\4.3.0\lib\netstandard1.3\Microsoft.CSharp.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.dependencyinjection\2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.dependencyinjection.abstractions\2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Development\Git\Nuget\packages\newtonsoft.json\10.0.3\lib\netstandard1.3\Newtonsoft.Json.dll" -a "C:\Development\Git\Nuget\packages\selenium.support\3.10.0\lib\netstandard2.0\WebDriver.Support.dll" -a "C:\Development\Git\Nuget\packages\selenium.webdriver\3.10.0\lib\netstandard2.0\WebDriver.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.nongeneric\4.3.0\lib\netstandard1.3\System.Collections.NonGeneric.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.specialized\4.3.0\lib\netstandard1.3\System.Collections.Specialized.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel\4.3.0\lib\netstandard1.3\System.ComponentModel.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.primitives\4.3.0\lib\netstandard1.0\System.ComponentModel.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.typeconverter\4.3.0\lib\netstandard1.5\System.ComponentModel.TypeConverter.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.dynamic.runtime\4.3.0\lib\netstandard1.3\System.Dynamic.Runtime.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq\4.3.0\lib\netstandard1.6\System.Linq.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq.expressions\4.3.0\lib\netstandard1.6\System.Linq.Expressions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.objectmodel\4.3.0\lib\netstandard1.3\System.ObjectModel.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit\4.3.0\lib\netstandard1.3\System.Reflection.Emit.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.serialization.formatters\4.3.0\lib\netstandard1.4\System.Runtime.Serialization.Formatters.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.serialization.primitives\4.3.0\lib\netstandard1.3\System.Runtime.Serialization.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.regularexpressions\4.3.0\lib\netstandard1.6\System.Text.RegularExpressions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading.tasks.extensions\4.3.0\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.readerwriter\4.3.0\lib\netstandard1.3\System.Xml.ReaderWriter.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.xmldocument\4.3.0\lib\netstandard1.3\System.Xml.XmlDocument.dll" -a "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BusinessLogic\bin\Debug\netstandard2.0\FFXIVCollector.BusinessLogic.dll" -a "C:\Development\Git\NetStandard.Extensions\TomSun.NetStandard.Extensions\bin\Debug\netstandard1.0\TomSun.NetStandard.Extensions.dll" -a "C:\Development\Git\NetStandard.Platform\TomSun.NetStandard.Platform\bin\Debug\netstandard1.0\TomSun.NetStandard.Platform.dll" -a "C:\Development\Git\Selenium.Extensions\TomSun.Selenium.Extensions\bin\Debug\netstandard2.0\TomSun.Selenium.Extensions.dll" -a "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\obj\Debug\netstandard2.0\FFXIVCollector.BlazorApp.dll"" exited with code 1.	FFXIVCollector.BlazorApp	C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\Blazor.MonoRuntime.targets	429	

```

The build output is:
```
1>------ Build started: Project: FFXIVCollector.BlazorApp, Configuration: Debug Any CPU ------
1>----- Smart Resolve References -----
1>FFXIVCollector.BlazorApp -> C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\bin\Debug\netstandard2.0\FFXIVCollector.BlazorApp.dll
1>Cannot find declaration of exported type 'System.Threading.Semaphore' from the assembly 'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>Cannot find declaration of exported type 'System.Reflection.Emit.DynamicMethod' from the assembly 'System.Reflection.Emit.Lightweight, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>Processing embedded resource linker descriptor: mscorlib.xml
1>Fatal error in IL Linker
1>Mono.Linker.MarkException: Error processing method: 'System.Boolean System.Linq.Expressions.Compiler.ILGen::ShouldLdtoken(System.Reflection.MethodBase)' in assembly: 'System.Linq.Expressions.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Reflection.Emit.DynamicMethod
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
1>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
1>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
1>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
1>   at Mono.Linker.Steps.MarkStep.Process()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\Blazor.MonoRuntime.targets(429,5): error MSB3073: The command "dotnet "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/illink/illink.dll" -c link -u link -t --verbose  -d "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/mono/bcl/" -d "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\../tools/mono/bcl/Facades/" -o "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.build\0.1.0\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Development\Git\Nuget\packages\docker.dotnet\3.125.1\lib\netstandard2.0\Docker.DotNet.dll" -a "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor\0.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Development\Git\Nuget\packages\microsoft.aspnetcore.blazor.browser\0.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.csharp\4.3.0\lib\netstandard1.3\Microsoft.CSharp.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.dependencyinjection\2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.dependencyinjection.abstractions\2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Development\Git\Nuget\packages\newtonsoft.json\10.0.3\lib\netstandard1.3\Newtonsoft.Json.dll" -a "C:\Development\Git\Nuget\packages\selenium.support\3.10.0\lib\netstandard2.0\WebDriver.Support.dll" -a "C:\Development\Git\Nuget\packages\selenium.webdriver\3.10.0\lib\netstandard2.0\WebDriver.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.buffers\4.4.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.nongeneric\4.3.0\lib\netstandard1.3\System.Collections.NonGeneric.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.collections.specialized\4.3.0\lib\netstandard1.3\System.Collections.Specialized.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel\4.3.0\lib\netstandard1.3\System.ComponentModel.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.primitives\4.3.0\lib\netstandard1.0\System.ComponentModel.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.componentmodel.typeconverter\4.3.0\lib\netstandard1.5\System.ComponentModel.TypeConverter.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.dynamic.runtime\4.3.0\lib\netstandard1.3\System.Dynamic.Runtime.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.io.filesystem.primitives\4.3.0\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq\4.3.0\lib\netstandard1.6\System.Linq.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq.expressions\4.3.0\lib\netstandard1.6\System.Linq.Expressions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.objectmodel\4.3.0\lib\netstandard1.3\System.ObjectModel.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit\4.3.0\lib\netstandard1.3\System.Reflection.Emit.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.ilgeneration\4.3.0\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.lightweight\4.3.0\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.3.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.serialization.formatters\4.3.0\lib\netstandard1.4\System.Runtime.Serialization.Formatters.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.serialization.primitives\4.3.0\lib\netstandard1.3\System.Runtime.Serialization.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.text.regularexpressions\4.3.0\lib\netstandard1.6\System.Text.RegularExpressions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading\4.3.0\lib\netstandard1.3\System.Threading.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading.tasks.extensions\4.3.0\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.readerwriter\4.3.0\lib\netstandard1.3\System.Xml.ReaderWriter.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.xml.xmldocument\4.3.0\lib\netstandard1.3\System.Xml.XmlDocument.dll" -a "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BusinessLogic\bin\Debug\netstandard2.0\FFXIVCollector.BusinessLogic.dll" -a "C:\Development\Git\NetStandard.Extensions\TomSun.NetStandard.Extensions\bin\Debug\netstandard1.0\TomSun.NetStandard.Extensions.dll" -a "C:\Development\Git\NetStandard.Platform\TomSun.NetStandard.Platform\bin\Debug\netstandard1.0\TomSun.NetStandard.Platform.dll" -a "C:\Development\Git\Selenium.Extensions\TomSun.Selenium.Extensions\bin\Debug\netstandard2.0\TomSun.Selenium.Extensions.dll" -a "C:\Development\Git\FFXIVCollector.WebApi\FFXIVCollector.BlazorApp\obj\Debug\netstandard2.0\FFXIVCollector.BlazorApp.dll"" exited with code 1.
1>Done building project "FFXIVCollector.BlazorApp.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========


```
Is there somewhere  a "not yet supported" list?

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, is there any action from our side here or should this go to the Mono repo?

**Comment by SteveSandersonMS** [comment]
For anything that fails specifically due to the linker (i.e., works OK if you use `<BlazorLinkOnBuild>false</BlazorLinkOnBuild>`), then it should be reported to Mono and isn't something we can address in this repo.

**Comment by mkArtakMSFT** [comment]
This issue was moved to mono/mono#12604
