### ISSUE TITLE
Unable to link with System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by robertsundstrom** [aspnet/AspNetCore#5627]
I added the ```System.IdentityModel.Tokens.Jwt``` package to my Blazor-project to handle JWT on the client. When building, I got the usual error about not being able to link because of dependencies, such as "Semaphore".

```cmd
3>TestApp.Client -> S:\Downloads\TestApp\src\TestApp.Client\bin\Debug\netstandard2.0\TestApp.Client.dll
3>Cannot find declaration of exported type 'System.Threading.Semaphore' from the assembly 'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
3>Fatal error in IL Linker
3>Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.DataContractSerialization, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
3>   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
3>   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
3>   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name)
3>   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
3>   at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(LinkContext context, AssemblyDefinition assembly, RootVisibility rootVisibility)
3>   at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(AssemblyDefinition assembly)
3>   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
3>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
3>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
3>   at Mono.Linker.Pipeline.Process(LinkContext context)
3>   at Mono.Linker.Driver.Run(ILogger customLogger)
3>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```
Is there a way to get around this? What is preventing me from using the package?

**Comment by mkArtakMSFT** [comment]
Looks like this was a Linker issue. If you still face this problem, please file an issue on the https://github.com/mono/mono repo.
