### ISSUE TITLE
FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#5640]
When working on replicating the `TabSet` component from the last Blazor community standup I got this exception with VS 2017 15.9 and the Blazor 0.7.0-preview1 build:

```
System.FormatException: Input string was not in a correct format.
 at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
 at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
 at System.String.Format(IFormatProvider provider, String format, Object[] args)
 at Microsoft.AspNetCore.Razor.Language.DefaultRazorDiagnostic.GetMessage(IFormatProvider formatProvider)
 at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.NotifyOnCodeGenerationComplete()
 at Microsoft.VisualStudio.Web.Editors.Razor.RazorCodeGenerator.<>c__DisplayClass67_0.<OnDocumentStructureChanged>b__0()
 at Microsoft.Web.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)
 --- End of stack trace from previous location where exception was thrown ---
 at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Here's the component file I was working on:

```html
<ul class="nav nav-tabs">
    @foreach (var tab in tabs)
    {
        <li class="nav-item">
            <a onclick="@(() => SelectTab(tab))" class="nav-link @(tab==)
        </li>
    }

</ul>


@functions {

}
```

**Comment by moljac** [comment]
I hit this issue when binding `Dictionary<int, string>` as configurable menu. After downloading symbols etc I was able to see something `DictionaryBlahBlahImpl<>` or `DictionaryBlahBlahInternal<>`.

Switched to `string[]`

Now with `string[]` it works.

Code was port from older ASP.net to ASP.net Core w Razor Pages.

No. I have no details. After searching and debugging for couple of hours I felt stupid for another couple of hours.

Maybe catching the Exception and giving meaningful explanation could save us few hours.

cheers

**Comment by rynowak** [comment]
The fix for this is simple so I'm sending it out. I have no concerns if we decide to punt.

**Comment by rynowak** [comment]
Fixed!
