### ISSUE TITLE
Update to SDK 2.2.100 throws "An item with the same key has already been added. Key: .wasm"

### ISSUE THREAD

**Issue by michaelvolz** [aspnet/AspNetCore#5666]
I updated my Blazor project from `2.2.100-preview3-009430` to `2.2.100` release. I now get the following exception:

```C#
System.ArgumentException : An item with the same key has already been added. Key: .wasm
Stack Trace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.ServerSideBlazorApplicationBuilderExtensions.UseServerSideBlazor[TStartup](IApplicationBuilder builder)
   at OpenGraphTilemaker.Web.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\flynn\Projects\OpenGraphTilemaker\src\OpenGraphTilemaker.Web.Server\Startup.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateServer(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at OpenGraphTilemaker.Web.Client.Tests.FunctionalTests.Get_EndpointsReturnSuccessAndCorrectContentType(String url) in C:\Users\flynn\Projects\OpenGraphTilemaker\tests\OpenGraphTilemaker.Web.Client.Tests\FunctionalTests.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
```

The line
`app.UseServerSideBlazor<Client.Startup>();`
seems to be the reason. 

Any suggestions?

**Comment by malachib** [comment]
On my linux machines this pinning down works.  On my mac however I get the same wasm error as before.  Using a `global.json` like this:

```
{
  "sdk": {
    "version": "2.1.400"
  }
}
```

And using 2.1.5 LTS which comes with 2.1.403 SDK

On both mac and linux, dotnet --version reports 2.1.403

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, if this is already fixed, please resolve.

**Comment by SteveSandersonMS** [comment]
Fixing in #6731

**Comment by SteveSandersonMS** [comment]
Actually it turns out it was already fixed (by conditionally adding the mapping), but the updated fix in #6731 is better because it's simpler.

**Comment by ctrl-alt-d** [comment]
I have the issue on `3.0.100-preview-010184` :

```
$ dotnet run --project Aliga3.XXX

C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(154,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\XXX\projectes\XXX\XXX.BlazorRestServer\XXX.BlazorRestServer.csproj]

Application startup exception: System.ArgumentException: An item with the same key has already been added. Key: .wasm
```

( I included warning just to show the version )

**Comment by SteveSandersonMS** [comment]
@ctrl-alt-d Looks like your app must still be using the earlier packages (Blazor 0.7.0?). It's only fixed in the newer bits we haven't released yet.

**Comment by sheryever** [comment]
@danroth27 after installing `dotnet core version 3.0.100` on Windows 10 and Windows 2012 R2 (Hosting machine) a component written in `dotnet standard 2` the dictionary is throwing "`An item with the same key...`" exception with a little strange behavior. They key i am adding is string while dictionary is showing random integer keys every time in the exception. like: "An item with the same key has already been added. Key: 7166148"

**Comment by danroth27** [comment]
@sheryever Could you please open a new issue with the full details on how to reproduce the problem you are seeing?

**Comment by sheryever** [comment]
@danroth27 our issue resolved, the dictionary was a static variable, we fixed it by using lock statement.

The interesting thing that we noticed with aspnet core is, the controller action was not async and neither running any thread but still it looks that more than one thread was accessing the dictionary at once on multiple calls from browser :)
