### ISSUE TITLE
Occasional 'address already in use' error when starting an app hosted in an Azure App Service

### ISSUE THREAD

**Issue by stijnherreman** [aspnet/AspNetCore#5699]
### Describe the bug
We have a number of ASP.NET Core apps hosted inside a single Azure App Service, as Virtual Applications. Occasionally after a restart (e.g. due to deploying), one or more apps will fail to start correctly and return HTTP 400 Bad Request to all requests. This appears to be due to a socket binding error.

### To Reproduce
1. Create one or more ASP.NET Core 2.1.1 applications. I target .NET Framework due to a dependency, I don't know if the issue also occurs when targetting .NET Core. I use a modified version of `CreateDefaultBuilder` that deals with configuration sources, it does not apply any non-default hosting or binding settings.
2. Deploy the applications to an Azure App Service, as Virtual Applications. I use an Azure DevOps pipeline for this. (see screenshot below)
3. Stop and Start the App Service until at some point one of the applications returns a HTTP 400.

### Expected behavior
All applications start successfully.

### Screenshots
![screenshot of the Virtual Applications configuration](https://user-images.githubusercontent.com/1618054/50167390-5b113280-02e9-11e9-9ebd-65241ae67c80.png)

### Additional context
The problem never occurs when running the application locally via Visual Studio.

This is the captured log:

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      Azure Web Sites environment detected. Using 'D:\home\ASP.NET\DataProtection-Keys' as key repository; keys will not be encrypted at rest.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://127.0.0.1:23222: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.<BindAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.<BindAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<StartAsync>d__22`1.MoveNext()
```

Could there be some race condition in deciding the port to use, when multiple apps try to start at the same time? Is this a supported scenario?

**Comment by shirhatti** [comment]
@stijnherreman There is a known issue in ANCMv1 when multiple applications attempt to start at the same time. This issue has been fixed in ANCMv2, but as it stands ANCMv1 is in maintenance mode and there are no plans to backport this fix.

The mitigation in this case is to for your application to use ANCMv2

You can change your `web.config` from

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore ... />
    </system.webServer>
  </location>
</configuration>
```

to (notice the modules attribute in the handlers collection has changed to `AspNetCoreModuleV2`

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore ... />
    </system.webServer>
  </location>
</configuration>
```

This should solve your problem

**Comment by stijnherreman** [comment]
Thanks, I'll look into updating to ASP.NET Core 2.2, I'll reopen this issue if the problem reappears.
