### ISSUE TITLE
Razor compiler crash in Regression_1068

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#6113]
Run the test `Regression_1068` in the Razor solution (after Blazor compiler is merged in). 

```
Test Name:	Microsoft.AspNetCore.Razor.Language.IntegrationTests.ComponentTypingTest.Regression_1068
Test FullName:	Microsoft.AspNetCore.Razor.Language.IntegrationTests.ComponentTypingTest.Regression_1068
Test Source:	C:\git\aspnet\AspNetCore-Tooling\src\Razor\test\Microsoft.AspNetCore.Razor.Language.Test\IntegrationTests\ComponentTypingTest.cs : line 81
Test Outcome:	Failed
Test Duration:	0:00:00.022

Result StackTrace:	
at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitRazorDirective(RazorDirectiveSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Main.Generated.cs:line 743
   at Microsoft.AspNetCore.Razor.Language.Syntax.RazorDirectiveSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 3269
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 165
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 102
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpCodeBlock(CSharpCodeBlockSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Main.Generated.cs:line 664
   at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpCodeBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 2292
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 165
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 102
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitMarkupBlock(MarkupBlockSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Main.Generated.cs:line 524
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.AttributeValueRewriter.VisitMarkupDynamicAttributeValue(MarkupDynamicAttributeValueSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperBlockRewriter.cs:line 563
   at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupDynamicAttributeValueSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 1344
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 165
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 102
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitGenericBlock(GenericBlockSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Main.Generated.cs:line 512
   at Microsoft.AspNetCore.Razor.Language.Syntax.GenericBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 324
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.RewriteAttributeValue(TryParseResult result, RazorBlockSyntax attributeValue) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperBlockRewriter.cs:line 291
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.TryParseAttribute(String tagName, MarkupAttributeBlockSyntax attributeBlock, IEnumerable`1 descriptors, ErrorSink errorSink, HashSet`1 processedBoundAttributeNames) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperBlockRewriter.cs:line 263
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.GetRewrittenChildren(String tagName, Boolean validStructure, MarkupStartTagSyntax tagBlock, TagHelperBinding bindingResult, RazorParserFeatureFlags featureFlags, ErrorSink errorSink, RazorSourceDocument source) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperBlockRewriter.cs:line 88
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.Rewrite(String tagName, Boolean validStructure, RazorParserFeatureFlags featureFlags, MarkupStartTagSyntax tag, TagHelperBinding bindingResult, ErrorSink errorSink, RazorSourceDocument source) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperBlockRewriter.cs:line 23
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewriter.TryRewriteTagHelperStart(MarkupStartTagSyntax startTag, MarkupTagHelperStartTagSyntax& rewritten, TagHelperInfo& tagHelperInfo) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperParseTreeRewriter.cs:line 270
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewriter.VisitMarkupElement(MarkupElementSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperParseTreeRewriter.cs:line 107
   at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupElementSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 1441
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 165
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 102
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitMarkupBlock(MarkupBlockSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Main.Generated.cs:line 524
   at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 472
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitRazorDocument(RazorDocumentSyntax node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Main.Generated.cs:line 490
   at Microsoft.AspNetCore.Razor.Language.Syntax.RazorDocumentSyntax.Accept[TResult](SyntaxVisitor`1 visitor) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\Generated\Syntax.xml.Syntax.Generated.cs:line 63
   at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Syntax\SyntaxRewriter.cs:line 19
   at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewrite(RazorSyntaxTree syntaxTree, String tagHelperPrefix, IEnumerable`1 descriptors) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\Legacy\TagHelperParseTreeRewriter.cs:line 26
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\DefaultRazorTagHelperBinderPhase.cs:line 61
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\RazorEnginePhaseBase.cs:line 40
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\DefaultRazorEngine.cs:line 51
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\DefaultRazorProjectEngine.cs:line 257
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.ProcessDesignTime(RazorProjectItem projectItem) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\src\Microsoft.AspNetCore.Razor.Language\RazorProjectEngine.cs:line 66
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToCSharp(String cshtmlRelativePath, String cshtmlContent) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\test\Microsoft.AspNetCore.Razor.Test.Common\Language\IntegrationTests\RazorIntegrationTestBase.cs:line 233
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToCSharp(String cshtmlContent) in C:\git\aspnet\AspNetCore-Tooling\src\Razor\test\Microsoft.AspNetCore.Razor.Test.Common\Language\IntegrationTests\RazorIntegrationTestBase.cs:line 163
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.ComponentTypingTest.Regression_1068() in C:\git\aspnet\AspNetCore-Tooling\src\Razor\test\Microsoft.AspNetCore.Razor.Language.Test\IntegrationTests\ComponentTypingTest.cs:line 86
Result Message:	System.InvalidCastException : Unable to cast object of type 'Microsoft.AspNetCore.Razor.Language.Syntax.CSharpExpressionLiteralSyntax' to type 'Microsoft.AspNetCore.Razor.Language.Syntax.CSharpTransitionSyntax'.
```

**Comment by iAmBipinPaul** [comment]
Looks like same issue.
```
 Unable to cast object of type 'Microsoft.AspNetCore.Razor.Language.Syntax.CSharpExpressionLiteralSyntax' to type 'Microsoft.AspNetCore.Razor.Language.Syntax.RazorMetaCodeSyntax'.
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpStatementBody(CSharpStatementBodySyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpStatementBodySyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpStatement(CSharpStatementSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpStatementSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpCodeBlock(CSharpCodeBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpCodeBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitMarkupBlock(MarkupBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.AttributeValueRewriter.VisitMarkupDynamicAttributeValue(MarkupDynamicAttributeValueSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupDynamicAttributeValueSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitGenericBlock(GenericBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.GenericBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.RewriteAttributeValue(TryParseResult result, RazorBlockSyntax attributeValue)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.TryParseAttribute(String tagName, MarkupAttributeBlockSyntax attributeBlock, IEnumerable`1 descriptors, ErrorSink errorSink, HashSet`1 processedBoundAttributeNames)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.Rewrite(String tagName, RazorParserFeatureFlags featureFlags, MarkupStartTagSyntax startTag, TagHelperBinding bindingResult, ErrorSink errorSink, RazorSourceDocument source)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewriter.TryRewriteTagHelperStart(MarkupStartTagSyntax startTag, MarkupTagHelperStartTagSyntax& rewritten, TagHelperInfo& tagHelperInfo)
```

**Comment by NTaylorMullen** [comment]
@iAmBipinPaul hmm, slightly different actually. Would you mind sharing the .cshtml content that caused the crash for you?

**Comment by iAmBipinPaul** [comment]
@NTaylorMullen Actually I'm updating  from `Blazor server side` to asp.net core 3.0  preview  2 Razor component and getting this issue don't now  which cshtml file is causing this issue.
> (It was working perfectly on .net core 2.1 before updating)

I will dig more on this tomorrow and will update here.
Thank you !

**Comment by iAmBipinPaul** [comment]
Here we are getting this above mention exception.

```csharp
 <Paging totalResult="@{ topic.TotalCount ?? 0}"
                currentPage="@State.CurrentPage" 
                pageSize="@pageSize" 
                PageChanged="PageChangedEvent"> 
</Paging>
```
Here we are not getting any exception and it works as it have to.
```csharp
 <Paging totalResult="11"
                currentPage="@State.CurrentPage" 
                pageSize="@pageSize" 
                PageChanged="PageChangedEvent"> 
</Paging>
```

When I'm using   `totalResult="@{ topic.TotalCount ?? 0}"` or  `totalResult="@{totalCount}"` it hangs , gives the above mention exception as well  as forces VS 2019 preview 2 to close.

but when I'm using  `totalResult="@totalCount"` it works so basically , it gives error when using curly bracket.

**Comment by NTaylorMullen** [comment]
@iAmBipinPaul thank you for the repro! I was able to reproduce it without Blazor as well and filed the following issue: https://github.com/aspnet/AspNetCore/issues/7159
