### ISSUE TITLE
[CI Error] ResponseFormats_Chunked

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#6136]
```
ServerComparison.FunctionalTests.ResponseTests.ResponseFormats_Chunked(variant: 
 Server: IISExpress, TFM: netcoreapp3.0, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess)
/chunked, chunked?
Expected: True
Actual:   (null)
   at ServerComparison.FunctionalTests.ResponseTests.CheckChunkedAsync(HttpClient client, ILogger logger)
    in /_/src/Servers/test/FunctionalTests/ResponseTests.cs:line 211
   at ServerComparison.FunctionalTests.ResponseTests.ResponseFormats(TestVariant variant, Func`3 scenario, String testName)
    in /_/src/Servers/test/FunctionalTests/ResponseTests.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by jkotalik** [comment]
#6168 which disables the test.
