### ISSUE TITLE
MvcPrecompilation tool fails for full framework projects on 2.1

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/AspNetCore#6499]
I noticed this when converting the mvc precompilation projects to using <Reference>. The error I see is
```
| [2019-01-08T13:31:57] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "C:\Users\johluo\AppData\Local\Temp\730bd8bf-dd55-4618-92f1-68f76a82d9ce" --framework net461 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false
 | [2019-01-08T13:31:57] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
 | [2019-01-08T13:31:57] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
 | [2019-01-08T13:31:58] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Mvc -> C:\gh\AspNetCore\src\Mvc\src\Microsoft.AspNetCore.Mvc\bin\Release\netstandard2.0\Microsoft.AspNetCore.Mvc.dll
 | [2019-01-08T13:31:58] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.Kestrel -> C:\gh\AspNetCore\src\Servers\bin\Microsoft.AspNetCore.Server.Kestrel\Release\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.dll
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   SimpleApp -> C:\gh\AspNetCore\src\mvc\ViewCompilation\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation\testassets\SimpleApp\bin\Release\net461\SimpleApp.exe
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Razor, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:      at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.Execute()
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:      at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.<Configure>b__17_0()
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:      at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:      at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompilationApplication.Execute(String[] args)
Core.Mvc.Razor.ViewCompilation-x86.exe" @"obj\Release\net461\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1. [C:\gh\AspNetCore\src\mvc\ViewCompilation\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation\testassets\SimpleApp\SimpleApp.csproj]
 | [2019-01-08T13:32:00] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Error: dotnet publish exited with exit code : 1
```

@pranavkm suspects that this is due to version mismatches that accumulated during the 2.1 patching process, e.g. Microsoft.AspNetCore.Mvc 2.1.3 and Microsoft.AspNetCore.Mvc.Razor.ViewCompilation 2.1.1.

**Comment by mkArtakMSFT** [comment]
Let's make sure that we address this if we ever have to patch MVC again for 2.1.

**Comment by rynowak** [comment]
We would also recommend that any user experiencing problems with this in 2.1 switch to Razor SDK for build-time compilation. The strategy used by precompilation is really fragile, which is why we deprecated it.

**Comment by pranavkm** [comment]
Closing this. We haven't had any reports of this, and I don't think we would consider patching a tool in 2.1 that we say is deprecated.
