### ISSUE TITLE
[CI Failure]: Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.ShutdownTests.GracefulTurnsAbortiveIfRequestsDoNotFinish

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#6556]
https://dnceng.visualstudio.com/public/_build/results?buildId=69781&view=logs

```
Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.ShutdownTests.GracefulTurnsAbortiveIfRequestsDoNotFinish
Assert.Contains() Failure
Not found: (filter expression)
In value:  ConcurrentQueue<LogMessage> [LogMessage { EventId = 3, Exception = null, LogLevel = Debug, Message = "Hosting starting" }, LogMessage { EventId = 4, Exception = null, LogLevel = Debug, Message = "Hosting started" }, LogMessage { EventId = 0, Exception = null, LogLevel = Debug, Message = "Loaded hosting startup assembly Libuv.FunctionalTe"... }, LogMessage { EventId = 0, Exception = null, LogLevel = Debug, Message = "TestServer is listening on port 5416" }, LogMessage { EventId = ConnectionStart, Exception = null, LogLevel = Debug, Message = "Connection id \"0HLJMLBPR2RNP\" started." }, ...]
```

Logs

```
| [0.001s] TestLifetime Information: Starting test GracefulTurnsAbortiveIfRequestsDoNotFinish at 2019-01-10T03:23:08
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [3.897s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [3.897s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [3.897s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 5416
| [5.059s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLJMLBPR2RNP" started.
| [5.210s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
| [5.211s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
| [5.212s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" received SETTINGS frame for stream ID 0 with length 12 and flags NONE
| [5.212s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [5.212s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
| [5.212s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" received HEADERS frame for stream ID 1 with length 15 and flags END_STREAM, END_HEADERS
| [5.215s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/2 GET https://localhost:5416/  
| [5.222s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [5.225s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to close gracefully during server shutdown.
| [5.228s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLJMLBPR2RNP" sending FIN because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout."
| [5.233s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLJMLBPR2RNP" request processing ended abnormally.
| System.IO.IOException: The read operation failed, see inner exception. ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
|    at System.Threading.Tasks.ValueTask`1.get_Result()
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.RawStream.ReadAsyncInternal(Memory`1 destination) in /_/src/Servers/Kestrel/Core/src/Adapter/Internal/RawStream.cs:line 113
|    at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
|    at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
|    --- End of inner exception stack trace ---
|    at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
|    at System.Threading.Tasks.ValueTask`1.get_Result()
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.AdaptedPipeline.ReadInputAsync(Stream stream) in /_/src/Servers/Kestrel/Core/src/Adapter/Internal/AdaptedPipeline.cs:line 120
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.PipeCompletion.IsCompletedOrThrow()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
|    at System.Threading.Tasks.ValueTask`1.get_Result()
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 187
| [5.235s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLJMLBPR2RNP" is closed. The last processed stream ID was 1.
| [5.236s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLJMLBPR2RNP" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
| [6.307s] Microsoft.AspNetCore.Server.Kestrel Debug: Some connections failed to abort during server shutdown.
| [6.318s] TestLifetime Information: Finished test GracefulTurnsAbortiveIfRequestsDoNotFinish in 6.3175427s
```

**Comment by muratg** [comment]
Looks like test isn't able to parse the error properly.
