### ISSUE TITLE
Flakiness in SignalR Long Polling Tests

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#6597]
```
Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.ServerThrowsHubExceptionIfBuildingAsyncEnumeratorIsNotPossible(hubProtocolName: "messagepack", transportType: LongPolling, hubPath: "/dynamic")
System.Exception : 2 error(s) logged.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport - LongPollingTerminated - Py2bW5PoMGOfHHqPLBAogg - Long Polling transport was terminated due to an error on connection.
===================
System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/LongPollingTransport.cs:line 31
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, ConnectionDelegate connectionDelegate, HttpConnectionDispatcherOptions options, ConnectionLogScope logScope) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs:line 300
   
at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, HttpConnectionDispatcherOptions options, ConnectionDelegate connectionDelegate) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs:line 78
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
===================
Microsoft.AspNetCore.Server.Kestrel - ApplicationError - Connection id "0HLJNG06HQRGU", Request id "0HLJNG06HQRGU:00000005": An unhandled exception was thrown by the application.
===================
System.InvalidOperationException: Reading is not allowed after reader was completed.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport.ProcessRequestAsync(HttpContext context, CancellationToken token) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/LongPollingTransport.cs:line 31
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, ConnectionDelegate connectionDelegate, HttpConnectionDispatcherOptions options, ConnectionLogScope logScope) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs:line 300
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteAsync(HttpContext context, HttpConnectionDispatcherOptions options, ConnectionDelegate connectionDelegate) in /_/src/Microsoft.AspNetCore.Http.Connections/Internal/HttpConnectionDispatcher.cs:line 78
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
===================
```

**Comment by davidfowl** [comment]
cc @BrennanConroy ever seen this? I wonder if this is related to the changes I made to any of the pooling changes made recently.

**Comment by davidfowl** [comment]
Ah actually, it looks SignalR specific https://github.com/aspnet/AspNetCore/blob/31c8423df1a2366f9a33706b0d8b55948bd8d127/src/SignalR/src/Microsoft.AspNetCore.Http.Connections/Internal/Transports/LongPollingTransport.cs#L31

**Comment by BrennanConroy** [comment]
This was a difficult one to track down. The problem is we set the connection state to `Inactive` outside of the state lock at https://github.com/aspnet/AspNetCore/blob/1f892d798d3163b4bd9d3c4e900f6bb5c2310f9c/src/SignalR/common/Http.Connections/src/Internal/HttpConnectionDispatcher.cs#L334
Which _can_ override the `Disposed` state set when the connection gets closed by a `DELETE` request.

**Comment by anurse** [comment]
This flakiness affects all Long Polling tests, so to mitigate it I'm disabling all Long Polling tests in HubConnection.
