### ISSUE TITLE
Exception thrown in ASP.NET Blazor Server Side Template

### ISSUE THREAD

**Issue by redradist** [aspnet/AspNetCore#6662]
### Describe the bug
Install ASP.NET Core 2.2 and try to create Blazor Application. After building and running Application exception is thrown

### To Reproduce
1) Install Ubuntu 16.04
2) Install ASP.NET Core 2.2 by link https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-2.2.102-linux-x64-binaries
3) Install Blazor template by the following command:
`dotnet new -i Microsoft.AspNetCore.Blazor.Templates`
4) Create Blazor Server Side Application
5) Build Application
6) Run Application
7) Exception is thrown:
```
Application startup exception: System.ArgumentException: An item with the same key has already been added. Key: .wasm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.ServerSideBlazorApplicationBuilderExtensions.UseServerSideBlazor[TStartup](IApplicationBuilder builder)
   at ASP.NETCoreWebApplication.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in {home_dir}/RiderProjects/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication.Server/Startup.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentException: An item with the same key has already been added. Key: .wasm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.ServerSideBlazorApplicationBuilderExtensions.UseServerSideBlazor[TStartup](IApplicationBuilder builder)
   at ASP.NETCoreWebApplication.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in {home_dir}/RiderProjects/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication.Server/Startup.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: .wasm
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.CreateContentTypeProvider(Boolean enableDebugging)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.ServerSideBlazorApplicationBuilderExtensions.UseServerSideBlazor[TStartup](IApplicationBuilder builder)
   at ASP.NETCoreWebApplication.Server.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in {home_dir}/RiderProjects/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication.Server/Startup.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at ASP.NETCoreWebApplication.Server.Program.Main(String[] args) in {home_dir}/RiderProjects/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication/ASP.NETCoreWebApplication.Server/Program.cs:line 11
```

### Expected behavior
Application should be started successfully

### Additional context
Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   {home_dir}/Software/dotnet-sdk-2.2.102-linux-x64/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.102 [{home_dir}/Software/dotnet-sdk-2.2.102-linux-x64/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [{home_dir}/Software/dotnet-sdk-2.2.102-linux-x64/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [{home_dir}/Software/dotnet-sdk-2.2.102-linux-x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [{home_dir}/Software/dotnet-sdk-2.2.102-linux-x64/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by IvanJosipovic** [comment]
Duplicate https://github.com/aspnet/AspNetCore/issues/5666
