### ISSUE TITLE
w3wp.exe crashes | Faulting module name: KERNELBASE.dll, version: 10.0.17763.134. ASP.NET Core 2.2.1

### ISSUE THREAD

**Issue by shapeh** [aspnet/AspNetCore#6756]
### Describe the bug
w3wp.exe crashes when trying to login via a custom made login procedure.
Using Identity + Dapper and ASP.NET Core 2.2.1

Faulting application name: w3wp.exe, version: 10.0.17763.1, time stamp: 0xcfdb13d8
Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0x1659a33b
Exception code: 0xe0434352
Fault offset: 0x0000000000055299
Faulting process id: 0x1904
Faulting application start time: 0x01d4adcbb533ae41
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: dc16e7b5-6a68-453c-ae7c-299c16e612ca
Faulting package full name:
Faulting package-relative application ID:

### To Reproduce
1. Using this version of ASP.NET Core 2.2.1
2. Run this code 

**Startup.cs**
```
        public void ConfigureServices(IServiceCollection services)
        {
            ....

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme,
                options =>
                {
                    options.LoginPath = "/Account/";
                    options.LogoutPath = "/Account/Logout";
                    options.ExpireTimeSpan = TimeSpan.FromMinutes(60); // Set your expiration time here
                    options.SlidingExpiration = true;
                });

            services.AddSingleton(_ => new UserManager());

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        }

```
**Views/Account/Index.cshtml**
```
<form asp-controller="Account" asp-action="Login" method="post" asp-route-returnurl="@ViewData["ReturnUrl"]">
    <div asp-validation-summary="ModelOnly"></div>
    <table class="list noborder">
        <tr><th colspan="2">Login</th></tr>
        <tr>
            <td>Email*</td>
            <td><input asp-for="Email" autocomplete="on" autofocus /></td>
        </tr>
        <tr>
            <td>Password*</td>
            <td><input asp-for="Password" autocomplete="on"  /></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
                <input type="submit" value="Login" onclick="this.value='Please wait a moment...'" />
            </td>
        </tr>
    </table>
</form>
```

**AccountController.cs**
```
    public class AccountController : BaseController
    {
        private readonly UserManager _userManager;

        public AccountController(UserManager userManager)
        {
            _userManager = userManager;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("~/account")]
        public IActionResult Login([FromQuery] string returnUrl,UserModel m)
        {
            if (!ModelState.IsValid)
                return View(m);

            returnUrl = returnUrl ?? Url.Action("Secure", "Account");

            try
            {
                _userManager.SignIn(this.HttpContext, m);
                return LocalRedirect(returnUrl);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("summary", ex.Message);
                return View();
            }
        }
   }
```

**UserManager.cs**
```
using Dapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using myproject.Models;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Security.Claims;
using System.Text.RegularExpressions;

namespace myproject.Helpers
{
    public class UserManager
    {
        public async void SignIn(HttpContext httpContext, UserModel user, bool isPersistent = false)
        {
            using (var con = new SqlConnection(Common.connectionString))
            {
                var dbUserData = await con.QueryFirstOrDefaultAsync<UserModel>("dbo.User_Login",
                    new
                    {
                        user.Email,
                        user.Password,
                        IPAddress = httpContext.Connection.RemoteIpAddress.ToString(),
                        UA = Regex.Replace(httpContext.Request.Headers["User-Agent"].ToString(), @"[&<>\""']", "")
                    },
                    commandType: CommandType.StoredProcedure
                ).ConfigureAwait(false);

                if (dbUserData?.Id > 0)
                {
                    ClaimsIdentity identity = new ClaimsIdentity(this.GetUserClaims(dbUserData), CookieAuthenticationDefaults.AuthenticationScheme);
                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                    await httpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal).ConfigureAwait(false);
                }
            }
        }

        public async void SignOut(HttpContext httpContext)
        {
            await httpContext.SignOutAsync().ConfigureAwait(false);
        }

        private IEnumerable<Claim> GetUserClaims(UserModel user)
        {
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.Email, user.Email)
            };
            claims.AddRange(this.GetUserRoleClaims(user));
            return claims;
        }

        private IEnumerable<Claim> GetUserRoleClaims(UserModel user)
        {
            return new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Role, user.PermissionType.ToString())
            };
        }
    }
}

```

Crash happens 1-2 seconds after clicking the Login button. It happens in the UserManager class when execution of the SQL proc occurs.

The proc is pretty basic - will only return a row if user exists:

```
CREATE PROCEDURE [dbo].[User_Login] 
	@Email nvarchar(64), 
	@Password nvarchar(64),
	@IPAddress nvarchar(15),
	@UA nvarchar(300) = null
AS
BEGIN
SET NOCOUNT ON;
SET NOCOUNT ON
	IF EXISTS (SELECT Id FROM dbo.Users WHERE Email = @Email AND [Password] = @Password AND Active = 1)
	BEGIN
		DECLARE @UserID int
			SELECT @UserID =  ID FROM dbo.Users WHERE Email = @Email AND [Password] = @Password AND Active = 1
			-- log access
			INSERT INTO dbo.UserLogons (UserID,IPAddress,UA) VALUES (@UserID,@IPAddress,@UA)
		
		SELECT * FROM dbo.Users 
		WHERE 
		Email = @Email 
			AND [Password] = @Password
			AND Active = 1

	END
END
```

**Application Event Log**:

**1**
> Application: w3wp.exe
> CoreCLR Version: 4.6.27207.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ArgumentNullException: Value cannot be null.
> Parameter name: provider
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal)
>    at myproject.Helpers.UserManager.SignIn(HttpContext httpContext, UserModel user, Boolean isPersistent) in C:\Web\myproject.com\myproject\myproject\Helpers\UserManager.cs:line 36
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> 

**2**

> Faulting application name: w3wp.exe, version: 10.0.17763.1, time stamp: 0xcfdb13d8
> Faulting module name: KERNELBASE.dll, version: 10.0.17763.134, time stamp: 0x1659a33b
> Exception code: 0xe0434352
> Fault offset: 0x0000000000055299
> Faulting process id: 0x1904
> Faulting application start time: 0x01d4adcbb533ae41
> Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: dc16e7b5-6a68-453c-ae7c-299c16e612ca
> Faulting package full name: 
> Faulting package-relative application ID: 

**3**

> Fault bucket , type 0
> Event Name: CLR20r3
> Response: Not available
> Cab Id: 0
> 
> Problem signature:
> P1: c:\windows\system32\inetsrv\w3wp.exe
> P2: 10.0.17763.1
> P3: cfdb13d8
> P4: Microsoft.Extensions.DependencyInjection.Abstractions
> P5: 2.2.0.18315
> P6: ceb67ed0
> P7: 41
> P8: d
> P9: System.ArgumentNullException
> P10: 
> 
> Attached files:
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE0B1.tmp.dmp
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE6AD.tmp.WERInternalMetadata.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE6CD.tmp.xml
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE6CB.tmp.csv
> \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE6EC.tmp.txt
> 
> These files may be available here:
> **Note - there are no files whatsoever in that folder**
> 
> Analysis symbol: 
> Rechecking for solution: 0
> Report Id: dc16e7b5-6a68-453c-ae7c-299c16e612ca
> Report Status: 134217728
> Hashed bucket: 
> Cab Guid: 0

**Debug Diag dump says:**

> In w3wp__myproject__PID__12176__Date__01_16_2019__Time_05_44_46PM__648__Second_Chance_Exception_E0434352.dmp the assembly instruction at KERNELBASE!RaiseException in C:\Windows\System32\KERNELBASE.dll from Microsoft Corporation has caused a CLR Exception on thread 30 with the following error information:
> 
>     Type:   System.ArgumentNullException 
>     Message:   Value cannot be null. 
> 
> This exception originated from System_Private_CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(). 
> 
> 
> 
> Module Information 
> 
> Image Name: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.1\System.Private.CoreLib.dll   Symbol Type:  PDB 
> Base address: 0x00000000`00005a4d   Time Stamp:  Fri Dec 07 16:46:14 2018  
> Checksum: 0x00000000`00000000   Comments:  System.Private.CoreLib 
> COM DLL: False   Company Name:  Microsoft Corporation 
> ISAPIExtension: False   File Description:  System.Private.CoreLib 
> ISAPIFilter: False   File Version:  4.6.27207.03 
> Managed DLL: True   Internal Name:  System.Private.CoreLib.dll 
> VB DLL: False   Legal Copyright:  Â© Microsoft Corporation. All rights reserved. 
> Loaded Image Name:  System.Private.CoreLib.dll   Legal Trademarks:   
> Mapped Image Name:     Original filename:  System.Private.CoreLib.dll 
> Module name:  System_Private_CoreLib   Private Build:   
> Single Threaded:  False   Product Name:  MicrosoftÂ® .NET Framework 
> Module Size:  12,59 MBytes   Product Version:  4.6.27207.03 @BuiltBy: dlab14-DDVSOWINAGE101 @Branch: release/2.2 @SrcCode: #https://github.com/dotnet/coreclr/tree/b24eee89da14b63be629b5bab80d24990316e1ba 
> Symbol File Name:  c:\symbols\System.Private.CoreLib.pdb\9DE46E3C963E48728A2995FD027553CC1\System.Private.CoreLib.pdb   Special Build:  & 
> 

Thread 30 looks like this: 
>  **Thread 30 - System ID 12000** 

**.NET Call Stack**
> [[HelperMethodFrame]]
> System_Private_CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+1f
> System_Private_CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()+1a2
> [[DebuggerU2MCatchHandlerFrame]]
> 
> 
> **Full Call Stack**
> KERNELBASE!RaiseException+69
> coreclr!RaiseTheExceptionInternalOnly+2fc
> coreclr!IL_Throw+16f
> [[HelperMethodFrame]]
> System_Private_CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+1f
> System_Private_CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()+1a2
> coreclr!CallDescrWorkerInternal+83
> coreclr!MethodDescCallSite::CallTargetWorker+2b5
> coreclr!QueueUserWorkItemManagedCallback+98
> coreclr!ManagedThreadBase_DispatchMiddle+e4
> coreclr!ManagedThreadBase_DispatchOuter+af
> [[DebuggerU2MCatchHandlerFrame]]
> coreclr!ManagedPerAppDomainTPCount::DispatchWorkItem+e0
> coreclr!ThreadpoolMgr::WorkerThreadStart+2df
> coreclr!Thread::intermediateThreadProc+8a
> kernel32!BaseThreadInitThunk+14
> ntdll!RtlUserThreadStart+21

### Expected behavior
The code to run without problems.

### Additional context
Other parts of the website runs without problems - e.g. I have other code that interacts with the database using Dapper - working perfectly fine. I suspect this is related to Identity in some way.

Problems happens with both InProcess and OutOfProcess hosting models. OutOfProcess gives me a WER file though:

[Report.wer.txt](https://github.com/aspnet/AspNetCore/files/2765690/Report.wer.txt)

**Here is my IIS App pool settings:** 
![app-pool-capture](https://user-images.githubusercontent.com/29387615/51272545-a858f080-19ca-11e9-98c0-78e2fda4e99c.PNG)

`dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by jkotalik** [comment]
It seems like your app is crashing due to 
```c#
Application: w3wp.exe
CoreCLR Version: 4.6.27207.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null.
Parameter name: provider
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal)
at **myproject.Helpers.UserManager.SignIn**(HttpContext httpContext, UserModel user, Boolean isPersistent) in C:\Web\myproject.com\myproject\myproject\Helpers\UserManager.cs:line 36
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

@Tratcher thoughts?

**Comment by shapeh** [comment]
@jkotalik Yeah, it is also what Debug Diag is saying: 

![debug-diag](https://user-images.githubusercontent.com/29387615/51274675-10f69c00-19d0-11e9-95df-f6f86c309ef4.PNG)

**Comment by shapeh** [comment]
Maybe bug is related to:

> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {7735cb78-2373-4fd0-9d95-3e1d15187ed3} was not found in the key ring.

**Some more logs from stdout:** 

```
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {37eff6f9-aa65-454b-8147-dcebb55de28e} with creation date 2019-01-16 19:52:56Z, activation date 2019-01-16 19:52:56Z, and expiration date 2019-04-16 19:52:56Z.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {37eff6f9-aa65-454b-8147-dcebb55de28e} may be persisted to storage in unencrypted form.
Hosting environment: Development
Content root path: C:\Web\myproject.com\myproject\myproject
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://myproject/account  
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Cookies was not authenticated. Failure message: Unprotect ticket failed
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'myproject.Controllers.AccountController.Index (myproject)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Index", controller = "Account"}. Executing action myproject.Controllers.AccountController.Index (myproject)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method myproject.Controllers.AccountController.Index (myproject) with arguments () - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method myproject.Controllers.AccountController.Index (myproject), returned result Microsoft.AspNetCore.Mvc.ViewResult in 1.2038ms.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view Index.
fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {7735cb78-2373-4fd0-9d95-3e1d15187ed3} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Index executed in 474.2345ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action myproject.Controllers.AccountController.Index (myproject) in 542.9143ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'myproject.Controllers.AccountController.Index (myproject)'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 721.9911ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://myproject/account  
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Cookies was not authenticated. Failure message: Unprotect ticket failed
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'myproject.Controllers.AccountController.Index (myproject)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Index", controller = "Account"}. Executing action myproject.Controllers.AccountController.Index (myproject)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method myproject.Controllers.AccountController.Index (myproject) with arguments () - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method myproject.Controllers.AccountController.Index (myproject), returned result Microsoft.AspNetCore.Mvc.ViewResult in 0.0353ms.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view Index.
fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {7735cb78-2373-4fd0-9d95-3e1d15187ed3} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Index executed in 14.005ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action myproject.Controllers.AccountController.Index (myproject) in 14.8023ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'myproject.Controllers.AccountController.Index (myproject)'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 20.9642ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://myproject/account application/x-www-form-urlencoded 229
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Cookies was not authenticated. Failure message: Unprotect ticket failed
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'myproject.Controllers.AccountController.Login (myproject)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Login", controller = "Account"}. Executing action myproject.Controllers.AccountController.Login (myproject)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method myproject.Controllers.AccountController.Login (myproject) with arguments (, myproject.Models.UserModel) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method myproject.Controllers.AccountController.Login (myproject), returned result Microsoft.AspNetCore.Mvc.LocalRedirectResult in 91.0294ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.LocalRedirectResultExecutor[1]
      Executing LocalRedirectResult, redirecting to /account/secure.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action myproject.Controllers.AccountController.Login (myproject) in 128.7308ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'myproject.Controllers.AccountController.Login (myproject)'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 138.6606ms 302 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://myproject/account/secure  
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Cookies was not authenticated. Failure message: Unprotect ticket failed
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'myproject.Controllers.AccountController.Secure (myproject)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Secure", controller = "Account"}. Executing action myproject.Controllers.AccountController.Secure (myproject)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
      AuthenticationScheme: Cookies was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action myproject.Controllers.AccountController.Secure (myproject) in 20.8258ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'myproject.Controllers.AccountController.Secure (myproject)'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 28.3781ms 302 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://myproject/Account/?ReturnUrl=%2Faccount%2Fsecure  
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[7]
      Cookies was not authenticated. Failure message: Unprotect ticket failed
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'myproject.Controllers.AccountController.Index (myproject)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Index", controller = "Account"}. Executing action myproject.Controllers.AccountController.Index (myproject)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method myproject.Controllers.AccountController.Index (myproject) with arguments (/account/secure) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method myproject.Controllers.AccountController.Index (myproject), returned result Microsoft.AspNetCore.Mvc.ViewResult in 0.008ms.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view Index.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Index executed in 1.0821ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action myproject.Controllers.AccountController.Index (myproject) in 1.4714ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'myproject.Controllers.AccountController.Index (myproject)'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.8485ms 200 text/html; charset=utf-8

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: provider
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal)
   at myproject.Helpers.UserManager.SignIn(HttpContext httpContext, UserModel user, Boolean isPersistent) in C:\Web\myproject.com\myproject\myproject\Helpers\UserManager.cs:line 36
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by jkotalik** [comment]
With regards to w3wp.exe crashing, that behavior is expected because the is an unhandled exception on a background thread.

In UserManager.cs, your SignIn() method has an async void, which should be async Task. My guess is that because it isn't awaited, correctly, an exception is thrown on a background thread which isn't caught, causing w3wp.exe to crash. See https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#async-void for why async void is a BAD idea.

Closing for now as I'm fairly certain that will fix your issue.

**Comment by shapeh** [comment]
@jkotalik - you are completely right, that did the trick - thanks! 🥇
