### ISSUE TITLE
[Test Failure] StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#6760]
```
2019-01-16T19:48:19.2565528Z   [xUnit.net 00:00:15.39]     Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation(methodName: "CancelableStream2", args: [1, 2]) [FAIL]
2019-01-16T19:48:19.4818914Z   Skipped  Microsoft.AspNetCore.SignalR.Tests.WebSocketsTransportTests.WebSocketsTransportSendsUserAgent
2019-01-16T19:48:19.4823363Z   Failed   Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation(methodName: "CancelableStream2", args: [1, 2])
2019-01-16T19:48:19.4826518Z   Error Message:
2019-01-16T19:48:19.4831817Z    System.TimeoutException : Operation in StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation timed out at /_/src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs:2753
2019-01-16T19:48:19.4833840Z   Stack Trace:
2019-01-16T19:48:19.4839238Z      at System.Threading.Tasks.TaskExtensions.<OrTimeout>d__6`1.MoveNext() in F:\vsagent\9\s\src\SignalR\common\testassets\Tests.Utils\TaskExtensions.cs:line 65
2019-01-16T19:48:19.4842362Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-16T19:48:19.4844811Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-01-16T19:48:19.4846764Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-16T19:48:19.4849834Z      at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2019-01-16T19:48:19.4852153Z      at Microsoft.AspNetCore.SignalR.Tests.HubConnectionHandlerTests.<StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation>d__81.MoveNext() in /_/src/SignalR/server/SignalR/test/HubConnectionHandlerTests.cs:line 2753
2019-01-16T19:48:19.4855595Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-16T19:48:19.4858397Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-01-16T19:48:19.4860926Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-16T19:48:19.4864113Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-16T19:48:19.4865934Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-01-16T19:48:19.4867514Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-16T19:48:19.4870291Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-16T19:48:19.4872602Z      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2019-01-16T19:48:19.4875036Z      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-01-16T19:48:19.4877362Z   Standard Output Messages:
2019-01-16T19:48:19.4879988Z    | [0.016s] TestLifetime Information: Starting test StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation-CancelableStream2-System.Object[] at 2019-01-16T19:48:14
2019-01-16T19:48:19.4883650Z    | [0.016s] Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver Debug: Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
2019-01-16T19:48:19.4886606Z    | [0.016s] Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver Debug: Registered SignalR Protocol: messagepack, implemented by Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.
2019-01-16T19:48:19.4888681Z    | [0.031s] Microsoft.AspNetCore.SignalR.HubConnectionHandler Debug: OnConnectedAsync started.
2019-01-16T19:48:19.4890792Z    | [0.031s] Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver Debug: Found protocol implementation for requested protocol: json.
2019-01-16T19:48:19.4893500Z    | [0.031s] Microsoft.AspNetCore.SignalR.HubConnectionContext Information: Completed connection handshake. Using HubProtocol 'json'.
2019-01-16T19:48:19.4896177Z    | [0.031s] Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher Debug: Received stream hub invocation: StreamInvocation { InvocationId: "d62273687c374ca4ade7e05539146a17", Target: "CancelableStream2", Arguments: [ 1, 2 ] }.
2019-01-16T19:48:19.4899077Z    | [0.031s] Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher Debug: Canceling stream for invocation d62273687c374ca4ade7e05539146a17.
2019-01-16T19:48:19.4902455Z    | [5.047s] Microsoft.AspNetCore.SignalR.HubConnectionHandler Debug: OnConnectedAsync ending.
2019-01-16T19:48:19.4904555Z    | [5.047s] TestLifetime Information: Finished test StreamHubMethodCanAcceptCancellationTokenAsArgumentAndBeTriggeredOnCancellation-CancelableStream2-System.Object[] in 5.0263646s
```

**Comment by jkotalik** [comment]
Failure: https://github.com/aspnet/AspNetCore/runs/50871258

**Comment by mikaelm12** [comment]
Will take a look at this

**Comment by anurse** [comment]
We're going to close this and reset the clock on this. We have a suspicion that we'll need to increase the timeout on it.
