### ISSUE TITLE
[Test Failure] FindsCustomWatchItems 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#6768]
```
2019-01-16T19:54:51.9058516Z   [xUnit.net 00:00:48.84]     Microsoft.DotNet.Watcher.Tools.Tests.MsBuildFileSetFactoryTest.FindsCustomWatchItems [FAIL]
2019-01-16T19:54:52.2754458Z   Failed   Microsoft.DotNet.Watcher.Tools.Tests.MsBuildFileSetFactoryTest.FindsCustomWatchItems
2019-01-16T19:54:52.2855320Z   Error Message:
2019-01-16T19:54:52.2856062Z    System.TimeoutException : The operation at /_/src/Tools/dotnet-watch/test/MsBuildFileSetFactoryTest.cs:281 timed out after reaching the limit of 30000ms.
2019-01-16T19:54:52.2909964Z   Stack Trace:
2019-01-16T19:54:52.2980165Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2019-01-16T19:54:52.3050861Z      at Microsoft.DotNet.Watcher.Tools.Tests.MsBuildFileSetFactoryTest.GetFileSet(MsBuildFileSetFactory filesetFactory) in /_/src/Tools/dotnet-watch/test/MsBuildFileSetFactoryTest.cs:line 279
2019-01-16T19:54:52.3077721Z      at Microsoft.DotNet.Watcher.Tools.Tests.MsBuildFileSetFactoryTest.FindsCustomWatchItems() in /_/src/Tools/dotnet-watch/test/MsBuildFileSetFactoryTest.cs:line 41
2019-01-16T19:54:52.3123762Z   --- End of stack trace from previous location where exception was thrown ---
2019-01-16T19:54:52.3206532Z   Standard Output Messages:
2019-01-16T19:54:52.3265142Z    verbose: Running MSBuild target 'GenerateWatchList' on 'C:\Users\vsagent\AppData\Local\Temp\dotnet-watch-tests\1366b3c306a64891952387f2e1dc6599\Project1.csproj'
2019-01-16T19:54:52.3418579Z    verbose: Started 'F:\vsagent\15\.dotnet\x64\dotnet.exe' with process id 3888
2019-01-16T19:54:56.4683461Z    verbose: Process id 3888 ran for 32468ms
2019-01-16T19:54:56.4684412Z    verbose: Watching 3 file(s) for changes

```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=74189

**Comment by javiercn** [comment]
@natemcmaster 

I'm skipping it as it blocking PRs. Will you do the needful?

**Comment by natemcmaster** [comment]
I won't because I don't have bandwidth for this. cc @muratg 

Instead of skipping, can you have @mkArtakMSFT or @Eilon override the required PR check to get your changes merged? I suspect there is a real product issue with file watching and don't want to totally suppress these failures.

**Comment by javiercn** [comment]
@natemcmaster Yeah, I ended up doing that as when I tried to skip it, another one in the same area started causing issues

**Comment by Eilon** [comment]
Unfortunately no great rules right now. Added you to a thread where we're discussing.

**Comment by BrennanConroy** [comment]
Should be fixed via https://github.com/aspnet/AspNetCore/pull/7173
