### ISSUE TITLE
Bad request data: "Malformed request: invalid headers."

### ISSUE THREAD

**Issue by msschl** [aspnet/AspNetCore#6799]
### Describe the bug

I have the following setup:
![picture](https://user-images.githubusercontent.com/5054780/51325379-135b0380-1a6d-11e9-9788-728faead6425.png)

All requests are correctly forwarded. The logs of the asp net core app outputs:
```
Hosting environment: Production
Content root path: C:\Data\site1\blue\
Now listening on: http://127.0.0.1:29403
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly site1.Service
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly Microsoft.AspNetCore.Server.IISIntegration
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLJSGRQPGA2E" started.
info: Microsoft.AspNetCore.Server.Kestrel[17]
      => ConnectionId:0HLJSGRQPGA2E
      Connection id "0HLJSGRQPGA2E" bad request data: "Malformed request: invalid headers."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      => ConnectionId:0HLJSGRQPGA2E
      Connection id "0HLJSGRQPGA2E" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLJSGRQPGA2E" sending FIN because: "The Socket transport's send loop completed gracefully."
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLJSGRQPGA2E" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLJSGRQPGA2F" started.
info: Microsoft.AspNetCore.Server.Kestrel[17]
      => ConnectionId:0HLJSGRQPGA2F
      Connection id "0HLJSGRQPGA2F" bad request data: "Malformed request: invalid headers."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      => ConnectionId:0HLJSGRQPGA2F
      Connection id "0HLJSGRQPGA2F" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLJSGRQPGA2F" sending FIN because: "The Socket transport's send loop completed gracefully."
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLJSGRQPGA2F" stopped.
```

### Configuration
- `mainentrypoint.server.com` site acting as a reverse proxy to the server-farm:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <clear />
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://farm.site1.local/{R:1}" logRewrittenUrl="true" />
                </rule>
            </rules>
            <rewriteMaps>
                <rewriteMap name="farm.site1.local" />
            </rewriteMaps>
        </rewrite>
        <httpErrors errorMode="DetailedLocalOnly" />
    </system.webServer>
</configuration>
```

- hosts file in `C:\Windows\System32\drivers\etc`:
```
127.0.0.1 farm.site1.local
127.0.0.1 blue.site1.local
127.0.0.1 green.site1.local
```

- server-farm configuration:
```
- name: farm.site1.local
- disk-caching: disabled
- servers:
  - blue.site1.local:
    - http port: 8000
  - green.site1.local:
    - http port: 8001
```

- `blue.site1.local` and `green.site1.local`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Site1.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false">
            </aspNetCore>
    </system.webServer>
  </location>
</configuration>
<!--ProjectGuid: A6177D24-065B-421B-B6A4-0C89540FAEA2-->
```
```
- name: blue.site1.local:
  - binding: http, port: 8000, IP-Address: 127.0.0.1
- name: green.site1.local:
  - binding: http, port: 8001, IP-Address: 127.0.0.1
```

### System Info
- Windows Server 2016 (Version 1607 (Build 14393.2125))
- Internet Information Services (Version 10.0.14393.0)
- IIS-URL-Rewrite-Module 2 (Version 7.2.1980)
- Microsoft Application Request Routing 2.5 (Version 2.5.1130)
- Microsoft Web Farm Framework (Version 1.1.1292)
- Microsoft Web Deploy 2.0 (Version 2.0.1070)
- Microsoft Web Platform Installer 5.0 (Version 5.0.50430.0)
- SSL Wildcard Certificate ("*.domain.de")
```
> dotnet --info

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
---
Updated:
- Added Configuration
- Added System Info

**Comment by blowdart** [comment]
Do you have an example of a request that is causing this?

**Comment by msschl** [comment]
It's a normal HTTPS GET to the main entrypoint with firefox:

```
GET https://mainentrypoint.server.com/
Host: mainentrypoint.server.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
TE: Trailers
```

**Comment by msschl** [comment]
When I change the binding for the site `blue.site.local` to
```
- http, 80, IP-Address of host Machine
- https, 443, IP-Address of host Machine + the installed certificate of the host machine (installed in Store: LocalMachine; My)
```

and execute the request (see comment above), everything works normally.

**Comment by jftsaraiva** [comment]
I have a very similar issue. 

In my case it works fine with IIS 8, 9, ... but doesn't work with IIS 7.5 and one specific SSL certificate.

That SSL certificate has a subject with an accented character:

![image](https://user-images.githubusercontent.com/2278476/51603855-e5f5d600-1f02-11e9-86aa-e78fe48fe667.png)

When URL Rewrite rewrites to http://localhost... in the log generated by `Failed Request Tracing Rules` I notice that X-ARR-SSL Header is still present with:

```
2048\|256\|C= (...)  O= ... Polit%E9cnico ... 
```

I think the issue is here. 

Why it works with IIS 8 (or newer) and doesn't with 7.5? Why it works with other SSL Cert? I can't understand.

I tried remove X-ARR-SSL from header following: 
- https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/setting-http-request-headers-and-iis-server-variables 
- https://forums.iis.net/post/2116033.aspx 

but it doesn't remove or change the header :-(, local asp.net core v2.2 app always receive original X-ARR-SSL header.

**Comment by msschl** [comment]
Any news on this 😅

**Comment by anurse** [comment]
> It's a normal HTTPS GET to the main entrypoint with firefox:

This is the request the browser is sending right? Could you get the request that the ASP.NET Core app is receiving using something like [Wireshark](https://www.wireshark.org/) or [Fiddler](https://www.telerik.com/fiddler) on the ASP.NET Core server?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by msschl** [comment]
Sorry for the late response. I've been trying to recreate this issue for a while now, but currently everything is working fine and as expected. I don't know why, since we haven't changed a thing. The only think I can imagine helped resolving this issue was a big poweroutage we had lately and thous a hard restart of this server.

So everything is working as expected now. Thank you very much.
