### ISSUE TITLE
Test failure: EmailFactorFailsAfterSecurityStampChangeTest

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspNetCore#6942]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=614714&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
System.Security.Cryptography.CryptographicException : An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
---- System.Xml.XmlException : Root element is missing.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs:line 141
   at Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1.GenerateAsync(String purpose, UserManager`1 manager, TUser user) in /_/src/Identity/Core/src/DataProtectionTokenProvider.cs:line 86
   at Microsoft.AspNetCore.Identity.Test.UserManagerSpecificationTestBase`2.EmailFactorFailsAfterSecurityStampChangeTest() in /_/src/Identity/Specification.Tests/src/UserManagerSpecificationTests.cs:line 1841
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath) in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 104
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext() in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 83
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements() in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 68
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys() in /_/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs:line 148
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 57
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 254
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 186
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing() in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 142
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs:line 102
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @ajcvickers

<details>
<summary>Additional details</summary>
<table>
<thead>
<tr>
<th>
Key
</th>
<th>
Value
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
_Type
</td>
<td>
<pre>
&quot;TriageBuildFailures.TeamCity.TeamCityBuild&quot;
</pre>
</td>
</tr>
<tr>
<td>
Id
</td>
<td>
<pre>
&quot;614714&quot;
</pre>
</td>
</tr>
<tr>
<td>
CIType
</td>
<td>
<pre>
&quot;TriageBuildFailures.TeamCity.TeamCityClientWrapper&quot;
</pre>
</td>
</tr>
<tr>
<td>
BuildTypeID
</td>
<td>
<pre>
&quot;XPlat_Windows_Win2008r2_Universe&quot;
</pre>
</td>
</tr>
<tr>
<td>
BuildName
</td>
<td>
<pre>
&quot;Win2008R2-Universe&quot;
</pre>
</td>
</tr>
<tr>
<td>
Status
</td>
<td>
<pre>
1
</pre>
</td>
</tr>
<tr>
<td>
Branch
</td>
<td>
<pre>
&quot;master&quot;
</pre>
</td>
</tr>
<tr>
<td>
StartDate
</td>
<td>
<pre>
&quot;2019-01-17T10:49:27-08:00&quot;
</pre>
</td>
</tr>
<tr>
<td>
WebURL
</td>
<td>
<pre>
&quot;http://aspnetci/viewLog.html?buildId=614714&amp;buildTypeId=XPlat_Windows_Win2008r2_Universe&quot;
</pre>
</td>
</tr>
<tr>
<td>
Failure:Status
</td>
<td>
<pre>
1
</pre>
</td>
</tr>
<tr>
<td>
Failure:Name
</td>
<td>
<pre>
&quot;VSTest: Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.Microsoft.AspNetCore.Identity.EntityFrameworkCore.InMemory.Test.InMemoryEFOnlyUsersTest.EmailFactorFailsAfterSecurityStampChangeTest&quot;
</pre>
</td>
</tr>
<tr>
<td>
Failure:BuildId
</td>
<td>
<pre>
&quot;614714&quot;
</pre>
</td>
</tr>
<tr>
<td>
Failure:TestId
</td>
<td>
<pre>
&quot;13015&quot;
</pre>
</td>
</tr>
</tbody>
</table>
</details>

**Comment by blowdart** [comment]
To Nate please. I’m on a bus trying to get to the airport so I can’t assign.


________________________________

**Comment by natemcmaster** [comment]
Yeah...I'm not likely to investigate this anytime soon. Okay if this sits untouched for a while (or forever)? I'm starting leave soon and have higher priorities than investigating a test failure that happened once in about 1,200 runs.

**Comment by ajcvickers** [comment]
@blowdart @Tratcher @HaoK This is causing quite a few test failures, and also seems like a product bug that should be fixed. Can we figure out who it should be assigned to (as a product bug) and what the priority is?
/cc @anurse @Pilchie @mkArtakMSFT

**Comment by BrennanConroy** [comment]
Closing as there hasn't been an issue since https://github.com/aspnet/AspNetCore/pull/10990 was merged
