### ISSUE TITLE
Generic Methods on SignalR Hubs Cause Poorly Worded Exceptions

### ISSUE THREAD

**Issue by HelloKitty** [aspnet/AspNetCore#6949]
### Describe the bug

When a SignalR hub contains generic public method members it will fail on SignalR registration. This itself is alright but the resulting exception is nonsense. It does not indicate the actual problem which leads to a goose chase for some people I'd imagine.

### To Reproduce

Register a SignalR hub with a generic public method.

### Expected behavior

A better exception message thrown when generic public methods are attempted to be registered by SignalR

### Additional context

Information I found related to this issue when searching: https://github.com/giraffe-fsharp/Giraffe/issues/295

I originally posted my findings in that issue. Definitely seems to be related to public generic method members.

Workarounds include making generic methods non-public.

**Comment by muratg** [comment]
The current error message seems to be 
```

Unhandled Exception: System.ArgumentException: Type a contains generic parameters
Parameter name: type
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Int32 index)
   at System.Dynamic.Utils.TypeUtils.ValidateType(Type type, String paramName, Boolean allowByRef, Boolean allowPointer)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.GetExecutor(MethodInfo methodInfo, TypeInfo targetTypeInfo)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor..ctor(MethodInfo methodInfo, TypeInfo targetTypeInfo, Object[] parameterDefaultValues)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DiscoverHubMethods()
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1..ctor(IServiceScopeFactory serviceScopeFactory, IHubContext`1 hubContext, IOptions`1 hubOptions, IOptions`1 globalHubOptions, ILogger`1 logger)
```

We can make this better.
