### ISSUE TITLE
[Test failure] RendererTest.CanRenderAsyncComponentsWithMultipleAsyncChildren

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#6953]
https://dev.azure.com/dnceng/public/_build/results?buildId=78506

```
 [xUnit.net 00:00:02.02]     Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncComponentsWithMultipleAsyncChildren [FAIL]
2019-01-23T17:10:22.2646129Z   Failed   Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncComponentsWithMultipleAsyncChildren
2019-01-23T17:10:22.2699250Z   Error Message:
2019-01-23T17:10:22.2754711Z    System.NullReferenceException : Object reference not set to an instance of an object.
2019-01-23T17:10:22.2977333Z   Stack Trace:
2019-01-23T17:10:22.3046592Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 439
2019-01-23T17:10:22.3133950Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 394
2019-01-23T17:10:22.3328157Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 370
2019-01-23T17:10:22.3481592Z      at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment) in /_/src/Components/Components/src/RenderHandle.cs:line 43
2019-01-23T17:10:22.3744799Z      at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in /_/src/Components/Components/src/ComponentBase.cs:line 111
2019-01-23T17:10:22.3792890Z      at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParameters() in /_/src/Components/Components/src/ComponentBase.cs:line 231
2019-01-23T17:10:22.3920211Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessAsynchronousWork() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 198
2019-01-23T17:10:22.3957322Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterCollection initialParameters) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 185
2019-01-23T17:10:22.4243861Z      at Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncComponentsWithMultipleAsyncChildren() in /_/src/Components/Components/test/RendererTest.cs:line 399
2019-01-23T17:10:22.4282433Z   --- End of stack trace from previous location where exception was thrown ---
```

/cc @SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
Looking into it

**Comment by pakrym** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=89124&view=ms.vss-test-web.build-test-results-tab

**Comment by javiercn** [comment]
I have a PR out for this

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/commit/f456e3d153039986e62d969b1c9d63aa301daf65
