### ISSUE TITLE
[Helix] 2 failing kestrel tests

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#7000]
OSX InMemory.FunctionalTests are failing:

```
[xUnit.net 00:00:01.37]     TlsHandshakeRejectsTlsLessThan12 [SKIP]
Skipped  TlsHandshakeRejectsTlsLessThan12
The active test run was aborted. Reason: Assertion Failed
System.InvalidOperationException: Block is being returned to disposed pool
   at System.Buffers.MemoryPoolThrowHelper.ThrowInvalidOperationException_BlockReturnedToDisposedPool(DiagnosticPoolBlock block) in /_/src/Shared/Buffers.MemoryPool/MemoryPoolThrowHelper.cs:line 52
   at System.Buffers.DiagnosticMemoryPool.Return(DiagnosticPoolBlock block) in /_/src/Shared/Buffers.MemoryPool/DiagnosticMemoryPool.cs:line 84
   at System.Buffers.DiagnosticPoolBlock.Dispose(Boolean disposing) in /_/src/Shared/Buffers.MemoryPool/DiagnosticPoolBlock.cs:line 87
   at System.Buffers.MemoryManager`1.System.IDisposable.Dispose()
   at System.IO.Pipelines.BufferSegment.ResetMemory()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2OutputProducer.ProcessDataWrites() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs:line 223
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2OutputProducer.ProcessDataWrites() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs:line 223
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.<>c.<.cctor>b__11_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2FrameWriter.WriteDataAsync(Int32 streamId, StreamOutputFlowControl flowControl, ReadOnlySequence`1 data, Int64 dataLength, Boolean endStream) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2FrameWriter.cs:line 386
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.<>c.<.cctor>b__11_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.ThreadPoolAwaitable.<>c.<OnCompleted>b__6_0(Object state) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/ThreadPoolAwaitable.cs:line 27
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Results File: /Users/dotnet-bot/dotnetbuild/work/7975f88e-17fb-4aa8-835e-db860217d7de/Work/8c94f244-418c-4bb4-9189-88cd92931907/Exec/TestResults/_dci-mac-build-093_2019-01-24_13_18_37.trx

```

Ubuntu Interop.FunctionalTest fails:
```
Failed   RunIndividualTestCase
Error Message:
 System.ComponentModel.Win32Exception : Permission denied
Stack Trace:
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 49
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 62
```

**Comment by HaoK** [comment]
in InMemory.FunctionalTests/Http2/Http2TimeoutTests.cs DATA_Sent_TooSlowlyDueToSocketBackPressureOnSmallWrite_AbortsConnectionAfterGracePeriod is also skipped

**Comment by HaoK** [comment]
Http2StreamTests.ContentLength_Received_ReadViaPipes also skipped due to failing on Debian queue

**Comment by jkotalik** [comment]
Can you give more details on the ContentLength_Received_ReadViaPipes failure?

**Comment by HaoK** [comment]
I don't have anything more than the logs:

https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190225.37/workItem/InMemory.FunctionalTests-netcoreapp3.0/wilogs

```
Failed   ContentLength_Received_ReadViaPipes
Error Message:
 Assert.Equal() Failure
Expected: GOAWAY
Actual:   RST_STREAM
Stack Trace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.VerifyGoAway(Http2Frame frame, Int32 expectedLastStreamId, Http2ErrorCode expectedErrorCode) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 1149
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.WaitForConnectionErrorAsync[TException](Boolean ignoreNonGoAwayFrames, Int32 expectedLastStreamId, Http2ErrorCode expectedErrorCode, String[] expectedErrorMessage) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 1170
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.ContentLength_Received_ReadViaPipes() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1055
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 | [0.000s] TestLifetime Information: Starting test ContentLength_Received_ReadViaPipes at 2019-02-25T22:14:36
 | [0.008s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
 | [0.008s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
 | [0.008s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received SETTINGS frame for stream ID 0 with length 0 and flags NONE
 | [0.008s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
 | [0.009s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received HEADERS frame for stream ID 1 with length 12343 and flags NONE
 | [0.015s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received CONTINUATION frame for stream ID 1 with length 4121 and flags END_HEADERS
 | [0.017s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id ":00000001": started reading request body.
 | [0.017s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received DATA frame for stream ID 1 with length 12 and flags END_STREAM
 | [0.019s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "(null)", Request id ":00000001": An unhandled exception was thrown by the application.
 | Xunit.Sdk.TrueException: Assert.True() Failure
 | Expected: True
 | Actual:   False
 |    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 96
 |    at Xunit.Assert.True(Boolean condition) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 63
 |    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.<>c.<<ContentLength_Received_ReadViaPipes>b__31_0>d.MoveNext() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1025
 | --- End of stack trace from previous location where exception was thrown ---
 |    at Microsoft.AspNetCore.Testing.DummyApplication.ProcessRequestAsync(HttpContext context) in /_/src/Servers/Kestrel/shared/test/DummyApplication.cs:line 45
 |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 573
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending HEADERS frame for stream ID 1 with length 55 and flags END_HEADERS
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending DATA frame for stream ID 1 with length 0 and flags END_STREAM
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id ":00000001": done reading request body.
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "(null)", Request id ":00000001": the application completed without reading the entire request body.
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)" is closed. The last processed stream ID was 1.
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0
 | [0.021s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
 | [0.024s] TestLifetime Information: Finished test ContentLength_Received_ReadViaPipes in 0.023529599999999998s

```

**Comment by jkotalik** [comment]
Ah found the issue. I think it is only a test issue.

**Comment by HaoK** [comment]
Cool if the fix is relatively straight forward, you can add it to my PR here https://github.com/aspnet/AspNetCore/pull/7763 and I can merge it with the fix instead of the skip

**Comment by jkotalik** [comment]
I'm going to need to investigate more. Feel free to skip for now until I identify if there is a perf regression.

**Comment by anurse** [comment]
Seeing some more asserts here: https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190301.38/workItem/InMemory.FunctionalTests-netcoreapp3.0/wilogs

```
Microsoft (R) Test Execution Command Line Tool Version 16.0.0-preview-20181205-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:02.45]     TlsHandshakeRejectsTlsLessThan12 [SKIP]
Skipped  TlsHandshakeRejectsTlsLessThan12
[xUnit.net 00:00:05.23]     AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterCooldownExpires [SKIP]
Skipped  AbortedStream_ResetsAndDrainsRequest_RefusesFramesAfterCooldownExpires
[xUnit.net 00:00:09.72]     DATA_Sent_TooSlowlyDueToSocketBackPressureOnSmallWrite_AbortsConnectionAfterGracePeriod [SKIP]
Skipped  DATA_Sent_TooSlowlyDueToSocketBackPressureOnSmallWrite_AbortsConnectionAfterGracePeriod
[xUnit.net 00:00:10.50]     ContentLength_Received_ReadViaPipes [SKIP]
Skipped  ContentLength_Received_ReadViaPipes
The active test run was aborted. Reason: Assertion Failed
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.UpdateConnectionState() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 1054
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPoolGlobals.<>c.<.cctor>b__5_0(Object state)
   at System.IO.Pipelines.InlineScheduler.UnsafeSchedule(Action`1 action, Object state)
   at System.IO.Pipelines.Pipe.CancelPendingRead()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.CancelPendingRead()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.IRequestProcessor.Tick(DateTimeOffset now) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 964
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.OnHeartbeat(Object state) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 477
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

(note that `ContentLength_Received_ReadViaPipes` is *not* the culprit, it's just the log message before the assertion)

**Comment by anurse** [comment]
@jkotalik is doing a full review of flaky/skipped tests, and I'd like to keep our test failure issues down to what RaaS shows (and Justin's work).
