### ISSUE TITLE
Microsoft.AspNetCore.SpaServices broken in NodeJS version > v8.11.3

### ISSUE THREAD

**Issue by k-vekos** [aspnet/AspNetCore#7067]
### Describe the bug
Microsoft.AspNetCore.SpaServices throw error "Failed to proxy the request" when running on NodeJS at a version greater than v8.11.3.

### To Reproduce
1. Have NodeJS v8.15.0 or greater installed
1. Open VS2017
2. Go to File > New > Project...
3. Select 'ASP.NET Core Web Application' click OK
4. On subsequent dialog window select '.NET Framework', 'ASP.NET Core 2.2', 'Angular', click OK
5. Open the resulting Solution
6. On the toolbar at the top, select the dropdown green arrow (debug) button and change selection to "\<Name of Project\>" then press F5 to build and run in Debug mode
7. Kismet console window opens and runs as expected but any attempts to connect to the hosted application will eventually timeout with this exception:

```
System.Net.Http.HttpRequestException: Failed to proxy the request to http://localhost:2331/, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:2331/.

The underlying exception message was 'An error occurred while sending the request.'.Check the InnerException for more details. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.<PerformProxyRequest>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.<PerformProxyRequest>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

8. Uninstall NodeJS v8.15.0, install NodeJS v8.11.3.
9. Rebuild and F5 to run the application again, now it works fine.

### Expected behavior
Application should work correctly with all versions of NodeJS up to v10 (Highest supported by Angular library as of v7)

### Screenshots
What Kestrel console shows with NodeJS v8.15.0 installed when I try to open the app in a browser:
![2019-01-28 12_53_13-ng_nodejsv8-15-0](https://user-images.githubusercontent.com/23462254/51857386-1e7d2180-2300-11e9-9237-5ca86ddea86f.png)

What it looks like when I switch tao v8.11.3 and is working:
![2019-01-28 12_53_13-ng_nodejsv8-11-4](https://user-images.githubusercontent.com/23462254/51857103-6c455a00-22ff-11e9-8dee-b114bd5d2209.png)

### Additional context
`dotnet --info` output: 
[dotnet.txt](https://github.com/aspnet/AspNetCore/files/2804293/dotnet.txt)

Visual Studio 2017 = v15.9.6
npm = v5.6.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @k-vekos.
Are you still facing this issue?

**Comment by weitenghuang** [comment]
I have the same issue with ASP.NET Core 2.1 and `UseReactDevelopmentServer`

**Comment by k-vekos** [comment]
@mkArtakMSFT I'm no longer having this issue on Node v10.15.3
