### ISSUE TITLE
Code blocks (@{ ... }) in TagHelper non-string attributes crash VS

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#7159]
### Describe the bug
Having a TagHelper with a non-string attribute and attempting to set it using a code block (@{ }) crashes VS.

and using 
### To Reproduce
1. In a Razor file in VS that has the MVC TagHelpers type `<script asp-append-version="@{123}"></script>`
2. See VS crash

```
Unable to cast object of type 'Microsoft.AspNetCore.Razor.Language.Syntax.CSharpExpressionLiteralSyntax' to type 'Microsoft.AspNetCore.Razor.Language.Syntax.RazorMetaCodeSyntax'.
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpStatementBody(CSharpStatementBodySyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpStatementBodySyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpStatement(CSharpStatementSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpStatementSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitCSharpCodeBlock(CSharpCodeBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.CSharpCodeBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitMarkupBlock(MarkupBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.AttributeValueRewriter.VisitMarkupDynamicAttributeValue(MarkupDynamicAttributeValueSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupDynamicAttributeValueSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitGenericBlock(GenericBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.GenericBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.RewriteAttributeValue(TryParseResult result, RazorBlockSyntax attributeValue)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.TryParseAttribute(String tagName, MarkupAttributeBlockSyntax attributeBlock, IEnumerable`1 descriptors, ErrorSink errorSink, HashSet`1 processedBoundAttributeNames)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.Rewrite(String tagName, RazorParserFeatureFlags featureFlags, MarkupStartTagSyntax startTag, TagHelperBinding bindingResult, ErrorSink errorSink, RazorSourceDocument source)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewriter.TryRewriteTagHelperStart(MarkupStartTagSyntax startTag, MarkupTagHelperStartTagSyntax& rewritten, TagHelperInfo& tagHelperInfo)
```

### Expected behavior
VS doesn't crash, the value is translated into C# as `ScriptTagHelper.AppendVersion = {123}` (invalid in normal TagHelpers but I believe this works in Components.

**Comment by iAmBipinPaul** [comment]
@NTaylorMullen  not to forget that it does through the same exception in the case of 
`dotnet build` when running form the command prompt.
