### ISSUE TITLE
Flaky test: Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncComponentsWithAsyncChildInit

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#7226]
https://dev.azure.com/dnceng/public/_build/results?buildId=86394
```
Failed   Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncComponentsWithAsyncChildInit
2019-02-03T21:57:52.8854300Z   Error Message:
2019-02-03T21:57:52.8953670Z    System.NullReferenceException : Object reference not set to an instance of an object.
2019-02-03T21:57:52.8954810Z   Stack Trace:
2019-02-03T21:57:52.8955440Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 439
2019-02-03T21:57:52.8956100Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 394
2019-02-03T21:57:52.8956720Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 370
2019-02-03T21:57:52.8957470Z      at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment) in /_/src/Components/Components/src/RenderHandle.cs:line 43
2019-02-03T21:57:52.8957960Z      at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in /_/src/Components/Components/src/ComponentBase.cs:line 111
2019-02-03T21:57:52.8958130Z      at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParameters() in /_/src/Components/Components/src/ComponentBase.cs:line 231
2019-02-03T21:57:52.8958480Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessAsynchronousWork() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 198
2019-02-03T21:57:52.8959140Z      at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterCollection initialParameters) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 185
2019-02-03T21:57:52.8959310Z      at Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncComponentsWithAsyncChildInit() in /_/src/Components/Components/test/RendererTest.cs:line 339
2019-02-03T21:57:52.8960300Z   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by javiercn** [comment]
https://github.com/aspnet/AspNetCore/commit/f456e3d153039986e62d969b1c9d63aa301daf65
