### ISSUE TITLE
[Helix] Socket.BindTests failures on Fedora.27

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#7267]
Tracking issue for skipped socket bindtests

```
[xUnit.net 00:00:03.18]     RegisterAddresses_HostName_Success [FAIL]
Failed   RegisterAddresses_HostName_Success
Error Message:
 System.Net.Sockets.SocketException : Name or service not known
Stack Trace:
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 191
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 40

[xUnit.net 00:00:03.36]     ListenAnyIP_HostName_Success [FAIL]
Failed   ListenAnyIP_HostName_Success
Error Message:
 System.Net.Sockets.SocketException : Name or service not known
Stack Trace:
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_Success(String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 357
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_HostName_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 338
```

**Comment by HaoK** [comment]
This looks like `[HostNameIsReachable]` doesn't work properly for this OS

**Comment by HaoK** [comment]
The Libuv.BindTests variant of these also fail for this OS

**Comment by anurse** [comment]
Closing. RaaS is vigilant and @jkotalik is reviewing flaky tests.

**Comment by jkotalik** [comment]
@anurse can you transfer this to internal?

**Comment by jkotalik** [comment]
Actually, I now notice this is for fedora27 (which is deprecated). Let me try re-enabling them.

**Comment by anurse** [comment]
Still want me to transfer?

**Comment by jkotalik** [comment]
Nah let's just close it, I'll reopen if necessary.
