### ISSUE TITLE
[Helix] Kestrel H2SpecTests.RunIndividualTestCase fail on everything but OSX/Windows

### ISSUE THREAD

**Issue by HaoK** [aspnet/AspNetCore#7299]
Tracking for skipped test:

These fail on all non OSX/Windows helix queues

```
Failed   RunIndividualTestCase
Error Message:
 System.ComponentModel.Win32Exception : Permission denied
Stack Trace:
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 50
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 62
Results File: /home/helixbot/dotnetbuild/work/32dcc8b8-82df-4dd5-a871-9c071b0cfad6/Work/a0bfc0a8-4bfc-4323-839e-b6a701682461/Exec/TestResults/_a000P73_2019-02-06_06_35_35.trx

```

**Comment by jkotalik** [comment]
For some reason, this is now being done in test discovery and the skip condition isn't being evaluatated:
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190409.32/workItem/Interop.FunctionalTests-netcoreapp3.0/wilogs
```
dotnet-install: Installation finished successfully.
Exception thrown during test discovery.
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
[xUnit.net 00:00:00.81] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 42
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 63
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Xunit.MemberDataAttributeBase.GetData(MethodInfo testMethod) in C:\Dev\xunit\xunit\src\xunit.core\MemberDataAttributeBase.cs:line 66
   at Xunit.Sdk.DataDiscoverer.GetData(IAttributeInfo dataAttribute, IMethodInfo testMethod) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\DataDiscoverer.cs:line 25
   at Xunit.Sdk.TheoryDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo theoryAttribute) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TheoryDiscoverer.cs:line 212
    Http2
    RunIndividualTestCase
+ _commandExitCode=1
+ exit 1
```

**Comment by anurse** [comment]
Is it happening reliably? Could there be a chmod problem? Maybe `h2spec` isn't properly marked as executable?

**Comment by anurse** [comment]
Closing in lieu of https://github.com/aspnet/AspNetCore-Internal/issues/2225
