### ISSUE TITLE
[CI Failure]:  Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncNestedComponents() 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#7306]
https://dev.azure.com/dnceng/public/_build/results?buildId=88548&view=ms.vss-test-web.build-test-results-tab

```
System.NullReferenceException : Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 439
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue() in /_/src/Components/Components/src/Rendering/Renderer.cs:line 394
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 370
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment) in /_/src/Components/Components/src/RenderHandle.cs:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged() in /_/src/Components/Components/src/ComponentBase.cs:line 111
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParameters() in /_/src/Components/Components/src/ComponentBase.cs:line 231
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToPendingTasks(Task task) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 332
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterCollection parameters) in /_/src/Components/Components/src/Rendering/ComponentState.cs:line 144
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterCollection initialParameters) in /_/src/Components/Components/src/Rendering/Renderer.cs:line 180
   at Microsoft.AspNetCore.Components.Test.RendererTest.CanRenderAsyncNestedComponents() in /_/src/Components/Components/test/RendererTest.cs:line 251
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by javiercn** [comment]
This is already fixed as part of f456e3d153039986e62d969b1c9d63aa301daf65
