### ISSUE TITLE
Test failure Mvc.FunctionalTests.BasicTests.CanRender_ViewsWithLayout and Mvc.FunctionalTests.BasicApiTest.FindByStatus_WithToken_ReturnsOkAndPet

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/AspNetCore#7313]
https://dev.azure.com/dnceng/public/_build/results?buildId=88732 **Linux build**
```
Failed   Microsoft.AspNetCore.Mvc.FunctionalTests.BasicTests.CanRender_ViewsWithLayout(url: "")
2019-02-06T17:26:56.3141821Z   Error Message:
2019-02-06T17:26:56.3141902Z    System.IO.IOException : The request was aborted or the pipeline has finished
2019-02-06T17:26:56.3141966Z   Stack Trace:
2019-02-06T17:26:56.3142058Z      at Microsoft.AspNetCore.TestHost.ResponseStream.CheckNotComplete() in /_/src/Hosting/TestHost/src/ResponseStream.cs:line 238
2019-02-06T17:26:56.3142167Z      at Microsoft.AspNetCore.TestHost.ResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/Hosting/TestHost/src/ResponseStream.cs:line 156
2019-02-06T17:26:56.3142371Z      at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternalAsync(Boolean flushEncoder)
2019-02-06T17:26:56.3142488Z      at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2019-02-06T17:26:56.3142619Z      at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
2019-02-06T17:26:56.3142765Z      at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
2019-02-06T17:26:56.3142853Z      at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
2019-02-06T17:26:56.3142979Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 138
2019-02-06T17:26:56.3143132Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1090
2019-02-06T17:26:56.3143264Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1190
2019-02-06T17:26:56.3143430Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1071
2019-02-06T17:26:56.3143585Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 851
2019-02-06T17:26:56.3143714Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 791
2019-02-06T17:26:56.3143856Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1144
2019-02-06T17:26:56.3144009Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 753
2019-02-06T17:26:56.3144151Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 123
2019-02-06T17:26:56.3144290Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 81
2019-02-06T17:26:56.3144781Z      at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) in /_/src/Http/Routing/src/RouterMiddleware.cs:line 48
2019-02-06T17:26:56.3144898Z      at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) in /_/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs:line 139
2019-02-06T17:26:56.3145221Z      at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) in /_/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs:line 74
2019-02-06T17:26:56.3145435Z      at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) in /_/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs:line 105
2019-02-06T17:26:56.3145765Z      at Microsoft.AspNetCore.Mvc.FunctionalTests.CultureReplacerMiddleware.Invoke(HttpContext context) in /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Infrastructure/CultureReplacerMiddleware.cs:line 45
2019-02-06T17:26:56.3146302Z      at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext() in /_/src/Hosting/TestHost/src/HttpContextBuilder.cs:line 69
2019-02-06T17:26:56.3146635Z   --- End of stack trace from previous location where exception was thrown ---
2019-02-06T17:26:56.3146756Z      at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Hosting/TestHost/src/ClientHandler.cs:line 112
2019-02-06T17:26:56.3146894Z      at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-02-06T17:26:56.3147006Z      at Microsoft.AspNetCore.Mvc.FunctionalTests.BasicTests.CanRender_ViewsWithLayout(String url) in /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/BasicTests.cs:line 95
2019-02-06T17:26:56.3147473Z   --- End of stack trace from previous location where exception was thrown ---
```
and
```
Failed   Microsoft.AspNetCore.Mvc.FunctionalTests.BasicApiTest.FindByStatus_WithToken_ReturnsOkAndPet(username: "writer@example.com")
2019-02-06T17:26:56.3148554Z   Error Message:
2019-02-06T17:26:56.3148647Z    System.IO.IOException : The request was aborted or the pipeline has finished
2019-02-06T17:26:56.3148719Z   Stack Trace:
2019-02-06T17:26:56.3158511Z      at Microsoft.AspNetCore.TestHost.ResponseStream.CheckNotComplete() in /_/src/Hosting/TestHost/src/ResponseStream.cs:line 238
2019-02-06T17:26:56.3158687Z      at Microsoft.AspNetCore.TestHost.ResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/Hosting/TestHost/src/ResponseStream.cs:line 156
2019-02-06T17:26:56.3158828Z      at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternalAsync(Boolean flushEncoder)
2019-02-06T17:26:56.3158964Z      at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonOutputFormatter.cs:line 153
2019-02-06T17:26:56.3159149Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 138
2019-02-06T17:26:56.3159309Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 849
2019-02-06T17:26:56.3159456Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 121
2019-02-06T17:26:56.3159613Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 81
2019-02-06T17:26:56.3159757Z      at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) in /_/src/Http/Routing/src/RouterMiddleware.cs:line 48
2019-02-06T17:26:56.3159897Z      at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 61
2019-02-06T17:26:56.3160042Z      at BasicApi.Startup.<>c__DisplayClass6_1.<<Configure>b__3>d.MoveNext() in /_/src/Mvc/benchmarkapps/BasicApi/Startup.cs:line 149
2019-02-06T17:26:56.3160555Z   --- End of stack trace from previous location where exception was thrown ---
2019-02-06T17:26:56.3160872Z      at Microsoft.AspNetCore.Mvc.FunctionalTests.CultureReplacerMiddleware.Invoke(HttpContext context) in /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Infrastructure/CultureReplacerMiddleware.cs:line 45
2019-02-06T17:26:56.3161022Z      at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext() in /_/src/Hosting/TestHost/src/HttpContextBuilder.cs:line 69
2019-02-06T17:26:56.3161656Z   --- End of stack trace from previous location where exception was thrown ---
2019-02-06T17:26:56.3161767Z      at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Hosting/TestHost/src/ClientHandler.cs:line 112
2019-02-06T17:26:56.3161927Z      at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Testing/Handlers/CookieContainerHandler.cs:line 48
2019-02-06T17:26:56.3162107Z      at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Testing/Handlers/RedirectHandler.cs:line 56
2019-02-06T17:26:56.3162237Z      at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-02-06T17:26:56.3162386Z      at Microsoft.AspNetCore.Mvc.FunctionalTests.BasicApiTest.FindByStatus_WithToken_ReturnsOkAndPet(String username) in /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/BasicApiTest.cs:line 104
2019-02-06T17:26:56.3162694Z   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please look into this? Thanks!

**Comment by pranavkm** [comment]
@Tratcher has anything with the TestHost changed recently? This is rendering a vanilla view and none of the code in this area has changed for a while.

**Comment by Tratcher** [comment]
Nothing that should cause this. It's likely this is a secondary exception after the request has been aborted for another reason. Does it repro?

**Comment by pranavkm** [comment]
Huh, this is 2.2 which makes this weirder yet.

**Comment by BrennanConroy** [comment]
Another one on 2.2 https://dev.azure.com/dnceng/public/_build/results?buildId=90700
```
Failed   Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.CacheTagHelper_CanCachePortionsOfViewsPartialViewsAndViewComponents
2019-02-08T17:03:38.6896658Z   Error Message:
2019-02-08T17:03:38.6898264Z    System.IO.IOException : The request was aborted or the pipeline has finished
2019-02-08T17:03:38.7278187Z   Stack Trace:
2019-02-08T17:03:38.7278311Z      at Microsoft.AspNetCore.TestHost.ResponseStream.CheckNotComplete() in /_/src/Hosting/TestHost/src/ResponseStream.cs:line 238
2019-02-08T17:03:38.7278475Z      at Microsoft.AspNetCore.TestHost.ResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/Hosting/TestHost/src/ResponseStream.cs:line 156
2019-02-08T17:03:38.7278626Z      at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternalAsync(Boolean flushEncoder)
2019-02-08T17:03:38.7278751Z      at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
2019-02-08T17:03:38.7278930Z      at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
2019-02-08T17:03:38.7279104Z      at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
2019-02-08T17:03:38.7279367Z      at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
2019-02-08T17:03:38.7279498Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 138
2019-02-08T17:03:38.7279644Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1090
2019-02-08T17:03:38.7279772Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1190
2019-02-08T17:03:38.7279924Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1071
2019-02-08T17:03:38.7280079Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 851
2019-02-08T17:03:38.7280203Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 791
2019-02-08T17:03:38.7280341Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 1144
2019-02-08T17:03:38.7280482Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 753
2019-02-08T17:03:38.7280618Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 123
2019-02-08T17:03:38.7280746Z      at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() in /_/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/Internal/ResourceInvoker.cs:line 81
2019-02-08T17:03:38.7284427Z      at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext) in /_/src/Http/Routing/src/EndpointMiddleware.cs:line 42
2019-02-08T17:03:38.7284565Z      at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext) in /_/src/Http/Routing/src/EndpointRoutingMiddleware.cs:line 78
2019-02-08T17:03:38.7284693Z      at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context) in /_/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs:line 139
2019-02-08T17:03:38.7284815Z      at Microsoft.AspNetCore.Mvc.FunctionalTests.CultureReplacerMiddleware.Invoke(HttpContext context) in /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Infrastructure/CultureReplacerMiddleware.cs:line 45
2019-02-08T17:03:38.7285047Z      at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext() in /_/src/Hosting/TestHost/src/HttpContextBuilder.cs:line 69
2019-02-08T17:03:38.7286611Z   --- End of stack trace from previous location where exception was thrown ---
2019-02-08T17:03:38.7286778Z      at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Hosting/TestHost/src/ClientHandler.cs:line 112
2019-02-08T17:03:38.7286932Z      at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-02-08T17:03:38.7323372Z      at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.CacheTagHelper_CanCachePortionsOfViewsPartialViewsAndViewComponents() in /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.FunctionalTests/HtmlGenerationTest.cs:line 323
2019-02-08T17:03:38.7323893Z   --- End of stack trace from previous location where exception was thrown ---
```

**Comment by mkArtakMSFT** [comment]
Closing as this is probably fixed already.
