### ISSUE TITLE
StreamPipeReader is reading from stream after complete

### ISSUE THREAD

**Issue by JamesNK** [aspnet/AspNetCore#7329]
I am using a `StreamPipeReader` to read from a stream that contains multiple messages, resulting in multiple `PipeReader.ReadAsync()` calls. I think the stream pipe reader is always reading from the stream, even after the stream is complete.

What I think is happening is:

1. First `ReadAsync()` is reading all the data from the stream
2. Second `ReadAsync()` will read from the stream again, get no data and report on the result that the pipe is complete. The remaining data is correctly returned.
3. Third `ReadAsync()` will read from the stream again, and the stream errors.

Error:

```
Test Name:	Buffering_SuccessResponsesStreamed
Test FullName:	Grpc.AspNetCore.FunctionalTests.ServerStreamingMethodTests.Buffering_SuccessResponsesStreamed
Test Source:	C:\Development\Source\grpc-dotnet\test\FunctionalTests\ServerStreamingMethodTests.cs : line 129
Test Outcome:	Failed
Test Duration:	0:00:40.215

Result StackTrace:	
at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.TestHost.ResponseStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync(PipeReader input) in C:\Development\Source\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\PipeExtensions.cs:line 207
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Grpc.AspNetCore.FunctionalTests.Infrastructure.MessageHelpers.AssertReadStreamMessageAsync[T](PipeReader pipeReader) in C:\Development\Source\grpc-dotnet\test\FunctionalTests\Infrastructure\MessageHelpers.cs:line 57
   at Grpc.AspNetCore.FunctionalTests.Infrastructure.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in C:\Development\Source\grpc-dotnet\test\FunctionalTests\Infrastructure\TaskExtensions.cs:line 51
   at Grpc.AspNetCore.FunctionalTests.ServerStreamingMethodTests.Buffering_SuccessResponsesStreamed() in C:\Development\Source\grpc-dotnet\test\FunctionalTests\ServerStreamingMethodTests.cs:line 162
   at NUnit.Framework.Internal.AwaitAdapter.TaskAwaitAdapter.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
Result Message:	System.InvalidOperationException : Reading is not allowed after reader was completed.
```

@jkotalik

**Comment by JamesNK** [comment]
Wrapping the stream in this fixes the error:

```cs
public class PipeReaderFixStream : Stream
{
    private readonly Stream _innerStream;
    private bool _isComplete;

    public PipeReaderFixStream(Stream innerStream)
    {
        _innerStream = innerStream;
    }

    public override bool CanRead => true;

    public override bool CanSeek => false;

    public override bool CanWrite => false;

    public override long Length => throw new System.NotImplementedException();

    public override long Position { get => throw new System.NotImplementedException(); set => throw new System.NotImplementedException(); }

    public override void Flush()
    {
        throw new System.NotImplementedException();
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        throw new System.NotImplementedException();
    }

    public override long Seek(long offset, SeekOrigin origin)
    {
        throw new System.NotImplementedException();
    }

    public override void SetLength(long value)
    {
        throw new System.NotImplementedException();
    }

    public override void Write(byte[] buffer, int offset, int count)
    {
        throw new System.NotImplementedException();
    }

    public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
    {
        if (_isComplete)
        {
            return 0;
        }

        var read = await _innerStream.ReadAsync(buffer, offset, count, cancellationToken);
        if (read == 0)
        {
            _isComplete = true;
        }

        return read;
    }
}
```

**Comment by jkotalik** [comment]
https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http/src/StreamPipeReader.cs#L251 pretty sure we just need to check this at the beginning of ReadAsync.
