### ISSUE TITLE
Test failure: LargeUpload(maxRequestBufferSize: 41943039, connectionAdapter: True, expectPause: False)

### ISSUE THREAD

**Issue by pakrym** [aspnet/AspNetCore#7336]
```
System.IO.IOException : Unable to read data from the transport connection: Broken pipe.
---- System.Net.Sockets.SocketException : Broken pipe
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.<>c__DisplayClass5_2.<<LargeUpload>b__0>d.MoveNext() in /_/src/Servers/Kestrel/test/FunctionalTests/MaxRequestBufferSizeTests.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.LargeUpload(Nullable`1 maxRequestBufferSize, Boolean connectionAdapter, Boolean expectPause) in /_/src/Servers/Kestrel/test/FunctionalTests/MaxRequestBufferSizeTests.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----

```

https://dev.azure.com/dnceng/public/_build/results?buildId=89124&view=ms.vss-test-web.build-test-results-tab

**Comment by anurse** [comment]
Dupe of https://github.com/aspnet/AspNetCore-Internal/issues/1775

**Comment by JunTaoLuo** [comment]
I've seen this test failure again here: https://dev.azure.com/dnceng/public/_build/results?buildId=181644&view=ms.vss-test-web.build-test-results-tab&runId=4387216&resultId=116920&paneView=debug. This didn't seem to look like the same error message as the issue linked as dupe so I'm going to reopen this one instead.

**Comment by anurse** [comment]
I'd much prefer a new RaaS-filed issue for that then. If we don't know for sure it's related, it's not helpful to reopen the existing issue.
