### ISSUE TITLE
SignalR: System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Http.HttpClientHandler' when calling "await Connection.StartAsync();"

### ISSUE THREAD

**Issue by MagicAndre1981** [aspnet/AspNetCore#7385]
### Describe the bug

When I try to connect to SignalR server in Xamarin App (UWP), where SignalR server is not available, I get the expected exception that server is not available:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Runtime.InteropServices.COMException: Der Text zu diesem Fehlercode wurde nicht gefunden.

Die Serververbindung konnte nicht hergestellt werden.
```

This is fine, but when I now start the AspNet Core SignalR server and try to connect again to SignalR service (without restarting the app) I get this unexpected exception:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClientHandler'.
```

### To Reproduce
1. Using this version of ASP.NET Core '...' https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.1.0
2. Run this code '....'

![image](https://user-images.githubusercontent.com/8274816/52476236-4d1bb780-2b9e-11e9-9a83-8df66037abd0.png)

### Expected behavior

Attempt to connect to SignalR should now find the started Server and connection should be started correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/8274816/52475611-42f8b980-2b9c-11e9-87fe-c57f05057b07.png)

### Additional context

-  VS2017 15.9.6
- Xamarin.Forms 3.4 Solution with UWP (MinVersion 16299, Target: 17763)

**Comment by davidfowl** [comment]
You’re not calling DisposeAsync anywhere in your code right?

**Comment by MagicAndre1981** [comment]
nope, I don't call DisposeAsync. 

I only noticed it in a fresh working copy where I haven't configured VS2017 to start the Server along with the UWP app

**Comment by bradygaster** [comment]
Would you have a stack trace or any deeper logging available, @MagicAndre1981 ? this would help us troubleshoot

**Comment by MagicAndre1981** [comment]
Here it is:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClientHandler'.
   at System.Net.Http.HttpClientHandler.CheckDisposed()
   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<NegotiateAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<GetNegotiationResponseAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<SelectAndStartTransport>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsyncCore>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.<StartAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Foo.Bar.App.<Connect>d__6.MoveNext()
```

**Comment by MagicAndre1981** [comment]
> You’re not calling DisposeAsync anywhere in your code right?

@davidfowl no, but I see that it is called by [SignalR when the 1st exception is raised](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/SignalR/clients/csharp/Client/src/HttpConnectionFactory.cs#L55):

I set the breakpoint in the downloaded .cs file and see this code is reached.

So this causes the ObjectDisposedException on 2nd attempt?

**Comment by davidfowl** [comment]
Yes we dispose the connection if there’s a problem creating it but we should be making a new one every time StartAsync is called.

**Comment by MagicAndre1981** [comment]
I've created a .net core 2.2 console app and here it works as expected with the same code. I'll create a new Xamarin.Forms app and try to repro it here again.

**Comment by MagicAndre1981** [comment]
@davidfowl 

ok, I created a new Xamarin.Forms app and here I have the same issue. on 2nd call I get the ObjectDisposedException while in .net core 2.2 I always the theexpected HttpRequestException with "Die Serververbindung konnte nicht hergestellt werden" which I handled in code. 

So is this a corefx issue? I see the code for [UWP](https://github.com/dotnet/corefx/tree/release/uwp6.1/src/System.Net.Http) and [.net core 2.2](https://github.com/dotnet/corefx/tree/release/2.2/src/System.Net.Http) differs a lot.

**Comment by davidfowl** [comment]
OK I'm going to put this issue in preview4 (since preview3 is winding down at the moment). If you could point us to that simple repro that would be great. We can figure out where the issue goes.

**Comment by MagicAndre1981** [comment]
@davidfowl

I played now a bit and see more details. 

[Compared to your demo](https://github.com/aspnet/SignalR-samples/blob/master/Xamarin/FormsClient/FormsClient/MainPage.xaml.cs#L25) I don't call `HubConnectionBuilder` .Build() all time, I only do it once in constructor. In my Connect method I check the state, if state is disconnected I call `StartAsync()`. Here I got the DisposedException on 2nd try.

So, I changed my code a bit to match your sample. In the constructor I now only use a dummy `new HubConnectionBuilder().WithUrl("https://foo:5001/bar").Build()` call. (this is important for the next step to prevent a NullReferenceException)

So for the first time I call the SingalR server, the state is disconnected (`if (Connection.State == HubConnectionState.Disconnected)`), here I configure the connection correctly with all data (correct url, transport, Protocol, TLS, logging) and call StartAsync(). So on all next connect attempts I set the Connection again and again with the HubConnectionBuilder.Build() call. This works now for 1,2,3 calls without DisposedException.

I started my selfhost server and in 4th try I was able to connect to the server.

I still don't understand why my old code worked for the Android App of the Xamarin solution and only failed for the UWP part of the Xamarin App.

**Comment by muratg** [comment]
@davidfowl Are you able to take this in preview4?

**Comment by davidfowl** [comment]
No I don’t have bandwidth to look into this one (And I don’t have a machine with the bits setup for Xamarin)

**Comment by muratg** [comment]
Tentatively putting this in preview5.

**Comment by anurse** [comment]
Triage decision: We think #8710 will overhaul a lot of this logic and we can revisit this when that lands. Preview 6

**Comment by MagicAndre1981** [comment]
@anurse

ok, currently I use my dummy HubConnectionBuilder workaround and everything is good, no error.

**Comment by anurse** [comment]
We think this will be improved in preview 6. If you see this issue again in that version, let us know and we can investigate further.

**Comment by MagicAndre1981** [comment]
I can only test it in 3.0 RTM and when [EF6 runs on .net standard 2.1](https://github.com/aspnet/EntityFramework6/issues/271#issuecomment-486057715). So until this happens I'll use my dummy HubConnectionBuilder workaround in 2.2/1.1.0.
