### ISSUE TITLE
[CI Failure]: RunIndividualTestCase-http2/6.2/1, HTTPS:True, Sends a HEADERS frame without the END_HEADERS flag, and a PRIORITY frame in 30.0323824s

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#7408]
```
| [0.004s] TestLifetime Information: Starting test RunIndividualTestCase-http2/6.2/1, HTTPS:True, Sends a HEADERS frame without the END_HEADERS flag, and a PRIORITY frame at 2019-02-09T03:19:43
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.022s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.022s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Interop.FunctionalTests
| [0.076s] Interop.FunctionalTests.H2SpecTests Debug: Hypertext Transfer Protocol Version 2 (HTTP/2)
| [0.077s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLKE7LI5E6H0" started.
| [0.079s] Interop.FunctionalTests.H2SpecTests Debug:   6. Frame Definitions
| [0.079s] Interop.FunctionalTests.H2SpecTests Debug:     6.2. HEADERS
| [0.096s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
| [0.096s] Interop.FunctionalTests.H2SpecTests Debug:            [send] SETTINGS Frame (length:6, flags:0x00, stream_id:0)
| [0.096s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
| [0.096s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] SETTINGS Frame (length:18, flags:0x00, stream_id:0)
| [0.096s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" received SETTINGS frame for stream ID 0 with length 6 and flags NONE
| [0.096s] Interop.FunctionalTests.H2SpecTests Debug:            [send] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
| [0.096s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [0.097s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] WINDOW_UPDATE Frame (length:4, flags:0x00, stream_id:0)
| [0.097s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" received SETTINGS frame for stream ID 0 with length 0 and flags ACK
| [0.097s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] SETTINGS Frame (length:0, flags:0x01, stream_id:0)
| [0.097s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" received HEADERS frame for stream ID 1 with length 16 and flags NONE
| [0.097s] Interop.FunctionalTests.H2SpecTests Debug:            [send] HEADERS Frame (length:16, flags:0x00, stream_id:1)
| [0.097s] Interop.FunctionalTests.H2SpecTests Debug:            [send] PRIORITY Frame (length:5, flags:0x00, stream_id:1)
| [0.097s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" received PRIORITY frame for stream ID 1 with length 5 and flags 0x0
| [0.097s] Interop.FunctionalTests.H2SpecTests Debug:            [send] CONTINUATION Frame (length:3512, flags:0x04, stream_id:1)
| [0.097s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLKE7LI5E6H0": HTTP/2 connection error.
| Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): The client sent a PRIORITY frame to stream ID 1 before signaling of the header block for stream ID 1.
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessPriorityFrameAsync() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 590
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1 payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 406
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 306
| [0.098s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLKE7LI5E6H0" is closed. The last processed stream ID was 1.
| [0.098s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "0HLKE7LI5E6H0" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
| [0.098s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLKE7LI5E6H0" sending FIN because: "The Socket transport's send loop completed gracefully."
| [0.099s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLKE7LI5E6H0" stopped.
| [0.127s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:26782->127.0.0.1:26781: wsarecv: An established connection was aborted by the software in your host machine.
| [0.127s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:26782->127.0.0.1:26781: wsarecv: An established connection was aborted by the software in your host machine.
| [0.128s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:26782->127.0.0.1:26781: wsarecv: An established connection was aborted by the software in your host machine.
| [0.128s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:26782->127.0.0.1:26781: wsarecv: An established connection was aborted by the software in your host machine.
| [0.128s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:26782->127.0.0.1:26781: wsarecv: An established connection was aborted by the software in your host machine.
| [0.128s] Interop.FunctionalTests.H2SpecTests Debug:            [recv] Error: read tcp 127.0.0.1:26782->127.0.0.1:26781: wsarecv: An established connection was aborted by the software in your host machine.
....
```

**Comment by muratg** [comment]
This should be fixed now.
