### ISSUE TITLE
SignalR CI errors (Test pass)

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#7423]
Not sure if this is expected as it ends "Test Run Successful."

```

Starting test group: SignalR/netcoreapp3.0
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Application startup exception: System.NotSupportedException: Duplicate definitions of 'OverloadedMethod'. Overloading is not supported.
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.DiscoverHubMethods() in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 561
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1..ctor(IServiceScopeFactory serviceScopeFactory, IHubContext`1 hubContext, IOptions`1 hubOptions, IOptions`1 globalHubOptions, ILogger`1 logger) in /_/src/SignalR/server/Core/src/Internal/DefaultHubDispatcher.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite scopedCallSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type) in /_/.nuget/packages/microsoft.extensions.activatorutilities.sources/3.0.0-preview.19105.4/contentFiles/cs/netstandard1.0/shared/ActivatorUtilities.cs:line 150
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider) in /_/.nuget/packages/microsoft.extensions.activatorutilities.sources/3.0.0-preview.19105.4/contentFiles/cs/netstandard1.0/shared/ActivatorUtilities.cs:line 139
   at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder) in /_/src/Servers/Connections.Abstractions/src/ConnectionBuilderExtensions.cs:line 14
   at Microsoft.AspNetCore.SignalR.SignalRConnectionBuilderExtensions.UseHub[THub](IConnectionBuilder connectionBuilder) in /_/src/SignalR/server/Core/src/SignalRConnectionBuilderExtensions.cs:line 31
   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.<>c__3`1.<MapHub>b__3_0(IConnectionBuilder builder) in /_/src/SignalR/server/SignalR/src/HubRouteBuilder.cs:line 58
   at Microsoft.AspNetCore.Http.Connections.ConnectionsRouteBuilder.MapConnections(PathString path, HttpConnectionDispatcherOptions options, Action`1 configure) in /_/src/SignalR/common/Http.Connections/src/ConnectionsRouteBuilder.cs:line 45
   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](PathString path, Action`1 configureOptions) in /_/src/SignalR/server/SignalR/src/HubRouteBuilder.cs:line 59
   at Microsoft.AspNetCore.SignalR.HubRouteBuilder.MapHub[THub](PathString path) in /_/src/SignalR/server/SignalR/src/HubRouteBuilder.cs:line 36
   at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c.<MapSignalRFailsForInvalidHub>b__0_1(HubRouteBuilder routes) in /_/src/SignalR/server/SignalR/test/MapSignalRTests.cs:line 18
   at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c__DisplayClass9_0.<BuildWebHost>b__2(HubRouteBuilder options) in /_/src/SignalR/server/SignalR/test/MapSignalRTests.cs:line 139
   at Microsoft.AspNetCore.Builder.SignalRAppBuilderExtensions.<>c__DisplayClass0_0.<UseSignalR>b__0(ConnectionsRouteBuilder routes) in /_/src/SignalR/server/SignalR/src/SignalRAppBuilderExtensions.cs:line 33
   at Microsoft.AspNetCore.Builder.ConnectionsAppBuilderExtensions.UseConnections(IApplicationBuilder app, Action`1 configure) in /_/src/SignalR/common/Http.Connections/src/ConnectionsAppBuilderExtensions.cs:line 36
   at Microsoft.AspNetCore.Builder.SignalRAppBuilderExtensions.UseSignalR(IApplicationBuilder app, Action`1 configure) in /_/src/SignalR/server/SignalR/src/SignalRAppBuilderExtensions.cs:line 35
   at Microsoft.AspNetCore.SignalR.Tests.MapSignalRTests.<>c__DisplayClass9_0.<BuildWebHost>b__1(IApplicationBuilder app) in /_/src/SignalR/server/SignalR/test/MapSignalRTests.cs:line 140
   at Microsoft.AspNetCore.Hosting.DelegateStartup.Configure(IApplicationBuilder app) in /_/src/Hosting/Hosting/src/Startup/DelegateStartup.cs:line 19
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 219
[xUnit.net 00:00:07.40]     Microsoft.AspNetCore.SignalR.Tests.WebSocketsTransportTests.WebSocketsTransportSendsUserAgent [SKIP]
Skipped  Microsoft.AspNetCore.SignalR.Tests.WebSocketsTransportTests.WebSocketsTransportSendsUserAgent
System.Exception: Failed to bind Stream message.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Tests.MethodHub.TestTypeCastingErrors(ChannelReader`1 source) in /_/src/SignalR/server/SignalR/test/HubConnectionHandlerTestUtils/Hubs.cs:line 231
[xUnit.net 00:00:05.31] Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests: Exception thrown during theory discovery on 'Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.HubConnectionCanSendAndReceiveMessages'; falling back to single test case.
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetWaitState()
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunProcessAndWait(String fileName, String arguments, String prefix, ILogger logger, TimeSpan timeout, String& output) in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 163
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunCommand(String commandAndArguments, String prefix, ILogger logger, String& output) in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 135
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunCommand(String commandAndArguments, String prefix, String& output) in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 131
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.Create() in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 44
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.get_Default() in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 23
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.SkipIfDockerNotPresentAttribute.CheckDocker() in /_/src/SignalR/server/StackExchangeRedis/test/SkipIfDockerNotPresentAttribute.cs:line 17
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.SkipIfDockerNotPresentAttribute.get_IsMet() in /_/src/SignalR/server/StackExchangeRedis/test/SkipIfDockerNotPresentAttribute.cs:line 12
   at Microsoft.AspNetCore.Testing.xunit.TestMethodExtensions.EvaluateSkipConditions(ITestMethod testMethod)
   at Microsoft.Extensions.Logging.Testing.LoggedConditionalTheoryDiscoverer.CreateTestCasesForDataRow(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo theoryAttribute, Object[] dataRow)
   at Xunit.Sdk.TheoryDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo theoryAttribute) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TheoryDiscoverer.cs:line 238
[xUnit.net 00:00:05.31] Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests: Exception during discovery:
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetWaitState()
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunProcessAndWait(String fileName, String arguments, String prefix, ILogger logger, TimeSpan timeout, String& output) in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 163
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunCommand(String commandAndArguments, String prefix, ILogger logger, String& output) in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 135
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.RunCommand(String commandAndArguments, String prefix, String& output) in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 131
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.Create() in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 44
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.Docker.get_Default() in /_/src/SignalR/server/StackExchangeRedis/test/Docker.cs:line 23
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.SkipIfDockerNotPresentAttribute.CheckDocker() in /_/src/SignalR/server/StackExchangeRedis/test/SkipIfDockerNotPresentAttribute.cs:line 17
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.SkipIfDockerNotPresentAttribute.get_IsMet() in /_/src/SignalR/server/StackExchangeRedis/test/SkipIfDockerNotPresentAttribute.cs:line 12
   at Microsoft.AspNetCore.Testing.xunit.TestMethodExtensions.EvaluateSkipConditions(ITestMethod testMethod)
   at Microsoft.Extensions.Logging.Testing.LoggedConditionalTheoryDiscoverer.CreateTestCasesForTheory(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo theoryAttribute)
   at Xunit.Sdk.TheoryDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo theoryAttribute) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TheoryDiscoverer.cs:line 263
   at Microsoft.Extensions.Logging.Testing.LoggedTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 132
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156
[xUnit.net 00:00:05.52]     Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisHubLifetimeManagerTests.CamelCasedJsonIsPreservedAcrossRedisBoundary [SKIP]
Skipped  Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisHubLifetimeManagerTests.CamelCasedJsonIsPreservedAcrossRedisBoundary
Results File: /home/vsts/work/1/s/artifacts/logs/SignalR-netcoreapp3.0-20190209.13.trx

Total tests: 1420. Passed: 1418. Failed: 0. Skipped: 2.
Test Run Successful.
Test execution time: 41.6505 Seconds
```

**Comment by mikaelm12** [comment]
The first exception is expected from the `MapHubFindsMultipleAuthAttributesOnDoubleAuthHub ` test making sure people don't create hubs with method overloads like this https://github.com/aspnet/AspNetCore/blob/3cd5054eb5d8851b25881cd05cccb931aaa022e6/src/SignalR/server/SignalR/test/MapSignalRTests.cs#L104-L113

The next is from testing type casting errors https://github.com/aspnet/AspNetCore/blob/b7d3b3aa13f0f0e18532307f886fac5127885411/src/SignalR/server/SignalR/test/HubConnectionHandlerTestUtils/Hubs.cs#L227

The other tests depend on Docker being present/could be blocked on issue https://github.com/aspnet/AspNetCore/issues/5345.

So yes, the first two are the actual tests, the other failures are expected 👍
