### ISSUE TITLE
HttpClient.SendAsync throwing  event.System.InvalidCastException: Unable to cast object of type '<>f__AnonymousType0`1[System.Net.Http.HttpRequestMessage]' to type '<>f__AnonymousType1`3[System.Net.Http.HttpRequestMessage,System.Guid,System.Int64]'

### ISSUE THREAD

**Issue by VidyaKukke** [aspnet/AspNetCore#7466]
Problem:
We are seeing httpClient.SendAsync throw the below exception some times. Capturing the call stack below as-is.

```
2019-02-11 19:42:36.034:[WRN] - [HttpDeliveryClient:Delivery:DeliverAsync:Failed] Delivery request for subscription=iotHubs//devices//modules//perfTopic/eventSubscriptions/perfSub InputEventUserId=75763db4-8320-4c93-b2d1-57bfa082c788 InputEventSystemId=d7aa88bd-2297-470d-91cf-b8e83f400377 outputEventId=980fb869-73ea-4c98-8a0f-7042e8368fa0 encountered an unexpected exception, postponing the output event.System.InvalidCastException: Unable to cast object of type '<>f__AnonymousType4`4[System.Net.Http.HttpResponseMessage,System.Guid,System.Int64,System.Threading.Tasks.TaskStatus]' to type '<>f__AnonymousType3`3[System.Net.Http.HttpResponseMessage,System.Net.Http.HttpRequestMessage,System.Threading.Tasks.TaskStatus]'.
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.TypedFetchProperty`2.Fetch(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.Fetch(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.Morph(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.Morph(Object args)
   at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.<>c__DisplayClass2_1.<.ctor>b__2(KeyValuePair`2 evnt)
   at System.Diagnostics.DiagnosticSourceEventSource.CallbackObserver`1.OnNext(T value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.EventGridEdge.Runtime.Broker.HttpDeliveryClient.InternalDeliverAsync(OutputEventHttpContent content, RuntimeEventSubscription subscription, CancellationToken token) line:84 file:E:\One\Azure\Azure-EventGrid-IoT-Edge\src\Runtime.Broker\Deliver\HttpDeliveryClient\HttpDeliveryClient.cs

Version:
Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]


Code Snippet:
using (HttpClient httpClient = this.httpClientFactory.CreateClient("someid"))
                using (var request = new HttpRequestMessage(HttpMethod.Post, url) { Content = content })
                {
                    using (HttpResponseMessage response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, token))
                    {
                        return response.StatusCode.ToDeliveryOutcome();
                    }
                }

content is of type OutputEventContent and that is 
internal class OutputEventHttpContent : HttpContent
    {
        private const string JsonContentType = "application/json; charset=utf-8";
        private static readonly byte[] JsonStartArray = Encoding.UTF8.GetBytes("[");
        private static readonly byte[] JsonEndArray = Encoding.UTF8.GetBytes("]");
        private static readonly byte[] JsonValueDelimiter = Encoding.UTF8.GetBytes(",");
        private static MediaTypeHeaderValue mediaTypeHeaderValue = MediaTypeHeaderValue.Parse(JsonContentType);

        private readonly CancellationToken token;

        public OutputEventHttpContent(OutputEvent outputEvent, CancellationToken token)
            : this(token)
        {
            this.FirstEvent = outputEvent;
        }

        public OutputEventHttpContent(ReadOnlyMemory<OutputEvent> outputEvents, CancellationToken token)
            : this(token)
        {
            this.FirstEvent = outputEvents.Span[0];
            this.RemainingEvents = outputEvents.Slice(1);
        }

        private OutputEventHttpContent(CancellationToken token)
        {
            this.Headers.ContentType = mediaTypeHeaderValue;
            this.token = token;
        }

        public OutputEvent FirstEvent { get; }

        public ReadOnlyMemory<OutputEvent> RemainingEvents { get; }

        protected override async Task SerializeToStreamAsync(Stream stream, TransportContext context)
        {
            await stream.WriteAsync(JsonStartArray, 0, JsonStartArray.Length);
            await stream.WriteAsync(this.FirstEvent.RawPayload.Value.Memory, this.token);

            for (int i = 0; i < this.RemainingEvents.Length; i++)
            {
                await stream.WriteAsync(JsonValueDelimiter, 0, JsonValueDelimiter.Length, this.token);
                OutputEvent outputEvent = this.RemainingEvents.Span[i];
                await stream.WriteAsync(outputEvent.RawPayload.Value.Memory, this.token);
            }

            await stream.WriteAsync(JsonEndArray, 0, JsonEndArray.Length, this.token);
        }

        protected override bool TryComputeLength(out long length)
        {
            length = 0;
            return false;
        }
    }
```

Any idea what could be causing this?

**Comment by Eilon** [comment]
@rynowak / @pakrym - do you think this is an issue in MS.Ext.Logging, CoreFX, or somewhere else?

**Comment by pakrym** [comment]
https://github.com/dotnet/corefx/issues/31322

**Comment by Eilon** [comment]
Good find. Closing this then. Please continue discussion at https://github.com/dotnet/corefx/issues/31322 as needed.
