### ISSUE TITLE
[Flaky test] GracefulShutdownWaitsForRequestsToFinish

### ISSUE THREAD

**Issue by javiercn** [aspnet/AspNetCore#7496]
https://dev.azure.com/dnceng/public/_build/results?buildId=93150&view=ms.vss-test-web.build-test-results-tab

```
System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown.
```

```
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Servers/Kestrel/shared/test/TestApplicationErrorLogger.cs:line 91
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass4_0.<Define>b__0(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.KestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelTrace.cs:line 169
   at Castle.Proxies.KestrelTraceProxy.NotAllConnectionsClosedGracefully_callback()
   at Castle.Proxies.Invocations.KestrelTrace_NotAllConnectionsClosedGracefully.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Moq.CastleProxyFactory.Invocation.ReturnBase() in C:\projects\moq4\src\Moq\ProxyFactories\CastleProxyFactory.cs:line 201
   at Moq.Return.Handle(Invocation invocation, Mock mock) in C:\projects\moq4\src\Moq\Interception\InterceptionAspects.cs:line 350
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation) in C:\projects\moq4\src\Moq\Interception\Mock.cs:line 21
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation invocation) in C:\projects\moq4\src\Moq\ProxyFactories\CastleProxyFactory.cs:line 176
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.KestrelTraceProxy.NotAllConnectionsClosedGracefully()
   at Microsoft.AspNetCore.Testing.CompositeKestrelTrace.NotAllConnectionsClosedGracefully() in /_/src/Servers/Kestrel/shared/test/CompositeKestrelTrace.cs:line 99
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/KestrelServer.cs:line 193
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StopAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/KestrelServer.cs:line 176
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.Dispose() in /_/src/Servers/Kestrel/Core/src/KestrelServer.cs:line 222
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.DisposeServiceProviderAsync(IServiceProvider serviceProvider) in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 372
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.DisposeAsync() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 364
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose() in /_/src/Hosting/Hosting/src/Internal/WebHost.cs:line 347
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.Dispose() in /_/src/Servers/Kestrel/shared/test/TransportTestHelpers/TestServer.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.ShutdownTests.GracefulShutdownWaitsForRequestsToFinish() in /_/src/Servers/Kestrel/test/FunctionalTests/Http2/ShutdownTests.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by javiercn** [comment]
@Eilon @muratg Can you assign as appropriate?

**Comment by muratg** [comment]
Another shutdown failure :(

cc @halter73

**Comment by Tratcher** [comment]
About the same as https://github.com/aspnet/AspNetCore-Internal/issues/1832
