### ISSUE TITLE
Flaky test: FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetCore#7626]
This build: https://dev.azure.com/dnceng/public/_build/results?buildId=97423

Ubuntu 16.04 x64 leg failed:

```
[xUnit.net 00:02:57.00]     Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable [FAIL]
  Failed   Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 114
     at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 86
     at Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithIterationEnvVariable() in /_/src/Tools/dotnet-watch/test/DotNetWatcherTests.cs:line 44
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   The temporary test folder is /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk
   Copying project /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/TestProjects/KitchenSink to /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk/KitchenSink
   Restoring msbuild project in KitchenSink
   Project directory: '/home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk/KitchenSink'
   Started process 28809: /home/vsts/work/1/s/.dotnet/dotnet restore
     Restoring packages for /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk/KitchenSink/KitchenSink.csproj...
     Generating MSBuild file /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk/KitchenSink/.net/obj/KitchenSink.csproj.nuget.g.props.
     Generating MSBuild file /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk/KitchenSink/.net/obj/KitchenSink.csproj.nuget.g.targets.
     Restore completed in 178.73 ms for /home/vsts/work/1/s/artifacts/bin/dotnet-watch.Tests/Release/netcoreapp3.0/tmp/vmdhkmop.hvk/KitchenSink/KitchenSink.csproj.
```

It failed on a PR that changed only an MD file, so it clearly was not related to that.

**Comment by Eilon** [comment]
Closing as dup of https://github.com/aspnet/AspNetCore-Internal/issues/1826 now that it failed on the internal CI as well.
