### ISSUE TITLE
BenchmarkDotNet projects currently broken on master

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#7632]
Running any benchmark on master that uses System.Memory results in:
```

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.AspNetCore.Server.Kestrel.Performance.InMemoryTransportBenchmark.GlobalSetupPlaintext()
   at BenchmarkDotNet.Autogenerated.Runnable.Run(IHost host) in C:\Users\jukotali\code\aspnetcore\src\Servers\Kestrel\perf\Kestrel.Performance\bin\release\netcoreapp3.0\50a0681a-ebe6-455c-ac9f-6c727bcfe24a\50a0681a-ebe6-455c-ac9f-6c727bcfe24a.notcs:line 124
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.Program.AfterAssemblyLoadingAttached(String[] args) 
```

I think we need to get a new version of BenchmarkDotNet, but I'm not 100% sure.

cc @sebastienros

**Comment by jkotalik** [comment]
nvrm, local corruption.
