### ISSUE TITLE
AspNetCore 3.0 Integration Tests on Appveyor (VS 2019)

### ISSUE THREAD

**Issue by cristipufu** [aspnet/AspNetCore#7652]
My **aspnet core 3.0** integration tests are failing on Appveyor (Visual Studio 2019 Preview), although on my local machine everything works as expected:

```
Failed   AspNetCoreRateLimit.Tests.ClientRateLimitTests.WhitelistPath
Error Message:
 System.TypeLoadException : Could not load type 'Microsoft.AspNetCore.Mvc.JsonResult' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Stack Trace:
   at Microsoft.Extensions.DependencyInjection.NewtonsoftJsonMvcCoreBuilderExtensions.AddServicesCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.NewtonsoftJsonMvcBuilderExtensions.AddNewtonsoftJson(IMvcBuilder builder)
   at AspNetCoreRateLimit.Demo.Startup.ConfigureServices(IServiceCollection services) in C:\projects\aspnetcoreratelimit\test\AspNetCoreRateLimit.Demo\Startup.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateServer(IWebHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at AspNetCoreRateLimit.Tests.ClientRateLimitTests..ctor(WebApplicationFactory`1 factory) in C:\projects\aspnetcoreratelimit\test\AspNetCoreRateLimit.Tests\ClientRateLimitTests.cs:line 18
Failed   AspNetCoreRateLimit.Tests.IpRateLimitTests.SpecificIpRule(ip: "84.247.85.224")
```

The tests are following the examples I found here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2

- Code: https://github.com/stefanprodan/AspNetCoreRateLimit/pull/62
- Appveyor: https://ci.appveyor.com/project/stefanprodan/aspnetcoreratelimit

Is this an _Appveyor_ environment issue? 

Any suggestions are most welcome,
Thanks

PS: I also raised a bug for the _Appveyor_ team [here](https://github.com/appveyor/ci/issues/2868).

**Comment by davidfowl** [comment]
It's not an appveyor bug it's a breaking change that's been fixed in the latest builds of ASP.NET Core 3.0, see https://github.com/aspnet/AspNetCore/issues/7220

**Comment by cristipufu** [comment]
Thanks
