### ISSUE TITLE
Exceptions encountered when running Razor Components application

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#7665]
I encountered these errors while trying to debug a Razor Components applications (the benchmarks UI by @sebastienros). The first exception was an ArgumentOutOfRangeException while trying to build the render tree. It looks like it was swallowed.

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength
   at System.Text.StringBuilder.ToString()
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder.AddContent(Int32 sequence, Object textContent)
   at Benchmarks.UI.App.Pages.Index.BuildRenderTree(RenderTreeBuilder builder) in C:\dev\git\Benchmarks\src\Benchmarks.UI.App\Pages\Index.cshtml:line 251
   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.ExecuteBackground(WorkItem item)
Exception thrown: 'MessagePack.Internal.MessagePackDynamicObjectResolverException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in MessagePack.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.AspNetCore.SignalR.Protocols.MessagePack.dll
Exception thrown: 'MessagePack.Internal.MessagePackDynamicObjectResolverException' in MessagePack.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.AspNetCore.Blazor.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Blazor.Server.BlazorHub:Warning: Unhandled Server-Side exception
```

This second exception ended up crashing the process (likely an async void somewhere 😉 )

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.UpdateRetainedChildComponent(DiffContext& diffContext, Int32 oldComponentIndex, Int32 newComponentIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Blazor.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Blazor.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Blazor.Server.Circuits.CircuitSynchronizationContext.ExecuteBackground(WorkItem item)
Exception thrown: 'System.TypeInitializationException' in Microsoft.AspNetCore.SignalR.Protocols.MessagePack.dll
Exception thrown: 'MessagePack.Internal.MessagePackDynamicObjectResolverException' in MessagePack.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.AspNetCore.Blazor.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.AspNetCore.Blazor.dll
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll
Object reference not set to an instance of an object.
```

cc @SteveSandersonMS @rynowak @javiercn

**Comment by SteveSandersonMS** [comment]
Do you have repro steps?

**Comment by davidfowl** [comment]
Nope, couldn't narrow it down. The application is here https://github.com/aspnet/Benchmarks/tree/master/src/Benchmarks.UI.Server. I might try to update to a newer version of razor components to see if that helps.

**Comment by SteveSandersonMS** [comment]
Ah, it was 0.7.0. There was a bad thread safety bug with rendering reported by a lot of people. It manifested in various ways, because it allowed corruption of some internal data structures.

We eliminated the bad asynchrony in 0.8.0 (or Preview 2 for Razor Components) and it went away as expected. 

If you still experience it with > 0.7.0, please let us know!

**Comment by davidfowl** [comment]
@SteveSandersonMS I'll try moving the app to razor components.
