### ISSUE TITLE
ProjectManagement.Front.blazor.config missing

### ISSUE THREAD

**Issue by JulienM28** [aspnet/AspNetCore#7667]
I juste updated ton .net core 3.0 preview 2 et blazor 0.8 preview.

I followed the update process.

Everything was fine until I launched the application and got an exception:

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not find file 'C:\Team Foundation\ProjectManagement\ProjectManagement\bin\Debug\netcoreapp3.0\ProjectManagement.Front.blazor.config'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Microsoft.AspNetCore.Components.Server.BlazorConfig..ctor(String assemblyPath)
   at Microsoft.AspNetCore.Components.Server.BlazorConfig.Read(String assemblyPath)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor[TProgram](IApplicationBuilder app)
   at ProjectManagement.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Team Foundation\ProjectManagement\ProjectManagement\Startup.cs:line 68

It works fine with a new project not updated from .net core 2.1 / Blazor 0.7

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @JulienM28.
We can't help you without more information so we're closing this issue.
One path you can sure take - start from a new project and bring your code.
Otherwise, if you're willing to share your project file, we may be able to suggest something. If so, please file a new issue and do that.
