### ISSUE TITLE
Fix SignalRSamples by reacting to #7751

### ISSUE THREAD

**Issue by halter73** [aspnet/AspNetCore#7841]
https://github.com/aspnet/AspNetCore/pull/7751 broke SignalRSamples

```
C:\dev\aspnet\AspNetCore\src\SignalR\samples\SignalRSamples> dotnet run
Application startup exception: System.InvalidOperationException: The CORS protocol does not allow specifying a wildcard (any) origin and credentials at the same time. Configure the CORS policy by listing individual origins if credentials needs to be supported.
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder.Build() in C:\dev\aspnet\AspNetCore\src\Middleware\CORS\src\Infrastructure\CorsPolicyBuilder.cs:line 232
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsOptions.AddPolicy(String name, Action`1 configurePolicy) in C:\dev\aspnet\AspNetCore\src\Middleware\CORS\src\Infrastructure\CorsOptions.cs:line 101
   at SignalRSamples.Startup.<>c.<ConfigureServices>b__0_1(CorsOptions o) in C:\dev\aspnet\AspNetCore\src\SignalR\samples\SignalRSamples\Startup.cs:line 38
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsService..ctor(IOptions`1 options, ILoggerFactory loggerFactory) in C:\dev\aspnet\AspNetCore\src\Middleware\CORS\src\Infrastructure\CorsService.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider) in C:\Users\shalter\.nuget\packages\microsoft.extensions.activatorutilities.sources\3.0.0-preview3.19115.4\contentFiles\cs\netstandard1.0\shared\ActivatorUtilities.cs:line 387
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters) in C:\Users\shalter\.nuget\packages\microsoft.extensions.activatorutilities.sources\3.0.0-preview3.19115.4\contentFiles\cs\netstandard1.0\shared\ActivatorUtilities.cs:line 88
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next) in C:\dev\aspnet\AspNetCore\src\Http\Http.Abstractions\src\Extensions\UseMiddlewareExtensions.cs:line 92
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build() in C:\dev\aspnet\AspNetCore\src\Http\Http\src\Internal\ApplicationBuilder.cs:line 98
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication() in C:\dev\aspnet\AspNetCore\src\Hosting\Hosting\src\Internal\WebHost.cs:line 224
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
```

**Comment by pranavkm** [comment]
Does the sample get tested as part of the build? I didn't see it fail when I check in my change.
