### ISSUE TITLE
[CI] AspNetCore-helix-test Windows.10.Amd64.ClientRS4 Catastrophic failures 

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#7867]
Catastrophic failure for every test

![image](https://user-images.githubusercontent.com/1142958/53256499-f515a280-36bf-11e9-80ff-abb3e8d91e54.png)

Looks like is unhappy with `dotnet` command params:
```
C:\dotnetbuild\work\4a1dd42a-43d9-45c6-b06a-4b00b4d944ad\Work\81deec84-10d1-471b-b5e5-ee1109f4d828\Exec>set helix=true 

C:\dotnetbuild\work\4a1dd42a-43d9-45c6-b06a-4b00b4d944ad\Work\81deec84-10d1-471b-b5e5-ee1109f4d828\Exec>C:\dotnetbuild\work\4a1dd42a-43d9-45c6-b06a-4b00b4d944ad\Payload\sdk\dotnet vstest Sockets.FunctionalTests.dll --logger:trx 

Welcome to .NET Core!
---------------------
GitHub: https://github.com/dotnet/core
Docs: https://aka.ms/dotnet-docs
HTTPS: https://aka.ms/aspnet-core-https

Telemetry statement: https://aka.ms/dotnet-cli-telemetry
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\dotnetbuild\work\4a1dd42a-43d9-45c6-b06a-4b00b4d944ad\Work\81deec84-10d1-471b-b5e5-ee1109f4d828\Exec\"$HELIX_CORRELATION_PAYLOAD\home"\.dotnet'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by HaoK** [comment]
Will be fixed as part of https://github.com/aspnet/AspNetCore/pull/7763

**Comment by HaoK** [comment]
Should be fixed by https://github.com/aspnet/AspNetCore/pull/7586
