### ISSUE TITLE
[CI] Failed ContentLength_Received_ReadViaPipes

### ISSUE THREAD

**Issue by benaadams** [aspnet/AspNetCore#7951]
Test: Ubuntu 16.04 x64 Job

Failed   ContentLength_Received_ReadViaPipes
```
ContentLength_Received_ReadViaPipes [FAIL]
  Failed   ContentLength_Received_ReadViaPipes
  Error Message:
   Assert.Equal() Failure
            ↓ (pos 0)
  Expected: 200
  Actual:   500
            ↑ (pos 0)
  Stack Trace:
     at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.ContentLength_Received_ReadViaPipes() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1064
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   | [0.000s] TestLifetime Information: Starting test ContentLength_Received_ReadViaPipes at 2019-02-26T13:35:15
   | [0.002s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE
   | [0.002s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0
   | [0.003s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received SETTINGS frame for stream ID 0 with length 0 and flags NONE
   | [0.003s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK
   | [0.003s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received HEADERS frame for stream ID 1 with length 12343 and flags NONE
   | [0.003s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received CONTINUATION frame for stream ID 1 with length 4121 and flags END_HEADERS
   | [0.005s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id ":00000001": started reading request body.
   | [0.006s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" received DATA frame for stream ID 1 with length 12 and flags END_STREAM
   | [0.007s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "(null)", Request id ":00000001": An unhandled exception was thrown by the application.
   | Xunit.Sdk.TrueException: Assert.True() Failure
   | Expected: True
   | Actual:   False
   |    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 96
   |    at Xunit.Assert.True(Boolean condition) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 63
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.<>c.<<ContentLength_Received_ReadViaPipes>b__31_0>d.MoveNext() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1028
   | --- End of stack trace from previous location where exception was thrown ---
   |    at Microsoft.AspNetCore.Testing.DummyApplication.ProcessRequestAsync(HttpContext context) in /_/src/Servers/Kestrel/shared/test/DummyApplication.cs:line 45
   |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 575
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending HEADERS frame for stream ID 1 with length 55 and flags END_HEADERS
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending DATA frame for stream ID 1 with length 0 and flags END_STREAM
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id ":00000001": done reading request body.
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "(null)", Request id ":00000001": the application completed without reading the entire request body.
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)" is closed. The last processed stream ID was 1.
   | [0.009s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id "(null)" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0
   | [0.262s] TestLifetime Information: Finished test ContentLength_Received_ReadViaPipes in 0.261312s
```

/cc @jkotalik

**Comment by benaadams** [comment]
Guessing, fix is https://github.com/aspnet/AspNetCore/pull/7933

**Comment by anurse** [comment]
Closing this as we believe it is fixed.
