### ISSUE TITLE
Controllers of IEnumerable return type return 200 when unhandled exception happens

### ISSUE THREAD

**Issue by yue-shi** [aspnet/AspNetCore#7984]
An AspNetCore controller that returns `IEnumerable<T>`, `ActionResult<IEnumerable<T>>` or `JsonResult` returns HTTP status code 200 with `[` in the body when there is an exception thrown from the iterator.

### To Reproduce

Create a simple controller by following [https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio](url). Change the **Get** endpoint to following 

~~~~
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return GetString().Select(s => s.ToLower());

            IEnumerable<string> GetString()
            {
                yield return null;
            }
        }
    }
~~~~

### Framework 4.7.2 behavior
~~~~
    public class ValuesController : ApiController
    {
        // GET api/values
        [HttpGet]
        [Route("api/values")]
        public IEnumerable<string> Get()
        {
            return GetString().Select(s => s.ToLower());

            IEnumerable<string> GetString()
            {
                yield return null;
            }
        }
    }
~~~~
returns 500 with stack trace
~~~~
at IEnumerableController4._7._2.Controllers.ValuesController.<>c.<Get>b__0_0(String s) in C:\src\test\IEnumerableController4.7.2\IEnumerableController4.7.2\Controllers\ValuesController.cs:line 14
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at WriteArrayOfstringToXml(XmlWriterDelegator , Object , XmlObjectSerializerWriteContext , CollectionDataContract )
at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)
at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
at System.Runtime.Serialization.DataContractSerializer.WriteObject(XmlWriter writer, Object graph)
at System.Net.Http.Formatting.XmlMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)
at System.Net.Http.Formatting.XmlMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__22.MoveNext()
~~~~

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/5083. See https://github.com/aspnet/Mvc/issues/5083#issuecomment-235631483 for solutions.

**Comment by uniqueumang** [comment]
How is this issue not consistent with .net framework implementation?
Looking at some other issues where changes have been made to align with .net framework, then the behaviour reported is inconsistent : https://github.com/dotnet/corefx/issues/18646
