### ISSUE TITLE
[Components] Router incorrectly resovling AppAssembly as string

### ISSUE THREAD

**Issue by Valks** [aspnet/AspNetCore#8018]
### Describe the bug
Using Razor Components, the Router AppAssembly value is been passed as a string instead of evaluating to typeof(Startup).Assembly resulting in a InvalidCastException

### To Reproduce
1. Using this version of ASP.NET Core '3.0.0-preview4-19123-01'
2. Run this code 'Create a new Razor Components project using the 3.0 preview template'

```
warn: Microsoft.AspNetCore.Components.Browser.Rendering.RemoteRenderer[1]
      Unhandled exception rendering component: Unable to set property 'AppAssembly' on object of type 'Microsoft.AspNetCore.Components.Routing.Router'. The error was: Unable to cast object of type 'System.String' to type 'System.Reflection.Assembly'.
System.InvalidOperationException: Unable to set property 'AppAssembly' on object of type 'Microsoft.AspNetCore.Components.Routing.Router'. The error was: Unable to cast object of type 'System.String' to type 'System.Reflection.Assembly'. ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Reflection.Assembly'.
   at Microsoft.AspNetCore.Components.Reflection.MemberAssignment.PropertySetter`2.SetValue(Object target, Object value)   at Microsoft.AspNetCore.Components.ParameterCollectionExtensions.SetParameterProperties(ParameterCollection& parameterCollection, Object target)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.ParameterCollectionExtensions.SetParameterProperties(ParameterCollection& parameterCollection, Object target)
   at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterCollection parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterCollection parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

### Expected behavior
Expect the Router to resolve the AppAssembly value.

### Additional context
Using the DotNet Core CI build: 3.0.100-preview4-010539

**Comment by Valks** [comment]
I came up with a temporary hack to get around it for now.

Create a derived component based on router and use reflection to assign the value. Then in App.razor remove the AppAssembly attribute.

App.razor
```
<InternalRouter />
```

InternalRouter.cs
```
using Microsoft.AspNetCore.Components.RenderTree;
using Microsoft.AspNetCore.Components.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1
{
    public class InternalRouter : Router
    {
        public InternalRouter()
            : base()
        {
            System.Reflection.PropertyInfo pi = typeof(Router).GetProperty("AppAssembly", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            pi.SetValue(this, typeof(Startup).Assembly, null);
        }
    }
}
```

**Comment by JerryMcMillan** [comment]
I was able to fix this by changing
`<Router AppAssembly="typeof(Startup).Assembly" />`
to
`<Router AppAssembly="@typeof(Startup).Assembly" />`

**Comment by Valks** [comment]
Hmm interesting that didn't work for me. I'll try again.

**Comment by JerryMcMillan** [comment]
Perhaps this should be titled "Errors in Razor Components template".

The other change I had to make to display the home page with no error was adding the `@` to `Match="@NavLinkMatch.All"` on line 11 in NavMenu.razor

**Comment by Valks** [comment]
Just tried the latest version and found it's working as you've said.

I'm going to close this as it seems like expected behaviour.
