### ISSUE TITLE
BadImageFormatException when running integration tests for x86 projects (runner is a x86 process)

### ISSUE THREAD

**Issue by luminescent** [aspnet/AspNetCore#8068]
I have a .net core 2.1.1 project that must run as an x86 process and is targeting the .net 462 framework, because it has dependencies on a few libraries targeting that framework and must run in a 32 bits process. Everything runs fine. 

I have a project with the similar settings where I put integration tests. I am using the `TestServer` in there. I am trying to call the API methods from the main project, using the `TestClient`. 

All of my integration tests fail as they're unable to load one of the dependent libraries, giving me a bad image format. Which usually happens when attempting to load a 32 bit library into a 64 bit process etc. 

Please see below the stack trace: 

```

Failed   Insight.MarketDataService.Host.IntegrationTests.HistoricalSpotFxRateTests.ShouldReturnNotFoundForCurrencyCodesWithoutConversions(ccFrom: "GBP", ccTo: "BAD")
Error Message:
 System.TypeInitializationException : The type initializer for 'Insight.MarketDataService.Host.IntegrationTests.TestClientFactory' threw an exception.
---- System.BadImageFormatException : Could not load file or assembly 'FSGDateTimeLibraryNative.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
-------- System.BadImageFormatException : Could not load file or assembly 'FSGDateTimeLibraryNative.dll' or one of its dependencies. The module was expected tocontain an assembly manifest.
Stack Trace:
   at Insight.MarketDataService.Host.IntegrationTests.TestClientFactory.get_HttpClient()
   at Insight.MarketDataService.Host.IntegrationTests.HistoricalSpotFxRateTests.<ShouldReturnNotFoundForCurrencyCodesWithoutConversions>d__2.MoveNext() in C:\work\src\market-data-service\src\Insight.MarketDataService.Host.IntegrationTests\HistoricalSpotFxRateTests.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at App.Metrics.Health.Extensions.DependencyInjection.Internal.HealthAssemblyDiscoveryProvider.<>c.<GetCandidateAssemblies>b__2_3(<>f__AnonymousType0`2 <>h__TransparentIdentifier0) in C:\projects\microsoftextensions\src\App.Metrics.Health.Extensions.DependencyInjection\Internal\HealthAssemblyDiscoveryProvider.cs:line 41
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at App.Metrics.Health.Extensions.DependencyInjection.Internal.HealthAssemblyDiscoveryProvider.GetCandidateAssemblies(DependencyContext dependencyContext) inC:\projects\microsoftextensions\src\App.Metrics.Health.Extensions.DependencyInjection\Internal\HealthAssemblyDiscoveryProvider.cs:line 38
   at Microsoft.AspNetCore.Hosting.HealthAspNetWebHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureHealth>b__0(WebHostBuilderContext context, IServiceCollection services) in C:\projects\aspnetcorehealth\src\App.Metrics.AspNetCore.Health.Hosting\HealthAspNetWebHostBuilderExtensions.cs:line 111
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder)
   at Insight.MarketDataService.Host.IntegrationTests.TestClientFactory..cctor() in C:\work\src\market-data-service\src\Insight.MarketDataService.Host.IntegrationTests\TestClientFactory.cs:line 17
----- Inner Stack Trace -----


```

I have used process monitor to check that all of the processes spun up by running tests are 32 bits and they are.  
I have tried different ways of starting the tests, using the `xunit.console.x86.exe`, the Visual Studio test runner with `.runsettings` etc. Process Monitor claims things run as 32 bits processes so there must be something else going on? 

Things run fine in the main project where I am not using `TestServer`. 

Output from `dotnet --info`

```

.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


```

**Comment by luminescent** [comment]
.csproj snippet, main project: 

```

    <PackageReference Include="App.Metrics.AspNetCore" Version="2.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Health" Version="2.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Health.Endpoints" Version="2.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Mvc" Version="2.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Reporting" Version="2.0.0" />
    <PackageReference Include="App.Metrics.Health.Checks.Http" Version="2.0.0" />
    <PackageReference Include="App.Metrics.Reporting.TextFile" Version="2.0.0" />
    <PackageReference Include="Flurl.Http.Signed" Version="2.3.2" />
    <PackageReference Include="Flurl.Signed" Version="2.8.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Antiforgery" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
    <PackageReference Include="SerilogTimings" Version="2.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="4.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="OneOf.Signed" Version="2.1.127" />

```

There are additional dependencies, they're internal ones and targeting the net642 framework.

**Comment by luminescent** [comment]
Even further info, the dll in question: 

```
---- System.BadImageFormatException : Could not load file or assembly 'FSGDateTimeLibraryNative.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

```
uses some C++ code. 

I have tried to look at the fuslogvw output but there's nothing for this one in particular (I get entries for almost everything else), so not sure what to do about the assembly manifest. Any pointers?

**Comment by muratg** [comment]
@luminescent what package does `FSGDateTimeLibraryNative.dl` come from? Could you check that package to see if it has 32-bit versions of the whatever native binaries it has?

**Comment by luminescent** [comment]
Yes that is a 32 bit library. All runs fine as an ASP. NET Core self hosted
process (32 bits again), it is only when using the `TestServer` that it's
tripping.

I don't think this is related to the bitness, as I said I have looked at
this with Process Monitor and _all_ of the processes spun up during
standalone run and integration test run are 32 bit.
