### ISSUE TITLE
Reenable InMemory tests on Helix Linux agents

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#8089]
Tests have been failing with different failures, including a debug assert:

```
The active test run was aborted. Reason: Assertion Failed
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.UpdateConnectionState() in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 1054
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPoolGlobals.<>c.<.cctor>b__5_0(Object state)
   at System.IO.Pipelines.InlineScheduler.UnsafeSchedule(Action`1 action, Object state)
   at System.IO.Pipelines.Pipe.CancelPendingRead()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.CancelPendingRead()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.IRequestProcessor.Tick(DateTimeOffset now) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 964
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.OnHeartbeat(Object state) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 477
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

As well as the process being killed without any other logs.

**Comment by jkotalik** [comment]
Instances: 
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190228.50/workItem/InMemory.FunctionalTests-netcoreapp3.0/wilogs
https://mc.dot.net/#/user/aspnetcore/pr~2Faspnet~2Faspnetcore/ci/20190228.49/workItem/InMemory.FunctionalTests-netcoreapp3.0/wilogs

These only happened on debian8, so I'll just disable for that agent.

**Comment by jkotalik** [comment]
closing in favor of https://github.com/aspnet/AspNetCore/pull/8104
