### ISSUE TITLE
Flaky SignalR test: HttpConnectionDispatcherTests.ErrorDuringPollWillCloseConnection

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8138]
Flaky SignalR test: Microsoft.AspNetCore.Http.Connections.Tests.HttpConnectionDispatcherTests.ErrorDuringPollWillCloseConnection

```
[xUnit.net 00:00:15.96]     Microsoft.AspNetCore.Http.Connections.Tests.HttpConnectionDispatcherTests.ErrorDuringPollWillCloseConnection [FAIL]
[xUnit.net 00:00:15.97]       System.TimeoutException : The operation at /_/src/SignalR/common/Http.Connections/test/HttpConnectionDispatcherTests.cs:2052 timed out after reaching the limit of 5000ms.
[xUnit.net 00:00:15.97]       Stack Trace:
[xUnit.net 00:00:15.97]            at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
[xUnit.net 00:00:15.97]         /_/src/SignalR/common/Http.Connections/test/HttpConnectionDispatcherTests.cs(2054,0): at Microsoft.AspNetCore.Http.Connections.Tests.HttpConnectionDispatcherTests.ErrorDuringPollWillCloseConnection()
[xUnit.net 00:00:15.97]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:15.97]       Output:
[xUnit.net 00:00:15.97]         | [0.001s] TestLifetime Information: Starting test ErrorDuringPollWillCloseConnection at 2019-03-03T02:37:59
[xUnit.net 00:00:15.97]         | [0.002s] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: New connection ED_orQIG7Vl2Rk2JS5zrWQ created.
[xUnit.net 00:00:15.97]         | [0.003s] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: Establishing new connection.
[xUnit.net 00:00:15.97]         | [0.003s] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: Resuming existing connection.
[xUnit.net 00:00:15.97]         | [5.013s] TestLifetime Information: Finished test ErrorDuringPollWillCloseConnection in 5.0128352s
Failed   Microsoft.AspNetCore.Http.Connections.Tests.HttpConnectionDispatcherTests.ErrorDuringPollWillCloseConnection
Error Message:
 System.TimeoutException : The operation at /_/src/SignalR/common/Http.Connections/test/HttpConnectionDispatcherTests.cs:2052 timed out after reaching the limit of 5000ms.
Stack Trace:
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Http.Connections.Tests.HttpConnectionDispatcherTests.ErrorDuringPollWillCloseConnection() in /_/src/SignalR/common/Http.Connections/test/HttpConnectionDispatcherTests.cs:line 2054
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 | [0.001s] TestLifetime Information: Starting test ErrorDuringPollWillCloseConnection at 2019-03-03T02:37:59
 | [0.002s] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager Debug: New connection ED_orQIG7Vl2Rk2JS5zrWQ created.
 | [0.003s] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: Establishing new connection.
 | [0.003s] Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher Debug: Resuming existing connection.
 | [5.013s] TestLifetime Information: Finished test ErrorDuringPollWillCloseConnection in 5.0128352s
```

**Comment by anurse** [comment]
Assigned to me to skip

**Comment by davidfowl** [comment]
Possible regressions from recent pipe changes?

cc @pakrym @benaadams

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore/issues/8182 related?

**Comment by halter73** [comment]
Why is TaskExtensions.DefaultTimeout only 5 seconds? In Kestrel we make it 30 because we've found that ThreadPool.QUWI takes over 5 seconds to schedule sometimes on our CI agents.
