### ISSUE TITLE
[Helix] Flaky Kestrel Test: ValidationFailureRejectsConnection

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8168]
`Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsConnectionAdapterTests.ValidationFailureRejectsConnection` is flaky in Helix. Failed in unrelated PR: https://github.com/aspnet/AspNetCore/pull/8143

```
[xUnit.net 00:00:03.37]     ValidationFailureRejectsConnection(mode: RequireCertificate) [FAIL]
[xUnit.net 00:00:03.37]       System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
[xUnit.net 00:00:03.37]       Stack Trace:
[xUnit.net 00:00:03.37]            at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
[xUnit.net 00:00:03.37]            at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
[xUnit.net 00:00:03.37]            at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
[xUnit.net 00:00:03.37]            at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
[xUnit.net 00:00:03.37]            at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
[xUnit.net 00:00:03.37]            at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
[xUnit.net 00:00:03.37]            at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:03.37]            at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:03.37]            at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:03.37]            at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
[xUnit.net 00:00:03.37]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:03.37]            at System.Net.Security.SslState.ThrowIfExceptional()
[xUnit.net 00:00:03.37]            at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
[xUnit.net 00:00:03.38]            at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
[xUnit.net 00:00:03.38]            at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
[xUnit.net 00:00:03.38]            at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_2(IAsyncResult iar)
[xUnit.net 00:00:03.38]            at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[xUnit.net 00:00:03.38]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:03.38]         /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsConnectionAdapterTests.cs(523,0): at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsConnectionAdapterTests.ValidationFailureRejectsConnection(ClientCertificateMode mode)
[xUnit.net 00:00:03.38]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:03.38]       Output:
[xUnit.net 00:00:03.38]         | [0.000s] TestLifetime Information: Starting test ValidationFailureRejectsConnection-RequireCertificate at 2019-03-04T02:33:48
[xUnit.net 00:00:03.38]         | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
[xUnit.net 00:00:03.38]         | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
[xUnit.net 00:00:03.38]         | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
[xUnit.net 00:00:03.38]         | [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL097A1T8GH" started.
[xUnit.net 00:00:03.38]         | [0.102s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
[xUnit.net 00:00:03.38]         | [0.102s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL097A1T8GH" closing because: "Server shutdown started during connection initialization."
[xUnit.net 00:00:03.38]         | [0.115s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL097A1T8GH" stopped.
[xUnit.net 00:00:03.38]         | [0.160s] TestLifetime Information: Finished test ValidationFailureRejectsConnection-RequireCertificate in 0.16014879999999998s
Failed   ValidationFailureRejectsConnection(mode: RequireCertificate)
Error Message:
 System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized
Stack Trace:
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsConnectionAdapterTests.ValidationFailureRejectsConnection(ClientCertificateMode mode) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsConnectionAdapterTests.cs:line 523
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 | [0.000s] TestLifetime Information: Starting test ValidationFailureRejectsConnection-RequireCertificate at 2019-03-04T02:33:48
 | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
 | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
 | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
 | [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL097A1T8GH" started.
 | [0.102s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
 | [0.102s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL097A1T8GH" closing because: "Server shutdown started during connection initialization."
 | [0.115s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLL097A1T8GH" stopped.
 | [0.160s] TestLifetime Information: Finished test ValidationFailureRejectsConnection-RequireCertificate in 0.16014879999999998s
```

**Comment by anurse** [comment]
Blocking https://github.com/aspnet/AspNetCore/pull/8143
