### ISSUE TITLE
Flaky IIS Test: CompressionTests+OutOfProcessV1.PassesThroughCompression

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8260]
`Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.CompressionTests+OutOfProcessV1.PassesThroughCompression` flaked out on AzP

```
[xUnit.net 00:16:55.99]     Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.CompressionTests+OutOfProcessV1.PassesThroughCompression [FAIL]
  Failed   Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.CompressionTests+OutOfProcessV1.PassesThroughCompression
  Error Message:
   System.InvalidOperationException : Sequence contains no elements
  Stack Trace:
     at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
     at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.CompressionTests.PassesThroughCompression()
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   | [0.005s] TestLifetime Information: Starting test PassesThroughCompression at 2019-03-06T06:55:00
   | [7.669s] TestLifetime Information: Finished test PassesThroughCompression in 7.6639403s
```

**Comment by jkotalik** [comment]
This is on 2.2 correct?

**Comment by anurse** [comment]
Yesh

**Comment by anurse** [comment]
Need to review how to skip this base-class test only in a single subclass. Also needs to be done on `release/2.2`
