### ISSUE TITLE
Asp .net core 3 preview 3 - some StateHasChanged cause "Cannot access a disposed object. Object name: 'IServiceProvider'."

### ISSUE THREAD

**Issue by julienGrd** [aspnet/AspNetCore#8406]
### Environment
.net core 3 preview 3 razor components

### Describe the bug
I call existing c# code through my razor component. This code is an old school 4.0 code (but class are recompiled to .NET standard), which call wcf services and raise an event when the result are here. My component suscribe to this event to do a StateHasChanged for refresh the UI.

When i call the StateHasChanged, not an each place but often, i now have an exception "Cannot access a disposed object. Object name: 'IServiceProvider'."

### To Reproduce
Unfortunately i was unable to reproduce the bug with the starter template. It's complicated to reproduce because My app execute existing c# code (a lot of code, with call to wcf services), and i can't put the entire project on internet because is the property of my company.

### Additional context
This bug appear after the migration preview 2 -> preview 3.
I thinks it's related to the "prerendering" functionnality, I already open a ticket regarding JsRuntime here : https://github.com/aspnet/AspNetCore/issues/8327
So, in the same way of JsRuntime, i wrap my call with try catch and it seems OK (my UI is refresh)

 this.Invoke(() =>
            {
                try
                {
                    this.StateHasChanged();
                }
                catch (Exception ex)
                {
                    //to prevent app crash when bug appear
                }
            });

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @julienGrd.
You have to override the `Dispose()` method and unsubscribe from the set of notifications.

**Comment by sbuchok** [comment]
@mkArtakMSFT Sorry, can you maybe elaborate? I'm having the exact same issue. What do I need to dispose of? What notifications? Can you give an example?

For me, this is happening if I refresh a page and could have something to do with making a JSON request, but the error is on StateHasChanged and doesn't really give any clues (at least that I can see) as to what is wrong.

This is the callstack, doesn't seem to help me, but I'm assuming you're smarter than I.
`   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass6_0.<CreateInitializer>b__2(IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.Rendering.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()`

Also, this is happening inside of a method that gets called OnInit of the page that does a search. When the page is refreshed, just prior to the page refreshing (pretty sure it's before onunload) this method is getting called. The stack trace has nothing before it. It just says [Resume Async Method]. Then after I continue passed the error, method gets called again. 

If I put breakpoints, there is no error (however I do lose my session, so that's something else I need to figure out and is probably unrelated). Seems hit or miss when breakpoints get involved.
