### ISSUE TITLE
Flaky Razor Components Test: ServerSideAppTest.HasHeading

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8436]
`Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerSideAppTest.HasHeading` flaked out on Windows: https://dev.azure.com/dnceng/public/_build/results?buildId=121311&view=ms.vss-test-web.build-test-results-tab

```
  Failed   Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerSideAppTest.HasHeading
  Error Message:
   OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document
    (Session info: headless chrome=72.0.3626.121)
    (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
  Stack Trace:
     at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
     at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
     at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
     at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
     at OpenQA.Selenium.Remote.RemoteWebElement.get_Text()
     at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerSideAppTest.HasHeading() in /_/src/Components/test/E2ETest/ServerExecutionTests/ServerSideAppTest.cs:line 41
  Standard Output Messages:
   browser Logs from Selenium:
   [3/12/2019 12:22:54 AM] - Info - http://127.0.0.1:57545/_framework/components.server.js 0:5144 "[2019-03-12T00:22:54.850Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:57545/_blazor'."
   [3/12/2019 12:22:55 AM] - Info - http://127.0.0.1:57545/_framework/components.server.js 0:5144 "[2019-03-12T00:22:55.734Z] Information: WebSocket connected to ws://127.0.0.1:57545/_blazor?id=KcIjO9J61m1jy77jKreQsg."
   [3/12/2019 12:22:55 AM] - Info - http://127.0.0.1:57545/_framework/components.server.js 0:5144 "[2019-03-12T00:22:55.735Z] Information: Using HubProtocol 'messagepack'."
   
   
   server Logs from Selenium:
   [3/12/2019 12:22:30 AM] - Info - Capabilities are: {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--headless"
      ]
    },
    "loggingPrefs": {
      "browser": "ALL"
    }
  }
   [3/12/2019 12:22:30 AM] - Info - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
   [3/12/2019 12:22:41 AM] - Info - Detected dialect: OSS
   [3/12/2019 12:22:42 AM] - Info - Started new session 816d82fa234e68db085ab157401be987 (org.openqa.selenium.chrome.ChromeDriverService)
```

**Comment by anurse** [comment]
I can mitigate this one test easily, but I'm concerned it'll be a bit of whack-a-mole as other Selenium-based tests fail. I could skip all the Razor Components Selenium tests but that's fairly aggressive. Thoughts @Eilon @mkArtakMSFT ?

**Comment by Eilon** [comment]
Do we have history on flakiness of the Selenium-based tests?

Is there a general change we can apply to reduce flakiness? E.g. slow the tests down w/ delays to reduce/eliminate flakiness?

**Comment by anurse** [comment]
Beyond my scope, I haven't explored the Selenium UI tests. It's possible delays would reduce flakiness, or retry logic. It depends on what's causing the failure. A "stale element reference" seems to indicate that you have a reference to a DOM element that gets moved or changed, and your reference is now broken (https://www.seleniumhq.org/exceptions/stale_element_reference.jsp)

**Comment by anurse** [comment]
@javiercn

**Comment by javiercn** [comment]
For reference, the link above doesn't work properly. (the one with the test results)

**Comment by anurse** [comment]
Ugh. I think it's because I restarted the build or something. There wasn't really any more data there, just the exception message and browser logs. There was a heading for "Selenium driver logs" but it had nothing after it.
