### ISSUE TITLE
AddResponseTypeAttributeCodeFixProvider error with multiple return results which has different parameters

### ISSUE THREAD

**Issue by DenissKulakov** [aspnet/AspNetCore#8551]
Package: Microsoft.AspNetCore.Mvc.Api.Analyzers v2.2.0

**Issue:**
Having multiple BadRequest results with different arguments in one controller method causes the exception when trying to autogenerate annotations for them.

**StackTrace:** 
System.ArgumentException : An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key,TValue value,Boolean add)
   at Microsoft.AspNetCore.Mvc.Api.Analyzers.AddResponseTypeAttributeCodeFixAction.CalculateStatusCodesToApply(CodeActionContext& context,IList`1 declaredResponseMetadata)
   at async Microsoft.AspNetCore.Mvc.Api.Analyzers.AddResponseTypeAttributeCodeFixAction.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Screenshot:**
![image](https://user-images.githubusercontent.com/12020171/54433920-b2327200-4735-11e9-97a8-153f2eed194a.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @DenissKulakov.
@pranavkm, can you please look into this? Thanks!

**Comment by khellang** [comment]
This has already been fixed in https://github.com/aspnet/AspNetCore/pull/6209 (reported earlier in https://github.com/aspnet/AspNetCore/issues/4480) 😄

**Comment by pranavkm** [comment]
Thanks @khellang. Closing this as dup.
