### ISSUE TITLE
JS Interop doesn't report the correct callstack 

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8612]
There's a catch and re-throw that's breaking call stacks when using JSInterop. We probably need to use `ExceptionDispatchInfo` here to try and preserve the information. 

You can repro this by adding a button that throws when clicked (server side).

I think the culprit is this pattern here: https://github.com/aspnet/Extensions/blob/master/src/JSInterop/Microsoft.JSInterop/src/DotNetDispatcher.cs#L106

I think we should also try to get rid of the `ContinueWith` here if possible (or specify the task scheduler). This has been problematic most places we do it. 

**Server**
```
 	MvcSandbox.dll!MvcSandbox.Components.Pages.Index.Throw() Line 9	C#
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync<object>(System.MulticastDelegate delegate, object arg) Line 49	C#
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(object arg) Line 38	C#
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(Microsoft.AspNetCore.Components.EventCallbackWorkItem callback, object arg) Line 260	C#
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(object arg) Line 61	C#
 	Microsoft.AspNetCore.Components.dll!Microsoft.AspNetCore.Components.Rendering.Renderer.DispatchEventAsync(int eventHandlerId, Microsoft.AspNetCore.Components.UIEventArgs eventArgs) Line 228	C#
>	Microsoft.AspNetCore.Components.Browser.dll!Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher.DispatchEvent(Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher.BrowserEventDescriptor eventDescriptor, string eventArgsJson) Line 25	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.JSInterop.dll!Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(string assemblyName, string methodIdentifier, object targetInstance, string argsJson)	Unknown
 	Microsoft.JSInterop.dll!Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(string callId, string assemblyName, string methodIdentifier, long dotNetObjectId, string argsJson)	Unknown
 	Microsoft.AspNetCore.Components.Server.dll!Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.BeginInvokeDotNetFromJS.AnonymousMethod__0() Line 137	C#
```

**Client**
```
Error: System.Exception: Here's a cool message
at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
```

**Comment by rynowak** [comment]
https://github.com/aspnet/Extensions/pull/1324
