### ISSUE TITLE
In .Net Core 3 preview, I can not run MVC Core with cshtml pages in VB.NET project

### ISSUE THREAD

**Issue by VBAndCs** [aspnet/AspNetCore#8783]
### Describe the bug
I created a VB.NET ASP.NET MVC (.net Core 3.0 preview) project based on a C# project, and of course still using cshtml pages. But when I run it, I got the error: can't find Index.cshtml, while it exists in the Views\Home folder! 

### To Reproduce
1. Using this version of ASP.NET Core 3.0 preview.
![dep](https://user-images.githubusercontent.com/48354902/54920852-faf3e300-4f0c-11e9-86a3-548889ee83c0.jpg)

2. VB project is attached.
[ConsoleApp5.zip](https://github.com/aspnet/AspNetCore/files/3003315/ConsoleApp5.zip)

![Index Not Found](https://user-images.githubusercontent.com/48354902/54921302-21fee480-4f0e-11e9-903b-c073e3d17557.jpg)

### Expected behavior
This works fine for .NET Core 2.1 like in this app:
https://github.com/mevdschee/aspnetcorevb

**Comment by pranavkm** [comment]
You will need to add a reference to the [`Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation`](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation) package. In addition for preview3, you need to set `<PreserveCompilationReferences>true</PreserveCompilationReferences>` in your project. The second bit should be addressed as part of preview4 - https://github.com/aspnet/AspNetCore/issues/7966

**Comment by VBAndCs** [comment]
@pranavkm 
Done, but no change!
By the way, C# project doesn't reference the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package, nor set the PreserveCompilationReferences!
Did you try these changes on the project I attached and worked for you? Maybe I have a problem in my VS 2019 preview! 
Note: I use Win 10 64 bit.
Thanks.

**Comment by VBAndCs** [comment]
@ @danroth27
Please don't close the issue too early. I still have the problem. 
Thanks.

**Comment by pranavkm** [comment]
Missed a bullet point, you'll need to configure runtime compilation as part of startup:

`services.AddMvc().AddRazorRuntimeCompilation()`

**Comment by VBAndCs** [comment]
@pranavkm 
Adding `services.AddMvc().AddRazorRuntimeCompilation()' caused a runtime exception un the line:
```VB.NET
app.UseRouting(
        Sub(routes)
            routes.MapApplication()
            routes.MapControllerRoute(
                    name:="default",
                    template:="{controller=Home}/{action=Index}/{id?}")
        End Sub)
```

The details:
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.AspNetCore.Hosting.IWebHostEnvironment' from assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<GetCallSite>b__7_0(Type type, CallSiteChain chain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<GetCallSite>b__7_0(Type type, CallSiteChain chain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<GetCallSite>b__7_0(Type type, CallSiteChain chain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<GetCallSite>b__7_0(Type type, CallSiteChain chain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<GetCallSite>b__7_0(Type type, CallSiteChain chain)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcEndpointRouteBuilderExtensions.MapActionDescriptors(IEndpointRouteBuilder routeBuilder, Type containingType)
   at Microsoft.AspNetCore.Builder.MvcEndpointRouteBuilderExtensions.MapApplication(IEndpointRouteBuilder routeBuilder)
   at ConsoleApp5.Startup._Closure$__._Lambda$__5-0(IEndpointRouteBuilder routes) in C:\Users\mhmd\source\repos\ConsoleApp5\Startup.vb:line 50
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseRouting(IApplicationBuilder builder, Action`1 configure)
   at ConsoleApp5.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\mhmd\source\repos\ConsoleApp5\Startup.vb:line 48
```

**Comment by VBAndCs** [comment]
Note: Adding the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package adds the VisualBasic Analyxers to the project, not C# analyzers. Is this the problem?

**Comment by VBAndCs** [comment]
@pranavkm
I installed the Microsoft.CodeAnalysis.CSharp but the exception still happens.
Could you please test with the attached app in the issue until it works?
Thanks for your efforts.

**Comment by pranavkm** [comment]
There were [some changes](https://github.com/aspnet/AspNetCore/issues/7749) in the preview3 milestone around that type. Are you using the preview3 SDK or newer?

**Comment by VBAndCs** [comment]
@pranavkm 
I use VS.NET 2019 preview 4.3

**Comment by pranavkm** [comment]
I'm not sure if VS releases install the .NET Core SDK. You can get the preview SDK from https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by VBAndCs** [comment]
I have v3.0.0-preview2. I once setup preview 3 but caused some issues so I uninstalled it. 
Anyway, why C# project runs correctly, but not VB project?
The "can't find view" message can only appear if the page is null (becuase the file is already in the folder). This means that Razor couldn't compile the page! I suspect that maybe there is some code that checked that the languge is VB so if didn't compile the cshtml page. Is there any new code added in the Razor project to do that?

**Comment by Eilon** [comment]
@VBAndCs you need to match the runtime and the packages. Any odd behavior you see with mismatched versions is not supported.

**Comment by VBAndCs** [comment]
@Eilon
I descovered some errors due to different namespaces of the two projects, but the problem stays!
I don't think this is due to package versions. The two projects uses the same packages, and C# works. 
I think this maybe related to precompiled views, which can't be used in VB.NET becuase it is generated as C# classes and will not be compiled. This is turned off in VB.NET project, but maybe Razor expects it somehow.

**Comment by Eilon** [comment]
@VBAndCs can you please post a complete app to GitHub that demonstrates the problem? And show your `dotnet --info` output so we see what you have installed.

**Comment by VBAndCs** [comment]
```
PM> dotnet --info 
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

[ConsoleApp5.zip](https://github.com/aspnet/AspNetCore/files/3014278/ConsoleApp5.zip)

**Comment by Eilon** [comment]
Thanks for posting the app! So this app causes an error when you run it?

**Comment by Eilon** [comment]
OK so it looks like you don't actually have the .NET Core 3.0 Preview 3 SDK. You have to install that, or else nothing is expected to work.

**Comment by VBAndCs** [comment]
It runs, but can't find the Index.chtml view 
![dep](https://user-images.githubusercontent.com/48354902/54920852-faf3e300-4f0c-11e9-86a3-548889ee83c0.jpg)

Looking at source code, this is not a file not found case, but the Page is null, so the Razor View engine couldn't create the page. Why?

**Comment by VBAndCs** [comment]
@Eilon
> OK so it looks like you don't actually have the .NET Core 3.0 Preview 3 SDK. You have to install that, or else nothing is expected to work.

I'll install it now, but remember: C# project is working now. Why?

**Comment by VBAndCs** [comment]
I set it up, and now I got runtime errors, and the browser shows:
```
HTTP Error 502.5 - Process Failure 
Common causes of this issue: 
The application process failed to start 
The application process started but then stopped 
The application process started but failed to listen on the configured port 
Troubleshooting steps: 
Check the system event log for error messages 
Enable logging the application process' stdout messages 
Attach a debugger to the application process and inspect 
For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681 
```

**Comment by VBAndCs** [comment]
This is the message that appears when I run:
![untitled1](https://user-images.githubusercontent.com/48354902/55096307-4c919e80-50c2-11e9-91e3-83c3e9b4a14e.jpg)

**Comment by VBAndCs** [comment]
@Eilon
And C# project doesn't compile anymore, giving NETSDK1045 error :
> The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.

This is why I removed this sdk last time. I expect that new sdk can run old apps. What should I do?

**Comment by Eilon** [comment]
Can you try uninstalling any old 3.0 versions you have? Did you restart VS after installing? This issue doesn't seem related to ASP.NET Core anymore.

**Comment by VBAndCs** [comment]
@Eilon 
It worked. Thanks.
1- I uninstalled all .Net Core SDKs.
2- I Installed SDK 3 preview.
3- I Created a fresh C# Web APP and copied its components to a VB app.
4- I modified the vbproj to set the PreserveCompilationReferences and add a reference to Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview3-19153-02" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.0.0-preview3-19153-02" />
  </ItemGroup>

</Project>
```

5- I added ' services.AddMvc().AddRazorRuntimeCompilation()' to the `Startup.ConfigureServices` method as @pranavkm said. This time it works, especially there wase some changes in the UseRouting in this version, so the exception didn't happen here:
```
        app.UseRouting(
             Sub(routes)
                 routes.MapControllerRoute(
                     name:="default",
                     template:="{controller=Home}/{action=Index}/{id?}")
                 routes.MapRazorPages()
             End Sub)
```

and know the app is working. I attached it.
Thanks.
[VB.zip](https://github.com/aspnet/AspNetCore/files/3014936/VB.zip)
