### ISSUE TITLE
Some server-side Razor Component exceptions are only visible in Javascript console

### ISSUE THREAD

**Issue by springy76** [aspnet/AspNetCore#8912]
Some component related exceptions which happen on server-side are not getting logged on the server (to console or wherever ILogger logs to) but only visible in javascript console on browser-side.

For example I forgot the register a DI service which showed no error in console but UI did not update for this page. Finally in browser console I found this log entry:

```
Error: System.InvalidOperationException: Cannot provide a value for property 'X' on type 'Y'. There is no registered service of type 'Z'.
    at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
    at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
```

I would expect to see exceptions happening on the server in the server log, too. (There is no client side Blazor).

**Comment by danroth27** [comment]
This should now be fixed in Preview4.
