### ISSUE TITLE
Error after profile editing using Azure B2C using default template

### ISSUE THREAD

**Issue by mnemcik** [aspnet/AspNetCore#9196]
I have created new ASP.NET Core web appliation and enabled Azure B2C for authentication. Once I log in and edit my profile I should be redirected back to the application screen. Instead the application returns error page. The exception thrown is:

```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: 'https://<domain>.b2clogin.com/tfp/cd730fdc-fce0-42b8-ad20-7d5e4c48ba70/b2c_1_edit-profile/v2.0/'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://<domain>.b2clogin.com/tfp/cd730fdc-fce0-42b8-ad20-7d5e4c48ba70/b2c_1_sign-up/v2.0/'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateIssuer(String issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateIssuer(String issuer, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

I have tried to change Issuer (iss) claim on user policies on Azure B2C tenant to support the format used by authentication handler (to include /tfp and {policy_name}) however the policy name in this case does not match (b2c_1_edit-profile vs b2c_1_sign-up). 

### To Reproduce
1. Using version of ASP.NET Core 2.1 + VS2017
2. Create new ASP.NET Core Web Application, select MVC template
3. `Change Authentication` to `Individual User Accounts` and `Connect to an existing user store in the cloud`
4. Fill in the details of the B2C application registration and continue to create new web application
5. Create/Update B2C application registration and set Reply URL to match the local application URL
6. Run the application from VS2017 and register/sign in.
7. Edit your profile by clicking on your name in the header and try to submit changes.
8. Application shows error page (URL is `https://localhost:44378/AzureADB2C/Account/Error`), exception being thrown is in the bug description.

### Expected behavior
User is redirected back to the application page without error being shown.

```
C:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Eilon** [comment]
@mnemcik this is certainly not expected behavior. Can you share your startup.cs (with any secrets removed) so we can take a look?

Tagging @jmprieur in case you have any thoughts.

**Comment by mnemcik** [comment]
Hi @Eilon , here is both Startup.cs (generated by default in the template, not changed):

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.AzureADB2C.UI;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace WebApplication3
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
                .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}

```

and appsettings.json:

```json
{
  "AzureAdB2C": {
    "Instance": "https://<domain-name>.b2clogin.com/tfp/",
    "ClientId": "0fe9f760-6de7-4131-a42c-dd15a98f725b",
    "CallbackPath": "/signin-oidc",
    "Domain": "<domain-name>.onmicrosoft.com",
    "SignUpSignInPolicyId": "B2C_1_sign-up",
    "ResetPasswordPolicyId": "B2C_1_reset-password",
    "EditProfilePolicyId": "B2C_1_edit-profile"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*"
}

```

**Comment by Eilon** [comment]
Thanks @mnemcik we will take a look.

**Comment by Eilon** [comment]
@jmprieur / @javiercn - any ideas on this? Does the Startup code and configuration look right?

**Comment by javiercn** [comment]
We haven't been able to repro this issue. I believe there must be some missconfiguration in your Azure B2C application.

**Comment by anurse** [comment]
Closing as we don't have a repro.
