### ISSUE TITLE
Intellisense/aspnetcore not allowing void -> object casting

### ISSUE THREAD

**Issue by wisepotato** [aspnet/AspNetCore#9197]
### Describe the bug
When using `ActionResult<object>` as a result, the resulting method allows for the return of `void` from another function, but it shouldn't, as this gives a ProgramException.

I dont know if this is a Roslyn bug or AspNetCore bug.

### To Reproduce
1. Using this version of ASP.NET Core 2.2
2. Run this code 
```c#
        private void ReturnVoid() { }


        public ActionResult<object> FaultyMethod()
        {
            return ReturnVoid();
        }
```
3. With these argumentsx
4. See error `ProgramException`

### Expected behavior
It should return an EmptyResult to the end user. Or give an error in intellisense/Roslyn that this sort of thing should not happen.

Or am I missing something here?

**Comment by Eilon** [comment]
@jaredpar - maybe a compiler issue? The return type of this method, `ActionResult<T>`, has some implicit conversions:
https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ActionResultOfT.cs#L56-L72

So maybe that's confusing things?

cc @rynowak

**Comment by jaredpar** [comment]
That's a pretty straight forward case (`void` to anything) so I'd be surprised if it's a compiler issue. Is there a stand alone sample to look at? Tried creating some quick repos and everything behaves as i would expect.

**Comment by Eilon** [comment]
I'm able to repro in an ASP.NET Core 2.2 app. When I run the code I get:

```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at WebApplication62.Controllers.HomeController.FaultyMethod()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I'll see if there's a simple repro.

**Comment by Eilon** [comment]
Here's a simple standalone repro on .NET Core 2.2:

```c#
using Microsoft.AspNetCore.Mvc;
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            new Test().FaultyMethod();
        }
    }

    public class Test
    {
        private void ReturnVoid() { }

        public ActionResult<object> FaultyMethod()
        {
            return ReturnVoid();
        }
    }
}


namespace Microsoft.AspNetCore.Mvc
{
    public sealed class ActionResult<TValue>
    {
        public ActionResult(TValue value)
        {
        }

        public static implicit operator ActionResult<TValue>(TValue value)
        {
            return new ActionResult<TValue>(value);
        }
    }
}
```

Run it and you get:

```

Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ConsoleApp2.Test.FaultyMethod()
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\elipton\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 10
```

**Comment by Eilon** [comment]
Same result on a ~3 week old .NET Core 3.0 preview 4 nightly build.

**Comment by Eilon** [comment]
@jaredpar - should we move this bug to Roslyn?

**Comment by jaredpar** [comment]
@Eilon yes we should. Can't do a real move though because don't have a dual Admin. I will do a manual move.

**Comment by Eilon** [comment]
Thanks @jaredpar

**Comment by jaredpar** [comment]
Moved to https://github.com/dotnet/roslyn/issues/34872

**Comment by wisepotato** [comment]
Woah you guys move fast.
