### ISSUE TITLE
[SignalR] JsonHubProtocol throw NoSuchFieldException

### ISSUE THREAD

**Issue by JMaroz** [aspnet/AspNetCore#9245]
Android 
- SignalR 1.0.2

Server
- ASP.NET Core 2.2.0
- SignalR 1.1.0
- Hosting on Docker over ECS on AWS Cloud Platform (no reverse proxy, just kestrel behind the balancer) 

In Android application we are experiencing some crash. 

`Fatal Exception: java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: Received
       at com.google.gson.Gson.fromJson(Gson.java:944)
       at com.microsoft.signalr.JsonHubProtocol.bindArguments(JsonHubProtocol.java:202)
       at com.microsoft.signalr.JsonHubProtocol.parseMessages(JsonHubProtocol.java:91)
       at com.microsoft.signalr.HubConnection.lambda$new$0(HubConnection.java:168)
       at com.microsoft.signalr.h.invoke(h.java:2)
       at com.microsoft.signalr.WebSocketTransport.onReceive(WebSocketTransport.java:76)
       at com.microsoft.signalr.WebSocketTransport.lambda$start$0(WebSocketTransport.java:53)
       at com.microsoft.signalr.z.invoke(z.java:2)
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onMessage(OkHttpWebSocketWrapper.java:84)
       at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

### To Reproduce
Unable to reproduce the behavior, the crash happen randomly

### Expected behavior
SignalR must catch the exception or not throw the exception

**Comment by anurse** [comment]
Can you provide a sample Java project that reproduces the issue?

**Comment by JMaroz** [comment]
The issues is in the SignalR library when the user send a new message and the app invoke the follow method
` 
    @WorkerThread
    private fun sendMessage(messageToSend: RealTimeEvent.Message) {
        log("Send: newMessage $messageToSend")
        eventCallback.postValue(messageToSend)
        try {
            if (isConnected()) {
                val message = messageToSend.message
                message.state = RealTimeMessage.State.Sent
                **hubConnection?.send(SEND_MESSAGE, message.message, UUID.fromString(message.conversationId), message.extData, message.attachments)**
            } else {
                notifySentError(messageToSend)
            }
        } catch (e: Exception) {
            logError("Error sending message with RealTimeMessenger", e)
            notifySentError(messageToSend)
        }
    }
`

**Comment by anurse** [comment]
Can you post a complete sample to a GitHub repo or something? Specifically, we need to see the **definitions** for the objects you are sending. For example, what is this `UUID` type? Is it compatible with GSON (the JSON serialization library we use)?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!

**Comment by acolombo25** [comment]
@JMaroz I solved the problem, the issue was proguard obfuscating enums inside the objects being sent and causing problems with GSON.
