### ISSUE TITLE
Error 502.5 - ANCM Out-Of-Process Startup 

### ISSUE THREAD

**Issue by KANekT** [aspnet/AspNetCore#9592]
### To Reproduce
1. Using this version of ASP.NET Core 2.2.*
2. Upload code to azure
x64

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\Innoline.exe" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="OutOfProcess" />
    </system.webServer>
  </location>
</configuration>

HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

in log
Unhandled Exception: System.IO.FileNotFoundException: Error reading the D:\home\site\wwwroot\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Innoline.Program.Main(String[] args) in \\Mac\Home\Desktop\new\Innoline.Web\Program.cs:line 11

**Comment by KANekT** [comment]
`using Innoline.Config;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;

namespace Innoline
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var webHost = BuildWebHost(args);
            webHost.Run();
        }

        public static IWebHost BuildWebHost(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseKestrel()
                .UseStartup<Startup>()
                .UseIISIntegration()
                .Build();
        }
    }
}
`

**Comment by jkotalik** [comment]
Does this happen consistently? I don't think this is a permission issue, but it could be.

**Comment by KANekT** [comment]
`    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreModuleName>AspNetCoreModule</AspNetCoreModuleName>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
`
worked in azure

`    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
`
not worked in azure

**Comment by anurse** [comment]
@KANekT are you still seeing this issue?

**Comment by KANekT** [comment]
@anurse I will check this as soon as possible

**Comment by KANekT** [comment]
<handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\Innoline.exe" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="InProcess" />
 
HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

Unhandled Exception: System.IO.FileNotFoundException: Error reading the D:\home\site\wwwroot\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Innoline.Program.Main(String[] args) in D:\OhMyBoss\server-main\Innoline.Web\Program.cs:line 12

**Comment by anurse** [comment]
> D:\OhMyBoss\server-main\Innoline.Web\ is my local path - why is use in azure ?

That path is just the source file path that is compiled in when you built the DLL. It's used by debuggers to help resolve the source file and for your own reference to know where the line of code is.

> Unhandled Exception: System.IO.FileNotFoundException: Error reading the D:\home\site\wwwroot\ directory.

Seems like something is locking or otherwise restricting your `wwwroot` directory. Could you create a sample project that reproduces this problem? It seems like this is more related to file watching issues on Azure App Service and the ANCM error is just how it is manifesting. 

@pranavkm @natemcmaster I see your names in the history for the `PhysicalFilesWatcher`. Is this something we've seen before? Just curious if there's something known here.

**Comment by natemcmaster** [comment]
Nope, haven't seen this before. Would be good to confirm first that D:\home\site\wwwroot\ exists and is readable before we assume its a problem with System.IO.FileSystemWatcher

**Comment by anurse** [comment]
Cool, just thought I'd check that first.

@KANekT Does this directory exist on the App Service server? You can check this by navigating to the "Advanced Tools" tab in the Azure Portal for your App Service. In there you can open the Debug Console and explore the file system.

**Comment by KANekT** [comment]
@anurse directory is exits in root:
![image](https://user-images.githubusercontent.com/580273/58399316-76365a00-8060-11e9-9507-78a177fd3330.png)

**Comment by KANekT** [comment]
i find https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-known-issues.md

but it Note this has been resolved as of January 2019.

**Comment by anurse** [comment]
I wonder if something is broken on your Azure App Service instance. Does this repro if you try temporarily deploying to a new App Service? If it does, can you provide a sample project that reproduces the issue?

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
