### ISSUE TITLE
Swashbuckle 4.0.1 is broken on latest bits

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#9695]
This change broke Swashbuckle: https://github.com/aspnet/AspNetCore/commit/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0#diff-82fb21b0c9d40a3f2a763341393fc5e1

Is there anything we can do to make this not be a breaking change?

```
System.MissingMethodException: 'Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware..ctor(Microsoft.AspNetCore.Http.RequestDelegate, Microsoft.AspNetCore.Hosting.IHostingEnvironment, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Builder.StaticFileOptions>, Microsoft.Extensions.Logging.ILoggerFactory)'.'
```

```
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.CreateStaticFileMiddleware(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware..ctor(RequestDelegate next, IHostingEnvironment hostingEnv, ILoggerFactory loggerFactory, SwaggerUIOptions options)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at EndpointRouting.Program.Main(String[] args) in C:\git\rynowak\Presentations\2019\Community-Standup-4-22\EndpointRouting\Program.cs:line 16
```

**Comment by davidfowl** [comment]
😢 I'm not sure if an easy way to fix this one. We can leave the old code there and suppress the warning. If we keep the old ctor and try to add the new one then it'll likely be ambiguos.

**Comment by Tratcher** [comment]
Why does it even set up StaticFiles like that? They could have done it just as easily in the UseSwaggerUI and wouldn't have had this issue. 

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/2b171c0fc6efe40f3a29a45c48d6b01221a0c214/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIMiddleware.cs#L48
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/2b171c0fc6efe40f3a29a45c48d6b01221a0c214/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs#L23

Would a reasonable fix be to show them how to refactor this so it works on 2.x and 3?

**Comment by davidfowl** [comment]
Yes that's also reasonable. Send a PR/open an issue.

**Comment by mkArtakMSFT** [comment]
@davidfowl was this revoled? Is there any pending work here?

**Comment by Tratcher** [comment]
@mkArtakMSFT the only proposed changes are in Swashbuckle.

**Comment by anurse** [comment]
Has anyone filed an issue on Swashbuckle to track this change? I'd like to close this issue out.

**Comment by alefranz** [comment]
Hi Andrew,
this has been fixed in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1082 and released in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0-rc2 so I believe it can be closed.

**Comment by alefranz** [comment]
Sample project if you want to do a quick check: https://github.com/alefranz/SampleApi

**Comment by anurse** [comment]
Awesome, thanks for checking back in @alefranz !
