### ISSUE TITLE
aspnet netcore 3 Preview 4: Json Formatter bug

### ISSUE THREAD

**Issue by DiyazY** [aspnet/AspNetCore#9712]
### Describe the bug
Got an unhandled exception when i made an api call.
aspnet serialization can't serialize object with Dictionary field to valid response.  There are some problems with formatter

### To Reproduce
1. Using this version of ASP.NET Core 3 Preview 4
2. In any controller,  Return DTO object with Dictionary 
```
               response.Content = new Dictionary<string, object>
                {
                    { "xyz", obj1 },
                    { "zyx", obj2 },
                };
                return Ok(response);
```

### Expected behavior
Should return valid json object

### Stacktrace

```
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.KeyValuePair`2[System.String,System.Object]' to type 'System.String'.
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.WriteEnumerable(JsonSerializerOptions options, WriteStackFrame& current, Utf8JsonWriter& writer)
   at System.Text.Json.Serialization.JsonSerializer.HandleEnumerable(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter& writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.HandleObject(JsonSerializerOptions options, Utf8JsonWriter& writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteObject(JsonSerializerOptions options, Utf8JsonWriter& writer, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.Write(Utf8JsonWriter& writer, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.Write(JsonWriterState& writerState, IBufferWriter`1 bufferWriter, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonSerializer.WriteAsyncCore(Object value, Type type, Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context, ICorsPolicyProvider corsPolicyProvider)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware`1.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by pranavkm** [comment]
You're likely running in to the same issue as https://github.com/aspnet/AspNetCore/issues/9673. Are you perhaps referencing an older version of `Microsoft.AspNetCore.Mvc.NewtonsoftJson`?

**Comment by DiyazY** [comment]
> You're likely running in to the same issue as #9673. Are you perhaps referencing an older version of `Microsoft.AspNetCore.Mvc.NewtonsoftJson`?

You are right. Thanks ;)
