### ISSUE TITLE
AddressInUseException when new instance of docker container is created

### ISSUE THREAD

**Issue by randyrod** [aspnet/AspNetCore#9743]
### Bug description
When previous instance of container is destroyed and a new instance is created by docker, the AddressInUseException is thrown. Although the port binding only specifies the container port and not the host port. Here the network settings from docker inspect of a working container:

       "NetworkSettings": {
           "Bridge": "",
           "SandboxID": "7ca4c991166252aef6bc5fcbd90f6f915d162dadbf595b1bd8d3377087332459",
           "HairpinMode": false,
           "LinkLocalIPv6Address": "",
           "LinkLocalIPv6PrefixLen": 0,
           "Ports": {
               "50008/tcp": [
                   {
                       "HostIp": "0.0.0.0",
                       "HostPort": "32778"
                   }
               ]
           },
           "SandboxKey": "/var/run/docker/netns/7ca4c9911662",
           "SecondaryIPAddresses": null,
           "SecondaryIPv6Addresses": null,
           "EndpointID": "bb262b04350434074cedc1dc0c475bac0fe52e74b8694b5c10c915e5b82fcc5c",
           "Gateway": "172.17.0.1",
           "GlobalIPv6Address": "",
           "GlobalIPv6PrefixLen": 0,
           "IPAddress": "172.17.0.12",
           "IPPrefixLen": 16,
           "IPv6Gateway": "",
           "MacAddress": "02:42:ac:11:00:0c",
           "Networks": {
               "bridge": {
                   "IPAMConfig": null,
                   "Links": null,
                   "Aliases": null,
                   "NetworkID": "78b10c0ce9b9a670cd3fd6d2366f23e889cdc46505b09eb2322ab329b78a6c0b",
                   "EndpointID": "bb262b04350434074cedc1dc0c475bac0fe52e74b8694b5c10c915e5b82fcc5c",
                   "Gateway": "172.17.0.1",
                   "IPAddress": "172.17.0.12",
                   "IPPrefixLen": 16,
                   "IPv6Gateway": "",
                   "GlobalIPv6Address": "",
                   "GlobalIPv6PrefixLen": 0,
                   "MacAddress": "02:42:ac:11:00:0c",
                   "DriverOpts": null
               }
           }
       }
This happened first time ever, we're using AWS ECS, it's common that multiple containers of the same image run on the same underlying instance and we never had these kinds of problems before. Could you also advice on a possible way to debug this in the future?

### Expected behavior
This should never happen, it is in a separate network stack and the port should never be occupied.

#### Stacktrace

```
Microsoft.AspNetCore.Server.Kestrel|FATAL|Unable to start Kestrel. System.IO.IOException: Failed to bind to address http://[::]:50008: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address in use ---> System.Net.Sockets.SocketException: Address in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```

**Comment by anurse** [comment]
> This should never happen, it is in a separate network stack and the port should never be occupied.

My understanding is that you're correct but it's docker's responsibility to ensure that.

Can you reproduce this reliably at all? Without a repro or additional diagnostics there's not a lot we can do. Perhaps running [`netstat -a`](https://ss64.com/bash/netstat.html) prior to starting up the app to see if there are any other processes holding the address?

**Comment by pgrm** [comment]
@anurse thx for the advise, we'll add `netstat -a` to the dockerfile to be executed as the first command, before `dotnet` to see if there are any weirdly occupied ports. 

It's something that happened back then  (3 weeks ago) quite reliably, but at the moment I haven't seen it for a while. We definitely didn't change anything in those regards, so all I could think of is a change in the docker image, as we just use the `mcr.microsoft.com/dotnet/core/aspnet:2.2` image we'd simply get the latest version every time we build a container for testing.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
