### ISSUE TITLE
could not find file 'System.Net.Http.resources'

### ISSUE THREAD

**Issue by Rabbit021** [aspnet/AspNetCore#9771]
### Describe the bug
My App Crashe with Unhandled Exception:  could not find file 'System.Net.Http.resources'.
I use independent publish， and I use  class **HttpClient** to request data.
Some times it crash.   when my network is not fine, it crashed frequently

###  Enviment
1. ASP.NET Core 2.0   in Window Server 2012 R2
2. I publish app with  `dotnet publish my.csproj -c debug -r win7-x64 -o %~dp0publish`

### Exception 

```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'Syste
m.Net.Http.resources'.
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name
, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlM
ark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(Cultur
eInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(Cultur
eInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean creat
eIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo reques
tedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stack
Mark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo cultur
e, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo cultur
e)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.Net.Http.WinHttpHandler.HandleAsyncException(WinHttpRequestState st
ate, Exception ex)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#37232
