### ISSUE TITLE
Authorized call to action with explicit `AuthenticationSchemes` uses wrong authentication scheme, but only after a different action was called

### ISSUE THREAD

**Issue by cypressious** [aspnet/AspNetCore#9779]
### Describe the bug
In my original application, I'm configuring two authentication schemes like so:

```cs
services.AddAuthentication("Bearer")
		.AddBasic() // uses scheme "Basic"
		.AddIdentityServerAuthentication(); // uses scheme "Bearer"
```

My controller looks like this

```cs
[Authorize]
[Route("")]
public class ValuesController : ControllerBase
{
    [HttpGet("bar")]
    public void Bar()
    {
    }

    [Authorize(AuthenticationSchemes = "Basic")]
    [HttpGet("foo")]
    public void Foo()
    {
    }
}
```

At first, when I call `/foo` using `Basic` authentication, the request will succeed. Only after I've called `/bar` using `Bearer` authentication, calling `/foo` with `Basic` authentication will fail with a 401.

I've set breakpoints in the respective authentication handlers and I can confirm that the `Basic` handler is called on the first call but not on the last one.

Now, the error can be reproduced without using `AddIdentityServerAuthentication()` by adding `[AllowAnonymous]` to the `Bar()` method. In that case, the following exception is thrown on the third call

```
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAlwaysRunResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### To Reproduce

- Check out https://github.com/cypressious/AspNetcoreAuthIssue and run it
- Call
```
localhost:5010/foo
Authorization: Basic YWRtaW46YWRtaW4=
```
- Call `localhost:5010/bar` 
- Call again
```
localhost:5010/foo
Authorization: Basic YWRtaW46YWRtaW4=
```

### Expected behavior
The last call to `localhost:5010/foo` succeeds

### global.json

```json
{
  "sdk": {
    "version": "2.2.104"
  }
}
```

**Comment by blowdart** [comment]
What are you calling the endpoints with? Browser, test client, postman?

**Comment by cypressious** [comment]
Postman and JetBrains Rider's HTTP file (https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html)

**Comment by blowdart** [comment]
@HaoK @Tratcher ?

**Comment by HaoK** [comment]
This seems similar to the other caching bug in 2.2 that was fixed in 3.0, I'll dig up the link

**Comment by HaoK** [comment]
Might be similar to this bug (which seems fixed in 3.0) https://github.com/aspnet/AspNetCore/issues/7687

**Comment by Eilon** [comment]
@HaoK please take a look to see if we'd want to patch this in 2.2.x and/or 2.1.x.

**Comment by HaoK** [comment]
Note: repros on 2.2 and 2.1, does not repro on 3.0

**Comment by rynowak** [comment]
@HaoK - did you try 3.0 without endpoint routing?
