### ISSUE TITLE
HttpProtocols.Http1AndHttp2 : "Unrecognized HTTP version: 'HTTP/2.0'"

### ISSUE THREAD

**Issue by linianhui** [aspnet/AspNetCore#9847]
### Describe the bug
When set Kestrel listen protocol to Http1AndHttp2, http/1.1 is ok, but http2 not work.

### To Reproduce
1. ASP.NET Core 2.2
2. Run this code 
    ```csharp
    using Microsoft.AspNetCore;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.AspNetCore.Server.Kestrel.Core;
    using Microsoft.AspNetCore.Http;

    namespace http2
    {
        public class Program
        {
            public static void Main(string[] args)
            {
                WebHost.CreateDefaultBuilder<Startup>(args)
                .UseKestrel(kestrelServerOptions =>
                {
                    kestrelServerOptions.ListenLocalhost(5000, listenOptions =>
                    {
                        //listenOptions.Protocols = HttpProtocols.Http1;
                        //listenOptions.Protocols = HttpProtocols.Http2;
                        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                    });
                })
                .Build()
                .Run();
            }
        }
        public class Startup
        {
            public void ConfigureServices(IServiceCollection services)
            {
                services.AddMvc();
            }

            public void Configure(IApplicationBuilder app)
            {
                app.UseMvc();
                app.Run(httpContext =>
                {
                    return httpContext.Response.WriteAsync(httpContext.Request.Protocol);
                });
            }
        }
    }
    ```
3. HTTP/1.1 is ok
    ```sh
    $ curl --http1.1 http://localhost:5000
    
    HTTP/1.1
    ```
4. HTTP/2 is error
    ```sh
    $ curl --http2-prior-knowledge http://localhost:5000

    curl: (16) Error in the HTTP2 framing layer
    ```
    error log:
    ```sh
    Now listening on: http://localhost:5000
    Application started. Press Ctrl+C to shut down.
    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
        Request starting HTTP/1.1 GET http://localhost:5000/
    info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
        Request finished in 103.9733ms 200
    info: Microsoft.AspNetCore.Server.Kestrel[17]
        Connection id "0HLMD91J2CIO8" bad request data: "Unrecognized HTTP version: 'HTTP/2.0'"
    Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unrecognized HTTP version: 'HTTP/2.0'
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectUnknownVersion(Byte* version, Int32 length)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
    ```

### Expected behavior
print HTTP/2

### Additional context
`dotnet --info`:
```sh
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#listenoptionsprotocols
```
Http1AndHttp2: HTTP/1.1 and HTTP/2. Requires a TLS and Application-Layer Protocol Negotiation (ALPN) connection to negotiate HTTP/2; otherwise, the connection defaults to HTTP/1.1.
```

To use http2-prior-knowledge you must disable HTTP1.

**Comment by hasithaAlex** [comment]
ALPN is not supported on:

.NET Framework 4.x on Windows
.NET Core on Linux with OpenSSL older than 1.0.2
.NET Core on OS X

**Comment by jjxtra** [comment]
Why is Http1AndHttp2 exposed as an option? It simply does not work...
